### ISSUE TITLE
如何在服务端和客户端设置密码？

### ISSUE THREAD

**Issue by OnionSalt** [ginuerzh/gost#1]
用-p参数貌似没有作用，例如：
我在服务端用 ./gost -p="abc"
客户端用 gost -p="xyz"
两个密码设置为不同，但是依然可以连接

连接到是很正常，看网页和视频都没问题，但是密码怎么设置呢？不设置密码也可以直接连接，这样的话不管是谁，只要知道我的服务端地址就都可以连接啊

**Comment by ginuerzh** [comment]
websocket暂不支持加密，下个版本会加入

**Comment by OnionSalt** [comment]
多谢回复，还有个问题：
我换用-ss，提示client.go:107: Bad version，shadowsocks具体要怎么用呢？

**Comment by ginuerzh** [comment]
shadowsocks模式通过sm设置加密方式(默认为rc4-md5)，sp设置加密密码(默认为ginuerzh@gmail.com)

**Comment by OnionSalt** [comment]
只能用手机？我用的win7，chrome浏览器，-ss不支持这个吗？

**Comment by ginuerzh** [comment]
shadowsocks模式与非shadowsocks模式是不兼容的，作为shadowsocks服务端时只能给shadowsocks客户端使用，其他(浏览器等)不能使用。如果想并存需要跑两个服务端

**Comment by OnionSalt** [comment]
我服务端和客户端都使用了-ss，所以模式应该没问题。另外，也就是说浏览器下不能使用shadowsocks模式吗？本人纯小白，对这些不是很懂啊。

**Comment by ginuerzh** [comment]
不知你说的服务端和客户端分别指的是哪里，我理解为服务端为远端(非本机)，客户端指本机。
首先远端的服务端不要使用-ss参数，只有本地电脑上运行的gost才需要设，远端如果设置-ss参数，本地的gost的是无法去连接的

**Comment by OnionSalt** [comment]
我的服务端在cloud9，客户端自然是在本机啦。
如果我想使用shadowsocks模式，那我在服务端还是使用-ws吗？比如./gost -ws。或者不带参数？比如./gost

**Comment by ginuerzh** [comment]
对的服务端保持不变./gost -ws
客户端添加-ss参数

**Comment by OnionSalt** [comment]
多谢，还有个问题：
怎么停止服务端的gost呢？我现在完全没法改参数了，每次都提示：main.go:52: listen tcp :8080: bind: address already in use。貌似服务端的gost一直在运行

**Comment by ginuerzh** [comment]
正常情况应该是不会出现这种情况的，
你可以在终端中运行 ps -ef | grep gost
如果有./gost 项，就使用命令 killall gost 就可以了

**Comment by OnionSalt** [comment]
用ps -ef看了下，是apache2占用8080端口了，估计是把，把它停掉就好了，但是shadowsocks模式依然不行，我是如下设置的：
服务端：
./gost -sp="abc" -ws
客户端：
gost.exe -L=":8899" -S="xxxxxxxxxxxxxxxxx.c9.io" -sp="abc" -ss

依然是连不上，命令行窗口还是返回client.go:107: Bad version

**Comment by OnionSalt** [comment]
用ps -ef看了下，是apache2占用8080端口了，估计是把，把它停掉就好了，但是shadowsocks模式依然不行，我是如下设置的：
服务端：
./gost -sp="abc" -ws
客户端：
gost.exe -L=":8899" -S="xxxxxxxxxxxxxxxxx.c9.io" -sp="abc" -ss

依然是连不上，命令行窗口还是返回client.go:107: Bad version

**Comment by ginuerzh** [comment]
你的手机上是怎么设置的

**Comment by OnionSalt** [comment]
我没在手机上用，我在台式机win7，chrome浏览器

**Comment by ginuerzh** [comment]
浏览器是不能使用shadowsocks模式的，不要使用ss参数，ss参数是给手机连接使用的

**Comment by OnionSalt** [comment]
原来如此，多谢啊，希望能尽快看到下个能设置密码的websocket版本

**Comment by bobyangchina** [comment]
不错的应用，远程服务端应该完善一下，如设置密码等。
大家如果想真正依赖它翻，部署到vps应该比云稳定些。
谢谢开发者！！！
