### ISSUE TITLE
可否使用 SSL 与服务器连接呢

### ISSUE THREAD

**Issue by ARwMq9b6** [ginuerzh/gost#10]
目前客户端中填写服务器的标准格式是 `gost -S=server_ip:port` , 使用 Cloud9 IDE 和 Heroku 只能
`gost -S=*.c9.io:80` 和 `gost -S=*.herkuapp.com:80` 可行，无法使用 SSL. 可否加入类似 `gost -S=https://*.herkuapp.com` 这种功能以使用 SSL 呢？

**Comment by ginuerzh** [comment]
如果你指的是想建立tls/ssl加密隧道连接，可以通过设置加密方式-m=tls来实现，-key, -cert参数可以用来设置自己的公钥和私钥文件。

**Comment by ARwMq9b6** [comment]
@ginuerzh 感谢回复。

我不是这个意思，`-m=tls` 应该和 `-m=aes-cfb-256` 一样，是加密数据用的。

我意思是 `gost -S=*.herkuapp.com:80` 这样能看到以下信息（猜测这是 `ws://` ，没加密协议，特征明显，担心被 GFW 识破）：

```
[2015/7/29 14:14:34:808]
GET / HTTP/1.1
Host: arcane-anchorage-9903.herokuapp.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: XlxOu1lJDWTHH5m0ES8rOg==


[2015/7/29 14:14:35:072]
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Upgrade: websocket
Sec-Websocket-Accept: m7v1j1mbSz6xGunKtPA6cYp3UkY=
Via: 1.1 vegur
```
如果使用 `wss://` 就是加密的，看不到以上明文信息，我想通过 `wss:` 使用 Herku 的 WebSocket 防止被 GFW 识别。

**Comment by ARwMq9b6** [comment]
@ginuerzh 感谢回复。

我不是这个意思，`-m=tls` 应该和 `-m=aes-cfb-256` 一样，是加密数据用的。

我意思是 `gost -S=*.herkuapp.com:80` 这样能看到以下信息（猜测这是 `ws://` ，没加密协议，特征明显，担心被 GFW 识破）：

```
[2015/7/29 14:11:34:101]
GET / HTTP/1.1
Host: *.herokuapp.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: *******************==


[2015/7/29 14:14:39:121]
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Upgrade: websocket
Sec-Websocket-Accept: ******************=
Via: 1.1 vegur
```
如果使用 `wss://` 就是加密的，看不到以上明文信息，我想通过 `wss:` 使用 Herku 的 WebSocket 防止被 GFW 识别。

**Comment by ginuerzh** [comment]
目前websocket方式不支持安全连接，后续会考虑添加

**Comment by ARwMq9b6** [comment]
@ginuerzh 感谢回复。
