### ISSUE TITLE
go build error with shadowsocks

### ISSUE THREAD

**Issue by chenhw2** [ginuerzh/gost#106]
# github.com/ginuerzh/gost
./conn.go:154: undefined: shadowsocks.DialWithRawAddrConn

**Comment by ginuerzh** [comment]
please see #67

**Comment by chenhw2** [comment]
~ # uname -a
Linux 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
~ # go version              
go version go1.8 linux/amd64
~ # cd github/gost/cmd/gost/
~/github/gost/cmd/gost ±master » go build .
# github.com/ginuerzh/gost
../../../../go/src/github.com/ginuerzh/gost/conn.go:154: undefined: shadowsocks.DialWithRawAddrConn
