### ISSUE TITLE
是否考虑集成 tun2socks 功能？

### ISSUE THREAD

**Issue by soffchen** [ginuerzh/gost#109]
https://github.com/songgao/water

**Comment by ginuerzh** [comment]
可以考虑，短期内不会。

**Comment by ginuerzh** [comment]
下一版本(2.9)开始支持tun/tap设备。

**Comment by steom** [comment]
it's possible with gost to redirect all internet traffic via tun/tap a-la tun2socks? 

tun2socks-windows-4.0-amd64.exe -tunAddr 10.0.0.2 -tunGw 10.0.0.1 -proxyType socks -proxyServer 192.168.101.1:1086 -dnsServer 8.8.8.8,8.8.4.4
