### ISSUE TITLE
HTTP 代理对 telegram 无效

### ISSUE THREAD

**Issue by nutinshell** [ginuerzh/gost#11]
可能是个 bug，```./gost -L :5555 -m rc4-md5 -p pass -ws -S``` 客户端，telegram desktop 设置使用生成的 http 代理，无法连接，别的 app 可以顺利使用生成的 http 代理。

**Comment by ginuerzh** [comment]
telegram对http代理的兼容性不是太好，可以使用socks5代理，速度更快。
