### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by networkextension** [ginuerzh/gost#111]
root@freebsd:~ # go get github.com/ginuerzh/gost
# github.com/ginuerzh/gost
golang/packages/src/github.com/ginuerzh/gost/conn.go:152: undefined: shadowsocks.DialWithRawAddrConn
root@freebsd:~ #

**Comment by ginuerzh** [comment]
Please clone this repo:
```
$ git clone github.com/ginuerzh/gost
$ cd cmd/gost
$ go build
```
