### ISSUE TITLE
关掉putty后就连不上了是什么情况啊？

### ISSUE THREAD

**Issue by c21xdx** [ginuerzh/gost#113]
大佬，我在VPS，centos 6.5上安装用putty连SSH安装gost, 
wget https://github.com/ginuerzh/gost/releases/download/v2.3/gost_2.3_linux_amd64.tar.gz
tar zxf gost_2.3_linux_amd64.tar.gz
cd gost_2.3_linux_amd64
./gost -L=http2+kcp://:443

下载客户端设置后可以连上，关掉putty后，就连不上了，putty连上SSH再输一下命令才连得上，这要怎么搞？我哪里搞错了

**Comment by mixool** [comment]
后台运行 nohup ./gost -L=http2+kcp://:443 &
