### ISSUE TITLE
gost能否进行反向代理

### ISSUE THREAD

**Issue by ssfdust** [ginuerzh/gost#114]
现在有一台服务器，公网ip为110.110.110.110，在内网中有一台192.168.1.1使用着8888端口运行着名为firmate的服务端。在没有路由器权限的情况下，能否利用gost将8888端口的数据转发到110.110.110.110的8888端口上。
谢谢。

**Comment by ginuerzh** [comment]
可以使用[2.4版本](https://github.com/ginuerzh/gost/releases/tag/v2.4-dev)中的ssh隧道实现。

在公网服务器(110.110.110.110)上运行:
```
$ gost -L ssh://admin:123456@:2222
```
在内网(192.168.1.1)机器上运行:
```
$ gost -L rtcp://0.0.0.0:8888/localhost:8888 -F ssh://admin:123456@110.110.110.110:2222?ping=60
```

具体用法可以参考[这篇文章](https://groups.google.com/forum/#!topic/go-gost/wdIbLraLnIM)。

**Comment by ssfdust** [comment]
十分感谢,十分感谢.

**Comment by qqqqqqrrrrhh123a** [comment]
反向隧道除了使用ssh协议，能不能使用socks5协议？如果socks5协议也行，那么反向隧道可以使用ss和ssr协议吗

**Comment by GavinAlison** [comment]
报错了， 
公网报错： 
{"handler":"http","kind":"handler","level":"info","listener":"tcp","local":"110.110.110.110:2222","msg":"192.168.1.1:14176 <> 110.110.110.110:2222","remote":"192.168.1.1:14176","service":"service-0","time":"2023-07-17T11:21:54.190+08:00"}
{"handler":"http","kind":"handler","level":"error","listener":"tcp","local":"110.110.110.110:2222","msg":"malformed HTTP request \"SSH-2.0-Go\"","remote":"192.168.1.1:14176","service":"service-0","time":"2023-07-17T11:21:54.190+08:00"}
{"duration":83842,"handler":"http","kind":"handler","level":"info","listener":"tcp","local":"110.110.110.110:2222","msg":"192.168.1.1:14176 >< 110.110.110.110:2222","remote":"192.168.1.1:14176","service":"service-0","time":"2023-07-17T11:21:54.190+08:00"}
{"handler":"auto","kind":"service","level":"error","listener":"tcp","msg":"malformed HTTP request \"SSH-2.0-Go\"","service":"service-0","time":"2023-07-17T11:21:54.190+08:00"}

内网报错：
{"handler":"rtcp","kind":"listener","level":"error","listener":"rtcp","msg":"route(retry=0) ssh: handshake failed: EOF","service":"service-0","time":"2023-07-17T11:24:31.930+08:00"}
{"handler":"rtcp","kind":"service","level":"warning","listener":"rtcp","msg":"accept: ssh: handshake failed: EOF, retrying in 5s","service":"service-0","time":"2023-07-17T11:24:31.930+08:00"}

请问该如何解决？

**Comment by GavinAlison** [comment]
对应的执行命令：
公网： 
 gost -L ssh:admin:123456@:2222

内网：
 gost -L rtcp://0.0.0.0:8099/localhost:8099 -F ssh://admin:123456@110.110.110.110:2222??ping=60
