### ISSUE TITLE
用gost和 privoxy实现转发http(s)到socks5代理有什么不同。

### ISSUE THREAD

**Issue by ldaochen** [ginuerzh/gost#115]
请问下用gost和privoxy(https://www.privoxy.org/)实现转发http(s)到socks5代理。
这两个实现性能有多大不同？
gost能直接作为代理(不设置转发)越过墙吗？

**Comment by ginuerzh** [comment]
我不太清楚privoxy是怎么实现的，但原理大体上应该差不多：将收到的http(s)请求重新封包成socks5协议的数据发给后端socks5代理。
gost可以直接作为代理，但若要过墙，中间传输的数据必须是加密的，所以普通的http/socks5代理是不行的。
