### ISSUE TITLE
每次网络断过以后，都必须重启gost，否则就卡死在那儿了。

### ISSUE THREAD

**Issue by douglas-lee** [ginuerzh/gost#118]
每次网络断过以后，都必须重启gost，否则就卡死在那儿了。这个问题能解决不？

**Comment by ginuerzh** [comment]
具体是哪一种模式下？

**Comment by f4nff** [comment]
就是心跳包的问题,我测试很多次了

**Comment by f4nff** [comment]
ssh+ socks5 +udp +心跳   估计这种就可以解决,

**Comment by douglas-lee** [comment]
我是在socks+http2的模式下出现此问题。

**Comment by ginuerzh** [comment]
HTTP2会有这个问题，后面版本中解决。

**Comment by ginuerzh** [comment]
在有大量短连接的场景下，例如大量的网页HTTP请求，HTTP2比较有优势，速度会比较快。
但对于长连接的情形，像SSH，视频播放等，没有太明显的区别。

**Comment by douglas-lee** [comment]
明白了，所以从理论上说，wss跟http2类似，只不过从协议上来说，http2可能更优于wss，可以这么理解吧？

**Comment by ginuerzh** [comment]
HTTP2应该会取代websocket。

**Comment by ginuerzh** [comment]
See #117
