### ISSUE TITLE
路由器上透明代理的设置

### ISSUE THREAD

**Issue by kirbyzhu** [ginuerzh/gost#119]
在小米路由器上运行 ./gost -L=redirect://:12345 -F=http+tls://****.arukascloud.io:443  -logtostderr -v=5

I0603 15:49:23.502898   12978 chain.go:91] HTTP2 is enabled
I0603 15:49:23.532437   12978 gost.go:118] open cert.pem: no such file or directory

在网内机器上访问fq，好像不走路由，一点链接信息都没有，请哪位指点一下是不是还需要其他配套的设置？

**Comment by rampageX** [comment]
Google `iptables`
