### ISSUE TITLE
openshift v3 布置好了gost，gost_v2.2_windows_386 客户端怎样设置参数启动

### ISSUE THREAD

**Issue by slulu164** [ginuerzh/gost#120]
openshift v3 布置好了gost，  布置都是route type：edge 。 gost_v2.2_windows_386 客户端怎样设置参数启动，
启动后是 怎样的设置，谢谢指导！

**Comment by jzp820927** [comment]
我觉得项目主页已经说的非常详细了，还有什么不懂的麽？

**Comment by slulu164** [comment]
@jzp820927 兄弟你好！openshift v3 布置好了gost ，gost_v2.2_windows_386 客户端

 -F wss://域名:443 连接不上，项目主页上看不明白，看了论坛里的我布置的是route type：edge模式，需要
用gost客户端 连接，另外启用浏览器端口是多少。你帮忙看看，谢谢！

**Comment by slulu164** [comment]
服务端配置 gost-ws  tcp 8080

**Comment by jzp820927** [comment]
你这个参数格式有误，不知道你那个 tcp 是什么东西，如果服务端是运行的 ws 协议，客户端就
gost -L=:8080 -F=ws://服务端地址:端口号
就行了。

**Comment by slulu164** [comment]
@jzp820927 服务端 Container: gost-ws
Image: wangyi2005/gost-ws 7934650 110.5 MiB
Ports: 8080/TCP  我试过 gost -L=:8080 -F=ws://服务端地址：443 不连接，
                             gost -L=:1080  -F=wss://域名:443 ’也不对  然后浏览器监听 127.0.0.1 1080  socks5

**Comment by jzp820927** [comment]
客户端这边应该是 http 代理类似，不是 socks5

**Comment by slulu164** [comment]
gost -L=:8080 -F=http://服务端地址；443 
浏览器 http 443 还是...

**Comment by jzp820927** [comment]
不知道你服务端有没有部署成功，你应该检查下服务端的日志。

**Comment by slulu164** [comment]
gost -L=:8080 -F=ws://服务端地址：443 
我再试试

**Comment by slulu164** [comment]
输入 http://gost-ws-cvb.7e14.starter-us-west-2.openshiftapps.com/ 服务端，提示404 page not found
应该是成功了，我试过gost -L=:8080 -F=ws://服务端地址：443 
浏览器http 443 和8080 无连接，客户端无日志输出

**Comment by slulu164** [comment]
cmd 拖到C:\Documents and Settings\Administrator\桌面\gost_v2.2_windows_386 运行，应该是对的，
怎么没有连接和日志输出

**Comment by jzp820927** [comment]
你上面的服务端地址是正确的嘛？如果地址是对的，我帮你试试

**Comment by slulu164** [comment]
服务端是对的，提示404 page not found 就是成功了，我部署了herpku服务端现在可以用了，客户端
gost -L=:1080  -F=wss://域名:443 ok .
没有动过环境变量 MODE ，应该是默认，谢谢老兄！

**Comment by jzp820927** [comment]
刚刚试了下，你这个服务端确实用不了，我用我账号部署试试，看看是什么问题，再给你反馈。

**Comment by slulu164** [comment]
谢谢了， jzp820927 兄弟！

**Comment by jzp820927** [comment]
应该是你的服务端有问题，建议你重新部署，刚刚我在我 openshift 上部署了，测试没问题。

**Comment by slulu164** [comment]
我再试试，谢谢

**Comment by jzp820927** [comment]
openshift 以前经常关停部署代理的 apps，有可能是不是你的这个应用被关了。

**Comment by slulu164** [comment]
我重新布置了，用gost -L=:8080 -F=wss://服务端地址: 8080
浏览器http 8080

**Comment by jzp820927** [comment]
你命令错了，最后的端口是 443
gost -L=:8080 -F=wss://域名:443

**Comment by slulu164** [comment]
我正在用 gost -L=:8080 -F=wss://域名:443 不连接，可能账号有问题

**Comment by slulu164** [comment]
我用的临时邮箱注册的

**Comment by slulu164** [comment]
我换个账号试试，谢谢指导

**Comment by jzp820927** [comment]
行

**Comment by slulu164** [comment]
终于找到原因了，太大意了，没有布置到edge，谢谢老兄！gost 的https 模式你在这个v3 平台布置过没有，
谢谢说明一下！
另外，gsonva pass 如果有镜像能否布置。

**Comment by jzp820927** [comment]
既然有镜像肯定可以部署。一般没事，我很少折腾，所以没在其他平台弄，反正原理都是一样的，要不就是 https，要不就是 wss，你依葫芦画瓢就行了。

**Comment by slulu164** [comment]
谢谢老兄！既然是朋友了，如果方便的话，加个qq,也方便说话和传文件，

**Comment by jzp820927** [comment]
我能说，从安全考虑，我不用 QQ 麽

**Comment by slulu164** [comment]
@jzp820927 理解兄弟，谢谢！
