### ISSUE TITLE
代理登录不支持域用户，密码不能包含特殊字符

### ISSUE THREAD

**Issue by ladygh** [ginuerzh/gost#122]
如题。像域用户登录比如用户test\user1
应该是写成 -L=test\user1:123456@proxy1:8080
因为域用户登录名里有\，这里就会出错

同时发现如果代理服务器登录用户密码里含有 @ # 这样的特殊字符，依然会出错

**Comment by Sg4Dylan** [comment]
测试发现密码里包含字符 `$` 也是不行的

**Comment by ginuerzh** [comment]
由于参数中的认证信息是要遵循标准URL格式，所以会有限制，目前的解决方案是通过外部文件来设置认证信息，这样就没有限制了。
认证信息的文件格式参考：https://github.com/ginuerzh/gost/blob/master/cmd/gost/secrets.txt
服务端:
`gost -L=:8080?secrets=secrets.txt`
客户端:
`gost -L=:8888 -F=:8080?secrets=secrets.txt`
