### ISSUE TITLE
linux arm版能在android上运行吗？

### ISSUE THREAD

**Issue by wooowooo** [ginuerzh/gost#125]

**Comment by ssfdust** [comment]
https://github.com/ginuerzh/gost/issues/59
https://github.com/ginuerzh/gost/issues/48
这issue开的也太随便了。

**Comment by ginuerzh** [comment]
Duplicate of #59

**Comment by f4nff** [comment]
建议不要搭理这种伸手党，作者的意图就不是翻墙，
有能力自己去整合，如果作者真那么做了，可能就不仅仅是去喝茶了，

**Comment by wooowooo** [comment]
我可能是伸手党，也可能是问了个在高手眼中白痴问题的菜鸟。
作者作了label处理，并未发话。若此project不欢迎菜鸟，作者一句话，我便滚。
@f4nff   不理我也罢，而提起敏感词的不是我。

**Comment by f4nff** [comment]
作者已经做了核心工作，有蓝灯等等，你自己可以替换下核心，别拉作者下水了，

**Comment by wooowooo** [comment]
我没有那个意思，我只是不明白为什么一个单纯菜鸟问题会造成这种局面。
我承认我误闯了清净之地。我想指出@f4nff若是想维护这里的清静，你这样做适得其反。
你从一楼往下看一看，是你提起敏感词的。

我的问题已经问完。后面这几楼都可以删掉。整个删掉也可以。
