### ISSUE TITLE
[Feature Request] 支持 Domain, IP, CIDR 规则

### ISSUE THREAD

**Issue by soffchen** [ginuerzh/gost#128]
可以根据 Domain, IP, CIDR 规则选择父级代理

请参考：
https://github.com/nadoo/glider
https://github.com/zhuhaow/SpechtLite
https://github.com/xjdrew/kone

**Comment by ginuerzh** [comment]
后面会先考虑增加负载均衡。

**Comment by goxofy** [comment]
楼主是否测试在协议转发方面glider和gost哪个效率更好？哪个资源消耗更低一些？ 主要是socks5转http

**Comment by soffchen** [comment]
请问路由模式下，多个 -F 是什么规则？是 chains 还是按 bypass 来逐个匹配筛选？
希望是：
-F socks://us_ip:port?bypass=~us.txt -F socks://hk_ip:port?bypass=~hk.txt ...
