### ISSUE TITLE
远程桌面连接:由于数据加密错误,这个会话将结束。

### ISSUE THREAD

**Issue by oooxooo** [ginuerzh/gost#132]
/root/gost_2.4-rc1_linux_amd64/gost -L=udp://:3389/ip:3389 -L=tcp://:3389/ip:3389
-----
问题：远程桌面连接:由于数据加密错误,这个会话将结束。
注：如果只转TCP没这问题。

**Comment by ginuerzh** [comment]
可否提供相应的LOG?

另外注意: UDP的转发通道是有超时的，默认为60s，对于每一个客户端如果在60s内没有任何数据交互，这个通道就会自动关闭，此时在log中会看到类似于以下信息：
`[udp] xx.xx.xx.xx:port >-< xx.xx.xx.xx:3389`

**Comment by oooxooo** [comment]
@ginuerzh 
 我尝试过加?ttl=120 可是还是一样
root@szz:~# /root/gost_2.4-rc1_linux_amd64/gost -L=udp://:34567/104.168.108.25:34567 -L=tcp://:34567/104.168.108.25:34567
2017/08/10 05:46:11 forward.go:36: [tcp] 123.74.26.227:7688 - 104.168.108.25:34567
2017/08/10 05:46:11 forward.go:44: [tcp] 123.74.26.227:7688 <-> 104.168.108.25:34567
2017/08/10 05:46:19 forward.go:46: [tcp] 123.74.26.227:7688 >-< 104.168.108.25:34567
2017/08/10 05:46:22 forward.go:36: [tcp] 123.74.26.227:7693 - 104.168.108.25:34567
2017/08/10 05:46:22 forward.go:44: [tcp] 123.74.26.227:7693 <-> 104.168.108.25:34567
2017/08/10 05:46:27 forward.go:94: [udp] 123.74.26.227:7694 <-> 104.168.108.25:34567
2017/08/10 05:46:35 forward.go:46: [tcp] 123.74.26.227:7693 >-< 104.168.108.25:34567

**Comment by f4nff** [comment]
这个有争议的,
最好的办法就是建立一个心跳机制,
一直保持隧道的畅通,
好像udp这块,时间久了没通信就自动通道了

**Comment by oooxooo** [comment]
@f4nff 
这个问题应该不是自动关闭造成的。因为我连60秒都没就报错连。

**Comment by ginuerzh** [comment]
@f4nff 
UDP端口转发，对于每一条通道都对应着服务器端的一个监听端口，所以通道是需要及时关闭来释放这些资源，对于DNS查询这种请求尤为重要，如果不及时关闭，服务器就会有大量的端口被占用。

@oooxooo 
我在本地用QUIC协议来进行转发测试，没发现有什么问题，你可以在本地网络中测试一下，以便排除网络因素。

**Comment by f4nff** [comment]
udp这块争议比较大,
使用率也少,
我测试有时候会异常断开,
加上cn2现在在封udp,
使用不多,

我个人觉得正常的逻辑应该是这样的,

quic client----quic server
中间应该设置一种心跳机制,

20s发送一个心跳,10秒 超时,超时2次自动断开,
只要客户端启动,就应该长期与服务端保持一个通信连接,

**Comment by ginuerzh** [comment]
quic自身是有心跳的，默认没有开启，若超过一分钟没有数据交互就会自动断开

**Comment by oooxooo** [comment]
@ginuerzh 
我这没经过代理直接用的是以下命令来转发，您这方式有用服务端做代理和客户端，我这下面直接转发没加-F ，转发远程桌面只TCP没问题加UDP却会提示加密失败，我用SOCAT来转发UDP测试是正常的，这应该是gost的BUG求完善。
gost_2.4-rc1_linux_amd64/gost -L=udp://:34567/104.168.108.25:34567 -L=tcp://:34567/104.168.108.25:34567

**Comment by f4nff** [comment]
你要提供详细的触发bug的动作行为,老板才能解决,

**Comment by ginuerzh** [comment]
不加-F的处理方式也是一样的，会在本机针对每条通道监听一个端口。

**Comment by oooxooo** [comment]
@ginuerzh 
您可以不加-F 转发远程桌面测试下，我个人觉得应该会马上知道结果的。或者我提供给您服务器测试也行。

**Comment by ginuerzh** [comment]
能说说具体的环境构建和测试流程吗？我没有用过远程桌面，所以不太清楚其使用方式。
