### ISSUE TITLE
VPS上安装GOST

### ISSUE THREAD

**Issue by flyingwhalefall** [ginuerzh/gost#135]
在铺天盖地的SS，vpn下发现一个隐蔽的神器GOST
可惜没学过计算机语言，网上材料又少写得不详细，不得不请问
在CENTOS 7 X64的VPS上如何安装GOST呢
看到一篇写
“如果你的VPS还未搭建GO环境，请先按此文http://briteming.blogspot.com/2013/05/linuxgo.html的蓝色部分搭建GO环境。
然后cd /root/mygo/,运行 go install github.com/ginuerzh/gost 来安装gost.(VPS中，需先安装git，ｍercurial:
apt-get install -y git mercurial 或者yum install -y git mercurial) ”

感觉超出计算机小白能操作的范围了，请问大佬是不是要这么做，还是有更简单些的安装手法，谢谢

**Comment by flyingwhalefall** [comment]
安装完GO，无法理解GOPATH，遂进入下一步安装gost

[root@host go]# go install github.com/ginuerzh/gost
can't load package: package github.com/ginuerzh/gost: cannot find package "github.com/ginuerzh/gost" in any of:
	/usr/local/go/src/github.com/ginuerzh/gost (from $GOROOT)
	/root/gopath/src/github.com/ginuerzh/gost (from $GOPATH)
[root@host go]# 

卡住了

**Comment by flyingwhalefall** [comment]
试着把源码下载加压到/usr/local/go/src/
再来
[root@host go]# go install gost_2.3_linux_amd64
can't load package: package gost_2.3_linux_amd64: no buildable Go source files in /usr/local/go/src/gost_2.3_linux_amd64

**Comment by hardway** [comment]
不想要自己编译的，其实可以直接下载作者发布的预编译版本，解压就可以用
https://github.com/ginuerzh/gost/releases

CentOS x64的话用linux_amd64版本就可以

**Comment by flyingwhalefall** [comment]
谢谢指点，可是对于小白来说真不懂得理解
把您说的下载解压到根目录下，就只有一个gost文件

[root@host ~]# gost -L="http://user:password@:25"
-bash: gost: command not found

linux好难。。。

**Comment by bace1996** [comment]
你应该用 `./` 来表示在当前目录下查找目标。
确保 `cd` 到gost可执行文件所在的目录下，然后尝试 `./gost -L="http://user:password@:25"`

**Comment by flyingwhalefall** [comment]
感谢bace1996，在你们看来，我提的问题有多白啊。。。

我把linux_amd64解压得到gost文件，放在vps根目录底下，如图，然后执行

[root@host ~]# ./gost -L="http://user:password@:25"
-bash: ./gost: Permission denied

这又是出了什么问题，能再指点下吗
![default](https://user-images.githubusercontent.com/30478118/29199653-35133788-7e81-11e7-865b-83886b7eba66.JPG)

**Comment by flyingwhalefall** [comment]
[root@host ~]# chmod +x gost
[root@host ~]# ./gost -L="http://user:password@:25"
F0810 22:41:12.504835   15399 main.go:83] listen tcp :25: bind: address already in use
goroutine 6 [running]:
github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog.stacks(0x9f1b00, 0xc400000000, 0x57, 0xac)
	/home/gerry/dev/src/go/src/github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog/glog.go:766 +0xa5
github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog.(*loggingT).output(0x9d4e20, 0xc400000003, 0xc420080180, 0x9753c9, 0x7, 0x53, 0x0)
	/home/gerry/dev/src/go/src/github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog/glog.go:717 +0x337
github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog.(*loggingT).printDepth(0x9d4e20, 0x3, 0x1, 0xc420103e10, 0x1, 0x1)
	/home/gerry/dev/src/go/src/github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog.(*loggingT).print(0x9d4e20, 0x3, 0xc420103e10, 0x1, 0x1)
	/home/gerry/dev/src/go/src/github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog/glog.go:637 +0x5a
github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog.Fatal(0xc420103e10, 0x1, 0x1)
	/home/gerry/dev/src/go/src/github.com/ginuerzh/gost/cmd/gost/vendor/github.com/golang/glog/glog.go:1125 +0x53
main.main.func1(0xc42000fb50, 0xc4200523c0, 0x7ffc6de4b7c2, 0x3, 0x7ffc6de4b7ad, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/home/gerry/dev/src/go/src/github.com/ginuerzh/gost/cmd/gost/main.go:83 +0x2b8
created by main.main
	/home/gerry/dev/src/go/src/github.com/ginuerzh/gost/cmd/gost/main.go:84 +0x1d9


这样就成功了？

**Comment by bace1996** [comment]
这表示你已经可以在这台机器上使用gost，但你给定的参数是不可用的。
` listen tcp :25: bind: address already in use` 表示你指定的`端口`（25）已经被系统占用。
通常情况下，数值较低的端口更容易与系统服务发生冲突，请尝试指定大于1024的端口值。

**Comment by flyingwhalefall** [comment]
谢谢bace1996、hardway 两位大佬，在GITHUB上小白能得到大佬指点太不容易了，感恩！！！
