### ISSUE TITLE
GOST客户端是否默认实现TLS

### ISSUE THREAD

**Issue by flyingwhalefall** [ginuerzh/gost#136]
官方说明里写到

SOCKS5代理
服务端:
gost -L=socks5://:1080
客户端:
gost -L=:8080 -F=socks5://server_ip:1080
如果两端都是gost(如上)则数据传输会被加密(协商使用tls或tls-auth方法)，否则使用标准SOCKS5进行通讯(no-auth或user/pass方法)。

也就是哪怕参数是-L=socks5，只要开启客户端就是SOCKS-TLS

那是否对于HTTP代理参数里
服务端:
gost -L=http://:443
客户端:
gost -L=:8080 -F=http://server_ip:443

只要开启客户端，也就是HTTP的参数却实现了HTTPS？

**Comment by ginuerzh** [comment]
HTTP与HTTPS两种模式是不兼容的，所以两端必须一致，使用HTTPS要手动指定：
gost -L=https://:443
gost -L=:8080 -F=https://server_ip:443

**Comment by flyingwhalefall** [comment]
谢谢大大的指点，从昨晚到现在都在反复测试安装，设置你的软件，真是个很棒软件，一个实现了HTTP,HTTPS,HTTP2,SOCKS,SOCKS-TLS,SS的功能。
有两个疑惑，请教下
1）v2ray作者说SS的TLS只是混淆方式，不是真正的TLS加密，GOST自带证书，我在文件夹里没看到，会不会也是种混淆方式，没有真正TLS加密？
2）gost设置个HTTP代理后，服务器端和客户端间通信是否加密，类似SS，无法被墙检测出访问什么网址呢？

再次谢谢你这个神器，希望能继续开发下去！！！

**Comment by ginuerzh** [comment]
1) 这里的所有TLS都是标准TLS，证书如果不手动指定，则在每次程序启动时自动生成一个。
2) HTTP只是上层协议，是否加密要看底层传输层用的是什么，如果用tls, wss, kcp, quic等加密隧道则都是加密的，否则就是明文。

**Comment by flyingwhalefall** [comment]
信息量好大，好好消化消化

谢谢大佬指点！

**Comment by zw0** [comment]
@ginuerzh socks5-tls 怎么指定自定义的证书？
