### ISSUE TITLE
如何实现开机自启动

### ISSUE THREAD

**Issue by flyingwhalefall** [ginuerzh/gost#137]
这两天学习GOST使用，实在是万能武器。
可是google了懂得nohup来不让进程当掉，但是挡不住VPS关机重启。
搜索了下实现开机自启动的方法，基本都要脚本。
可是没学过计算机专业的懵了。实在不懂怎么写脚本
假设我GOST在/gost目录下，请教大家怎么编写自启动脚本，谢谢指教

**Comment by flyingwhalefall** [comment]
学习了下shadowsocks的自启动脚本，看不懂参数怎么改



#!/bin/sh
# chkconfig: 2345 90 10
# description: Start or stop the Shadowsocks R server
#
### BEGIN INIT INFO
# Provides: Shadowsocks-R
# Required-Start: $network $syslog
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Start or stop the Shadowsocks R server
### END INIT INFO
 
# Author: Yvonne Lu(Min) <min@utbhost.com>
 
name=shadowsocks
PY=/usr/bin/python
SS=/root/shadowsocksr/shadowsocks/server.py
SSPY=server.py
conf=/root/shadowsocksr/user-config.json
 
start(){
    $PY $SS -c $conf -d start
    RETVAL=$?
    if [ "$RETVAL" = "0" ]; then
        echo "$name start success"
    else
        echo "$name start failed"
    fi
}
 
stop(){
    pid=`ps -ef | grep -v grep | grep -v ps | grep -i "${SSPY}" | awk '{print $2}'`
    if [ ! -z $pid ]; then
        $PY $SS -c $conf -d stop
        RETVAL=$?
        if [ "$RETVAL" = "0" ]; then
            echo "$name stop success"
        else
            echo "$name stop failed"
        fi
    else
        echo "$name is not running"
        RETVAL=1
    fi
}
 
status(){
    pid=`ps -ef | grep -v grep | grep -v ps | grep -i "${SSPY}" | awk '{print $2}'`
    if [ -z $pid ]; then
        echo "$name is not running"
        RETVAL=1
    else
        echo "$name is running with PID $pid"
        RETVAL=0
    fi
}
 
case "$1" in
'start')
    start
    ;;
'stop')
    stop
    ;;
'status')
    status
    ;;
'restart')
    stop
    start
    RETVAL=$?
    ;;
*)
    echo "Usage: $0 { start | stop | restart | status }"
    RETVAL=1
    ;;
esac
exit $RETVAL

**Comment by ssfdust** [comment]
如果是比较新的机器的话 不用这么麻烦。有systemd。
# /usr/lib/systemd/system/gost@.service
[Unit]
Description=GO Simple Tunnel
After=network.target

[Service]
Type=simple
User=nobody
ExecStart=/usr/bin/gost -C /etc/gost/%i.json

[Install]
WantedBy=multi-user.target

直接systemctl enable gost@config就行了。
启动是systemctl start gost@config

config是配置存储的文件名，/etc/gost/config.json。

**Comment by flyingwhalefall** [comment]
谢谢大侠指导，看了你的建议，马上上网把systemd，systemctl检索了一下
然后这么做的

在 /usr/lib/systemd/system/  目录下添加gost.service文件 ,写入

[Unit]
Description=GO Simple Tunnel
After=network.target

[Service]
Type=simple
User=nobody
ExecStart=/gost/gost   -C /gost/config.json

[Install]
WantedBy=multi-user.target



[root@host ~]# systemctl enable gost.service
Created symlink from /etc/systemd/system/multi-user.target.wants/gost.service to /usr/lib/systemd/system/gost.service.


好像是可以了。不过大侠
 /usr/lib/systemd/system/gost@.service   @是不是多打的字母啊？还是有什么深意吗？
@ssfdust

**Comment by flyingwhalefall** [comment]
[root /]# systemctl list-units --type=service
UNIT                                                                                LOAD       ACTIVE SUB          DESCRIPTION
 gost.service                                                                    loaded      active running      GO Simple Tunnel

gost已经实现开机运行了，但是建立的HTTPS代理在浏览器上并不能用。
进一步解决问题，估计是config.json出问题。

参考官方指南，想在VPS建立HTTPS代理，端口8080，
config.json如下

**{
    "ServeNodes": [
        " https://:8080"
    ]
 }**

应该没错吧，为什么按这个配置开机自启动，无法让配置生效呢，最后一步请大家指导下
@ssfdust @ginuerzh

**Comment by ginuerzh** [comment]
HTTPS代理如果要在浏览器中直接使用，需要提供相应的域名证书。
否则就需要将HTTPS代理转成HTTP或SOCKS5代理来使用：
gost -L :8888 -F https://server_ip:8080

**Comment by flyingwhalefall** [comment]
我已经在客户端gost目录下内置了有效的key和cert，
而且在用命令行形式在服务器端
./gost  -L= https://:8080  
后在浏览器可以正常用HTTPS代理 (域名：8080）。

所以问题跟证书应该没关，不知为何systemd enable  gost没成功启动上述命令。我vps是centos7 64位，
部署的gost是2.3 linux 64位。

**Comment by ssfdust** [comment]
ExecStart=/usr/bin/gost -C /etc/gost/%i.json
@后面的内容是替代%i占位符 启动时运行gost@config_file
实质上是运行 /usr/bin/gost -C /etc/gost/config_file.json

**Comment by flyingwhalefall** [comment]
@ssfdust  谢谢大佬，按照我写的那个方法做也是对的吗？

**Comment by ssfdust** [comment]
能运行就对了。

**Comment by flyingwhalefall** [comment]
@ssfdust  谢谢！

**Comment by flyingwhalefall** [comment]
**[root /]# service v2ray status**
● v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2017-08-12 03:07:27 EDT; 21s ago
 Main PID: 1077 (v2ray)
   Memory: 12.5M
   CGroup: /system.slice/v2ray.service
           └─1077 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Aug 12 03:07:27 host.localdomain systemd[1]: Started V2Ray Service.
Aug 12 03:07:27 host.localdomain systemd[1]: Starting V2Ray Service...
Aug 12 03:07:29 host.localdomain v2ray[1077]: V2Ray v2.33 (One for all) 20170609
Aug 12 03:07:29 host.localdomain v2ray[1077]: An unified platform for anti-censorship.
Aug 12 03:07:30 host.localdomain v2ray[1077]: 2017/08/12 03:07:30 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:443
Aug 12 03:07:30 host.localdomain v2ray[1077]: 2017/08/12 03:07:30 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:19841
Aug 12 03:07:30 host.localdomain v2ray[1077]: 2017/08/12 03:07:30 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:443
Aug 12 03:07:30 host.localdomain v2ray[1077]: 2017/08/12 03:07:30 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:19841

/etc/init.d/functions: line 63: /dev/stderr: Device or resource busyRedirecting to /bin/systemctl status  v2ray.service

**[root /]# service gost status**
● gost.service - GO Simple Tunnel
   Loaded: loaded (/usr/lib/systemd/system/gost.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2017-08-12 03:07:27 EDT; 32s ago
 Main PID: 1076 (gost)
   Memory: 6.5M
   CGroup: /system.slice/gost.service
           └─1076 /gost/gost -C /gost/config.json

Aug 12 03:07:27 host.localdomain systemd[1]: Started GO Simple Tunnel.
Aug 12 03:07:27 host.localdomain systemd[1]: Starting GO Simple Tunnel...

/etc/init.d/functions: line 63: /dev/stderr: Device or resource busyRedirecting to /bin/systemctl status  gost.service


同样用systemd添加开机自启动的service，v2ray 会提示监听443端口，而gost却没提示监听8080端口。
果然gost虽然成功启动，但没使HTTPS 8080监听生效。。。

**Comment by asins** [comment]
我使用上面的配置未能正常以服务形式启动gost，谁帮我看下原因：

● gost.service - GO Simple Tunnel
   Loaded: loaded (/usr/lib/systemd/system/gost.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-10-26 22:46:21 CST; 4s ago
  Process: 1629 ExecStart=/usr/local/bin/gost -C /etc/gost/config.json (code=exited, status=1/FAILURE)
 Main PID: 1629 (code=exited, status=1/FAILURE)

Oct 26 22:46:21 nootn systemd[1]: Started GO Simple Tunnel.
Oct 26 22:46:21 nootn systemd[1]: Starting GO Simple Tunnel...
Oct 26 22:46:21 nootn systemd[1]: gost.service: main process ...E
Oct 26 22:46:21 nootn systemd[1]: Unit gost.service entered f....
Oct 26 22:46:21 nootn systemd[1]: gost.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by siemenstutorials** [comment]
> 如果是比较新的机器的话 不用这么麻烦。有systemd。
> 
> ```
> # /usr/lib/systemd/system/gost@.service
> [Unit]
> Description=GO Simple Tunnel
> After=network.target
> 
> [Service]
> Type=simple
> User=nobody
> ExecStart=/usr/bin/gost -C /etc/gost/%i.json
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> 直接systemctl enable gost@config就行了。
> 启动是systemctl start gost@config
> 
> config是配置存储的文件名，/etc/gost/config.json。

大佬您好！您的意思是要先创建gost.service这个文件然后贴入以下脚本：
> [Unit]
> Description=GO Simple Tunnel
> After=network.target
> 
> [Service]
> Type=simple
> User=nobody
> ExecStart=/usr/bin/gost -C /etc/gost/%i.json
> 
> [Install]
> WantedBy=multi-user.target
是这样吗？那cfonfig.json是要设置什么吗？》
在VPS上测试了下不行 不知道问题出在哪里故来请教！！！

**Comment by Jayjjjjj** [comment]
> 我使用上面的配置未能正常以服务形式启动gost，谁帮我看下原因：
> 
> ```shell
> $systemctl status gost.service
> 
> ● gost.service - GO Simple Tunnel
>    Loaded: loaded (/usr/lib/systemd/system/gost.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Thu 2017-10-26 22:46:21 CST; 4s ago
>   Process: 1629 ExecStart=/usr/local/bin/gost -C /etc/gost/config.json (code=exited, status=1/FAILURE)
>  Main PID: 1629 (code=exited, status=1/FAILURE)
> 
> Oct 26 22:46:21 nootn systemd[1]: Started GO Simple Tunnel.
> Oct 26 22:46:21 nootn systemd[1]: Starting GO Simple Tunnel...
> Oct 26 22:46:21 nootn systemd[1]: gost.service: main process ...E
> Oct 26 22:46:21 nootn systemd[1]: Unit gost.service entered f....
> Oct 26 22:46:21 nootn systemd[1]: gost.service failed.
> Hint: Some lines were ellipsized, use -l to show in full.
> ```
> 
> `/usr/lib/systemd/system/gost.service`
> 
> ```shell
> [Unit]
> Description=GO Simple Tunnel
> After=network.target
> 
> [Service]
> Type=simple
> User=nobody
> ExecStart=/usr/local/bin/gost -C /etc/gost/config.json
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> 配置`/etc/gost/config.json`
> 
> ```json
> {
>     "ServeNodes": [
>         "ss://chacha20:123456@:443"
>     ]
> }
> ```
> 
> 直接使用`/usr/local/bin/gost -C /etc/gost/config.json`能正常启动命令，

检查权限
