### ISSUE TITLE
JSON config with -C seems no longer work in version 2.4 RC1

### ISSUE THREAD

**Issue by yyfearth** [ginuerzh/gost#138]
I tried `gost -L=socks5+h2://:8443` works fine with client

But then I change to use the JSON config `gost -C=/etc/gost/config.json`
```
{
    "ServeNodes": [
        "socks5+h2://:8443"
    ]
}
```

Client cannot connect to the server, got `getsockopt: connection refused`

Same thing happens on client, use `-L` with `-F` directly works, but use `-C` not.

Also debug option `-D` with `-C` does not print anything.

**Comment by ginuerzh** [comment]
This issue has been fixed in the master branch, see issue #129

**Comment by yyfearth** [comment]
@ginuerzh BTW, how to see the logs with -C or it should be just the same as use -L directly after the bug is fixed?

**Comment by yyfearth** [comment]
And when a new release will be upload after the fix?

**Comment by ginuerzh** [comment]
Yeah, The -C is the same as the direct use of -L -F.
The RC2 may be released next week.

**Comment by yyfearth** [comment]
The RC2 fixed the issue.
