### ISSUE TITLE
HTTPS代理无法设置为VPS开机自启动

### ISSUE THREAD

**Issue by flyingwhalefall** [ginuerzh/gost#139]
承接[原来的问题](https://github.com/ginuerzh/gost/issues/137)

反复对比，发现如果设置开机自启动为SOCKS5，也就是配置文件为
_{
    "ServeNodes": [
        "socks5://:8080"
    ]
 }_

可以实现重启后SOCKS5服务在浏览器可行，

但是改配置文件为

_{
    "ServeNodes": [
        "https://:8080"
    ]
 }_

重启VPS

# ss -lnp  查询下端口，得到
Netid State      Recv-Q Send-Q                                                Local Address:Port             
.........                                                          
tcp   LISTEN     0      128                                                              :::8080                                                                         :::*                   users:(("gost",pid=1080,fd=3))

可见GOST成功开机启动，也监听了8080端口

看看HTTPS能否正常使用
浏览器上HTTPS代理设置为     证书域名：8080 也没错（已经在nghttpx+squid）上证实可用。

可是网页返回如下错误信息

无法访问此网站

网址为 https://www.google.com/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_PROXY_CERTIFICATE_INVALID

个人感觉可能是自启动GOST，没法到达命令行启动那样自动加载GOST目录内的key 和 cert文件，导致加密认证失败。不知大大怎么看 @ginuerzh  等你来最后给个权威解释了

之所以这么执着这个设置，原因是HTTP/SOCKS5未加密不适合fq，而SOCKS-TLS只有ios的shadowsocket支持，如果不想打开GOST客户端，最好的选择就是设置VPS自启的HTTPS代理了，绑定域名证书。

**Comment by ginuerzh** [comment]
可以通过参数指定：
`gost -L="https://:8080?cert=/path/to/my/cert/file&key=/path/to/my/key/file"`
参考README: https://github.com/ginuerzh/gost#tls

**Comment by flyingwhalefall** [comment]
哦，对的，看来首页要多读几遍才行，马上试验！谢谢大佬！！！！

**Comment by flyingwhalefall** [comment]
{
    "ServeNodes": [
      "https://:8080?cert=/gost/cert.pem&key=/gost/key.pem"
    ]
 }


哈哈，终于可以开机自启动了，看来如果需要挂载证书，自启动config里要直接指定证书路径，因为开机自启动无法自动挂载证书。
