### ISSUE TITLE
Support data forwarding for tunnels

### ISSUE THREAD

**Issue by ginuerzh** [ginuerzh/gost#142]
As of now, we have supported TCP port forwarding, but the data being forwarded is transported over the unencrypted raw TCP tunnel, sometimes we need a secure tunnel.

The data forwarding tunnel can forward data over any tunnel, such as TLS (like stunnel), KCP, QUIC, SSH, etc. For example:
server side, a TLS forwarding tunnel that forwards data to port 8080, and an SNI proxy: 
`gost -L tls://:443/:8080 -L sni://:8080`
client side: 
`gost -L :8888 -F forward+tls://server_ip:443`

Then all the HTTP(S) requests from client port 8888 will be forwarded to server port 8080 (SNI proxy) and the data is encrypted between client and server.

**Comment by untoreh** [comment]
is there a way to choose the destination from the client?
