### ISSUE TITLE
域名分流功能

### ISSUE THREAD

**Issue by flyingwhitewhale** [ginuerzh/gost#143]
下一步是否考虑把域名分流集成进来
实现v2ray, https,SOCKS OVER TLS等TLS加密都能把客户端设为443，根据域名证书，分流到各自端口去呢，
尽量减少非HTTPS常见端口走TLS流量呢

**Comment by ginuerzh** [comment]
SNI?

**Comment by flyingwhitewhale** [comment]
sni 在gost如何实现根据域名分流呢？

比如我v2ray服务器端想实现www.abc.com  分流到 Vmess  10000端口
https代理想实现123.abc.com 分流到20000端口
命令应该怎么设置呢

**Comment by ginuerzh** [comment]
这个是负载均衡的一种方式，等负载均衡功能实现以后可以考虑支持

**Comment by jzp820927** [comment]
LS 说的应该是 智能路由。

**Comment by ginuerzh** [comment]
队，但在我看来这算是某种形式的负载均衡，都是将流量按照一定的规则进行分配

**Comment by jzp820927** [comment]
恩，叫法不一样，意思是一样的，这个功能对于一些有限制的代理来说也非常实用，可以绕过代理限值。

**Comment by flyingwhitewhale** [comment]
谢谢大佬，主要是希望能把多个支持TLS的代理工具都用443口走，然后到服务器端GOST来进行分流，回到自己 tcp-tls ,websocket-tls , https 的轨道内，走自己独立的端口，现在v2ray和nginx配合，已经可以实现多个三级域名进行不同的传输设置
