### ISSUE TITLE
HTTP 抢先发送数据

### ISSUE THREAD

**Issue by Max-Sum** [ginuerzh/gost#144]
常规的 HTTP 代理实现会等到代理服务器返回 200 OK 之后才开始发送数据。如果提前到连接完成后，直接开始发送数据，则可以减少一个RTT的时间。
![default](https://user-images.githubusercontent.com/4883681/29305901-9f63da1c-81cd-11e7-8815-2cf28cedb692.png)

通常情况下，这些预发送数据会被放到服务器的 TCP 缓存池中，不会造成问题。
唯一的问题是错误处理，如果代理无法连接目标服务器，或者代理密码错误，则后面发送的数据会被当做 HTTP 请求处理，自然就会出错了。出现这种情况的时候，直接关闭链接即可。

**Comment by Max-Sum** [comment]
如果接受这种优化方式的话，还可以做服务端的优化，即将 200 OK 的返回提前到与目标服务器链接完成前。如果链接出错或超时，则断开连接。

**Comment by ginuerzh** [comment]
下个版本会增加隧道转发功能 #142 ，如果使用转发方式的话，就可以实现0-RTT，转发隧道会直接将HTTP请求转发给目标主机，而忽略第一次的CONNECT请求。

**Comment by Max-Sum** [comment]
这样是不是就只能代理 http 或者 https 协议了呢？

**Comment by ginuerzh** [comment]
没有，这种是一种通用型的转发隧道，可以转发任何数据，不关心数据的类型。

**Comment by ginuerzh** [comment]
鱼与熊掌不可兼得
HTTP本身是标准协议，在代理链中有可能是其他类型的HTTP代理服务，如果不按常规来处理，可能会得不到期望的结果。
另外对于很多HTTP请求，浏览器都会缓存连接，因此第一次多一个RTT对于使用来说基本不会有什么影响。

**Comment by Max-Sum** [comment]
只是一个简单的推荐。我在自己的 http 代理上使用了这个特性，目前并没有发现有什么问题。可以考虑增加一个特殊选项设定是否开关。

**Comment by Justsoos** [comment]
据说google quic 正在实现这些降低握手损耗的技术，还包括更多协议栈算法优化，可以先不着急修改http这个老旧协议，等quic的革命就好。

**Comment by Max-Sum** [comment]
这个与 TCP 层面的优化并不矛盾，可以叠加 TCP False Start 等优化达成更好的效果。

**Comment by Max-Sum** [comment]
> It is legal for the client to send some data intended for the server
> before the "200 Connection established" (or any other success or
> error code) is received.

https://tools.ietf.org/html/draft-luotonen-web-proxy-tunneling-01

这个行为是被规范的合法行为，完全可以做。

**Comment by shellus** [comment]
为这个功能-1

对于实现不健壮的HTTP代理服务器，在它得到一个CONNECT请求后，应该是没有数据到达了。
但是如果是本ISSUE的请求，那么收到CONNECT请求后，紧跟着就是要发送的数据。这可能会让服务器误认为这些数据是CONNECT请求的Body部分，从而导致HTTP代理服务器进入异常流程。
这是一个危险的优化
