### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by testcaoy7** [ginuerzh/gost#145]
我设置了一个运行obfs4协议的服务器：
gost -L obfs4://user:userpassword@0.0.0.0:443

Windows客户端指令如下：
gost -L socks5://127.0.0.1:1082 -F "obfs4://user:password@（Public IP）:443/?cert=DfO8gCQWka73Op0W%2FoQQ2IyrheHRlkcqtYsHjW4K8kEJlwIi6%2BEtht%2FNPURd5XIahqZZfw&iat-mode=0"

看了一个YouTube视频后连接中断（看的时候速度飞快，>57000），提示“No connection could be made because the target machine actively refused it.”  

重启服务器后问题解决，请问是何原因造成该现象？

**Comment by ginuerzh** [comment]
有出错时候的LOG吗？

**Comment by testcaoy7** [comment]
当现象发生后，LOG信息里不再有新的 “地址<->网址” 和 “地址>-<网址”这样的信息，似乎只是服务器不响应了

**Comment by ginuerzh** [comment]
如果后面会自动恢复，那很有可能是你的网络问题。

**Comment by testcaoy7** [comment]
可能，不清楚obfs4是不是能真正避开DPI，或是已经可以被检测到了

请问有一个-obfs4-distBias的flag是有什么功能？

**Comment by ginuerzh** [comment]
我没有研究过obfs4，所以也不知道这些参数的用处。
