### ISSUE TITLE
socks5+wss 无法使用

### ISSUE THREAD

**Issue by flyingwhitewhale** [ginuerzh/gost#146]
socks5+wss没用过，因为跟ws相比胜在加密，看首页涉猎不多，自己尝试，服务器和客户端都是2.4 RC-2

服务器端
gost -L=socks5+wss://:1080

客户端
gost -L=:1080 -F= socks5+wss://x.x.x.x:1080

浏览器设定
socks5   127.0.0.1:1080

一直连不上，浏览器 提示
无法访问此网站

网址为 https://www.google.com/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_SOCKS_CONNECTION_FAILED

客户端提示见下图
![default](https://user-images.githubusercontent.com/30478118/29374900-a9aaefb0-82e5-11e7-852d-25cc9d64994c.JPG)

不知问题出在哪

**Comment by ginuerzh** [comment]
`gost -L=:1080 -F= socks5+wss://x.x.x.x:1080`
这里面的-F参数写的有问题，`-F=`与参数中间不能有空格。

**Comment by flyingwhitewhale** [comment]
谢谢大佬，果然，我也是醉了。。。
请教下大佬
socks5+ws 传输实际是没有加密的，用来上google，是不是很快vps的IP会被封掉
按照上回您的指点
如果想让 vps更安全，首选还是HTTPS，HTTP2， SOCKS-TLS，QUIC 以及WSS吧
刚才比较了下，这几种似乎速度没有很大差别，您的目的主要还是提供多个备选方案，没有倾向性的吧。
@ginuerzh

**Comment by ginuerzh** [comment]
区别无为就是加密和不加密，至于速度，不同的网络不同的区域直接有很大的差别，具体使用哪一种，就要自己去实验了。

**Comment by flyingwhitewhale** [comment]
明了，谢谢大佬，希望能继续保持更新，有这么多玩法的爱国软件太稀有了

**Comment by cod1ingcoding** [comment]
不过这个貌似貌似走不过cloudflare。
