### ISSUE TITLE
Consider using "classic" confinement for Ubuntu Snap

### ISSUE THREAD

**Issue by nobodyknowsus** [ginuerzh/gost#147]
The configuration file can't be placed in system /etc directory as limited to current "strict" confinement, which is inconvenient when setting Gost as a service. Please consider change the confinement in `snapcraft.yaml` to "classic" mode. Otherwise, please add a more specific error message. The current error message will just be "permission denied", which took me a time to find it related to snap confinement.

**Comment by ginuerzh** [comment]
I do not have a deep understanding of the use of this parameter, and I have changed it to classic, but the snap store rejected:
```
(NEEDS REVIEW) confinement 'classic' not allowed. If your snap needs classic confinement to function, please make a request for this snap to use classic by creating a new topic in the forum using the 'store' category and detail the technical reasons why classic is required. lint-snap-v2_confinement_classic

confinement 'classic' not allowed with plugs/slots lint-snap-v2_confinement_classic_with_interfaces
```
So I think it is not recommended to use the `classic` mode.
