### ISSUE TITLE
can i compile a version for mipsel

### ISSUE THREAD

**Issue by cutemanworking** [ginuerzh/gost#148]
how can i  compile a binary for my router which is based on mipsel cpu with debian 8?

**Comment by ginuerzh** [comment]
Do you mean `linux/mipsle`? 
Go 1.8 has supported it: https://golang.org/doc/go1.8#ports

**Comment by cutemanworking** [comment]
many thanks!

**Comment by cutemanworking** [comment]
编译时出以下错误，请问有什么建议?
./ss.go:87: undefined: shadowsocks.DialWithRawAddrConn

**Comment by cutemanworking** [comment]
finally compiled my own version. many thanks!!!!
