### ISSUE TITLE
QUIC传输不能用了

### ISSUE THREAD

**Issue by flyingwhitewhale** [ginuerzh/gost#150]
前几天刚在gost的服务器端把QUIC,WSS,HTTP2都写入了config，跟客户端配合良好，也成功设定开机自启了。
今天不知为何用客户端WSS,HTTPS都正常联网，用QUIC，浏览器反复提示ERR_SOCKS_CONNECTION_FAILED

客户端截图如下
![default](https://user-images.githubusercontent.com/30478118/29676705-5a155174-892b-11e7-8e9d-89aa5205aa53.JPG)

查看了下vps的端口，显示GOST正常监听QUIC的UDP端口，不知是哪出了问题，请大佬们指点一二，谢谢

**Comment by ginuerzh** [comment]
需要确认服务端是否运行正常。
简单的办法是在服务器端将quic转成其他协议，例如https：
`gost -L https://:1443 -F quic://:port`

客户端再使用https方式访问服务器，如果正常，则基本可以确认是网络问题。

**Comment by flyingwhitewhale** [comment]
还是不行，先替换2.4版本，重新看看，谢谢大佬
