### ISSUE TITLE
关于TLS的建议

### ISSUE THREAD

**Issue by testcaoy7** [ginuerzh/gost#151]
1、现有TLS依赖于证书。能否增加PSK方式，利用诸如TLS_PSK_WITH_AES_128_GCM_SHA256（RFC5487）这样的密码学套件，在没有证书的情况下进行TLS加密传输

2、能否增加TLS 1.3的支持

**Comment by pexcn** [comment]
等待中… https://github.com/golang/go/issues/9671

**Comment by xanadus0** [comment]
Go 官方已经支持 TLS 1.3 了
> As announced in Go 1.12, Go 1.13 enables support for TLS 1.3 in the crypto/tls package by default.
https://golang.org/doc/go1.13#tls_1_3
