### ISSUE TITLE
v2.4 cant find the pem or secrets.txt

### ISSUE THREAD

**Issue by cutemanworking** [ginuerzh/gost#152]
it seems that the latest version can't find the pem or secrests.txt. but the 2.4-rc2 is ok. 
2017/09/05 11:18:09 main.go:71: open /etc/gost/privkey.pem?secrets=/etc/gost/secrets.txt: no such file or directory

**Comment by ginuerzh** [comment]
What is the specific command line that reproduces this problem?

**Comment by cutemanworking** [comment]
i tried below testing:
![image](https://user-images.githubusercontent.com/20323985/30118004-6fa6d6ec-9354-11e7-919a-c9b2124fc004.png)
![image](https://user-images.githubusercontent.com/20323985/30118116-c0196e3c-9354-11e7-9c2a-af434a0cdb08.png)

**Comment by ginuerzh** [comment]
You should replace the `?` between `privkey.pem` and `secrets` with `&`.

**Comment by cutemanworking** [comment]
problem solved! sorry to bother you and thanks for your time!
