### ISSUE TITLE
FreeRadius auth

### ISSUE THREAD

**Issue by sfoxdev** [ginuerzh/gost#153]
Is there any posibility to add freeradius auth? I'm not familiar with GO, but saw that it possible in other project https://github.com/jamesboswell/caddy-radius

Why I'm asking - I have few socks5 proxies (dante) that auth users by one freeradius server. I tested Gost to forward from one to other server with auth and every time i need to start like:
1. At server side.
-L=socks5://test:test@:1080
2. At next hop
-L=test:test@:1080 -F=socks://test:test@<IP>:1080

I would happy to tell Gost use freeradius server for auth.

P.S: also I have question on how to forward from server to server without typing password, because at the end waiting socks5 proxy that authorize users

**Comment by ginuerzh** [comment]
The RADIUS may not match the positioning of this tool.

The forward tunnel mode will be added to version 2.5, then you can forward client data directly to target server:

Server side:
`gost -L socks5://test:test@:1080`

Client side:
`gost -L tcp://:8080 -F forward://server_ip:1080`

Now any data received from port 8080 will be forwarded to server_ip:1080.

**Comment by sfoxdev** [comment]
Thanks for reply, I'll wait for v2.5
