### ISSUE TITLE
2.4正式版启动不了

### ISSUE THREAD

**Issue by flyingwhitewhale** [ginuerzh/gost#154]
今天一看2.4出来马上把VPS上的GOST更新了，更新后systemctl restart gost
结果发现gost启动不了

[root /]# systemctl status gost
● gost.service - GO Simple Tunnel
   Loaded: loaded (/usr/lib/systemd/system/gost.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-09-05 10:14:22 EDT; 13s ago
  Process: 3232 ExecStart=/gost/gost -C /gost/config.json (code=exited, status=203/EXEC)
 Main PID: 3232 (code=exited, status=203/EXEC)

Sep 05 10:14:22 host.localdomain systemd[1]: Started GO Simple Tunnel.
Sep 05 10:14:22 host.localdomain systemd[1]: Starting GO Simple Tunnel...
Sep 05 10:14:22 host.localdomain systemd[1]: gost.service: main process exited, code=exited, status=203/EXEC
Sep 05 10:14:22 host.localdomain systemd[1]: Unit gost.service entered failed state.
Sep 05 10:14:22 host.localdomain systemd[1]: gost.service failed.

Exit code: 3

不知什么问题，请教大佬，谢谢

**Comment by flyingwhitewhale** [comment]
我的是Centos 7 x86_64 bbr  ，firewalld暂时关闭下也无法启动,
反复重启vps也无法解决问题     @ginuerzh

**Comment by flyingwhitewhale** [comment]
chmod +x gost
解决问题，顺便解决了2.4 rc2版碰到的QUIC不能用的问题

**Comment by asins** [comment]
/usr/lib/systemd/system/gost.service  这个文件能提供下吗？

新人不知怎么写成服务在后台自动启动
