### ISSUE TITLE
ssh forwarding over kcp

### ISSUE THREAD

**Issue by untoreh** [ginuerzh/gost#155]
is it possible to forward ssh over kcp ?

**Comment by ginuerzh** [comment]
There is no problem in theory, but that is not the intention of this tool.

**Comment by prehistoric-penguin** [comment]
@ginuerzh I am new to gost, after viewed the doc, I am still confusing. Can you please explain  the command `gost -L :8080 -F kcp://:8388 -F ssh://:2222` , is it the server side command? Then how to use the client? 

Thanks in advance!
