### ISSUE TITLE
使用gost作为shadowsocks服务器端时连接只能保持30秒

### ISSUE THREAD

**Issue by cyilin** [ginuerzh/gost#158]
gost版本2.4（badf099）
运行gost服务器端和客户端
```
gost -D -L=ss://chacha20:password@:8000
gost -D -L=:1080 -F=ss://chacha20:password@127.0.0.1:8000
```
使用curl下载一个文件
```
curl --socks5-hostname 127.0.0.1:1080 --limit-rate 1024k -o test http://speedtest.singapore.linode.com/100MB-singapore.bin                         
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 30  100M   30 30.7M    0     0  1023k      0  0:01:40  0:00:30  0:01:10 1027k
curl: (18) transfer closed with 72659070 bytes remaining to read
```

改为ssh或socks5协议不会出现30秒断开的情况。

**Comment by cyilin** [comment]
看上去gost在ss连接后设置了30秒超时，https://github.com/ginuerzh/gost/blob/master/ss.go#L175 更改这里的时间后可以使ss的连接保持更长时间了

而shadowsocks-go是每次数据转发时更新超时时间
https://github.com/shadowsocks/shadowsocks-go/blob/master/shadowsocks/pipe.go#L23

**Comment by ginuerzh** [comment]
是这地方的问题，不过不是时间长短的问题，是后面获取到客户端的请求后没有清除这个超时定时器。

shadowsocks-go应该也会出现这个问题，虽然每次读到数据后就更新，但对于下载来说数据是单向的，服务端是读不到客户端的数据的，所以如果设置了超时，下载时间过长，也是会断开的。

**Comment by asins** [comment]
我在brew update时遇到同样的问题，有办法解决这问题吗？一单被标注为超时，那原有的续传能力都丢失了。

**Comment by cyilin** [comment]
@asins 作者已经修复了这个问题，只是没有发布新版本。你可以自己从源代码编译一份最新版。

**Comment by asins** [comment]
没写过go语言，不知如何编译，能提供一份linux centos下的版本嘛
