### ISSUE TITLE
请求添加狗洞P2P协议支持

### ISSUE THREAD

**Issue by shellus** [ginuerzh/gost#159]
狗洞p2p，请求添加支持。
https://github.com/vzex/dog-tunnel

用起来像这样 -F dt://<remote_server>/<tunnel_name>

就可以实现使用另一台**内网机器作为代理节点**了。

**Comment by ginuerzh** [comment]
虽然是P2P，但还是需要一个中间服务器进行协助。
P2P的复杂度很高，在复杂的网络下很难保证稳定性，一般用户也基本上用不到。
另外我也没有想好怎么去集成，短期不会考虑。
当然，如果有好的建议也欢迎提出！

**Comment by shellus** [comment]
> P2P的复杂度很高

狗洞也是go语言开发，直接使用它的代码即可。

> 在复杂的网络下很难保证稳定性

狗洞支持无法P2P则使用服务器代理的机制，所以是百分百成功的

**Comment by ssfdust** [comment]
其实，如果真的那么需要，可以自己写一个，然后提交pull request啊。ginuerzh不想弄，就别强人所难了。

**Comment by shellus** [comment]
是的，但是在我动手之前，我需要先询问是否可能被接受，和确定集成方案。

**Comment by ginuerzh** [comment]
欢迎提交PR，方案可以自己定，一起评估。
