### ISSUE TITLE
请问自己的服务器上能搭载Gost吗？

### ISSUE THREAD

**Issue by 5points** [ginuerzh/gost#16]
我有自己的服务器，是centos6的系统，请问可以搭建Gost吗

**Comment by ginuerzh** [comment]
可以用，
使用gost v1.8版，
32-bit (https://github.com/ginuerzh/gost/releases/download/v1.8/gost_1.8_linux_386.tar.gz)
64-bit (https://github.com/ginuerzh/gost/releases/download/v1.8/gost_1.8_linux_amd64.tar.gz)
服务器端运行：gost -L :9999 -tls
客户端运行：gost -L :8899 -S your.server.ip:9999 -tls
设置好本地代理为localhost:8899就可以了

**Comment by 5points** [comment]
谢谢解答^ ^
