### ISSUE TITLE
希望添加自动切换线路功能

### ISSUE THREAD

**Issue by yknext** [ginuerzh/gost#161]
最近服务不是很稳定，经常需要手动切换，希望可以添加多个出口自动切换功能
比如可以配置多个ChainNodes
根据优先级、可用性自动切换可用的服务器
    "ChainNodesList": [
         ["socks5://172.24.10.1:1080"],
         ["socks5://172.24.10.2:1080"],
         ["socks5://172.24.10.3:1080"]
]
可用性检测可以配置一个网址，定时去检测比如google
我目前是写了一个脚本，定时切换，但这样并不完美，
要同时运行多个gost实例去连接多个服务器

`#!/bin/bash

declare -a socks5_list=(
"socks5://127.0.0.1:1084"
"socks5://127.0.0.1:1082" # hk1
"socks5://127.0.0.1:1083" # us1
"socks5://127.0.0.1:1081" # v2ray gs
"socks5://127.0.0.1:1080" # v2ray www
)

proxy=`cat /opt/gost/config.json | jq '.ChainNodes[0]'`
status=0      
check_times=3 # if fail times
sleep_sec=5  # sleep secound
while [[ $check_times -gt 0 ]]; do
  #echo "check proxy : $proxy"
  curl -sSf --socks5-hostname $proxy www.google.com > /dev/null || status=$?
  if [[ $status -ne 0 ]]; then
    date
    echo "check again ..."
    let check_times=check_times-1
	if [[ $check_times -ne 0 ]]; then
	  sleep $sleep_sec
	fi
  else
    #echo 'proxy is ok '
    exit 0
  fi
done

 check status
if [[ $status -ne 0 ]]; then
  echo "switch proxy ..."
  for i in "${socks5_list[@]}"
  do
    echo 'check proxy list at: '$i
	status=0
	curl -sSf --socks5-hostname $i www.google.com > /dev/null || status=$?
	if [[ $status -eq 0 ]]; then
	  echo 'switch to '$i
	  F='"'
	  jq_reg='.ChainNodes[0]='$F$i$F
	  tmp=$(mktemp)
	  jq $jq_reg /opt/gost/config.json > "$tmp" && mv "$tmp" /opt/gost/config.json
	  supervisorctl restart gost
	  echo 'switch to : '$i | mailx -v -s 'Switch Notify' mail@gmail.com
          exit 0
	fi
  done
fi`

**Comment by ginuerzh** [comment]
后面会支持负载均衡

**Comment by yknext** [comment]
@ginuerzh 如果后端的外网IP不一致的话，负载均衡在一些服务可能出问题，比如google，频繁提示验证码

**Comment by ginuerzh** [comment]
负载均衡与线路切换不冲突，可以在负载均衡之上增加优先级控制，现阶段只关注负载均衡。

**Comment by ginuerzh** [comment]
关于会话保持的讨论，请移步 #235
