### ISSUE TITLE
这个报错是什么情况，连上之后没网络

### ISSUE THREAD

**Issue by forestzhang945** [ginuerzh/gost#165]
![image](https://user-images.githubusercontent.com/9585063/31715781-afa4b3a0-b437-11e7-8dcd-48d962391318.png)

**Comment by ginuerzh** [comment]
客户端和服务器的运行参数是什么

**Comment by forestzhang945** [comment]
![image](https://user-images.githubusercontent.com/9585063/31755463-2fcae380-b4d1-11e7-97b6-a973535687c4.png)
两段加密信息设置不一致连接会导致报错进程中断吗？

**Comment by ginuerzh** [comment]
这种情况出现了panic是个BUG
