### ISSUE TITLE
这个软件可否当作帽架使用？

### ISSUE THREAD

**Issue by Just2co** [ginuerzh/gost#166]
我这里有几个sock5高速稳定代理，能否通过这个软件转换成http代理，作为goagent梯子的前置？突破GFW封锁？请了解的朋友帮忙安利一下！

**Comment by 2378** [comment]
关注一下

**Comment by ginuerzh** [comment]
可以互相转换：
`gost -L=:8080 -F=socks5://socks_ip:port`
这样8080端口就是一个HTTP代理服务。

**Comment by Just2co** [comment]
@ginuerzh socks4协议支持不?比如 gost -L=:8080 -F=socks4://socks_ip:port

**Comment by ginuerzh** [comment]
支持
