### ISSUE TITLE
~

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#167]

**Comment by ginuerzh** [comment]
不太明白是什么意思，你是希望行为是这样的还是不希望？

**Comment by f4nff** [comment]
是希望 host: = www.baidu.com

希望 host 可以自定义指定域名,

**Comment by ginuerzh** [comment]
这种情况下，是直接通过指定的ip来连接目标地址，host在这个过程中不会起到任何作用，与混淆也没有任何关系。可以简单的理解为自定义DNS负载均衡。

**Comment by f4nff** [comment]
知道不会起作用,但是很多网络是host进行检测白名单的,比如免流,
