### ISSUE TITLE
不能连接到服务器。

### ISSUE THREAD

**Issue by ssfdust** [ginuerzh/gost#17]
Server:CentOS 6.5 gost_1.8
    gost -L=:8080 -tls

Client :Windows 7 & Archlinux gost 1.8
  gost.exe -L=:8899 -S=104.238.xxx.xxx:8080 -tls
Explorer:Chrome & SwithyOmega Plugin
method:http/https/socks 127.0.0.1 8899

Client Log：
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:06 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:05:36 client.go:175: malformed HTTP request "\x04\x01\x00Pӓ\x04\x1f\x00"
2015/09/21 13:07:11 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:07:11 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:07:11 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:07:11 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:07:11 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:07:11 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:07:41 client.go:175: malformed HTTP request "\x04\x01\x01\xbb\x05\t\xfa\xa4\x00"
2015/09/21 13:11:04 client.go:235: GetAddrInfoW: No such host is known.
2015/09/21 13:11:34 client.go:175: malformed HTTP request "\x04\x01\x01\xbb\x05\t\xfa\xa4\x00"

Linux下和Windows下报错一致。服务器能ping的通，ss代理正常。使用gost的时候，http代理和tls代理报错是一致的，我不清楚是哪里的问题。另外，服务器的gost没有任何日志输出。

**Comment by ginuerzh** [comment]
客户端机器是否有代理?

**Comment by ssfdust** [comment]
没有，目前 只开启了gost。

**Comment by ssfdust** [comment]
我不知道发生了什么,但是它工作了...
Holy shit..
Closed
