### ISSUE TITLE
建议增加路由功能

### ISSUE THREAD

**Issue by tsln1998** [ginuerzh/gost#171]
原因嘛。。说正当点是为了绕过部分无须代理的网站。。

**Comment by xxxman2008** [comment]
外面有很多方案了，我觉得，作者把单一的这个 功能，做好，做完美，文档做完整，就是一件很好的事情了。至于附加功能。。要不让作者收费吧。。哈哈哈。

现在 文档，尤其是配置说明文档。。唉。还是太烂。

**Comment by tsln1998** [comment]
有道理。。说明文档确实有点。。。。有空我fork过去改改

**Comment by ginuerzh** [comment]
2.6分支已经增加路由控制功能，使用方法请参考：
https://docs.ginuerzh.xyz/gost/bypass/
