### ISSUE TITLE
gost 2.4 , broken pipe after running minutes later.

### ISSUE THREAD

**Issue by xxxman2008** [ginuerzh/gost#172]
github 下载的 GOST 2.4 windows x64版本。

Server   ：  KCP 侦听 443端口   (Debian 8 X64  ,升级到最新的 内核, 开IPV6 )
Client ：  -L 本地1080   -F = KCP://serverip:443   
中国电信线路。server和client 运行目录下，均存在相同 KCP.JSON
KCP配置参数：｛
        "key": "自定义",
	"crypt": "aes192",
	"mode": "fast",
	"mtu" : 1400,
	"sndwnd": 2048,
	"rcvwnd": 2048,
	"datashard": 10,
	"parityshard": 3,
	"dscp": 0,
	"nocomp": false,
	"acknodelay": false,
	"nodelay": 0,
	"interval": 40,
	"resend": 0,
	"nc": 0,
	"sockbuf": 4194304,
	"keepalive": 10,
	"snmplog": "",
	"snmpperiod": 60
｝
问题：一段时间以后，会出现 “broken pipe”

socks.go:417: [socks5-connect] 192.168.1.208:4785 -> groups.google.com:443 : broken pipe
socks.go:417: [socks5-connect] 192.168.1.208:4675 -> clients4.google.com:443 : broken pipe
socks.go:417: [socks5-connect] 192.168.1.208:4791 -> clients4.google.com:443 : broken pipe
socks.go:417: [socks5-connect] 192.168.1.208:4687 -> groups.google.com:443 : broken pipe
socks.go:417: [socks5-connect] 192.168.1.208:4724 -> groups.google.com:443 : broken pipe
socks.go:417: [socks5-connect] 192.168.1.208:4823 -> groups.google.com:443 : broken pipe
socks.go:417: [socks5-connect] 192.168.1.208:4866 -> clients4.google.com:443 : broken pipe
socks.go:417: [socks5-connect] 192.168.1.208:4887 -> groups.google.com:443 : broken pipe
socks.go:417: [socks5-connect] 192.168.1.208:4924 -> clients4.google.com:443 : broken pipe
socks.go:417: [socks5-connect] 192.168.1.208:4963 -> groups.google.com:443 : broken pipe

**Comment by ginuerzh** [comment]
KCP的问题请移步https://github.com/xtaci/kcptun/issues
