### ISSUE TITLE
example中Serve的接口不对

### ISSUE THREAD

**Issue by vinllen** [ginuerzh/gost#174]
example的Serve接口是2个参数，一个是处理本地的连接，一个是处理远端的连接。s.Serve(ln, h)。
但是代码server.go里面的Serve只接收一个Handler参数：func (s *Server) Serve(h Handler) error。
请问是接口更改了吗？

**Comment by ginuerzh** [comment]
example中的代码比较老了，后面也没有去更新了。

**Comment by vinllen** [comment]
@ginuerzh 那请问有最新的例子吗，比如tcp转发：接受一条tcp连接，转发至另外一个tcp端口

**Comment by ginuerzh** [comment]
最好的例子是 https://github.com/ginuerzh/gost/blob/master/cmd/gost/main.go
所有支持的协议都在这里面

**Comment by vinllen** [comment]
@ginuerzh 好的，我学习一下，谢谢了
