### ISSUE TITLE
一些杂七杂八的问题。

### ISSUE THREAD

**Issue by xxxman2008** [ginuerzh/gost#175]
环境情况：
Oversea Server （出口），跳板机（阿里云，中间Bridge），客户端（侦听本地SOCKS5 ，-F 到跳板机）

客户端在空闲一段时间后，总是会出现 类似如下的错误消息
2017/11/02 18:04:35 socks.go:417: [socks5-connect] 192.168.1.208:10992 -> www.google.com:443 : NetworkIdleTimeout: No recent network activity.
2017/11/02 18:04:48 socks.go:417: [socks5-connect] 192.168.1.208:10998 -> google.com:443 : 503 Service unavailable
2017/11/02 18:04:48 socks.go:417: [socks5-connect] 192.168.1.208:10994 -> www.google.com:443 : 503 Service unavailable

我确实在 “客户端-->跳板机-->出口  ”  分别使用过  KCP/QUIC/SS 进行连接，都出现过短暂断开（ 没有仔细分析过断开的原因。）。所以，不能保证上诉错误一定是在 KCP的情况下独有的。

整合 最近几天的使用情况，提出建议如下：

1、补充，细化一下配置文档。现在的说明文档有点含糊不清。建议 将配置分成2个部分，一个是 Global范围的 ，比如 TLS文件配置，用户名及密码文本，KeepAlive或者Ping包或者心跳包 的 间隔。。第二部分是某些协议特有的配置，比如 KCP.JSON 什么的。 有可能的话，也请对 gost使用配置文件的 方法及格式作详细说明。

2、可以增加一个 维持链接 的 配置，由用户设定一个 URL  ，由系统定时去获取数据。这样可以第一时间在系统内部 发现 远程tunnel（就这样表述吧，大家懂的） 的 错误，并加以处理。

**Comment by ginuerzh** [comment]
NetworkIdleTimeout: No recent network activity.这种错误是在哪种模式下报的？像KCP, QUIC是基于UDP的，所以内部会有超时机制。

1. 文档会在后面不断完善。
2. 对于短连接的协议，即使检测到出错也不能做什么。对于长连接协议(有心跳包可以自动检测连接状态。

**Comment by kirbyzhu** [comment]
@ginuerzh 有个奇怪的问题，我客户端用2.4dev0303的那个版本可以正常运行的命令，换成2.4最新的之后就闪退了。是有命令格式调整么？

**Comment by ginuerzh** [comment]
是的，中间进行了一次较大的重构，参数有变，可以用`gost -h` 查看。

**Comment by xxxman2008** [comment]
目前，客户端（win10） 执行的命令是 gost -L=sock5://:1080 -F=quic://跳板机IP：port  -D=false，，NetworkIdleTimeout: No recent network activity.这种错误就是  是在这种模式下报的。

**Comment by ginuerzh** [comment]
目前所使用的QUIC版本，默认1分钟无数据交互服务器端会关闭连接。
可以通过在客户端设置keepalive参数来发送心跳保持连接：
```
gost -L=sock5://:1080 -F=quic://ip:port?keepalive=1
```

**Comment by xxxman2008** [comment]
OK ，我试一试， keepalive 的单位是 “分钟”？？通常不应该是 秒么？

另外，刚才发现另外一个现象。
上面提到，如果闲置一段时间，会出现“超时”，通常情况下，此时刷新一下页面，gost 会自动重连。但是，。。。。偶尔会出现即使刷新页面，也无济于事，此时从  gost 的log 来看，好像通路是正常的，但是，客户端浏览器还是无法获取到页面。

只有重启GOST 进程，才能解决上面的问题。
上诉情况，或许是windows 特有的。因为 在 跳板机和 出口服务器上，linux 下，gost 好像都能比较正常的 长时间工作。

**Comment by ginuerzh** [comment]
keepalive是个标志，开或不开心跳检测，这一版的quic中无法设置超时时长和心跳频率。

这个现象需要具体的复现流程。

**Comment by xxxman2008** [comment]
嗯。其实，这个问题，我有一个和你不同的思路，但是，因为我不会GO ，再说，看人家代码都挺累。哈哈哈。。所以。。

我的猜测，会不会是  本地SOCK代理/PROXY1/PORXY2/PROXY[N]。。。。之间session 不同步导致的。。
你看，有这样的一种可能，就是 远程出口服务器断开了 和webserver（比如谷歌）的连接，但是，这个“断开”，没有（或者是无法）忠实的反馈回  客户端。。然后。导致了这个现象。

Anyway 。。这个对使用稍微有点影响，不过可以凑合着用。
