### ISSUE TITLE
quic首包丢失会卡住无法使用

### ISSUE THREAD

**Issue by ranbochen** [ginuerzh/gost#177]
这应该是go-quic包的一个bug，
当首包丢失时，HandshakeTimeout机制会失效,Ｄial就一直卡住
不知道新版本有没有修改这个bug,可以尝试更新下依赖库

https://github.com/ginuerzh/gost/blob/484aa888d0c66388a7a2b1a3adab54c17a365c01/quic.go#L122-L126

**Comment by ginuerzh** [comment]
我测试没发现有这个问题。

**Comment by ranbochen** [comment]
出bug时wireshark抓包发现第一个包发出去了(Client hello)，之后没有任何UDP包发送，
然后dial一直卡住没返回（我在代码中添加了begin Dial 和 end Dial日志）

我用quic测试拨号到一个不存在的UDP地址，
新版本返回handshaketimeout错误，
集成的旧版本是idletimeout
这种测试中wireshark抓到发送了很多次udp包，这点跟出bug时表现不一样

更新下quic库之后用了3天没出现，新版库应该是解决了，
总之，更新到新版本quic库吧
