### ISSUE TITLE
请教下BT流量下的应用如何优化

### ISSUE THREAD

**Issue by kslr** [ginuerzh/gost#178]
我这里使用Socks5 Auth为BT程序做代理，流量在30/M左右。
从日志记录可以看到大量的超时和连接被关闭。
ulima -n 已经设置了955360
```shell
gost -L=socks5://test:test123@:1080
```

**Comment by ginuerzh** [comment]
BT网络是点对点传输的，整个网络是动态的，客户端获取到的节点列表会存在一些已经失效的节点，所以这种情况是正常的。
