### ISSUE TITLE
gost tls客户端不指定证书，也能连接是什么原因

### ISSUE THREAD

**Issue by yuan78** [ginuerzh/gost#18]
我用的是1.8版的，服务器端用了自己签发的证书，并用gost tls 命令指定了证书路径并成功运行，但是发现gost tls客户端不指定证书，也能连接是什么原因？这样岂不是没有安全性可言，请尽快修复这个bug.

**Comment by ginuerzh** [comment]
为了使用方便，目前版本中内置了一个默认的证书。
如果担心数据安全，可以提供自己的证书文件
