### ISSUE TITLE
最希望的功能

### ISSUE THREAD

**Issue by moorn** [ginuerzh/gost#180]
能否像cow那样实现自动分流，直连，被墙的时候自动代理，可以指定direct，proxy，reject名单，最想要的功能，谢谢！

**Comment by ginuerzh** [comment]
gost的关注点是隧道本身，而不会去考虑目标地址的状态。

**Comment by moorn** [comment]
@ginuerzh 如果实现此功能，放在路由器上全局或者随便什么设备，不用考虑代理问题，实现了自动分流，所有上网设备访问互联网畅通无阻，非常方便，目前没有很好的实现此功能的软件，大都是需要判定白名单黑名单IP类的软件，没有完美的实现自动化的，cow不更新了，meow删了，TcpRoute2也不怎么更新，使用起来都有问题，gost加上此功能，就完美了，并不影响关注点是隧道本身，希望大神考虑下,谢谢！

**Comment by ginuerzh** [comment]
检测目标主机状态本身是一个复杂的工作，如果再引入复杂的代理链，就更加难以判断。
即使做这项功能，独立成一个新项目会是更好的办法。这个项目就保持其单一性吧！
