### ISSUE TITLE
本地使用gost 将https 443端口转发使用shadow使用

### ISSUE THREAD

**Issue by drcayman** [ginuerzh/gost#182]
C:\gost.exe -L :1080 -L http2://:443/:1080 -F ss://aes-256-cfb:xxxx@xx.xx202.138:443

这样使用是不可以使用的  应该如何使用？

**Comment by drcayman** [comment]
@sheerun

**Comment by ginuerzh** [comment]
若你指的是将本地443端口映射到远程的1080端口：
```
gost -L tcp://:443/:1080 -F ss://aes-256-cfb:xxxx@xx.xx202.138:443
```
