### ISSUE TITLE
关于 json 配置文件的建议？

### ISSUE THREAD

**Issue by jzp820927** [ginuerzh/gost#183]
目前用 gost 运行了多条不同的转发规则，现在的方式是运行了多个 gost 的进程，每个进程运行一条转发规则。我在想，能不能把 json 配置文件的功能增强一下，把多条转发规则都写到一个 json 的配置文件里面，然后通过指定的配置文件运行一个 gost 进程，然后这一个 gost 的进程可以同时运行配置文件里面的多个转发规则。目前运行多个 gost 进程感觉对资源造成无意义的浪费，而且管理起来也比较麻烦，每个进程都要独自管理，很不方便。

配置文件类似下面这样，也就是用数组来配置多条规则，规则之间互相独立，每条规则实现不同的功能：
{
　　{
　　　　"ServeNodes": [
　　　　　　":8080",
　　　　　　"ss://chacha20:12345678@:8338"
　　　　],
　　　　"ChainNodes": [
　　　　　　"http://192.168.1.1:8080",
　　　　　　"https://10.0.2.1:443"
　　　　],
　　　　"Debug": true
　　},
　　{
　　　　"ServeNodes": [
　　　　　　":8081",
　　　　　　"ss://chacha20:12345678@:8338"
　　　　],
　　　　"ChainNodes": [
　　　　　　"http://192.168.1.2:8080",
　　　　　　"https://10.0.2.2:443"
　　　　],
　　　　"Debug": true
　　},
　　{
　　　　"ServeNodes": [
　　　　　　":8082",
　　　　　　"ss://chacha20:12345678@:8338"
　　　　],
　　　　"ChainNodes": [
　　　　　　"http://192.168.1.3:8080",
　　　　　　"https://10.0.2.3:443"
　　　　],
　　　　"Debug": true
　　}
}

**Comment by fredericky123** [comment]
想顺便问下J大，能否给出gost用于gae的配置文件，gp不开发了，希望能继续使用gae，谢过J大

**Comment by ginuerzh** [comment]
这个可以试一下

**Comment by jzp820927** [comment]
感觉作者答复，能实现就好，期待，谢谢！

**Comment by yyfearth** [comment]
这个也是我很需要的一个功能 这样就不用多个进程了

不过 @jzp820927 你的例子有问题，你这样写，最外层应该是个数组，所以应该用 `[...]` 而不是 `{...}`

**Comment by ginuerzh** [comment]
dev分支已经支持多组配置，格式为：
```json
{
    "Debug": true,
    "ServeNodes": [
        ":8080",
        "ss://chacha20:12345678@:8338"
    ],
    "ChainNodes": [
        "http://192.168.1.1:8080",
        "https://10.0.2.1:443"
    ],
    "Routes": [
        {
            "ServeNodes": [
                "ws://:1443"
            ],
            "ChainNodes": [
                "socks://:192.168.1.1:1080"
            ]
        },
        {
            "ServeNodes": [
                "quic://:443"
            ]
        }
    ]
}
```

在原配置文件格式上增加一个Routes字段，Routes中的每一项代表一条独立的转发规则。这样可以保持与原配置兼容。

由于Debug选项是全局共享的，所以只会使用最外层的Debug参数设置。

**Comment by jzp820927** [comment]
@ginuerzh 非常感谢，马上测试。
@yyfearth 没深入研究 json 的语法，只是大概写个样子，把意思表达出来而已。
