### ISSUE TITLE
【功能申请】只让部分流量经过上游代理

### ISSUE THREAD

**Issue by kingname** [ginuerzh/gost#184]
在设置了上游代理的情况下，如何只让符合特定规则的HTTP/HTTPS请求经过上游代理，其他的HTTP/HTTPS请求直接访问。

例如我要访问A网站，网站里面有很多的Ajax异步请求。我只想让其中的一条异步请求经过上游代理，而其他的请求全部直接访问。

**Comment by ginuerzh** [comment]
这个可以通过外部工具实现，现阶段暂不考虑。

**Comment by zw0** [comment]
surge?
