### ISSUE TITLE
socks5 server : bad version error

### ISSUE THREAD

**Issue by xxxman2008** [ginuerzh/gost#186]
环境描述：client 端，win10  ，最新补丁，执行命令如下
gost -L=socks5://:1080 -F=quic://aliyunip:1091 -D=false

浏览器：chrome + SwitchyOmega 插件（管理proxy）

client 不定时 ，出现如下错误 : 
 16:45:16 socks.go:437: [socks5-connect] 内网208:6006 >-< notifications.google.com:443
 16:45:16 socks.go:437: [socks5-connect] 内网208:6010 >-< play.google.com:443
 16:45:44 socks.go:437: [socks5-connect] 内网208:7095 >-< www.facebook.com:443
 16:46:00 socks.go:435: [socks5-connect] 内网208:7587 <-> ichef-1.bbci.co.uk:443
 16:46:11 socks.go:435: [socks5-connect] 内网208:7609 <-> ichef.bbci.co.uk:443
 16:46:21 socks.go:435: [socks5-connect] 内网208:7661 <-> www.bbc.com:80
 16:46:43 socks.go:437: [socks5-connect] 内网208:5129 >-< clients4.google.com:443
 16:46:54 socks.go:378: [socks5] Bad version
 16:47:13 socks.go:378: [socks5] Bad version
 16:47:51 socks.go:378: [socks5] Bad version
 16:47:51 socks.go:437: [socks5-connect] 内网208:5565 >-< www.voachinese.com:443
 16:47:51 socks.go:437: [socks5-connect] 内网208:5489 >-< www.voachinese.com:443
 16:47:51 socks.go:437: [socks5-connect] 内网208:5581 >-< www.voachinese.com:443
 16:47:51 socks.go:437: [socks5-connect] 内网208:5579 >-< www.voachinese.com:443
 16:47:57 socks.go:378: [socks5] Bad version
 16:48:21 socks.go:378: [socks5] Bad version
 16:48:28 socks.go:378: [socks5] Bad version
 16:49:21 socks.go:378: [socks5] Bad version
 16:50:06 socks.go:437: [socks5-connect] 内网208:5585 >-< gdb.voanews.com:443
 16:50:06 socks.go:437: [socks5-connect] 内网208:5587 >-< gdb.voanews.com:443
 16:50:06 socks.go:437: [socks5-connect] 内网208:5589 >-< gdb.voanews.com:443

**Comment by ginuerzh** [comment]
这个要确认是否有其他程序也在向这个端口发送数据。

**Comment by recall704** [comment]
我遇到过这个错误，原因是：
服务器使用了 协议 a， 但是客户端填写了协议 b
