### ISSUE TITLE
遇到一个问题，问问作者看能不能解决？

### ISSUE THREAD

**Issue by jzp820927** [ginuerzh/gost#187]
gost -L=:8080 -F=192.168.1.1:8081
我用的 -F 后面的 http 代理是不支持 CONNECT 方法的，因为只代理 http 协议，不代理 tcp，所以也用不着 CONNECT。

虽然我也看到了项目首页 README.md 中倒数第二行，有说明 “代理链中的HTTP代理节点必须支持CONNECT方法。” 不过还是希望作者，看能不能增加个参数，通过参数的方式来指定后端代理请求数据时所用的 Method 。非常感谢！

参数可以像下面这样：
gost -L=:8080 -F=192.168.1.1:8081?method=get

**Comment by ginuerzh** [comment]
当前条件其实已经放宽了，当代理链的最后一个代理节点是HTTP时，会直接将HTTP请求转发给这个节点，所以一般的非443端口的请求都是原始的HTTP请求，只有HTTPS（一般为443端口）才是CONNECT方法。

**Comment by jzp820927** [comment]
这个我倒是发现了，只是我的用法有点奇葩，前一跳代理必须用 socks5 协议，后一跳又不支持 CONNECT。
所以我的用法是：
规则：gost -L=:8080 -F=192.168.1.1:8081
流程：上级应用用 socks5 协议连接 gost 的 8080 端口，然后 gost 转到 后一级 http 代理的 8081 端口。
通过测试我发现，如果用 http 协议的 8080 端口来连 gost 是正常的，应该就是你上面说的 “当代理链的最后一个代理节点是HTTP时，会直接将HTTP请求转发给这个节点” 的情况，但是用 socks5 的时候，就不行了，我观察 gost 的日志发现是：
socks.go:437: [socks5-connect] 127.0.0.1:45664 >-< www.example.com:80
socks5 协议的时候是用的 connect，所以我想，是不是转到 -F 后面节点的时候，也是用的 connect 的方法，导致失败了，不知道能不能解决这个问题？

**Comment by ginuerzh** [comment]
是的，这个功能只对HTTP代理服务有效。
SOCKS5是通用代理协议，其上所传输的数据格式对它来说都是未知的。

不过你可以尝试在中间加一个SNI代理：
gost -L :8080 -F sni://:1443

gost -L sni://:1443 -F 192.168.1.1:8081

SNI代理如果收到一般的HTTP请求，就会按普通的HTTP代理来处理。

**Comment by Justsoos** [comment]
按协议说明，我记得，http 代理如果不支持 connect 方法，是不能代理 https 这种加密协议的，只能代理明文 http，和具体端口无关。 所以，也不至于有楼主的这个需求的实现。

**Comment by jzp820927** [comment]
@ginuerzh 好的，谢谢提供解决方案，我空了试试，非常感谢。

**Comment by jzp820927** [comment]
@ginuerzh 刚刚用你提供的方法测试了一下，倒是成功把 CONNECT 请求转换为普通的 GET 请求了，但还是有点问题，不能成功访问请求的网站。

我查看了一下末端代理的日志，也就是 192.168.1.1:8081 的日志
正常情况下的请求日志是下面这样
2017/11/27 21:26:07 GET http://www.example.com/images/1.jpg

用了 gost + sni 转了一下后，请求日志变成下面这样了，好像主机名丢失了？
2017/11/27 21:36:43 GET /images/1.jpg

**Comment by ginuerzh** [comment]
你用的是最新代码吗，后面我有做修改，会把地址转成绝对地址。

**Comment by jzp820927** [comment]
不好意思，近段时间工作比较忙，一直没时间来 github 上回复，那我用最新的 dev 分支的源码，直接编译测试一下，再来反馈，谢谢！

**Comment by jzp820927** [comment]
刚刚测试了几次，确实是用的最新源代码，不过我好像找到了导致问题的原因，如果我用一般的普通的 url 地址测试，比如：http://www.example.com/images/1.jpg 这类普通的绝对地址，没啥问题，但是如果 url 有 302 跳转的话，在重新请求跳转后的地址的时候，就会丢失主机名

日志的话，就是像下面这样：
直接用后端代理（192.168.1.1:8081）的正常日志是这样：
2017/12/06 16:10:26 GET http://www.example.com/
2017/12/06 16:10:26 GET http://www.example.com/zh/

用 gost + sni 转到后端代理（192.168.1.1:8081）的时候，日记就变成下面这样了
2017/12/06 16:10:54 GET http://www.example.com/
2017/12/06 16:10:55 GET /zh/

可以明显看出来，第一次请求是正常的，然后 302 再次请求的时候，主机名就丢了。
还请 @ginuerzh 看看，问题出在哪儿，该怎么解决，谢谢！
