### ISSUE TITLE
Q: 是否支持通过ssr/ss的socks5的UDP转发？

### ISSUE THREAD

**Issue by Justsoos** [ginuerzh/gost#189]
用了软件，好用！感谢作者
有个问题：
用
`$ gost.exe -L=tcp://:3333/8.8.8.8:53?ttl=60 -F=socks5://127.0.0.1:1080`
转发本地tcp查询，走ssr/ss的socks5没问题。
但
`$ gost.exe -L=udp://:3333/8.8.8.8:53?ttl=60 -F=socks5://127.0.0.1:1080`
无效。看了gost介绍，可能**只支持gost自建的socks5**（？），由于ssr/ss也能转发udp，但不知道是否也在支持内？换句话说，其他socks5程序在远程服务端，没有建立udp通道，而gost 的远程服务端建立了这个通道。
或者，是我命令使用问题，由于udp是无连接协议导致没有返回通路？

**Comment by Justsoos** [comment]
另外，测了 gost 自建的 socks5 服务，relay udp和tcp都很好用。也许ssr / ss并没有在socks5上放出udp relay，而是内嵌到协议内部了吧？但目前用 ssr / ss 转发udp需求的确很多，第一是服务器多，第二是比如游戏，dns等等需求。自建gost socks5目前还比较少。

**Comment by ginuerzh** [comment]
UDP数据如果使用代理链转发的话，使用的是UDP-Over-TCP，这是GOST中特有的方式。

SS的UDP relay是自定义协议，与SOCKS5不兼容。GOST已经支持SS UDP relay的服务端，客户端会在后面添加。

**Comment by Justsoos** [comment]
多谢作者的好作品。希望能同样加上 ssr 协议支持。ssr 虽然主作者已经被迫 afk，但整个体系的FQ能力，使用方便程度，用户群都大过ss。
