### ISSUE TITLE
明明，我的/root/下是有public.crt的。怎么提示没有这样的文件呢？

### ISSUE THREAD

**Issue by briteming** [ginuerzh/gost#191]
hi.

root@RegalMusty-VM:~/gost_2.4_linux_amd64# ls
gost
root@RegalMusty-VM:~/gost_2.4_linux_amd64# ./gost -L="http2://:1443?cert=~/public.crt&key=~/private.key" 
2017/11/19 21:13:35 main.go:71: open ~/public.crt: no such file or directory
root@RegalMusty-VM:~/gost_2.4_linux_amd64#

"~/public.crt: no such file or directory"是什么意思？明明，我的/root/下是有public.crt的。怎么提示没有这样的文件呢？

**Comment by ginuerzh** [comment]
把 /public.crt 提换成 ./public.crt，注意前面有个点，或直接把 `/` 去掉。private.key也一样。
