### ISSUE TITLE
gost有没有什么吉祥物啊

### ISSUE THREAD

**Issue by 0312birdzhang** [ginuerzh/gost#196]
最近做一个东西用到gost，然后需要一个icon，找了找也没有发现gost的吉祥物 🐐 🐭

**Comment by ginuerzh** [comment]
抱歉，没有

**Comment by 0312birdzhang** [comment]
觉得可以搞一个，这东西太强大了，👍👍👍

**Comment by ginuerzh** [comment]
本人才疏学浅，没有这方面的天赋，欢迎有志青年发挥自己的特长 :grinning:

**Comment by 0312birdzhang** [comment]
哈哈，我也没有这方面的天赋，征集勇士 🎏
