### ISSUE TITLE
deploy in heroku failed in /vendor/gopkg.in/xtaci/kcp-go.v2/fec.go

### ISSUE THREAD

**Issue by tangkv** [ginuerzh/gost#197]
-----> Go app detected
-----> Fetching jq... done
-----> Checking vendor/vendor.json file.
 !!    The 'heroku.goVersion' field is not specified in 'vendor/vendor.json'.
 !!    
 !!    Defaulting to go1.9.2
 !!    
 !!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-govendor#build-configuration
 !!    
-----> Installing go1.9.2
-----> Fetching go1.9.2.linux-amd64.tar.gz... done
-----> Fetching govendor... done
 !!    Installing package '.' (default)
 !!    
 !!    To install a different package spec set 'heroku.install' in 'vendor/vendor.json'
 !!    
 !!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-govendor#build-configuration
 !!    
-----> Fetching any unsaved dependencies (govendor sync)
-----> Running: go install -v -tags heroku . 
github.com/ginuerzh/gost/vendor/git.torproject.org/pluggable-transports/goptlib.git
github.com/ginuerzh/gost/vendor/git.torproject.org/pluggable-transports/obfs4.git/common/csrand
github.com/ginuerzh/gost/vendor/github.com/dchest/siphash
github.com/ginuerzh/gost/vendor/git.torproject.org/pluggable-transports/obfs4.git/common/drbg
github.com/ginuerzh/gost/vendor/github.com/agl/ed25519/edwards25519
github.com/ginuerzh/gost/vendor/git.torproject.org/pluggable-transports/obfs4.git/transports/base
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/curve25519
github.com/ginuerzh/gost/vendor/github.com/agl/ed25519/extra25519
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/hkdf
github.com/ginuerzh/gost/vendor/git.torproject.org/pluggable-transports/obfs4.git/common/probdist
github.com/ginuerzh/gost/vendor/git.torproject.org/pluggable-transports/obfs4.git/common/ntor
github.com/ginuerzh/gost/vendor/git.torproject.org/pluggable-transports/obfs4.git/common/replayfilter
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/poly1305
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/salsa20/salsa
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/gosocks4
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/nacl/secretbox
github.com/ginuerzh/gost/vendor/git.torproject.org/pluggable-transports/obfs4.git/transports/obfs4/framing
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/gosocks5
github.com/ginuerzh/gost/vendor/git.torproject.org/pluggable-transports/obfs4.git/transports/obfs4
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector
github.com/ginuerzh/gost/vendor/github.com/go-log/log
github.com/ginuerzh/gost/vendor/github.com/klauspost/compress/snappy
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go/protocol
github.com/ginuerzh/gost/vendor/github.com/hashicorp/golang-lru/simplelru
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go/internal/utils
github.com/ginuerzh/gost/vendor/github.com/hashicorp/golang-lru
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/aes12
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go/congestion
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go/qerr
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go/frames
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/fnv128a
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go-certificates
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go/ackhandler
github.com/ginuerzh/gost/vendor/github.com/ryanuber/go-glob
github.com/ginuerzh/gost/vendor/github.com/Yawning/chacha20
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/blowfish
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/cast5
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go/crypto
github.com/ginuerzh/gost/vendor/github.com/shadowsocks/shadowsocks-go/shadowsocks
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go/handshake
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/pbkdf2
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/ed25519/internal/edwards25519
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go/flowcontrol
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/ed25519
github.com/ginuerzh/gost/vendor/github.com/lucas-clemente/quic-go
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/ssh
github.com/ginuerzh/gost/vendor/golang.org/x/net/http2/hpack
github.com/ginuerzh/gost/vendor/golang.org/x/text/transform
github.com/ginuerzh/gost/vendor/golang.org/x/text/unicode/bidi
github.com/ginuerzh/gost/vendor/golang.org/x/text/secure/bidirule
github.com/ginuerzh/gost/vendor/golang.org/x/text/unicode/norm
github.com/ginuerzh/gost/vendor/gopkg.in/gorilla/websocket.v1
github.com/ginuerzh/gost/vendor/golang.org/x/net/idna
github.com/ginuerzh/gost/vendor/github.com/klauspost/cpuid
github.com/ginuerzh/gost/vendor/golang.org/x/net/lex/httplex
github.com/ginuerzh/gost/vendor/github.com/klauspost/reedsolomon
github.com/ginuerzh/gost/vendor/golang.org/x/net/http2
github.com/ginuerzh/gost/vendor/github.com/pkg/errors
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/salsa20
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/tea
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/twofish
github.com/ginuerzh/gost/vendor/golang.org/x/crypto/xtea
github.com/ginuerzh/gost/vendor/golang.org/x/net/bpf
github.com/ginuerzh/gost/vendor/golang.org/x/net/internal/iana
github.com/ginuerzh/gost/vendor/golang.org/x/net/internal/netreflect
github.com/ginuerzh/gost/vendor/golang.org/x/net/ipv4
github.com/ginuerzh/gost/vendor/gopkg.in/xtaci/smux.v1
github.com/ginuerzh/gost/vendor/gopkg.in/xtaci/kcp-go.v2
# github.com/ginuerzh/gost/vendor/gopkg.in/xtaci/kcp-go.v2
vendor/gopkg.in/xtaci/kcp-go.v2/fec.go:57:29: too many arguments in call to reedsolomon.New
vendor/gopkg.in/xtaci/kcp-go.v2/fec.go:57:56: undefined: reedsolomon.WithMaxGoroutines
 !     Push rejected, failed to compile Go app.
 !     Push failed

**Comment by shellus** [comment]
请联系devcenter.heroku.com客服解决。此问题和gost代码及仓库无关。

devcenter.heroku.com并非标准的golang执行环境，gost开发团队无需也无法保证gost代码与devcenter.heroku.com运行环境兼容。

**Comment by tangkv** [comment]
多谢耐心解释，明白原因了。
