### ISSUE TITLE
gost 2.5 部署heroku报错。

### ISSUE THREAD

**Issue by jlzsss** [ginuerzh/gost#199]
报错信息如下：
E:\GOPATH\src\github.com\ginuerzh\gost\cmd\gost>git push heroku master
Counting objects: 603, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (562/562), done.
Writing objects: 100% (603/603), 1.43 MiB | 28.00 KiB/s, done.
Total 603 (delta 53), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Go app detected
remote: -----> Fetching jq... done
remote: -----> Checking vendor/vendor.json file.
remote:  !!    The 'heroku.goVersion' field is not specified in 'vendor/vendor.j
son'.
remote:  !!
remote:  !!    Defaulting to go1.9.2
remote:  !!
remote:  !!    For more details see: https://devcenter.heroku.com/articles/go-ap
ps-with-govendor#build-configuration
remote:  !!
remote: -----> Installing go1.9.2
remote: -----> Fetching go1.9.2.linux-amd64.tar.gz... done
remote: -----> Fetching govendor... done
remote:  !!    Installing package '.' (default)
remote:  !!
remote:  !!    To install a different package spec set 'heroku.install' in 'vend
or/vendor.json'
remote:  !!
remote:  !!    For more details see: https://devcenter.heroku.com/articles/go-ap
ps-with-govendor#build-configuration
remote:  !!
remote: -----> Fetching any unsaved dependencies (govendor sync)
remote: -----> Running: go install -v -tags heroku .
remote: can't load package: import cycle not allowed
remote: package github.com/ginuerzh/gost
remote:         imports github.com/ginuerzh/gost
remote: import cycle not allowed
remote: package github.com/ginuerzh/gost
remote:         imports github.com/ginuerzh/gost
remote:  !     Push rejected, failed to compile Go app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to gost.
remote:
To https://git.heroku.com/gost.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/gost.git'

**Comment by shellus** [comment]
请联系git.heroku.com客服排查，此问题和gost仓库及代码无关。
