### ISSUE TITLE
怎么生成自定义的公钥文件和私钥文件呢？

### ISSUE THREAD

**Issue by ARwMq9b6** [ginuerzh/gost#2]
1.2 版本中加入了 websocket tunnel 的加密功能，我想使用自定义的 -key 和 -cert ，怎样生成它们呢？

**Comment by ginuerzh** [comment]
生成证书的工具网上可以搜到很多，这里给个参考
https://msdn.microsoft.com/zh-cn/library/bfsktky3(v=vs.80).aspx

ARwMq9b6 <notifications@github.com>于2015年5月16日周六 下午6:59写道：

**Comment by ginuerzh** [comment]
不过不建议使用tls加密，这种加密只是对数据加密，无法保证对其他人的访问控制

**Comment by ARwMq9b6** [comment]
@ginuerzh 多谢解答。

我用的 [Cloud9](https://c9.io/) , 设置的加密方式只有 rc4 和 table 能行，设置 aes-128-cfb, aes-192-cfb, aes-256-cfb, des-cfb, bf-cfb, cast5-cfb, rc4-md5 方式后客户端无反应，服务端显示 "unexpected EOF" ，不知道是什么原因。（或许是我的电脑不支持这些加密方式或服务器不支持这些方式）

请问 table 和 rc4 哪个更安全些呢？

**Comment by ginuerzh** [comment]
客户端和服务器必须都是1.2版.

在 15/5/16，ARwMq9b6<notifications@github.com> 写道：

**Comment by ARwMq9b6** [comment]
我想钻进老鼠窟。

**Comment by OnionSalt** [comment]
也就是说tls对数据加密和访问控制只能二选一了？有没有两者兼顾的方式？我用的也是cloud9免费版，那rc4或者table哪个能兼顾？
