### ISSUE TITLE
地址处理问题

### ISSUE THREAD

**Issue by kuyagic** [ginuerzh/gost#20]
使用 此代理 访问有些http网站会导致错误的跳转

比如 http://powerampapp.com 会跳转成 http://powerampapp.comhttp/powerampapp.com/

还有很多这种情况...

**Comment by ginuerzh** [comment]
是有这样的问题，会在下一个版本中修正，感谢反馈。

**Comment by kuyagic** [comment]
2.0-rc3 又出现了这个问题 
站点是 http://sharewareonsale.com/s/lopeedit-pro-giveaway-coupon-sale
在http跳转到 https checkout的时候出问题
点 get lopeedit pro now 跳转出错 出错的地址显示为http://sharewareonsale.comhttp/sharewareonsale.com/checkout
