### ISSUE TITLE
数据包里面有gost标记？

### ISSUE THREAD

**Issue by trivita** [ginuerzh/gost#200]
smartsniff简单抓了一下
本地:8080 forward给远端h2://:443，firefox走socks5

数据包里面能看见包含gost，后续还有一串数字
这个特征很明显啊

**Comment by ginuerzh** [comment]
你使用的h2隧道是加密的

**Comment by trivita** [comment]
@ginuerzh 我知道 但是我抓的raw包里面能看见gost字符串

**Comment by ginuerzh** [comment]
有抓到的数据展示一下吗

**Comment by trivita** [comment]
今天贴图

**Comment by shellus** [comment]
@trivita 今天已经过去8天了。

**Comment by devcodewak** [comment]
估计是这里 ： https://github.com/ginuerzh/gost/blob/master/gost.go#L84
服务端首次启动时，随机生成的证书组织项是串: gost
tls握手过程中，服务端发给客户端的SeverHello报文中含有证书，泄了该串。

**Comment by shellus** [comment]
那这个是没办法的，总归会有各种特征的。
毕竟不是shadowsocks这种预置密钥的协议。
加密传输前，有协商过程，就有特征。

**Comment by devcodewak** [comment]
把证书的组织项改为随机串，也是一种办法。

**Comment by douglas-lee** [comment]
那使用自定义证书是否就可以规避这个问题？
