### ISSUE TITLE
怎么实现nginx+kcp共享80？

### ISSUE THREAD

**Issue by shellus** [ginuerzh/gost#206]
我的意思是，gost监听kcp 80端口，转发到tcp 80端口的nginx，请问怎么操作？
服务器：gost -L kcp://:80 -F tcp://127.0.0.1:80
客户机：gost -L tcp://:81 -F kcp://185.215.213.41:80
客户机测试：curl localhost:81

我这样不行。

**Comment by ginuerzh** [comment]
共享端口，需要使用nginx做域名分流

**Comment by shellus** [comment]
@ginuerzh
并不是共享tcp 80端口。
nginx独占tcp 80端口。
gost使用kcp（udp）的80端口。
不冲突的。
我想问怎么实现。

**Comment by shellus** [comment]
仔细的再次阅读了文档，发现实现这个功能，将会用到

本地tcp端口转发
KCP传输方式

如果是TCP端口转发， 将会是这样的：
gost -L tcp://:80/127.0.0.1:80
将tcp的80，转发到tcp的80， 如果加上传输方式，应该像这个样子：
gost -L tcp+kcp://:80/127.0.0.1:80
但是这样明显有个问题，就是这变成了kcp 80 转发到 kcp 80，两端都变了传输方式。
所以，应该像这个样子才对：
gost -L tcp://kcp://:80/127.0.0.1:80
但是实际上，gost并没有这种语法。

**Comment by shellus** [comment]
其实感觉gost的tcp端口转发实现得有问题，不应该使用：
gost -L tcp://:81/127.0.0.1:80 这样子的。

应该用：
gost -L tcp://81 -F tcp://127.0.0.1:80

这样的话，就可以使用：
gost -L tcp+kcp://80 -F tcp://127.0.0.1:80
来实现本Issue所说的需求了。

**Comment by ginuerzh** [comment]
如果你是想通过KCP通道来转发数据的话，在2.5中可以实现：
服务端：gost -L kcp://:80/:80
客户端：gost -L tcp://:81 -F forward+kcp://:80

这样本地的81端口就会通过KCP通道直接映射到服务端的TCP 80端口。

**Comment by shellus** [comment]
服务端：gost -L kcp://:80/:80

这样用感觉好混乱。

gost -L kcp://:80

的意思是 gost -L socks5(&http)+kcp://:80

但是变成了gost -L kcp://:80/:80，意思竟变成了两个数据流的转发。
这样真的好吗？太难理解了吧

**Comment by ginuerzh** [comment]
其实二者没有多大区别，目的是一样的，只不过传输的通道不一样而已。

最初设计的TCP端口转发，是标准的转发模式：
gost -L tcp://:8080/:9090
因为是原始TCP，所以使用起来会较通用一些。

后面2.5中转发功能增加了对其他隧道的支持：
gost -L kcp://:8388/:8080
用法上与原来的TCP端口转发没有什么区别。但因为是特定的隧道类型，所以通用性上就没有原始TCP好了。

或者你也可以理解为第一种是客户端行为，可以通过客户端控制转发的目标地址，对于服务端是透明的。
第二种是服务端行为，由服务端控制目标地址。

**Comment by shellus** [comment]
gost2.5还没有release，就先不搞了，先用kcptun实现吧。
