### ISSUE TITLE
add default path for config file

### ISSUE THREAD

**Issue by untoreh** [ginuerzh/gost#208]
currently a json config must be specified with `-C` and it does not look for like a `gost.json` file in the cwd am i correct in this?

**Comment by recall704** [comment]
![image](https://user-images.githubusercontent.com/7451408/34462230-1c1bda6e-ee7a-11e7-8173-f970349cd952.png)

 i can get the file name from cwd. 
have you give the right format json file ?
how about a absolute path like `/path/to/config.json`

**Comment by untoreh** [comment]
`kcp.json` is loaded from cwd, so it should follow the same behaviour

**Comment by recall704** [comment]
maybe you can debug it by your self.

**Comment by untoreh** [comment]
@recall704 
Took a look and what I wanted is achieved by this patch in `cmd/gost/main.go`
```patch
40c40
<       flag.StringVar(&configureFile, "C", "", "configure file")
---
>       flag.StringVar(&configureFile, "C", "gost.json", "configure file")
60c60
<       if flag.NFlag() == 0 || len(routes) == 0 {
---
>       if len(routes) == 0 {
```
