### ISSUE TITLE
是否兼容1.x版本

### ISSUE THREAD

**Issue by redfrog999** [ginuerzh/gost#21]
我用了开发者的1.x版本部署了几个APP在heroku，我想知道2.0版本还能兼容吗？如果可以的话怎么设置参数呢？特别是在我设置了密码的情况下。另外，我测试下来2.0版本跑ss效率很高，穿透能力很强，希望开发者能继续努力改进。

**Comment by ginuerzh** [comment]
部分功能是兼容的，例如http模式，socks及ss模式是不兼容的，建议全部使用2.0版

**Comment by redfrog999** [comment]
感谢回复。另外，出正式版的时候，是否能够加上对chacha20等加密方式的支持呢，不完整支持SS的多个加密格式还是有诸多不便。对了，多个链路转发的时候，会偶尔发生丢失链路的情况，也希望在正式版得到修复。

**Comment by ginuerzh** [comment]
chacha20其实是支持的，只不过在编译的时候，用的shadowsocks-go的库是旧的，所以就把chacha20丢了，可以自己编译一个版本来使用chacha20。
丢失链路问题，是否有更详细的描述，或日志信息？

在 2016/1/8，David Tai<notifications@github.com> 写道：

**Comment by redfrog999** [comment]
因为俺不是程序员，所以自己编译什么的，要搭建环境等等一大堆事情还是搞得比较繁琐，还是希望开发者来搞定：）。

丢失链路的情况是昨天发生的，重启之后到现在一直都正常了，所以我估计是我这边的线路问题。我现在开启了最高等级的log输出，如果下次还有这样的错误重现应该可以抓到日志信息。现在我搞了个三级链路，目前测试下来转发效率很不错，我会继续使用，有问题再反馈。
