### ISSUE TITLE
Provide AppImage, Snap or Flatpak

### ISSUE THREAD

**Issue by baimafeima** [ginuerzh/gost#211]
Could you provide an AppImage, Snap or Flatpak for easy cross-platform installation? I have briefly read through https://github.com/ginuerzh/gost/blob/master/README_en.md but I have some questions: 
1. Does `gost` come with a GUI or is it a terminal-based application? 
2. Is `gost` a client or a server application or both at the same time?
3. Can you provide a clear list of all dependencies for `gost` if one wants to build it from source?

**Comment by ginuerzh** [comment]
1. Terminal-based.
2. It can be used as client or server, depending on how it is used.
3. There is no dependency.
