### ISSUE TITLE
在手机上连着gost玩游戏，经常掉线

### ISSUE THREAD

**Issue by afyji** [ginuerzh/gost#213]
我再国外，国内服务器在阿里云。到阿里云的延迟非常稳定，100左右。跳ping的可能很低。丢包也很低。

我用的安卓ss客户端。确定tcp和udp都代理到国内的gost上了。

但是完王者荣耀和QQ斗地主。疯狂掉线

QQ斗地主基本没办法玩，10-20s就掉线。我的内核参数也按照ss官方给的方案优化的。

不知道有什么方案能够优化的么

**Comment by afyji** [comment]
环境是

我的手机->国外的gost（SS）->国内阿里云gost(socks5)->QQ斗地主

所以不存在防火墙干扰这种可能性。因为是sock5进入到国内的

**Comment by 2378** [comment]
不存在干扰可能性？ 这话有点天真啊

**Comment by ginuerzh** [comment]
如果你用的是2.4版，那很可能是 #158 中的问题导致的
