### ISSUE TITLE
请问新版本的是已经不能像旧版的采用AES加密吗？

### ISSUE THREAD

**Issue by vampire4n** [ginuerzh/gost#22]
看到已经没有-m和-p选项，那么websocket下是不是不能采用AES加密了？

**Comment by ginuerzh** [comment]
websocket下的socks5模式(socks+ws)自动使用tls加密，无需手动指定，其他加密方式已不支持。后续会支持wss方式。
vampire4n <notifications@github.com>于2016年1月8日 周五20:25写道：
