### ISSUE TITLE
Details improved

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#220]
gost -L=:1088 -F=mws://192.168.1.2:8080

存在一种情况,如果tcp握手成功,没有成功建立隧道连接,就会一直卡着,
能不能加一个隧道建立超时?  比如3s ?
因为nat层转发会存在tcp空链接,需要断开重新发起请求,

**Comment by f4nff** [comment]
如果隧道建立超时,就像那些发起当前隧道请求的那些连接一个超时或者主动断开的信号,

**Comment by ginuerzh** [comment]
`xtaci/smux`本身有心跳和超时机制
