### ISSUE TITLE
服务端套上cdn后如何中转？

### ISSUE THREAD

**Issue by beechRu** [ginuerzh/gost#221]
你好，我已经在服务端建立了一个http + tls 隧道并实现成功访问。但是我给服务器套上Cloudflare后，域名对应的真实ip被cf提供的ip取代，请问如何解决？

**Comment by shellus** [comment]
你好，请给出你服务端的启动参数

**Comment by beechRu** [comment]
查了一下，已经了解到需要用ws

现在的问题：
[socks5-connect] 127.0.0.1:53384 -> www.google.com:443 : read tcp 10.25.96.144:53385->104.24.105.78:443: wsarecv: An existing connection was forcibly closed by the remote host.

服务端配置：
./gost -L="mwss://username:password@:443?cert=cert_path&key=key_path"

客户端（win）配置：
gost -L=:localport -F=mwss://username:password@mydomain.com:443

SwitchyOmega协议：
socks5

CF配置
Full SSL：flexible

另外
mwss加上socks选项还会报bad version错误（但是直连下可以成功连接）

**Comment by shellus** [comment]
我这里使用参数：

服务端：
gost -L socks5+mwss://:1235

客户端：
gost -L :1081 -F socks5+mwss://MY_Server_IP:1235

测试：
curl -x socks5://127.0.0.1:1081 ip.sb

测试OK。

你的问题可能在于使用了`mwss://username:password@:443`这种方式配置认证信息。
因为mwss是一种传输方式，并不支持用户名密码配置。
虽然单独使用传输方式来作为-L的参数等同于为socks5传输协议设置认证信息。但是实际上可能产生非预期的结果。

**Comment by shellus** [comment]
我这里使用显式制定socks5协议+mwss传输协议+socks5认证信息，测试成功，参数：
服务端：
gost -L socks5+mwss://abc:123@:1235

客户端：
gost -L :1081 -F socks5+mwss://abc:123@MY_Server_IP:1235

测试：
curl -x socks5://127.0.0.1:1081 ip.sb

另请注意：mwss传输协议要求gost2.5，请使用gost -V命令查看你的服务端和客户端的版本是否均为2.5rc1

**Comment by shellus** [comment]
另外，我这里使用腾讯云CDN测试，服务端收不到任何数据，可能腾讯云不支持websocks反向代理。

**Comment by Kwan9** [comment]
百度CDN和CF支持WS

**Comment by beechRu** [comment]
你好

服务端和本地均已更新至2.5，认证信息仍然保留，服务器端口任意填了一个
继续尝试连接后客户端无输出信息，一段时间后输出i/o timeout.

直接填IP则连接成功.

**Comment by shellus** [comment]
套了cdn的情况下吗？

**Comment by beechRu** [comment]
是的，ping mydomain.com 以后显示的是cf的IP

**Comment by shellus** [comment]
cf的回源端口指定了吗？没有指定的话是默认80，那么你服务端的gost参数必须监听在80端口。

**Comment by beechRu** [comment]
服务端已经改成监听80端口，带认证参数和不带认证都试了一遍
同时客户端尝试-F domain.com:443 和 :80 都不行
443 依然报websocket bad handshake，80 则是 tls: oversized record received with length
请问是不是cf还有哪里没设置正确？

**Comment by shellus** [comment]
> iplocation.net查询显示的还是服务器的ip

这说明直接连接服务器成功，没有经过cf

**Comment by mixool** [comment]
> iplocation.net查询显示的还是服务器的ip，这算连接成功吗？
这样应该是已经成功了，相当于用CF中转到了你的服务器，所以查询结果应该是服务器IP.
