### ISSUE TITLE
Waiting for SOCKS4 on the same port with others

### ISSUE THREAD

**Issue by gusarov** [ginuerzh/gost#225]
Socks4 less redundant in case when local DNS works. I like the flow when people can choose whatever version they need on client side. There is no reason to split such details by version, but even if it is, why not to expect socks4 for "gost -L :8080" ?
I've tried:
```
gost -L :8080
gost -L :8080 -L socks4:8080
gost -L socks4+socks5//:8080
gost -L socks5+socks4//:8080
```
nothing solves this

**Comment by ginuerzh** [comment]
SOCKS4 does not  support authentication method, for security reason, I have disabled SOCKS4 when run as `gost -L :8080` since v2.4.

**Comment by gusarov** [comment]
ok, but when it runs as "gost -L :8080" it does not requests any authentication anyway...
now it just seems like a missing feature, ok, you might have any reason to avoid this behavior by default, but how about those who just want go get this functionality? may be additional command line option then?

**Comment by ginuerzh** [comment]
You can run a SOCKS4 server standalone: 
`gost -L socks4://:1080`

More usage please refer to the docs: https://docs.ginuerzh.xyz/gost/en/
