### ISSUE TITLE
2.5 平衡好像沒作用

### ISSUE THREAD

**Issue by delphinuz** [ginuerzh/gost#228]
gost.exe -L=:1080 -F=socks5://localhost:1081?localhost,localhost:1082

browser指向1080，但gost只會將流量分配給1081，而1082一直沒接收到流量。

**Comment by ginuerzh** [comment]
参数格式不对，少了`ip=`

gost.exe -L=:1080 -F=socks5://localhost:1081?`ip=`localhost,localhost:1082

**Comment by delphinuz** [comment]
謝謝，若能再加個pac如autoproxy功能就更完美了。
