### ISSUE TITLE
kcp错误提示：[kcp] operation not supported

### ISSUE THREAD

**Issue by shellus** [ginuerzh/gost#229]
按照文档：https://docs.ginuerzh.xyz/gost/kcp/

执行：
root@sg:~# gost -V
gost 2.5-rc1 (go1.9.3)

root@sg:~# gost -L=kcp://:8388
2018/02/26 21:10:09 kcp.go:240: [kcp] operation not supported

请问这是bug，还是文档错误？

@ginuerzh

**Comment by ginuerzh** [comment]
这是kcp库报的错，具体要去kcptun里面问了

**Comment by shellus** [comment]
谢谢，我去找找看看

**Comment by shellus** [comment]
虽然报这个提示，但是不影响使用。
在kcptun的仓库和kcp-go的仓库均未搜索到“operation not supported” 这个关键词，包括代码和issue

**Comment by shellus** [comment]
有头绪了，正在跟踪

**Comment by shellus** [comment]
```
// SetDSCP sets the 6bit DSCP field of IP header
func (l *Listener) SetDSCP(dscp int) error {
	if nc, ok := l.conn.(net.Conn); ok {
		return ipv4.NewConn(nc).SetTOS(dscp << 2)
	}
	return errors.New(errInvalidOperation)
}
```
是kcptun库的这个函数返回的提示

**Comment by shellus** [comment]
大概明白了，SetDSCP函数要求Listener的conn必须是一个net.Conn接口，否则不支持`sets the 6bit DSCP field of IP header`
而kcp是net.UDPConn类型，是不符合net.Conn的，所以会返回不支持设置DSCP 的提示。

**Comment by shellus** [comment]
但是不对啊。
gopath/src/net/udpsock.go:88
```
type UDPConn struct {
	conn
}
```
net.UDPConn 是继承net.conn的，而net.conn是实现了net.Conn接口的
也就是说，net.UDPConn是实现net.Conn接口了的。为什么会断言失败呢？

**Comment by shellus** [comment]
试了一下，搞不定，不如在gost代码中去掉SetDSCP函数调用吧。反正不可能成功。
SetDSCP只能为一个UDPConn调用。
而gost的kcp Listener中的conn是net.PacketConn 永远不能成功的。

反正SetDSCP也没什么用，去掉，免得每次用kcp都显示这个错误提示。

@ginuerzh 你觉得怎么样？

**Comment by shellus** [comment]
最后跟踪发现问题出在vendor/golang.org/x/net/internal/netreflect/socket_19.go:20
```
// SocketOf returns the socket descriptor of c.
func SocketOf(c net.Conn) (uintptr, error) {
	switch c.(type) {
	case *net.TCPConn, *net.UDPConn, *net.IPConn, *net.UnixConn:
		return 0, errOpNoSupport
	default:
		return 0, errInvalidType
	}
}
```

这个判断是否可以设置socket选项的函数，始终会返回errOpNoSupport错误或者另一个无效类型错误。

在同级目录的socket.go和socket_posix.go也有SocketOf函数实现，但是源文件上方的注解`// +build !go1.9`表明，这个源文件已经不适用于go1.9

_19结尾的文件表示golang1.9版本编译时使用的代码文件。

那么就是说，在golang1.9，将不再支持为socket设置选项。

现在gost在go1.8已经无法编译，并且没有支持go1.8的打算。

那么我们只剩下一个选择：在gost代码中去掉SetDSCP调用。

@ginuerzh

**Comment by ginuerzh** [comment]
感谢花时间测试，已将这部分注释掉了。
