### ISSUE TITLE
http+tls 模式下 使用 Basic 认证 然后会导致Chrome崩溃

### ISSUE THREAD

**Issue by kuyagic** [ginuerzh/gost#23]
测试版本 2.0-rc2
Chrome版本 47.0.2526.106
使用 Flora_Pac 生成的 PAC ,其中关键语句如下
 return 'HTTPS ssl_domain:8080; DIRECT' ;
命令行 -L=http+tls://user:pass@server-ip:8080
然后 访问需要代理的网站 弹出 gost 的Basic 认证框, 输入正确的密码点确定后 Chrome崩溃.

如果不加Basic 认证 是可以使用的.

另外,直接用SwitchOmega 指定 *HTTPS* 代理,不使用 pac 脚本 ,也是会导致崩溃的.

所以不明问题点,特来告知作者你一下 不知道是不是软件导致还是PAC问题.

谢谢.

**Comment by ginuerzh** [comment]
这个问题应该是chrome导致的，可以参考：
https://code.google.com/p/chromium/issues/detail?id=570171
https://github.com/FelisCatus/SwitchyOmega/issues/446

可以换用chrome 48尝试一下。
