### ISSUE TITLE
The memory in io.Copy (writer, reader) ends

### ISSUE THREAD

**Issue by dmitry-online** [ginuerzh/gost#230]
![out](https://user-images.githubusercontent.com/30704678/36675108-4ac7cc44-1b32-11e8-9162-a282d4f24024.png)

Hello, I ran into the problem of a lack of memory on the server when trying to install more than 10,000 connections

I open about 10 thousand local ports and transfer traffic from the local port to a remote socks5 server

The diagram above shows that most of the memory is spent on the io.Copy function, maybe there is a problem with incorrect copying of the buffer?

Machine Features:
4x CPU
6gb memory

**Comment by dmitry-online** [comment]
the machine behaves as follows - memory consumption is maximum, after 10 minutes the program is turned off due to lack of RAM

**Comment by ginuerzh** [comment]
`io.Copy` internally allocates 32KB as a buffer, so `io.CopyBuffer` with a buffer pool like `sync.Pool` may be a better choice.
