### ISSUE TITLE
负载均衡的问题

### ISSUE THREAD

**Issue by cjjdaq** [ginuerzh/gost#235]
多服务器负载均衡的情况下是否支持会话保持功能？有些服务会检查来源ip，比如一些网页登录了，刷新下又变成未登录。

**Comment by ginuerzh** [comment]
如果有会话保持，(对于单个用户)就失去负载均衡的意义了。
不过后面可以考虑针对特定地址指定特定路径。

**Comment by cjjdaq** [comment]
不会，针对指定的端口，或源ip,或远程ip,特定子域进行会话保持，可以设定一个超时时间，超时了重新轮询，这样不会固定在一个服务器上了

**Comment by cjjdaq** [comment]
@ginuerzh 
源IP，VIP，和端口

当采用这种方式时，负载均衡器根据每个TCP SYN数据包中的源IP地址、目的IP地址和目的端口号码进行会话保持。在客户端发出的TCP SYN数据包中，目的IP地址是负载均衡器上的虚拟IP(VIP)地址，目的端口号码表示客户端想要访问的应用。采用这种方式时，对于客户端的第一个连接请求，负载均衡器会根据负载均衡算法选择一台服务器，对于源IP地址、VIP和目的端口这三项相同的后续连接都会转发到同一台服务器，直到会话保持计时器超时。采用这种方法关键的一点是，如果用户访问不同的应用，不同的目的端口号码或者VIP，负载均衡器不会把此类请求发送到同一台服务器，而是根据服务器的负载状况转发到一个合适的服务器上。

希望能够加入此种会话保持。

**Comment by ginuerzh** [comment]
关于会话保持，我的想法是这样的：
1. 首先不是所有网站都需要会话保持功能，所以如果全局使用的话意义不大。
2. GOST本身支持多级代理，若使用两个及以上代理，采用源IP和端口来确定路径基本上不可行。

目前已经支持路由控制，比较简单的实现方式是在路由控制中针对指定的目标地址开启会话保持。
如果会话保持开启，则针对这个目标地址的第一次路由选择仍旧按照正常的方式选出一条路径。但后续的请求会一直使用此路径，直到此路径失效。
