### ISSUE TITLE
路由宝上无法运行。

### ISSUE THREAD

**Issue by xuiv01** [ginuerzh/gost#236]
golang 1.10 windows x64
env GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -a -ldflags "-s -w" -o gost.mipsle

目标机器mt7620a，helloworld是可以编译运行的，gost既无输出，也不退出，netstat查不到gost的端口

**Comment by ginuerzh** [comment]
每次起来时，会生成随机的证书，在性能较差的设备上会耗时较长。

**Comment by xuiv** [comment]
我其实己经弄好了，只要把代码中的quic和kcp去掉就能正常运行了，只是用一段时间后会停止响应，现在换成ngrok了，不需要路由器代理了。

**Comment by flynaj** [comment]
清除golang的缓存在编译一下

**Comment by ginuerzh** [comment]
下个版本可以使用自己的证书文件作为默认证书，不用每次都随机生成。
