### ISSUE TITLE
socks5 和 https 代理安全吗？

### ISSUE THREAD

**Issue by pexcn** [ginuerzh/gost#238]
这两种代理方式可以直接在中国大陆使用而不被墙吗？

**Comment by ginuerzh** [comment]
Https本身是安全的

**Comment by pexcn** [comment]
感谢解答，那 socks5 的安全性如何呢？
我在一个小 vps 上运行 gost 开了没有验证的 socks5 代理，在中国大陆一直能用，也没有被墙...

**Comment by ginuerzh** [comment]
gost中的socks5默认会使用tls加密

**Comment by pexcn** [comment]
但是能配合 switchyomega 能直接用的，socks 5 不是明文的吗？

**Comment by zw0** [comment]
gost 和是 socks5-tls

**Comment by pexcn** [comment]
为什么能和 switchyomega 直接用？我是只用了 socks5://:443 这个参数

**Comment by Justsoos** [comment]
http1.x 的 tls 并不完全安全，socks5 服务器还是能获取一定信息，http2 有很大加强。
但没辙，你现在能大规模用上https 1.x，已经是托了斯诺登的福了。
更进一步的安全，还不能靠 http1.x
