### ISSUE TITLE
提个关于转发代理的建议。。。

### ISSUE THREAD

**Issue by jzp820927** [ginuerzh/gost#24]
目前的转发代理的工作模式是，单个转发代理，或者是一条转发代理链。
我的想法是这样的，能不能再增加一种转发代理的工作模式，就是设置多个转发代理，然后这些转发代理工作在负载均衡模式，也就是说，如果当前正在工作的转发代理突然失效了，程序能够自动检测到，并且切换到另一个可用的转发代理继续工作？
这样可以避免代理的单点故障导致的网络中断，保证网络长时间运行不中断，不知道这个建议能否实现？

**Comment by ginuerzh** [comment]
之前有考虑过这个功能，不过由于其复杂性就没有添加，目前也不会考虑去实现此功能。

**Comment by jzp820927** [comment]
好吧，我也是随便想到的，既然太麻烦就算了吧

**Comment by sobasin** [comment]
添加负载均衡的确会改变gost目前一条命令的风格，不过还是很值得期待。
如果要实现，可能需要借助config文件了。
BTW, cow和MEOW在这方面做得不错，目前我是在gost前面放一个MEOW实现多条线路备份的，需要负载均衡的也可以自己发挥。
