### ISSUE TITLE
socks代理模式下，建议server端可以强制设置MethodTLSAuth

### ISSUE THREAD

**Issue by zhaozhongshu** [ginuerzh/gost#244]

**Comment by ginuerzh** [comment]
SOCKS5会根据所使用的客户端来判断选用哪一种模式，当客户端也是gost时，会自动使用MethodTLS/MethodTLSAuth。
当客户端是第三方SOCKS5客户端时，会采用标准SOCKS5协议，使用NoAuth/UserPass模式。
