### ISSUE TITLE
Socks5 TLS & TLS+AUTH

### ISSUE THREAD

**Issue by dblokhin** [ginuerzh/gost#247]
```golang	// MethodTLS is an extended SOCKS5 method for TLS.
	MethodTLS uint8 = 0x80
	// MethodTLSAuth is an extended SOCKS5 method for TLS+AUTH.
	MethodTLSAuth uint8 = 0x82
```
Is there any RFC document where describes this methods?
Which client does support these methods? (Google Chrome, FireFox?)
Where are they used (`0x80`, `0x82`)? Thanks.

**Comment by ginuerzh** [comment]
As defined in [RFC 1928](https://tools.ietf.org/html/rfc1928) : 
```
  o  X'80' to X'FE' RESERVED FOR PRIVATE METHODS
```
These two methods are defined by GOST.
