### ISSUE TITLE
为了gost的发展，提一些建议，希望作者能看到！

### ISSUE THREAD

**Issue by LiaoChangFei** [ginuerzh/gost#255]
作者您好，
我这是第二次给您提建议了，虽然第一次建议提的鲁莽，但还是得到了你的认可，非常荣幸。
gost给大家带来了诸多便利，对于作者的无私奉献深表感谢，我想每一个使用gost的人都是这样想的。
gost稳定强大的功能，无疑给很多人留下了深刻的印象，gost优点很多，这里就不再赘述。

下面我来提几点建议：

建议并不是意见
若作者您认同，希望能早日实施；若觉得建议可笑，那便笑笑；若觉得建议可气，请消消气；

0x1.>我希望gost端口映射部分能借鉴下frp，因为frp的易用已经深入各领域，一些服务器，树莓派和内外网站架设等都在使用，这无疑也给frp作者带来了不小的商机和利润。我想同领域任何好的地方我们都应该借鉴和学习。所以我恳请作者能够借鉴frp的长处和配置方式，来使gost变得更强大！

frp开源地址：https://github.com/fatedier/frp

**Comment by f4nff** [comment]
sb,不会用,就别瞎叽歪

**Comment by XYDsoft** [comment]
有些人实在没家教，由于他们受教育程度低而且从小无父无母缺乏管教。中国人很多，狗也不少，更有不少没注射过狂犬疫苗的狗到处乱咬人。这种物种的出现实乃家国不幸。lz不要和狗一般见识，有好的建议还望继续提

**Comment by ginuerzh** [comment]
gost本身集成的功能很多，不能保证每个点都做到完美，满足所有人的需求。但有好的建议还是会采纳，并不断进行改进。
frp是一款很强大的内网穿透工具，但其具体的功能和设计我没有仔细的研究过，后面有时间的话我会去详细了解一下。如果你觉得哪个功能点比较好，也可以直接提出来。

**Comment by f4nff** [comment]
别鸟他,frp跟gost的rtcp差不多,一个采用kcptun作为隧道,一个采用xtaci/smux多路复用的tcp作为反向隧道,
gost采用ssh+mbind-socks5
他自己没搞清楚,就在那瞎叫,不过我提的建议倒是很好的,

**Comment by f4nff** [comment]
添加反向代理

A----内网---可以连接B (10.0.0.1)
B----外网---C可以连 (2.2.2.2)

C---连接B
B---连接A

C通过A的内网进行数据转发.

比如

A:   gost -F=mws://2.2.2.2:80?key=pass&tunnel=true
B:   gost -L=mws://:80?tunnel=true
C:   gost -L=:1080 -F=mws://2.2.2.2:80?key=pass&tunnel=true
目的,可以让几个内网的机子连接一个mws服务端,
这一个mws服务端根据key匹配多个内网转发数据,

**Comment by flynaj** [comment]
Gost，可以做端口映射的，只是配置文件不像fro，gost 功能更全面
