### ISSUE TITLE
rtcp支持传输类型吗

### ISSUE THREAD

**Issue by fbion** [ginuerzh/gost#256]
gost -L=socks5://:8080
gost -L=rtcp://:8081/127.0.0.1:8082 -F=socks5://192.168.1.2:8080
这样没问题

如果监听 gost -L ws://:8080
是不是不行
为什么？

**Comment by f4nff** [comment]
不看wiki

**Comment by fbion** [comment]
@f4nff 请指教 : )

**Comment by ginuerzh** [comment]
rtcp是基于socks5协议实现的，所以协议类型只能是socks5，但传输类型可以是任意的：
gost -L=socks5+ws://:8080
gost -L=rtcp://:8081/127.0.0.1:8082 -F=socks5+ws://192.168.1.2:8080

详细用法请参考：https://docs.ginuerzh.xyz/gost/port-forwarding/

**Comment by fbion** [comment]
@ginuerzh 单独socks5协议可以明白，socks5+ws: 的原理是socks5套上伪装的ws?

**Comment by fbion** [comment]
明白了 好神奇
