### ISSUE TITLE
如何查看支持哪些参数

### ISSUE THREAD

**Issue by fbion** [ginuerzh/gost#257]
配置格式

端口转发相关的节点配置格式请参考端口转发。

在GOST中节点的配置为类URL格式(适用于-L和-F参数)：

[scheme://][user:pass@host]:port[?param1=value1&param2=value2]
[?param1=value1&param2=value2] 有哪些 除了手册里面的

**Comment by ginuerzh** [comment]
不同的节点类型有不同的params，目前没有对这些参数进行统一说明的文档。
