### ISSUE TITLE
Linux TPROXY server support?

### ISSUE THREAD

**Issue by elico** [ginuerzh/gost#258]
I wrote an example library at:
- <https://github.com/elico/go-linux-tproxy>

Which demonstrates how to Listen and Dial a TPROXY socket\connection.
I think that it would be a great addition to have gost the ability to use Linux TPROXY to intercept traffic.

I also created an example of a simple socks proxy that rotates the outgoing addresses of connections:
- <https://github.com/elico/go-linux-tproxy/tree/master/examples/socks-proxy-1>

(I am only able to write\read English...)

**Comment by ginuerzh** [comment]
Many thanks for your great work!

**Comment by xxxman2008** [comment]
tproxy only works on xNix ，so, it will lost compaxxxbil(u know the word) .  I don't suggest it .  keep  simple and  stable is most wanted.

**Comment by elico** [comment]
@xxxman2008 it's an optional feature...
If you have and you need tproxy you can use it.

**Comment by ginuerzh** [comment]
Tproxy based UDP transparent proxy has been added in v2.10

**Comment by elico** [comment]
@ginuerzh Thanks!

**Comment by springzfx** [comment]
Will tproxy based **TCP** transparent proxy supported too?
