### ISSUE TITLE
救教：如何建立内部管道用来替换net.Listen和net.Conn

### ISSUE THREAD

**Issue by xuiv** [ginuerzh/gost#262]
gae不支持net.Listen，只有一个socket.Dial可以用，crowbard可以建立基于http的tcp连接，我在里面加了一个socket5代理服务器，如何去掉socket5对端口的侦听，让crowbard直接和socket5代理不通过端口通信？
我用两个bytes.Buffer替换后无法正常工作，它的read和write不会阻塞，cpu占用很快就会超100%，有不占用端口不是unix套接字的东西用吧，类似net.Conn但是不占端口不写磁 盘的。
我的代码在：https://github.com/xuiv/gae_proxy

**Comment by f4nff** [comment]
添加反向代理

A----内网---可以连接B (10.0.0.1)
B----外网---C可以连 (2.2.2.2)

C---连接B
B---连接A

C通过A的内网进行数据转发.

比如

```
A:   gost -F=mws://2.2.2.2:80?key=pass&tunnel=true
B:   gost -L=mws://:80?tunnel=true
C:   gost -L=:1080 -F=mws://2.2.2.2:80?key=pass&tunnel=true
```
目的,可以让几个内网的机子连接一个mws服务端,
这一个mws服务端根据key匹配多个内网转发数据,

你需要这种,本地不监听端口

**Comment by xuiv** [comment]
呵呵，谢谢了，我搞定了。
