### ISSUE TITLE
socks5代理加用户名密码的写法这样对吗？

### ISSUE THREAD

**Issue by chen56** [ginuerzh/gost#264]
docker:latest版的

docker run -d -p 7070:7070   --name gost ginuerzh/gost -L=socks5://gost:gost@:7070 -D貌似不工作

docker run -d -p 7070:7070   --name gost ginuerzh/gost -L=socks5://:7070 -D
不加密码可以工作

**Comment by ginuerzh** [comment]
服务端有log吗？
你可以尝试使用其他Socks5客户端去连接.。
