### ISSUE TITLE
strategy choice in simple+complex?

### ISSUE THREAD

**Issue by untoreh** [ginuerzh/gost#267]
I am not sure how the simple+complex strategy choice is made? Does simple follow the strategy defined in `peer.json`? I think an in-line option like `?strategy=random` would be needed so that for example you can have a preferred list of transports with `peer.json` and a random pool of ips by adding `?strategy=random` in the `peer.json` node configuration

**Comment by untoreh** [comment]
I think as it is now it can be made to work like this by nesting 2 `peer.json` so that you have the 
- **top** `?peer=peer_pt.json` with:
_fifo_ strategy and only `proto+transport://` specs

and each entry has another 

- **bottom** `?peer=peer_ips.json` with
_random_ strategy and only `?ip=iplist.txt`

**Comment by untoreh** [comment]
However there is this use case which I think behaves badly:
- There is 1 client (an ip) that is doing a lot of http requests
- if you use random, gost _potentially_ sets up a new tunnel for each requests
- this makes gost use a lot of ram (I reached 150M)
It can be worked around by setting  the `ttl` but I don't think it is the ideal solution because obviously gost is opening and closing a lot of connections.
I think there are 2 solutions:
- Classic IP hashing: the source of each client is mapped to a random tunnel (the first working tunnel, of course it should retry until it finds a working one)
- Once random: this is maybe easier to implement in gost, basically if there are no active tunnels (established connections) then the _first_ new tunnel is established using _random_ strategy. Subsequent clients all use this tunnel until there is no more traffic, then the next new tunnel is again chosen using random strategy. This could be further tweaked by using a "forced" `ttl` so that gost keeps switching dst ip at predefined intervals.
@ginuerzh what do you think?

**Comment by ginuerzh** [comment]
Yeah, we need a `strategy` param. The `?ip=...` usage is just a shorthand of the complex mode, so it follows the complex strategy.
For simplicity, the nested `?peer=...` options will be omited, only the `?ip=...` take effect.

**Comment by untoreh** [comment]
specifying `fifo` in peer.json and `?strategy=random` in nodes entry doesn't choose a random IP but always the first on `2.6`

**Comment by ginuerzh** [comment]
@untoreh Can't reproduce, could you provide more detail about your CMD and config?

**Comment by untoreh** [comment]
@ginuerzh 
If you have peer.txt
```
strategy fifo
max_fails 9
fail_timeout 30

peer http2://[user:pass]@:[port]?ip=ips.txt&strategy=round
peer mwss://[user:pass]@:[port]?ip=ips.txt&strategy=round
```
Logic would be to always use the first peer (`http2`) but rotating the ips (`strategy=round`)
and only pass over to peer `mwss` if all the "subpeers" of `http2` are within `fail_timeout`.

On the other hand if you have 
```
strategy round
max_fails 9
fail_timeout 30

peer http2://[user:pass]@:[port]?ip=ips.txt&strategy=fifo
peer mwss://[user:pass]@:[port]?ip=ips.txt&strategy=fifo
```
It should switch between `http2` and `mwss` at each request, but a request for example on `http2` should first try all the ips specified in `ips.txt` in `fifo` order and don't switch to `mwss` unless all the ips are in `fail_timeout`.

Currently, only the `strategy` defined in `peer` config file is fulfilled while the `strategy` parameter in the peer url is ignored.

If this level of fine tuning is useful is debatable since one could just do put the peers with the same type in the `peer` config like:
```
strategy round/fifo
max_fails 9
fail_timeout 30

peer http2://[user:pass]@ip1:[port]
peer http2://[user:pass]@ip2:[port]
peer http2://[user:pass]@ipn:[port]
peer mwss://[user:pass]@ip1:[port]
peer mwss://[user:pass]@ip2:[port]
peer mwss://[user:pass]@ipn:[port]
```
and it would be "mostly" the same but more verbose.
