### ISSUE TITLE
tls: oversized record received with length 20037

### ISSUE THREAD

**Issue by caoyufei** [ginuerzh/gost#268]
```
root@ip-172-31-46-222:/data# gost -L http+tls://:10086
2018/06/07 15:33:14 http.go:92: [http] 203.187.163.xxx:44791 - 172.31.46.222:10086 : tls: oversized record received with length 20037
```

**Comment by ginuerzh** [comment]
It is likely that some malformed data are sent to this port

**Comment by zouhua** [comment]
@ginuerzh  我是在python 里面用的代理，目标站点套了CF的 CDN

**Comment by ginuerzh** [comment]
CF本身已经是tls加密了，所以服务就不需再用tls模式了。

**Comment by untoreh** [comment]
maybe a blacklist should be added so that ips resulting in tls errors get blacklisted, and the blacklist should be saved on disk
