### ISSUE TITLE
VPS上已配置完毕，可是客户端无法连接

### ISSUE THREAD

**Issue by LeeGo486** [ginuerzh/gost#273]
作者，你好。
我在自己的VPS上已经配置完毕：
sudo gost -D -L=socks+tls://admin:admin123@:443?cert=cert.pem&key=key.pem
得到一个PID = 14118
客户端我用的是Suger，在Suger中我配置好后。无法访问VPS，不知道什么原因。我已经输入参数D，可是无法看到日志。
我不知道日志放在哪里，请指教。感谢

**Comment by ginuerzh** [comment]
日志默认是输出到stderr，你可以重定向到文件中:
```
gost -D -L="socks+tls://admin:admin123@:443?cert=cert.pem&key=key.pem" > gost.log
```
要注意的是如果参数中有`&`，则需要用引号`"`或`'`包裹参数。

**Comment by LeeGo486** [comment]
OK, 感谢作者
