### ISSUE TITLE
redirect 透明代理问题

### ISSUE THREAD

**Issue by jarwin123** [ginuerzh/gost#274]
hi：
   我的客户端是ubuntu，我的配置如下：
![default](https://user-images.githubusercontent.com/8475971/41835403-07256860-788a-11e8-9b53-20e8bad86b81.png)
![default](https://user-images.githubusercontent.com/8475971/41835486-57b55556-788a-11e8-9944-f168dcacf3fc.png)
服务端是台国外服务器，gost配置如下：
![default](https://user-images.githubusercontent.com/8475971/41835509-6c3b5e12-788a-11e8-8e3d-dabbb8de22a8.png)
我在客户端发起请求：
![default](https://user-images.githubusercontent.com/8475971/41835543-91d247bc-788a-11e8-8d3c-e3fbe4e49795.png)
请求总是错误。国外服务器访问youtube的结果如下：
![default](https://user-images.githubusercontent.com/8475971/41835605-d051f9f6-788a-11e8-8355-91dddb51670b.png)

我的配置是根据你提供的资料配置的，配置有什么问题吗？结果就是访问不了

**Comment by ginuerzh** [comment]
可能是dns的问题，你可以访问一个正常的网站试试。

**Comment by jarwin123** [comment]
www.youtube.com是正常的网页

**Comment by soffchen** [comment]
74.86.151.167 并不是 Google 的 IP，这个是 DNS 污染了

redirect 模式需要处理 dns 问题的

**Comment by jarwin123** [comment]
@soffchen 可以细说下吗？redirect模式需要处理dns问题

**Comment by soffchen** [comment]
先本地解析的

**Comment by jarwin123** [comment]
我解析了，为什么gost在下载东西的时候，总是连接会断，

**Comment by jarwin123** [comment]
session总是会端掉

**Comment by jarwin123** [comment]
![default](https://user-images.githubusercontent.com/8475971/42953519-37c1bf06-8bad-11e8-9b86-e1599b4b9928.png)

**Comment by jarwin123** [comment]
![default](https://user-images.githubusercontent.com/8475971/42953684-8d0a3cae-8bad-11e8-98f6-ce65dde94db6.png)

**Comment by jarwin123** [comment]
![default](https://user-images.githubusercontent.com/8475971/42954192-b4128b98-8bae-11e8-990a-f8cc4643ae4a.png)
![default](https://user-images.githubusercontent.com/8475971/42954233-cdd19722-8bae-11e8-8892-697fdf120653.png)
这个是服务器端日志，wget 一个文件，总是间断

**Comment by ginuerzh** [comment]
你的ss服务端用的是什么版本

**Comment by jarwin123** [comment]
2.5

**Comment by ginuerzh** [comment]
服务端有报错吗，从客户端看是30秒超时，这个在2.5版本之前是ss的一个bug(#158)，在2.5中已经修复。
你可以换成其他类型的代理(如http,socks5)再试试。

**Comment by recall704** [comment]
像 youtube 这样的网站，最好使用 sni，不要使用 redirect

**Comment by lucifersp** [comment]
> 2.5
> ![default](https://user-images.githubusercontent.com/8475971/42977730-803e3432-8bfb-11e8-8c00-d1efb3298ea2.png)



> ![default](https://user-images.githubusercontent.com/8475971/42954192-b4128b98-8bae-11e8-990a-f8cc4643ae4a.png)
> ![default](https://user-images.githubusercontent.com/8475971/42954233-cdd19722-8bae-11e8-8892-697fdf120653.png)
> 这个是服务器端日志，wget 一个文件，总是间断

你好，我也遇到了和你一样的问题，请问你最后是怎么解决的，方便告知一下吗
