### ISSUE TITLE
AWS的EC2主机问题

### ISSUE THREAD

**Issue by LeeGo486** [ginuerzh/gost#275]
作者，你好：
这两天我又申请了一个AWS--EC2的VPS，我想试一试HTTPS隧道。
这是我的命令：`sudo gost -L=http+tls://admin:admin123@domain.com:443?cert=cert.pem&key=key.pem`
执行结果返回了一个PID，但是接着日志里面就显示：
`2018/06/28 03:53:06 main.go:79: listen tcp xxx.xxx.xxx.255:443: bind: cannot assign requested address`
防火墙我开了，端口我也开了。
请问作者，这是AWS的问题吗？

**Comment by ginuerzh** [comment]
Dup #273

**Comment by LeeGo486** [comment]
我把命令中的域名去掉就好了。
原命令：
`sudo gost -L=http+tls://admin:admin123@domain.com:443?cert=cert.pem&key=key.pem`
新命令：
`sudo gost -L=http+tls://admin:admin123@:443?cert=cert.pem&key=key.pem`

**Comment by ginuerzh** [comment]
监听的地址只能是本地的IP，EC2中的IP都是内网IP，域名对应的IP是一个公网IP， 所以是无法监听的。

**Comment by LeeGo486** [comment]
OK,感谢作者，我还是去换个主机吧。EC2太麻烦。
