### ISSUE TITLE
路由控制域名匹配不正确

### ISSUE THREAD

**Issue by deepjia** [ginuerzh/gost#276]
期望结果:
对 Gost 2.6，配置 Bypass 规则，使得 `ip.cn` 和 `www.ip.cn` 均被匹配，不走代理

根据文档：
在 `-F` 的参数末尾添加 `?bypass=bypass.txt`
`bypass.txt` 中添加 `*.ip.cn` ，规则应能够匹配 `ip.cn` 和 `www.ip.cn`

实际结果：
配置为 `*.ip.cn` 时，对 `www.ip.cn` 匹配，对 `ip.cn` 不匹配
尝试配置为 `ip.cn` 时: 均不匹配
尝试配置为 `.ip.cn` 时: 均不匹配
尝试配置为 `*ip.cn` 时: 终于两者均匹配

存在的问题：
`*.ip.cn` 匹配的不正确，应能匹配上裸域 `ip.cn` 和非裸域 `www.ip.cn`
`.ip.cn` 也应该能匹配上裸域 `ip.cn` 和非裸域 `www.ip.cn`
`ip.cn` 应当能匹配裸域

**Comment by ginuerzh** [comment]
bypass中域名采用的是通配符匹配方式，`*.example.com` 这种只能匹配上example.com的子域名。不过后面会考虑对`.example.com`这种特殊形式的支持。

**Comment by deepjia** [comment]
后面的两条是提议，issue 主要是指到第一条：
规则写的是`*.ip.cn`，能匹配到`https://ip.cn`，但无法匹配到`https://www.ip.cn`

**Comment by ginuerzh** [comment]
按照通配符规则，是不应该匹配，所以就需要`.example.com`这种特殊方式来匹配这种需求。

**Comment by deepjia** [comment]
哦对，那看起来其他的匹配方式是必要的了，这是个 Feature 了

希望后面可以有正则或者 .example.com 这种方式

**Comment by deepjia** [comment]
已验证生效 #https://github.com/ginuerzh/gost/commit/c11b5ddce8f198589a3a2dabb849da38620bffc0
