### ISSUE TITLE
Certbot创建的证书GOST无权限读取

### ISSUE THREAD

**Issue by LeeGo486** [ginuerzh/gost#277]
作者，你好：
不好意思，又是我有问题。请海涵～
经过这段时间的折腾，学到了GOST的不少使用方法。从不会看log，到EC2无法解析域名，都得到了你的帮助，非常感谢。

这次，我使用别的主机商，创建了一台新的VPS。用Certbot生成了证书。
证书位置：
> /etc/letsencrypt/live/domain.com/live/cert.pem

> /etc/letsencrypt/live/domain.com/live/privkey.pem

这些都准备好后，我用如下命令去创建我的隧道：
`sudo gost -D -L="http+tls://admin:admin123@domain.com:443?cert=/etc/letsencrypt/live/domain.com/cert.pem&key=/etc/letsencrypt/live/domain.com/privkey.pem" > gost.log`
得到的结果是：

> open /etc/letsencrypt/live/domain.com/cert.pem: permission denied

我虽然用了sudo，但感觉gost还是无法提升权限来读取文件。
请问作者，问题出在哪里？

**Comment by LeeGo486** [comment]
补充点信息，我用的是ubuntu 16.04，gost 是通过sudo snap apt-get install gost安装的。

**Comment by ginuerzh** [comment]
snap安装的gost是没有权限访问非home目录，参考#147

**Comment by LeeGo486** [comment]
明白了，谢谢。
