### ISSUE TITLE
QUIC的问题

### ISSUE THREAD

**Issue by testcaoy7** [ginuerzh/gost#278]
服务器上运行的gost命令：
`gost -L="socks5+quic://:443?cert=mydomain.com.cer&key=mydomain.com.key"`

客户端的命令：
`gost -L=:8080 -F="socks5+quic://11.22.33.44:443"`（11.22.33.44为服务器IP）

症状：QUIC无法连接

服务器日志输出：`quic.go:212: [quic] accept: cipher: message authentication failed`
客户端日志输出：`quic dial HandshakeTimeout: Crypto handshake did not complete in time.`

**Comment by ginuerzh** [comment]
这个是由于参数命名冲突导致的，QUIC后来增加了一个AES加密的功能，可以对原始UDP数据再进行一次加密。所使用的加密密钥也是通过`key`参数来设定，所以与tls证书的参数冲突。
在2.6版本中已经修正。

**Comment by testcaoy7** [comment]
好久了，2.6正式版还没发布呀
