### ISSUE TITLE
负载均衡可否支持本地端口？

### ISSUE THREAD

**Issue by chenhw2** [ginuerzh/gost#279]
场景：
服务A: 监听本地 1000
服务B: 监听本地 1001
服务C: 监听本地 1002

GOST:
监听2000，负载均衡到上面的3个端口

现在的GOST看起来要forward才能负载均衡

**Comment by ginuerzh** [comment]
2.6中的端口转发直接支持负载均衡，不需要再进行一次forwarding了：
```
gost -L tcp://:2000/:1000,:1001,:1002
```

**Comment by chenhw2** [comment]
好的 谢谢

应该是本地端口转发`gost -L tcp://:2000/127.0.0.1:1000,127.0.0.1:1001,127.0.0.1:1002`

**Comment by chenhw2** [comment]
v2.6.1正常
v2.7.0开始出现上述错误
