### ISSUE TITLE
socks+wss方式出错

### ISSUE THREAD

**Issue by helloyan** [ginuerzh/gost#28]
使用socks+ws方式时可以正常连接，但是wss则报错
版本：RC2
http: TLS handshake error from 114.230.*.*:52455: tls: first record does not look like a TLS handshake

**Comment by helloyan** [comment]
请帮忙关闭，是我自己搞错了，服务器端更新了rc2，客户端忘记同步更新

**Comment by jinlongplus** [comment]
我也遇到这个问题了！
服务端的配置：
-L="socks+wss://:443" 
客户端的配置：
 -L=:8080 -F=socks+ws://server_ip:port
