### ISSUE TITLE
可以增加对 TCP Fast Open (TFO) 的支持吗？

### ISSUE THREAD

**Issue by pexcn** [ginuerzh/gost#283]
可以快那么一点...

**Comment by ginuerzh** [comment]
Blocked by https://github.com/golang/go/issues/4842

**Comment by Anankke** [comment]
Go 已经支持 TFO，请重新考虑支持。

**Comment by ginuerzh** [comment]
有吗？貌似官方已经明确不支持了，我想这个功能可以cancel掉了，意义不大
