### ISSUE TITLE
bypass 白名单规则不生效

### ISSUE THREAD

**Issue by everyx** [ginuerzh/gost#285]
使用如下的配置文件

```json
{
    "Debug": false,
    "Retries": 1,
    "ServeNodes": [
        ":5580?bypass=~bypass.txt&secrets=secrets.txt",
        ":5581"
    ],
    "ChainNodes": [
        "socks5://127.0.0.1:1080"
    ]
}
```

secrets 设置是 ok 的，但是 bypass 就不行，我的理解就是使用 `~` 以后，只有我加入到 `bypass.txt` 中的域名才会走本地的 socks 代理，其他的则不会，但是我再 `bypass.txt` 中加入如下内容后打开百度，还是会走代理

```txt
.google.com
*.google.com
```

是我的配置错误还是我的理解有问题呢？使用的版本是 2.5

**Comment by ginuerzh** [comment]
bypass 是2.6版本中新增的功能

**Comment by everyx** [comment]
@ginuerzh 以为最新的release 版本肯定支持文档中的所有功能，请问 2.6 什么时候发布？

**Comment by ginuerzh** [comment]
近期会发布RC版

**Comment by everyx** [comment]
@ginuerzh 今天尝试了一下 RC 版本，发现 bypass 是直接拒绝对应请求，对应的 Wiki 中的描述

```
当执行代理链的节点选择时，每当确定一个代理链层级节点后，会应用此节点上的路由配置(bypass参数)，若此次请求的目标地址包含在此配置中，则代理链终止于此节点(且不包含此节点)。
```

请问怎么设置才能让不在 名单内 的走直连呢？

**Comment by fiysid** [comment]
在ChainNodes里面"socks5://127.0.0.1:1080?bypass=~bypass.txt"

**Comment by koaiwu** [comment]
在ChainNodes里面"socks5://127.0.0.1:1080?bypass=~bypass.txt"

**Comment by cloudruan** [comment]
> @ginuerzh 今天尝试了一下 RC 版本，发现 bypass 是直接拒绝对应请求，对应的 Wiki 中的描述
> 
> ```
> 当执行代理链的节点选择时，每当确定一个代理链层级节点后，会应用此节点上的路由配置(bypass参数)，若此次请求的目标地址包含在此配置中，则代理链终止于此节点(且不包含此节点)。
> ```
> 
> 请问怎么设置才能让不在 名单内 的走直连呢？

我也有这个问题，怎么搞定呢？

**Comment by perk67h6ins** [comment]
> > @ginuerzh 今天尝试了一下 RC 版本，发现 bypass 是直接拒绝对应请求，对应的 Wiki 中的描述
> > ```
> > 当执行代理链的节点选择时，每当确定一个代理链层级节点后，会应用此节点上的路由配置(bypass参数)，若此次请求的目标地址包含在此配置中，则代理链终止于此节点(且不包含此节点)。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问怎么设置才能让不在 名单内 的走直连呢？
> 
> 我也有这个问题，怎么搞定呢？

同问
