### ISSUE TITLE
路由控制的格式说明

### ISSUE THREAD

**Issue by everyx** [ginuerzh/gost#287]
在 [wiki 中](https://docs.ginuerzh.xyz/gost/bypass/) 举了如下的例子

```
127.0.0.1       只匹配直接 IP 访问的，还是也会匹配带域名解析后的 IP？
172.10.0.0/16   同上
localhost
*.example.com   通配符匹配
.example.org    匹配 www.example.com 和 example.com?
```
疑惑在于 
1. IP 或者 IP 段匹配的时候是否会包含解析后匹配到该 IP 的访问？
2. .example.com 这类的匹配是匹配哪些？

**Comment by ginuerzh** [comment]
bypass的过滤是在域名解析之前，所以不处理解析后的IP。
`.example.com`这种形式与`*example.com`是一样的，会匹配`example.com`，`sub.example.com`。

**Comment by everyx** [comment]
好的，那通配符支持像

subdoma*.example.com 能匹配到  subdomain.example.com 和 subdomain.subdomain.example.com 吗？

**Comment by ginuerzh** [comment]
支持

**Comment by cloudruan** [comment]
如果域名在bypass范围内，比如*.cn, 能否支持让该域名可以直接访问，而不是现在的拒绝访问?

**Comment by ginuerzh** [comment]
@cloudruan 你是怎么使用的
