### ISSUE TITLE
关于2.6版的“路由控制”和“DNS控制”的建议

### ISSUE THREAD

**Issue by jzp820927** [ginuerzh/gost#289]
1、DNS 控制当中的 DNS 的协议类型，目前有：udp， tcp，tls，三种，能不能再增加一个 doh 协议 （DNS over HTTPS），比如 Google DNS over HTTPS。
2、路由控制，目前有 IP,CIDR,域名或域名通配符地址 等几种类型，能否再增加一个 协议类型，比如按 http、https 等不同的协议类型来匹配黑白名单模式。

**Comment by ginuerzh** [comment]
1. DoH在2.7版中已经添加
2. 暂不考虑更上层的协议类型

**Comment by jzp820927** [comment]
收到，谢谢！
