### ISSUE TITLE
关于文档中的scheme写法

### ISSUE THREAD

**Issue by weijarz** [ginuerzh/gost#290]
https://docs.ginuerzh.xyz/gost/configuration/
这里似乎说scheme是协议类型+传输类型，比如ss+h2c时是这样，但是用tcp/quic时似乎要反过来
```
server: gost -L 'ss+quic://chacha20:pwd@:8080
client: gost -L=:8123 -F=ss+quic://chacha20:pwd@ip:8080
```
这样写连接不上。

反而是传输类型+协议类似能连上：
```
server: gost -L 'quic+ss://chacha20:pwd@:8080
client: gost -L=:8123 -F=quic+ss://chacha20:pwd@ip:8080
```

是我理解有误吗？

另外quic+ss或kcp+ss时，对于没被墙的网址没问题，google之类就打不开会reset，似乎是退化成明文被墙拦截了，不知道是哪里的问题。

**Comment by ginuerzh** [comment]
`ss+quic`是正确的写法，我在本地测试是没问题的。
`quic+ss`是错误用法，这种写法等同于`http`。

协议类型如果不支持，则会被当作`http`;
传输类型如果不支持，则会被当作`tcp`。

**Comment by weijarz** [comment]
@ginuerzh 谢谢，你这么一说我理解了我碰到的现象了。

刚才试了下也知道了为什么之前我试的基于udp的kcp和quic都不行，因为我用的digitalocean家的vps，它家有一好处是一个本机ip和一个免费float ip可以指向本地ip。因为我是多人共用，ip经常被杀，用float ip比别家都方便之处是不用删除新建机子，花一分钟换个float ip就行。刚才试下来用本机ip才行，看来float ip过不了udp流量。

PS.  gost在linux下用似乎不会打印任何出错信息，甚至比如端口冲突直接退出等
