### ISSUE TITLE
TCP透明代理 + http(s)抓包

### ISSUE THREAD

**Issue by gitprotogit** [ginuerzh/gost#291]
请问目前使用gost当redirect代理，希望在这个代理中抓包调试是否可行？

目前有两种思路，一个是把tcp拷贝一份，但是看了一下代码，好像io使用一次就没用了，不知道可以如何拷贝，一种是tcp转成http协议，但是这样又会有功能缺陷。

请求大大帮忙，指点迷津，谢谢

**Comment by ginuerzh** [comment]
代码中可以通过一个中间buffer来捕获数据，先copy到buffer中

**Comment by ginuerzh** [comment]
你可以在`transport()`中捕获数据：https://github.com/ginuerzh/gost/blob/master/server.go#L101
