### ISSUE TITLE
希望能加入全平台SDK，例如这样。

### ISSUE THREAD

**Issue by XYDsoft** [ginuerzh/gost#294]
gost功能出众，但是很多不熟悉go语言的开发者使用起来还是多有不便的
为了让更多的开发者参与进来，我建议加入全平台SDK，
例如下面这个同类项目
_

> 为防止广告宣传嫌疑，链接被隐藏

_

**Comment by f4nff** [comment]
very good～

**Comment by ginuerzh** [comment]
目前没有过多精力来做这一块
