### ISSUE TITLE
动态更新配置文件

### ISSUE THREAD

**Issue by XYDsoft** [ginuerzh/gost#295]
每次修改完配置文件都要先将gost结束掉再开启
使用起来有些不方便
希望能够动态载入和更新配置文件
例如可以指定web端口，通过web提交配置文件
这样也能远程更新配置文件
希望作者能够考虑加入

**Comment by ginuerzh** [comment]
目前部分配置已经支持热更新，其他配置文件热更新比较复杂，后续版本中再考虑。
