### ISSUE TITLE
sni有问题?

### ISSUE THREAD

**Issue by wxdczd** [ginuerzh/gost#297]
2018/09/13 11:55:42 sni.go:98: [sni] [bypass] :443
panic: runtime error: slice bounds out of range

goroutine 446 [running]:
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector.(*ClientHelloHandshake).ReadFrom(0xc4203dec40, 0xbe8f20, 0xc42007ac90, 0x3a, 0x0, 0x0)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector/handshake.go:102 +0x999
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector.(*ClientHelloHandshake).Decode(0xc4203dec40, 0xc42008a100, 0x35, 0x35, 0x0, 0xc4203deb70)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector/handshake.go:47 +0x89
github.com/ginuerzh/gost.readClientHelloRecord(0x7f645c3e5498, 0xc42007e0c0, 0x0, 0x0, 0xc42007e000, 0x0, 0x0, 0xc4201606c0, 0xc420001828, 0xc420026538, ...)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/sni.go:221 +0xc6
github.com/ginuerzh/gost.(*sniHandler).Handle(0xc420096058, 0xbf57a0, 0xc42000c008)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/sni.go:85 +0x7cc
created by github.com/ginuerzh/gost.(*Server).Serve
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/server.go:81 +0x46f

**Comment by ginuerzh** [comment]
这个问题可以复现吗？

**Comment by dreamren** [comment]
可以说100%复现了吧
`panic: runtime error: slice bounds out of range

goroutine 6277 [running]:
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector.(*ClientHelloHandshake).ReadFrom(0xc420a3ec40, 0xbe8f20, 0xc422f82000, 0x3a, 0x0, 0x0)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector/handshake.go:102 +0x999
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector.(*ClientHelloHandshake).Decode(0xc420a3ec40, 0xc424406900, 0x35, 0x35, 0x0, 0xc420a3eb70)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector/handshake.go:47 +0x89
github.com/ginuerzh/gost.readClientHelloRecord(0x7f15add1c140, 0xc4233837e0, 0x0, 0x0, 0xc423383700, 0x0, 0x0, 0xc423f10320, 0xc422885540, 0x10, ...)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/sni.go:221 +0xc6
github.com/ginuerzh/gost.(*sniHandler).Handle(0xc42000c078, 0xbf57a0, 0xc423f10358)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/sni.go:85 +0x7cc
created by github.com/ginuerzh/gost.(*Server).Serve
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/server.go:81 +0x46f
`

**Comment by dreamren** [comment]
> 这个问题可以复现吗？



> 这个问题可以复现吗？

可以说是100%复现
`panic: runtime error: slice bounds out of range

goroutine 6277 [running]:
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector.(*ClientHelloHandshake).ReadFrom(0xc420a3ec40, 0xbe8f20, 0xc422f82000, 0x3a, 0x0, 0x0)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector/handshake.go:102 +0x999
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector.(*ClientHelloHandshake).Decode(0xc420a3ec40, 0xc424406900, 0x35, 0x35, 0x0, 0xc420a3eb70)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector/handshake.go:47 +0x89
github.com/ginuerzh/gost.readClientHelloRecord(0x7f15add1c140, 0xc4233837e0, 0x0, 0x0, 0xc423383700, 0x0, 0x0, 0xc423f10320, 0xc422885540, 0x10, ...)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/sni.go:221 +0xc6
github.com/ginuerzh/gost.(*sniHandler).Handle(0xc42000c078, 0xbf57a0, 0xc423f10358)
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/sni.go:85 +0x7cc
created by github.com/ginuerzh/gost.(*Server).Serve
	/Users/zhengrui/src/go/src/github.com/ginuerzh/gost/server.go:81 +0x46f
`

**Comment by dreamren** [comment]
跑一会就会出现这种情况然后挂掉~

**Comment by dreamren** [comment]
使用的方法是这样的：
gost -L sni://:443 -F=ss://password:method@ip:port
并发量较高的时候甚至秒挂，如果需要的话可以提供测试机器

**Comment by dreamren** [comment]
测试了下v2.6，问题已经得到解决，作者辛苦了！

**Comment by 2378** [comment]
> 测试了下v2.6，问题已经得到解决，作者辛苦了！

thank for share

**Comment by dreamren** [comment]
v2.6跑了几天后，问题又出现了一次
panic: runtime error: slice bounds out of range

goroutine 9174015 [running]:
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector.(*ClientHelloHandshake).ReadFrom(0xc001feec50, 0x9c8d20, 0xc001a89e90, 0x0, 0x0, 0xc0003687e0)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector/handshake.go:82 +0x8e3
github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector.(*ClientHelloHandshake).Decode(0xc001feec50, 0xc00005c000, 0x69, 0x69, 0x0, 0xc001feeb00)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/vendor/github.com/ginuerzh/tls-dissector/handshake.go:47 +0x88
github.com/ginuerzh/gost.readClientHelloRecord(0x7fd5d27ed000, 0xc000368760, 0x0, 0x0, 0xc000368700, 0x0, 0x0, 0xc0013d2c00, 0xc000879d88, 0x554b28, ...)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/sni.go:221 +0xed
github.com/ginuerzh/gost.(*sniHandler).Handle(0xc00000c078, 0x9d2480, 0xc000134318)
        /Users/zhengrui/src/go/src/github.com/ginuerzh/gost/sni.go:85 +0x73e
created by github.com/ginuerzh/gost.(*Server).Serve

**Comment by ginuerzh** [comment]
请使用2.7版本
