### ISSUE TITLE
DNS控制 配置文件不支持ipv6

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#298]
https://docs.ginuerzh.xyz/gost/dns/

`timeout     30
ttl         60

# ip[:port] [protocol] [hostname]
8.8.8.8
8.8.8.8     tcp
1.1.1.1     udp
1.1.1.1:53  tcp
1.1.1.1:853 tls     cloudflare-dns.com `

参数支持ip6，dns.txt里面不支持ipv6

**Comment by ginuerzh** [comment]
dns配置文件中是支持ipv6的，格式为：
::1
或
[::1]:53

**Comment by ginuerzh** [comment]
不过2.6版本中DNS的failover机制有问题，在2.7分支中已经修复。
