### ISSUE TITLE
I use it as websockets, there is no reaction

### ISSUE THREAD

**Issue by ericyin521** [ginuerzh/gost#3]
I deploy it on c9.io cloud, the teminal prompt "ws.go:64: websocket: version != 13" , I think the cloud server has been running , my client computer is OSX 10.7 , I type this in teminal ,"./gost -L=:8080 -S=demo-project-Myusername.c9.io -ws" , there is no reaction except infinite waiting

**Comment by ginuerzh** [comment]
You should configure your web browser proxy to use it
