### ISSUE TITLE
2.0 rc2触发google的异常流量监测

### ISSUE THREAD

**Issue by helloyan** [ginuerzh/gost#30]
经测试，2.0RC2版本会触发google的异常流量监测，加密方式为 socks5+tls/wss，使用2.0RC版本则没有遇到此问题

关于此网页

我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认这些请求是由您而不是自动程序发出的。为什么会这样？

如果 Google 自动检测到从您的计算机网络发出的请求可能违反服务条款，就会显示此网页。这些请求一旦停止，此阻断即会失效。在此期间，如果您能破解上述人机识别系统，就可以继续使用我们的服务。

该流量可能是由恶意软件、浏览器插件或发送自动请求的脚本发出的。如果您与他人共享网络连接，请向管理员寻求帮助 — 这可能是由多台计算机使用同一 IP 地址导致的。了解详情

有时，如果您使用的是自动程序普遍使用的高级条款或者正在快速连续地发送请求，则可能需要破解人机识别系统。

IP 地址：2400:8900::f03c:91ff:fe3b:****
时间：2016-01-26T01:01:56Z
网址：https://www.google.com/search?q=asdf&ie=utf-8&oe=utf-8

**Comment by soffchen** [comment]
Google 对 ipv6 的检查一直莫名其妙，我估计不是 gost 的问题。

**Comment by helloyan** [comment]
有办法解决吗？

**Comment by soffchen** [comment]
服务器出去的时候不要走 ipv6

**Comment by ginuerzh** [comment]
这种情况有时会出现，有时又不会，特别在切换代理服务器时，出现几率较高，目前还不清楚检测机制。

**Comment by helloyan** [comment]
我这里2.0RC版本从没出现过，RC2每次请求必现

**Comment by helloyan** [comment]
see here [Google屏蔽Linode的IPv6导致SSH隧道不可用
](http://codelife.me/blog/2013/11/16/google-block-linode-traffic-over-ipv6/)
