### ISSUE TITLE
有没有考虑作icmp，ping代理？

### ISSUE THREAD

**Issue by Justsoos** [ginuerzh/gost#301]
早年的ptunnel是C写的，性能瓶颈大，跨平台也不好，也没人维护了，如果gost能重造go版本，那就太有吸引力了。

**Comment by Git-XiaoQin** [comment]
+1

**Comment by Justsoos** [comment]
https://github.com/wangyu-/udp2raw-tunnel  wangyu 做了

**Comment by f4nff** [comment]
@Justsoos 

https://github.com/wangyu-/udp2raw-tunnel根本不是 tcp/udp over icmp

**Comment by ginuerzh** [comment]
v3版本中已经添加：https://gost.run/tutorials/icmp/
