### ISSUE TITLE
epoll_wait超过128无法正常运行，端口关闭

### ISSUE THREAD

**Issue by j0ck1e** [ginuerzh/gost#302]
**gost version: 2.5**
**distribution: ubuntu 18.04**

`gost -L ss+obfs4://aes-256-cfb:123456789@:18080`
---
### 问题1:
使用`nc`和`strace`简单调试之后发现 每发一个包会产生一个`epoll_wait`，当发包128个之后`gost`程序就无法正常收到包，此时端口还开放
![](https://files.catbox.moe/x4xxb3.png)

---
### 问题2:
正常使用的过程中隔三差五会出现程序还在运行但是绑定的端口却关闭了的情况

**Comment by ginuerzh** [comment]
我在本地测试没有发现什么问题，不排除是网路干扰。
端口关闭是否有异常log?

**Comment by j0ck1e** [comment]
### 问题一复现方式
```bash
gost -D -L ss+obfs4://aes-256-cfb:123456789@:18080
```

使用strace分析进程
```bash
sudo strace -vfF -p <进程pid>
```

写一个脚本并运行
```shell
i=1
while [ 1=1 ];
  do
    nc -z -v 127.0.0.1 18080;
    echo $i;
    i=$(($i+1));
  done
```

此时可以观察到`strace`输出大概128行的`epoll_wait`，`gost`程序没有任何日志产生，这之后就收不到数据包了
```
[pid  5845] epoll_wait(4, [{EPOLLIN, {u32=1830629232, u64=139760066441072}}], 128, -1) = 1
[pid  5845] epoll_wait(4, [{EPOLLIN, {u32=1830629232, u64=139760066441072}}], 128, -1) = 1
[pid  5845] epoll_wait(4, [{EPOLLIN, {u32=1830629232, u64=139760066441072}}], 128, -1) = 1
```

### 端口异常关闭，程序还在运行的问题
首先`dmesg` 、`journal -f`没有发现任何系统上的报错或警告
`gost`没有输出任何日志（`server inited`这个先不算）,使用`strace`跟踪，内容较多，贴pastebin里了
<https://pastebin.com/H2YfHHuE>
