### ISSUE TITLE
logs to fluentbit or another UDP TCP server

### ISSUE THREAD

**Issue by mhf-ir** [ginuerzh/gost#306]
How can we have log collector ?
Specially for timeouts and errors?

I have centralized  log like ELK or Fluentd or FluentBit ... in need special method or config to pass data into log server. JSON is preferred.

**Comment by mhf-ir** [comment]
Also if log file based on syslog rfc we can use with fail2ban for block unauthorized requests

**Comment by ginuerzh** [comment]
To keep it simple, I have no plan for it.
