### ISSUE TITLE
next proxy on failure, try, healthcheck

### ISSUE THREAD

**Issue by mhf-ir** [ginuerzh/gost#307]
If gost had mechanism that serve the proxy and try to connect via multiple options will be awesome:

gost listen on socks5://:9090 and if request received then try to connect via "socks5://server-a:22" if faild then try to send to "socks5://server-b:23" and will be better if remember this option as first choose on next request.

Even better using multiple choose level: Round robin or last healthy or much better in another thread test them and bring up quickest one as first proxy .

This feature will be helpful on cross countries or data centers for connection fail over solution.

**Comment by ginuerzh** [comment]
The `retry` feature has been add for proxy chain in v2.5, see [the doc](https://docs.ginuerzh.xyz/gost/en/getting-started/#configuration-file).

When a request received, the proxy chain first performs node selection (random, round-robin or fifo) for each level to determine a path, then a connection to the target address will be established through the selected path. If the connection failed and retry > 1, a new path will be selected again.

**Comment by mhf-ir** [comment]
i will try it thanks for support
