### ISSUE TITLE
remote: conn.go:10:2: cannot find package "github.com/golang/glog" in any of:

### ISSUE THREAD

**Issue by Xiaoyuyexi** [ginuerzh/gost#31]
remote: 	/app/tmp/cache/go1.4.2/go/src/github.com/golang/glog (from $GOROOT)
remote: 	/tmp/build_0e42156230034c956db02b5cb5cd4412/.heroku/go/src/github.com/ginuerzh/gost/Godeps/_workspace/src/github.com/golang/glog (from $GOPATH)
remote: 	/tmp/build_0e42156230034c956db02b5cb5cd4412/.heroku/go/src/github.com/golang/glog
remote: godep: go exit status 1
remote: 
remote:  !     Push rejected, failed to compile Go app

这要怎么办 heroku 不支持 import "github.com/golang/glog" ??

**Comment by amu1680c** [comment]
你的第三方依赖库用的还是1.x版本的，这样是部署不了的
