### ISSUE TITLE
compile failed with go1.11

### ISSUE THREAD

**Issue by h1k0n** [ginuerzh/gost#314]
![image](https://user-images.githubusercontent.com/11515010/47332493-12a31300-d6b2-11e8-83d2-76e6372658d0.png)

**Comment by h1k0n** [comment]
Thank you. Maybe I should describe my problem directly. From vendor.json we know the revision of kcp-go.v2 is bf95749e1be2. If I set GO111MODULE=off and build, no error. if I set GO111MODULE=on and build,  get error. I think update the revision in vendor.json can fix this problem.

**Comment by ginuerzh** [comment]
This repo has not been tested against Go module feature, it currently uses `govendor` for the package management.
