### ISSUE TITLE
报错，监听端口失败 main.go:79: listen tcp :12355: setsockopt: permission denied

### ISSUE THREAD

**Issue by Zyx-A** [ginuerzh/gost#317]
以多种方式执行命令，都会报错，参考如下：
> $ sudo /snap/bin/gost -L redirect://:12355 -F 127.0.0.1:1080
> $ sudo /snap/bin/gost -L :12355 -F 127.0.0.1:1080
> $ gost -L :12355 -F 127.0.0.1:1080
> $ sudo su - root
> \# /snap/bin/gost -L :12355 -F 127.0.0.1:1080

都报相同的错：
> main.go:79: listen tcp :12355: setsockopt: permission denied

gost版本：
> gost 2.5 (go1.10)

go环境版本：
> go version go1.10.2 linux/amd64

操作系统版本：
> deepin 15.7
> 类同 debian 8.0

**Comment by ginuerzh** [comment]
snap版的限制较多，建议使用发布的二进制版
