### ISSUE TITLE
TCP 透明代理

### ISSUE THREAD

**Issue by yisangwu** [ginuerzh/gost#320]
TCP 透明代理 后端server 拿到的还是 gost机器的ip。。。。  
client ip 呢？ 
后端server 可以那一下吗？

**Comment by ginuerzh** [comment]
TCP透明代理是作用于传输层，类似于NAT，已经将客户端与服务器之间隔离，无法直接获取客户端的IP。

**Comment by yisangwu** [comment]
多谢回复解惑，谢谢！
