### ISSUE TITLE
是否可以请作者写个 Systemd  的 配置脚本

### ISSUE THREAD

**Issue by raymondmeg** [ginuerzh/gost#328]
如题，是否可以请作者写个 Systemd 的 service 脚本。我现在是这样写的 ：

[Unit]  
Description=Gost   
[Service]  
ExecStart=/opt/gost_2.4_linux_amd64/gost  -L=xxxx -D=false >/dev/null 2>&1

ExecStop=/bin/kill -TERM $MAINPID
  
ExecReload=/bin/kill -HUP $MAINPID  

killMode=process  
After=network.target  

[Install]  
WantedBy=multi-user.target  

“gost_2.4_linux_amd64”  这个请忽略，实际目前版本是 2.5  。。但是，最近一个月，发现 隔一阵子 ，这个 Gost.service  会 停止工作。

因此，是否可以请作者做个  Systemd 的标准  Service 文件。。以便能 long live  running 。。

**Comment by danangua** [comment]
建议尝试版本gost_2.1，后续版本碰到某些恶意扫描会出错。我用ss协议时试过很多版本。

**Comment by recall704** [comment]
```
cat > gost.service << EOF
[Unit]
Description=Gost Proxy
After=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/gost -L=:8080
Restart=always

[Install]
WantedBy=multi-user.target
EOF
```

可以参考下这个

**Comment by tychusyuan** [comment]
[Unit]
Description=Gost Proxy
After=network.target
Wants=network.target

[Service]
Type=simple
StandardError=journal
User=work
AmbientCapabilities=CAP_NET_BIND_SERVICE
ExecStart=/home/work/app/gost/gost -C /home/work/etc/gost/gost.json
ExecReload=/bin/kill -HUP $MAINPID
Restart=always

[Install]
WantedBy=multi-user.target
