### ISSUE TITLE
请问能不能给客户端加个回显

### ISSUE THREAD

**Issue by fyhong** [ginuerzh/gost#329]
就是成功连接到服务器后，客户端显示sucess之类的文字

**Comment by ginuerzh** [comment]
连接成功会有类似：
```
x.x.x.x:xx <-> x.x.x.x:xx
```
这种提示

**Comment by fyhong** [comment]
这种提示只会在数据请求时才显示，而且即使两ip之间配置误误，这种提示仍然会出现。
我需要的是像狗洞之类的软件一样， 客户端成功连接到服务器就显示。
这样可以看到服务器和客户端之间是不是通的。不需打开浏览器，访问网站，然后发现访问不了才知道配置有问题.

**Comment by ginuerzh** [comment]
客户端不会主动去连接服务器，只在请求到来时才会去连接。
