### ISSUE TITLE
website thumbnails return 404

### ISSUE THREAD

**Issue by 7KjN3mHq** [ginuerzh/gost#33]
When I access http://exhentai.org/ (need login e-hentai first) Display as Thumbnails can find many 404 with gost-2.0-rc2 client.
Using squid is ok.
Maybe this is "User-Agent: Go-http-client/1.1" caused?

**server log**:
I0209 18:25:18.762884   10603 http.go:21] [http] CONNECT exhentai.org:80
I0209 18:25:19.078412   10603 http.go:60] HTTP/1.1 200 Connection established
Proxy-Agent: gost/2.0-rc2

**client log**:
I0209 18:25:25.645671   26596 http.go:76] [http] CONNECT exhentai.org OK
I0209 18:25:25.645671   26596 conn.go:80] [::1]:7465 disconnected, connections:11
I0209 18:25:28.631839   26596 conn.go:75] [::1]:7491 connected, connections: 12

**Comment by ginuerzh** [comment]
that is ok for me, a thumbnail is displayed with no error.

**Comment by 7KjN3mHq** [comment]
Thanks for your check. It works well now, maybe server caused this issue.
