### ISSUE TITLE
远程端口映射，不能自动重连。

### ISSUE THREAD

**Issue by guijun** [ginuerzh/gost#330]
参照指令 gost -L=rtcp://:2222/192.168.1.1:22 [-F=... -F=socks5://172.24.10.1:1080]
步骤：
建立了远程端口映射，通过测试确认该连接可用。
发呆几个小时后，再次尝试连接远程端口，发现无法连接。
将远端(服务器 )上的gost重新启动
观察到，内网的运行的gost并没有检测到 远端服务器上的gost重启动操作，并尝试重新连接。
观察到，再不能通过远程端口连接到内网的主机

**Comment by ginuerzh** [comment]
通过socks5来做远程端口转发，默认仅建立一个原始TCP连接，心跳和超时由使用此连接的应用自己来控制。
可以开启multiplex模式，让gost来管理连接状态：
```
gost -L rtcp://:2222/192.168.1.1:22 -F socks5://172.24.10.1:1080?mbind=true
```
通过`mbind`参数来开启multiplex模式。

**Comment by f4nff** [comment]
即使如此，multiplex的心跳是建立在隧道建立成功之后，
如果第一个包发送成功，没有任何数据返回，是没有判断超时的。
这个我在#316里面有环境模拟。

**Comment by guijun** [comment]
如果确定无法自动连接，那么是否可以在连接idle一定的时间后，客户端强制重新建立连接？

**Comment by guijun** [comment]
实际上，我的测试中mbind也已经开启。

**Comment by ginuerzh** [comment]
开启mbind后客户端有什么异常log吗？

**Comment by guijun** [comment]
异常也是没有的。就是不重连....

**Comment by f4nff** [comment]
是#316问题，而且我还搭建了重现的环境，就是不信…

**Comment by ginuerzh** [comment]
目前代码正在全面优化，这种问题会在后面解决

**Comment by ginuerzh** [comment]
这个问题应该已经fixed了，请使用2.7版本。
