### ISSUE TITLE
Option "dns" causes domains in a "bypass" list not resolved remotely

### ISSUE THREAD

**Issue by bohrshaw** [ginuerzh/gost#331]
In commands below, the first behaves as expected, while the second does not. The domains in `/path/to/domains.txt` are not resolved remotely in the second command.

- `gost -L=":1080" -F="foo.com:8080/?bypass=~/path/to/domains.txt"`
- `gost -L=":1080?dns=172.16.1.1" -F="foo.com:8080/?bypass=~/path/to/domains.txt"`

**Comment by ginuerzh** [comment]
Some HTTP proxy may not support CONNECT method to a non-443 port, so in GOST HTTP proxy, if the last node in the proxy chain is also an HTTP proxy, all non CONNECT requests will be forwarded to the last proxy node by default. The forwarded requests can not use the DNS resolver.

In the next version, an option will be added to control the forward behavior manually. For now, you can use SOCKS5 mode to communicate with local proxy.

**Comment by bohrshaw** [comment]
Thanks for your suggestion. But the domain names are resolved locally whether using SOCKS5 or HTTP mode to communicate with local proxy.

**Comment by ginuerzh** [comment]
What is the GOST version do you use?

I have tested against the 2.6.1 version in SOCKS5 mode, and it works well.

Here is my local test case:

```
gost -L=:18080 -D
```

```
gost -L=:11080?dns=1.1.1.1 -F=:18080?bypass=~github.com -D
```

```
curl --socks5-hostname localhost:11080 http://github.com
```

The resolver log will appear on server :11080:
```
resolver.go:139: [resolver] github.com via 1.1.1.1:53/udp [192.30.255.112 192.30.255.113]
```

And the :18080 server will receive a CONNECT request:
```
CONNECT 192.30.255.112:80 HTTP/1.1
Host: 192.30.255.112:80
Proxy-Connection: keep-alive
User-Agent: Chrome/60.0.3112.90
```

**Comment by bohrshaw** [comment]
> The resolver log will appear on server :11080:
This means the domain is resolved locally. It should be resolved on server :18080 IMO.

**Comment by ginuerzh** [comment]
No, it is resolved by 1.1.1.1:53. If no DNS resolvers specified, it will be resolved on :18080

**Comment by bohrshaw** [comment]
- I suppose the DNS option is just telling *where* to resolve domain names.
- And the Bypass option should take precedence here.

What I intended in the first place is to resolve only bypassed name in the specified DNS server. Is there any way I can do this now?

**Comment by ginuerzh** [comment]
The DNS resolver is independent of bypass, for now you can not control the rules.

**Comment by ginuerzh** [comment]
Closed due to inactive.

**Comment by sergeevabc** [comment]
Dear @ginuerzh,

I have a HTTPS proxy, a remote DoH server and a list of domains (say, `domains.txt`) to be opened via that proxy. Right now I understand how to do the first part using GOST:

``` console
$ gost.exe -L socks5://:1080 -F https://username:password@a.b.c.d:443
```

It works well, but, of course, all requests are proxified.

But how do I proxy only domains from the list and resolve them via DoH?
