### ISSUE TITLE
gost Proxy 等字样明文发送，会被识别

### ISSUE THREAD

**Issue by wen-long** [ginuerzh/gost#333]
如题，使用 ws 等隧道类型时，每每有新连接时，服务器也会使用明文
```
HTTP/1.1 200 Connection established
Proxy-Agent: gost/2.6.1
```
回复，这段明文会可以被防火墙作为检测的依据，极大降低了传输流量特征的隐蔽性

**Comment by ginuerzh** [comment]
代理协议本身与正常的HTTP请求协议不同，即使不加这个Header也是很容易区分出来的，如果担心被识别，建议使用加密

**Comment by wen-long** [comment]
> 代理协议本身与正常的HTTP请求协议不同，即使不加这个Header也是很容易区分出来的，如果担心被识别，建议使用加密

打算在 mws 隧道内使用 shadowsocks，ss 是加密的，mws 是想对外隐藏连接数信息。但 mws 的代理响应头是明文的

**Comment by SeaHOH** [comment]
除非伪装成其它协议，否则还是能被识别。比如 https proxy 和 server 就没啥区别。
但是代理是很普通很正常的应用，如无特别需求没必要搞这些。

**Comment by wen-long** [comment]
并不是为了混淆
而是，何必光明正大的告诉途径设备我这是 gost 流量，而且还是 Proxy-Agent 呢？
再说http.go 里 DefaultUseragent 也是 Chrome，若按 @SeaHOH 所说，为何不用 gost + version 呢？

**Comment by SeaHOH** [comment]
不理解如何不混淆又隐蔽，你给个修改方案？

**Comment by wen-long** [comment]
请问这段是不是为了隐蔽？如果不是，为何不与第二段一样使用 gost+version?

https://github.com/ginuerzh/gost/blob/83906404ae5f21b3a893e770073355b1ce643480/gost.go#L52
https://github.com/ginuerzh/gost/blob/83906404ae5f21b3a893e770073355b1ce643480/http.go#L297

既然 DefaultUserAgent 是伪装 Chrome 那 ProxyAgent 又何必诚实的告诉别人是 gost 呢

**Comment by SeaHOH** [comment]
这其实是为了兼容性，因为有些服务器对未包含 Chrome 字样的 User-Agent 很不友好。
