### ISSUE TITLE
Asking for advice and some clarification.

### ISSUE THREAD

**Issue by aphypnise** [ginuerzh/gost#334]
Hello.

Thanks for your great program, which I'm using since quite of time. Nevertheless, I came to ask you some advice, because there are a lot of options and setup possible thanks to your program, but I cannot figure out what options I could choose, and I have the feeling that my setup is suboptimal.

To put it simply, I have a restrictive proxy between me and internet, which only accepts http/https (80 and 443) data, which must be forwarded to the proxy before-hand (8080) I have a dedicated server that have full internet access, and I logically want to have internet with decent speed with tcp and udp unrestricted.

I'm on linux, and for the moment I was using an iptables redirection, forwarded to the http proxy, and then forwarded to my dedicated server with shadowsocks, encrypted in aes. With this setup, I only have tcp. I don't even know if this optimal or suboptimal, there are so many options, and a lot of documentation around the web is in Chinese. 

So it would be nice if you could lend me a hand, wit some suggestions, it could be used after for some general recommendations for others, idk.

Thanks in advance !

**Comment by ginuerzh** [comment]
If your own server can be accessed by the restrictive proxy, then your TCP traffic should be able to forward to the server. You can try the command below on your local host (assume a shadowsocks server has been started in your dedicated  server on port 443):
```
gost  -L :1080 -F proxy-ip:8080 -F ss://server_ip:443
```

**Comment by aphypnise** [comment]
Yeah, that's nice but that's I was using before, but the main question for me was : 
Is there any other option using gost that would permit me to also use udp, without a huge performance loss ? 

Since there are so many options, I'm kinda lost if this is even possible.

Thanks.

**Comment by ginuerzh** [comment]
Due to your firewall restriction (only TCP allowed), UDP should be tunneled over TCP, and the performance will be dropped inevitably.
