### ISSUE TITLE
https 代理问题

### ISSUE THREAD

**Issue by caoyufei** [ginuerzh/gost#337]
服务器运行
`gost -L=:8080`

- 然后浏览器代理插件配置HttP 代理
- 所有的https 都访问不了, http又可以

- 是我的使用姿势不对？还是？

**Comment by ginuerzh** [comment]
有log吗？

**Comment by f4nff** [comment]
代理插件的问题，因为本地证书是gost自动生成的，系统本身不那啥，那个插件会验证证书，所以～
自己搞个域名证书就可以，跟程序没关系，自己使用问题，
gost本身默认就是忽略证书的，
