### ISSUE TITLE
2.7版并不能加载配置文件

### ISSUE THREAD

**Issue by fyhong** [ginuerzh/gost#342]
2.7版本-C 参数不能加载配置文件，2.6版正常加载。

[root@izj6c7edxmv7twnjqthh50z ~]# ./gost -C ./gost2.json 
  -C string
    	configure file
  -D	enable debug log
  -F value
    	forward address, can make a forward chain
  -L value
    	listen address, can listen on multiple ports
  -V	print version
  -obfs4-distBias
    	Enable obfs4 using ScrambleSuit style table generation

**Comment by ginuerzh** [comment]
我这边测试没问题，你的gost2.json内容是什么？

**Comment by fyhong** [comment]
但是同一个配置文件，用2.6加载一点问题都没有。
[root@izj6c7edxmv7twnjqthh50z ~]# ./gost -C ./gost2.json 
  -C string
    	configure file
  -D	enable debug log
  -F value
    	forward address, can make a forward chain
  -L value
    	listen address, can listen on multiple ports
  -V	print version
  -obfs4-distBias
    	Enable obfs4 using ScrambleSuit style table generation
[root@izj6c7edxmv7twnjqthh50z ~]# ./gost26 -C ./gost2.json 
^C

**Comment by ginuerzh** [comment]
要看一下配置文件内容才能确定是什么问题。

**Comment by fyhong** [comment]
我将网址用test.com代替了
{
    "Routes": [
	{ "ServeNodes": ["ss://chacha20:test@:19414"], "ChainNodes": ["ss://chacha20:test@test.com:8899"] },
	{ "ServeNodes": ["ss://chacha20:test@:8201"], "ChainNodes": ["kcp://test2.com:9002"] },
	{ "ServeNodes": ["ss://chacha20:test@:9096"] },
	{ "ServeNodes": ["tls://:443", "kcp://:9002"] },
	{ "ServeNodes": ["tcp://:9097/test23.com:8899"] },
	{ "ServeNodes": ["ss://rc4-md5:12075@:8198", "ssu://rc4-md5:12075@:8198"] },
	{ "ServeNodes": ["tcp://:8206/test33.com:8899"] },
	{ "ServeNodes": ["ss://chacha20:11261@:9826", "ssu://chacha20:11261@:9826"] }
    ]
}

**Comment by fyhong** [comment]
刚刚又测试了，不添加Routes,直接以下格式可以加载
{
"ServeNodes": [
"tcp://:9093/ip:port",
"tcp://:9929/ip2:port",
"tcp://:9930/ip3:port"
	]
}
