### ISSUE TITLE
一些强大的建议

### ISSUE THREAD

**Issue by hktalent** [ginuerzh/gost#343]
1、增加p2p 隧道出udp、tcp，socks5
2、增加p2p reverse socks5
3、增加在没有互联网的情况下，内网中自动发现其他节点的功能，可以使用p2p和DHT的特性
这样内网中，只要有其中一台能够上互联网，其他节点都可以自动路由到他上互联网，形成一个完美都“网”

也就是说，不需要VPS来当server
任何节点是server也是client
运行的时候生成一个p2p key,连接的时候指定就可以了

**Comment by f4nff** [comment]
看似很好的建议，其实意义不大，内网确实可以利用起来，但是p2p实在不敢恭维，
在全球udp传输会被特别的Qos，尤其精品线路，UDP基本残废，
比如阿里云这些，如果网络不好，连续发几个udp没有回包，直接屏蔽了。
内网如何利用可以看 #338 
使用优质服务器中转，才有意义。
p2p很复杂，更不要提什么dht，花了很多功夫去搞，然后效果不佳，没有太多实用意义。
