### ISSUE TITLE
Wiki文档建议：说明在使用 shadowsocks 协议时，如果配合 secrets.txt，只会用第一条的 method 和 password

### ISSUE THREAD

**Issue by everyx** [ginuerzh/gost#346]
原本我以为和 http/socks 协议一样，能在一个 ss 服务上使用多个（加密方式）用户名和密码，然后发现默认只会取第一条，可能注明一下会好一些，谢谢。

**Comment by everyx** [comment]
不知道能否实现单端口多用户，如果可以，文档就没问题了 😂

**Comment by ginuerzh** [comment]
shadowsocks协议是无协商的，所以无法针对多用户设置不通的认证信息。

**Comment by everyx** [comment]
> 
> 
> shadowsocks协议是无协商的，所以无法针对多用户设置不通的认证信息。

嗯嗯，当时想到这个问题，也搜索了一下，的确是不行
