### ISSUE TITLE
负载均衡模式 fifo 某种情况下失效

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#347]
```
{
    "Debug": false,
    "Retries": 3,
    "Routes": [
        {
            "Retries": 3,
            "ServeNodes": [
	":1080"
            ],
            "ChainNodes": [
		"mwss://11.ww.com:443?peer=peer.json"
            ]
        }
    ]
}
```
peer.json  如下
```
{
    "strategy": "round",
    "max_fails": 1,
    "fail_timeout": 30,
    "nodes":[
	"mwss://11.ww.com:443?ip=29.17.34.1",
	"mwss://1.R22233.net:443?ip=19.247.134.2",
	"mwss://1.2W2233.net:443?ip=23.222.34.1"
	]
}
```

peer.json 

**strategy - 指定节点选择策略，round - 轮询，random - 随机, fifo - 自上而下。默认值为round。**

当
```
	"mwss://11.ww.com:443?ip=29.17.34.1",
	"mwss://1.R22233.net:443?ip=19.247.134.2",
```
全部失效的时候，使用 round - 轮询，random - 随机 都可以自动切换到 最后一个 节点 
`	"mwss://1.2W2233.net:443?ip=23.222.34.1"`

但是，使用 fifo - 自上而下 模式的时候，前两个节点失效，就无法切换到 
`	"mwss://1.2W2233.net:443?ip=23.222.34.1"`

记得之前的版本没这样的问题，

**Comment by ginuerzh** [comment]
`peer`参数在2.7中改成新的格式了：
https://github.com/ginuerzh/gost/blob/master/.config/peer.txt
以前的json格式也可以兼容，不过要把`fail_timeout`去掉。

**Comment by f4nff** [comment]
ok
