### ISSUE TITLE
请教大神 如何均衡两条代理链

### ISSUE THREAD

**Issue by jfc8000** [ginuerzh/gost#351]
我有两条代理链 分别是
A链路 gost -L=:8080 -F=http://1.1.1.1:8080 -F=socks5://2.2.2.2:1080
B链路 gost -L=:8081 -F=http://3.3.3.3:8080 -F=socks5://4.4.4.4:1080
我想均衡这两条链路流量

我现在用的笨办法 需要开3个gost进程 两个分别开启链路 再1个用来均衡

请问大神 如何用1个脚本 只用1个gost进程实现均衡？

**Comment by ginuerzh** [comment]
试试这个：
gost -L=:8080 -F=http://:8080?ip=1.1.1.1,3.3.3.3 -F=socks5://:1080?ip=2.2.2.2,4.4.4.4

**Comment by jfc8000** [comment]
#2
大侠 这样会形成4条代理链 有两条不通的 1.1.1.1-4.4.4.4 3.3.3.3-2.2.2.2

**Comment by jfc8000** [comment]
如果节点配置文件支持这种写法就好了
{
    "strategy": "random",
    "max_fails": 1,
    "fail_timeout": 30,
    "nodes": [
        "http://1.1.1.1:8080 -F=socks5://2.2.2.2:1080",
        "http://3.3.3.3:8080 -F=socks5://4.4.4.4:1080"
    ]
}

**Comment by f4nff** [comment]
@jfc8000   good～

**Comment by f4nff** [comment]
```
{
"strategy": "random",
"max_fails": 1,
"fail_timeout": 30,
"nodes": [
"http://1.1.1.1:8080 -F=socks5://2.2.2.2:1080",
"http://3.3.3.3:8080 -F=socks5://4.4.4.4:1080"
]
}
```

这个判断代理链通还是只判断http通不通，需要注意下，
必须判断代理链

**Comment by ginuerzh** [comment]
v3版本中可以通过转发链组来实现，单个服务中可以使用多条转发链，并支持负载均衡。
https://gost.run/concepts/chain/#_4
