### ISSUE TITLE
bad version error

### ISSUE THREAD

**Issue by e2ge** [ginuerzh/gost#353]
Hello, 打算利用gost的quic协议做ss的wrap，配置如下。

sslocal指向local gost的L：socks5+tcp://1080
local gost F利用quic指向remote server的gost L：quic://server ip:port
remote gost F指向remote ssserver：socks5+tcp://127.0.0.1:1081

感觉没什么问题，但是log显示如下：
2019/01/24 11:53:03 socks.go:801: [socks5] 127.0.0.1:4616 -> 127.0.0.1:1080: Bad version
2019/01/24 11:53:03 socks.go:801: [socks5] 127.0.0.1:4618 -> 127.0.0.1:1080: Bad version

server gost没什么log提示。

希望指点，谢谢。

**Comment by e2ge** [comment]
感觉问题是，ss出来的连接是单纯的tcp，不是socks5+tcp，但是gost貌似不能单纯的指定tcp，会有一个默认的http+socks协议。

**Comment by ginuerzh** [comment]
ss-local和ss-server之间是走shadowsocks协议，所以gost也要用shadowsocks协议，整个流程应该是：

ss-local ---(ss)---> gost-ss ---(quic)---> gost-quic ---(ss)---> ss-server

**Comment by e2ge** [comment]
我大概理解你的意思了，相当于ss-local和本地-L的gost-ss通信，然后通过quic连到服务器。
但是如果在本地-L一个gost-ss的话，虽然quic有tls，那样quic传送的包就没有ss混淆加密了吧？这样在本地实现一个ss-local到gost-ss貌似就没有什么意义了，还不如直接gost -L一个socks5。
不知道我的理解是否正确？

**Comment by e2ge** [comment]
我的想法是：
明文---ss-local---(tcp加密包)---gost(?)---quic---gost(?)---(tcp加密包)---ss-server---明文

。。。
我觉得gost貌似已经有这个功能了。。。
本地：-L socks5://1080 -F ss+quic://....
远程：-L ss+quic://....

但是在教程里没看到ss+quic的配置，不知道是否已经实现？只看到ss+kcp和ss+tls

**Comment by e2ge** [comment]
试了一下ss+quic，配置上没什么问题，但是因为gost用的是shadowsocks-go这个库，这个原来的作者貌似弃了，新换了一个作者更新的也不及时，虽然把ota去了，但是貌似并没有实现AEAD加密，gost也不支持AEAD。
换成这个库会更好一些，之前有issue谈过这个问题。
https://github.com/shadowsocks/go-shadowsocks2

**Comment by ginuerzh** [comment]
既然已经使用quic了，上层用什么协议已经没有多大区别了

**Comment by e2ge** [comment]
我的看法是，单纯的quic是单侧tls的，然后端口也是暴露的，那么如果里面没有账户认证的话，任何一个人都可以用quic进行连接的，所以里面用ss做认证可以增加服务器的安全。

**Comment by f4nff** [comment]
本来就是很小众的东西，谁知道你的ip 端口，杞人忧天，

**Comment by e2ge** [comment]
@f4nff 端口是不管你用了什么程序的，gost和ss都是一样的，随便扫一下就出来了。

**Comment by f4nff** [comment]
来来来，你来扫一下，
ss是tcp协议，普通的扫描只能扫描端口有没有开放，如果需要确定ss服务，需要dpi，门槛很高的，
再说一下quic，本身就是udp，udp扫描大多都没用，udp跟tcp不一样，
然后你需要确定quic服务，你需要dpi，本来就是小众，除非你自己写，目前没见过类似的扫描，

**Comment by e2ge** [comment]
@f4nff 我理解你说的理由，但是就像你说的，你也无法保证扫描不出来。
打个不恰当的比喻，虽然sha1已经被google暴力破解出来了，你也可以说实际应用上破解率极低，但是现在业界也还是摒弃了sha1，改成了sha256。况且我认为扫描udp端口和破解sha1比起来简单多了，就算因为协议原因udp端口扫描只能知道端口打开与否，但是如果有人只要一扫描出来就尝试quic连接怎么办，专门针对quic，我觉得也不是没有这个可能，不需要确定你是否是gost-quic还是其他的quic。

**Comment by f4nff** [comment]
不语，

**Comment by SeaHOH** [comment]
不要使用常用端口就没事，有好些网站专门 IPv4 全网扫主机服务。。。

**Comment by ginuerzh** [comment]
下个版本会增加对新ss库的支持: #82
