### ISSUE TITLE
log channels separation

### ISSUE THREAD

**Issue by mhf-ir** [ginuerzh/gost#354]
I need to know is there any way to separate log channel for these use cases:

* Invalid auth for add fail2ban action ban :sos: 
* output log format per channel

```json
{
   "logs": {
     "_default": {
         "format": "json",
         "path": "to/json/log"
     },
     "auth" : {
          "format": "syslog",
          "path": "to/gost/auth.log"
     },
   }
}
```
Log keys could be log facility on syslog [RFC 3164](https://tools.ietf.org/html/rfc3164#section-4.1.1)
Format is useful for using log collector like fluentd, fluentbit or logstash etc ...

**Comment by ginuerzh** [comment]
No, the log is not divided according to the functions, and there is no plan for this.
