### ISSUE TITLE
似乎各个节点的server_domain_name没有办法指定dns解析方式

### ISSUE THREAD

**Issue by wa3y** [ginuerzh/gost#359]
版本：gost 2.7.2

分别在三个shell中执行：
```../gost.exe -L=:23333 -D```
```../gost.exe -L=:10809?dns=127.0.0.1:23333/tls -F=socks5://www.google.com:80 -D```
```curl 1.1.1.1 --proxy socks5h://127.0.0.1:10809```

可以发现第一个shell中没有出现任何提示信息，说明此处对于www.google.com的解析没有经过```127.0.0.1:23333/tls```

这会造成一些困扰，比如似乎安卓设备上用一些终端模拟的软件没有办法直接使用```./gost -L=:1080 -F=ss://[something]:[something]@server_domain_name:port```
会产生错误```[socks5] 127.0.0.1:45405 -> 127.0.0.1:1080 : dial tcp: lookup www.google.com on [::1]:53: read udp [::1]:48812->[::1]:53: read: connection refused```

能否考虑解决一下这个问题？

**Comment by ginuerzh** [comment]
目前的dns解析只是针对发出的请求目标地址，暂时不考虑对节点本身的解析。

**Comment by fanthos** [comment]
参考
`https://github.com/fatedier/frp/commit/00b9ba95aeef38135a48fe42917d9aa2fac4f879`
修改dns解析器
