### ISSUE TITLE
io.Copy 占用cpu非常大，

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#360]
100Mbps cpu 占用都到7-9%了，i7 四代U。

这很不正常，

网上搜索了下，

https://golangtc.com/t/55160aaa421aa9704b000015

**Comment by f4nff** [comment]
测试模式 mws/mwss～5并发下载跑满100Mbps！～

**Comment by ginuerzh** [comment]
对于长连接的协议只能使用io.Copy
