### ISSUE TITLE
udp走ss是不可能的吗？

### ISSUE THREAD

**Issue by shownb** [ginuerzh/gost#361]
服务端和客户端都是 2.7.2
以下没有问题 
服务端
> gost -L=:443

客户端
> gost -L udp://:500/[服务器ip]:500 -L udp://:4500/[服务器ip]:4500 -L udp://:1701/[服务器ip]:1701 -F [服务器ip]:443

如果换了ss协议，就出现2019/02/08 06:10:12 forward.go:208: [udp] [::]:500 - 服务器ip:500 : read tcp 192.168.1.123:54844->服务器ip:443: i/o timeout

猜测是ss不支持udp ？

**Comment by ginuerzh** [comment]
UDP端口转发是传输层原始数据的转发，与具体的协议无关。你的[服务器ip]:500 跑的是ss udp服务吗？

**Comment by shownb** [comment]
> UDP端口转发是传输层原始数据的转发，与具体的协议无关。你的[服务器ip]:500 跑的是ss udp服务吗？

vpn的500 4500 1701

**Comment by ginuerzh** [comment]
500是vpn服务，接收的也是vpn协议数据
