### ISSUE TITLE
第一次发起连接会失败

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#364]
`gost -L=:1089 -F=?peer=peer.json`

peer.json
```
# strategy for node selecting
strategy        round

max_fails       2

fail_timeout    30s

# period for live reloading
reload          10s

# peers
peer    mwss://ra.elyzc.net:443?ip=80.63.188.5
peer    mwss://ra.qdlyzc.net:443?ip=80.63.188.6
```

第一次发起连接，会提示 
`dial tcp: missing address`

![image](https://user-images.githubusercontent.com/19538878/52920054-7fb67480-3343-11e9-8e36-791977bda8ae.png)

第二次就正常。

**Comment by ginuerzh** [comment]
-F必须指定一个地址

**Comment by f4nff** [comment]
地址都在peer.json里面，如果固定一个地址，那么这个地址失效呢？
都丢peer.json里面，这样peer.json支持热更新，即使第一个失败了，
还可以更新。如果固定，失败了，必须关闭程序。

**Comment by ginuerzh** [comment]
后面会兼容你说的这种情况

**Comment by f4nff** [comment]
这个问题还是没纠正,如果固定连接里面不写入一个peer,第一次发起请求会失败.
提示 

> dial tcp: missing address

**Comment by f4nff** [comment]
> gost -L=:1089 -F=?peer=peer.json

> # strategy for node selecting
> strategy        round
> 
> max_fails       1
> 
> fail_timeout    30s
> 
> # period for live reloading
> reload          10s
> 
> # peers
> peer    mwss://ra.elyzc.net:443?ip=80.63.188.5
> peer    mwss://ra.qdlyzc.net:443?ip=80.63.188.6

**Comment by f4nff** [comment]
ok
