### ISSUE TITLE
请问能不能详细解释一下端口转发功能？

### ISSUE THREAD

**Issue by fyhong** [ginuerzh/gost#370]
我看了gost的文档说明
TCP远程端口转发
将目标TCP端口B映射到本地TCP端口A，所有到端口B上的数据会被转发到端口A。此功能类似于SSH的远程端口转发功能。

gost -L=rtcp://:2222/192.168.1.1:22 [-F=... -F=socks5://172.24.10.1:1080]
将172.24.10.1:2222上的数据(通过代理链)转发到192.168.1.1:22上。

我现在的环境如下:
服务器:
gost -L kcp://:9999
客户端
gost -L rtcp://:8080/:80 -F kcp://server_ip:9999

然后我访问server_ip:8080, 根本就连不上本地的80端口啊，我再到服务器上面netstat -na | grep 8080
发现服务器根本没有开启8080端口

**Comment by fyhong** [comment]
gost -L rtcp://:8080/:80 -F kcp://server_ip:9999
按照文档的说明我应该理解为
将server_ip:8080上的数据(通过代理链)转发到127.0.0.1:80上。

**Comment by ginuerzh** [comment]
客户端改为：
`gost -L rtcp://:8080/:80 -F socks5+kcp://server_ip:9999?mbind=true`
远程端口转发是利用SOCKS5 BIND协议的扩展来实现的，所以最后一个代理节点是SOCKS5类型才可以。
后面会在文档中添加说明。

**Comment by fyhong** [comment]
按照上面的改了还是不可以。
服务器端仍然没有开放8080端口

[d:\~]$ ssh server_ip 8080


Connecting toserver_ip:8080...
Could not connect to 'server_ip' (port 8080): Connection failed.

Type `help' to learn how to use Xshell prompt.

**Comment by ginuerzh** [comment]
有log吗？

**Comment by fyhong** [comment]
这个问题我已经解决了，是版本问题
