### ISSUE TITLE
如何搭建在路由器上面，使得全局强制通过gost转发出去，tcp+udp

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#371]
有很多ss脚本，可以在路由器里面运行，
但是ss只能转发tcp流量，
gost可以tcp+udp，（fps游戏加速）
有没有大神搞个脚本，
使用gost 代理所有ip走隧道出去（加个例外名单更好）

**Comment by f4nff** [comment]
[https://github.com/izerosoul/shadowsocks_erx](https://github.com/izerosoul/shadowsocks_erx)
这有个ss路由器脚本，走的是dns over tcp
gost没这么麻烦，直接udp://:53/1.1.1.1:53
就好了，
有没用大神拿这个改一下，可以转发udp的，默认采用mws协议，

**Comment by recall704** [comment]
https://docs.ginuerzh.xyz/gost/redirect/

**Comment by f4nff** [comment]
@recall704   目前只支持tcp

**Comment by recall704** [comment]
@f4nff 

```bash
ip route flush table 100
ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N GOST
iptables -t mangle -I GOST 1 -m set --match-set proxy-server dst -j RETURN
iptables -t mangle -I GOST 2 -m set --match-set black-list dst -j RETURN
iptables -t mangle -I GOST 3 -p tcp  -m set --match-set cnproxy dst -j RETURN
iptables -t mangle -A GOST -p udp -j TPROXY --on-port 8443 --tproxy-mark 0x01/0x01

iptables -t mangle -A PREROUTING -j GOST
```

我也不知道有没有效

**Comment by ginuerzh** [comment]
2.10已经支持udp透明代理

**Comment by aogg** [comment]
> ```shell
> GOST
> ```



> https://docs.ginuerzh.xyz/gost/redirect/

这个不是PREROUTING，好像不能直接接收iptables的DNAT

@ginuerzh @recall704
