### ISSUE TITLE
请教一下gost的kcp能不能作为kcptun服务器？

### ISSUE THREAD

**Issue by fyhong** [ginuerzh/gost#372]
因现梅林路由上面只有kcptun.
请问这个能不能对接gost建出来的kcp server,如果能的话需要怎样做？谢谢

**Comment by ginuerzh** [comment]
gost与kcptun使用的是相同的库，二者是可以互相兼容的，只要保证两端的参数一致。

**Comment by fyhong** [comment]
但是kcptun是有一个target参数的。gost怎样设置这个参数？

**Comment by ginuerzh** [comment]
kcp是传输层，本身只负责转发数据，所以kcptun中要使用target指定数据最终的去处。gost中传输层和协议层可以共存。
例如，你要转发ss协议：`gost -L ss+kcp://chacha20:123456@:8388`
这样gost本身即是一个kcp server又是一个ss server。

当然也可以使用转发模式：`gost -L kcp://:8388/ss-server:8338`
这种方式就与kcptun基本一样了，8388是kcp server, ss-server:8338是要转发到的ss server，即kcptun中的target。

**Comment by fyhong** [comment]
已解决，谢谢
