### ISSUE TITLE
请教http+tls代理证书问题

### ISSUE THREAD

**Issue by jarwin123** [ginuerzh/gost#373]
你好，为什么用gost的http+tls代理，浏览器验证证书会通过呢？一般https代理浏览器都会提示证书错误警告的，我用过mitmproxy，他的证书需要在浏览器添加可信任。我想知道gost是怎么做的？谢谢！

**Comment by ginuerzh** [comment]
没有遇到过这种情况，应该是你的浏览器设置问题。

**Comment by jarwin123** [comment]
不是这个意思，我是想问技术问题，gost没有让浏览器产生warning，为什么别的代理是需要设置浏览器，而gost不需要设置

**Comment by jarwin123** [comment]
client ————》gost-----》real_server
gost做为代理，也会有自己的证书，客户端https连接的时候，gost会把自己的证书发给客户端，但是这个证书不是real_server的证书，客户端的浏览器应该会出现证书不可信的，gost的证书的CA浏览器默认是可信任的？

**Comment by ginuerzh** [comment]
gost自动生成的证书与其他方式生成的自签名证书没有什么区别，所以你遇到的这种情况应该与gost无关。至少我测试下来，没有出现你说的这种情况。

**Comment by f4nff** [comment]
@ginuerzh  他想表达的意思是提供  `gost -L=https://:443  `
![image](https://user-images.githubusercontent.com/19538878/54800839-f88c5180-4c9e-11e9-8a79-8d92922cdeb9.png)
然后使用代理插件，选择https，连接gost提供的https代理，

这时候代理插件会默认验证证书，因为gost默认是自己生成，所以不被插件认同，

他想解决这个问题很简单，自己搞个域名去申请个免费证书就是了，

比如申请了一个三个月的证书，
域名是 
44.bb.com

把证书丢到服务端，然后执行
`gost -L=https://:443  `

这时候gost会加载申请到的证书，
然后把44.bb.com 指向gost

然后在代理插件里面写
44.bb.com ：443

就好了，

这不是gost的问题，是代理插件默认验证证书，

**Comment by f4nff** [comment]
> 你好，为什么用gost的http+tls代理，浏览器验证证书会通过呢？一般https代理浏览器都会提示证书错误

> 警告的，我用过mitmproxy，他的证书需要在浏览器添加可信任。我想知道gost是怎么做的？谢谢！


mitmproxy 还有 goagent ，那类是http转发，所以需要本地载入一个自签发的根证书，
http转发就是client--server之间传输是http请求包，是短连接的轮询。

gost 是tcp转发，
