### ISSUE TITLE
希望添加输入log到文件功能！

### ISSUE THREAD

**Issue by flynaj** [ginuerzh/gost#375]
gost 作为服务长长期稳定使用,其实可以需要日志，可以考虑添加 quiet 参数不输出日志。
或者添加 log 参数把日志存入文件。

**Comment by f4nff** [comment]
可以考虑添加 quiet 参数不输出日志

**Comment by ginuerzh** [comment]
可以使用重定向

**Comment by f4nff** [comment]
nohup ./gost -C 1.json >/dev/null 2>&1 &
