### ISSUE TITLE
local http > socks forwarding

### ISSUE THREAD

**Issue by krem** [ginuerzh/gost#378]
I need http to socks5 forwarding.
Pointing browser to socks5 127.0.0.1:1080 works ok.
I do
gost -L:8080 -F:127.0.0.1:1080
Testing by browser with proxy settings: 127.0.0.1:8080
I get - "The connection was reset" (page does not load) on the http:// urls, and bypassing proxy by browser for https:// urls
Version is 
gost 2.7.2 (go1.11.5 linux/amd64)

**Comment by f4nff** [comment]
`gost -L=:8080 -F=socks5://127.0.0.1:1080`

**Comment by krem** [comment]
thank you!
