### ISSUE TITLE
2.0 rc3 出现错误：tls.go:60] open cert.pem: no such file or directory

### ISSUE THREAD

**Issue by tsenzhi** [ginuerzh/gost#38]
要自己在本地和远端gost目录下都放置cert.pem和key.pem吗

**Comment by ginuerzh** [comment]
2.0优先考虑用户自己的证书(会先尝试加载cert.pem, key.pem文件)，如果失败，则使用内置的证书(2.0版内部有一个默认的证书)。

一般情况下，上面的错误信息可以忽略，如果需要更高的安全性，可以生成自己的证书，当没有以上错误出现时，表明自己的证书加载成功。

**Comment by tsenzhi** [comment]
平时都能正常使用，今天突然不能使用了，查看日志出现上述情况后，日志就不再产生，停在 tls.go:60] open cert.pem: no such file or directory 处。

自己通过openssl genrsa -out key.pem 2048 产生cert.pem，key.pem，但出现错误：tls.go:60] crypto/tls: failed to parse certificate PEM data，是不是这样产生的证书解析有问题。

**Comment by ginuerzh** [comment]
把日志级别调高(-v=4)，如果没有任何日志输出，则应该是网络不通。

**Comment by tsenzhi** [comment]
今天正常了，设置都同以前一样，一直都是把日志级别调高(-v=4)，昨天只输出上述信息，可能是网络不通，谢谢了
