### ISSUE TITLE
奇怪的过大内存占用问题

### ISSUE THREAD

**Issue by wa3y** [ginuerzh/gost#380]
在用http协议监听的时候，向监听的端口发送非常长的全是\x00的数据，会导致极大的内存占用（并且数据发送完后并不能恢复到原有水平）

大概，写150M数据会占300M内存，写300M数据会占600M内存

具体复现方式：执行```./gost -L=:9050```，再执行```dd if=/dev/zero bs=150M count=1 >/dev/tcp/127.0.0.1/9050```，可以发现gost占用极大内存

另一种类似的占用极大内存方式：
执行```./gost -L=:9050 -F=http://127.0.0.1:10001```，执行```dd if=/dev/zero bs=150M count=1 | nc -lnvp 10001```，再执行```curl 1.1.1.1 --proxy socks5h://127.0.0.1:9050```，可以发现gost也会占用极大内存

**Comment by ginuerzh** [comment]
Go的内存管理机制会缓存部分分配的内存，以便重复利用。
