### ISSUE TITLE
quic 模式有bug~

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#382]
触发方法,

```
gost -L=quic://:9823

gost -L=:1082 -F=quic://www.baidu.com:9823
```

然后找个高清一些视频,然后一直来回拖动进度条,
然后~
然后就凉凉了,不通了,
需要好一会才能恢复传输,

同样是udp传输协议的kcp却没这样的问题.

**Comment by ginuerzh** [comment]
本地测试也会有问题吗

**Comment by f4nff** [comment]
对,也有问题,这个问题在kcptun里面也出现过,不过kcptun 已经纠正了,
目前测试quic也存在这个问题.

**Comment by ginuerzh** [comment]
quic默认不会通过心跳保持连接，30秒内无数据传输就会断开。
可以手动开启心跳试试：
```
gost -L=:1082 -F=quic://:9823?keepalive=true
```

**Comment by f4nff** [comment]
更新一下库撒,
当时kcptun 出现这样的问题

`https://github.com/xtaci/smux/issues/48`
