### ISSUE TITLE
DNS進階問題DOH通過前置代理

### ISSUE THREAD

**Issue by iimhs** [ginuerzh/gost#383]
請問gost作者，由於doh使用tcp連接，目前gost只能使用本地直接連接doh=1.0.0.1，技術上能否實現，doh通過代理連接？如下所示：doh能否經過前置代理9090連接？以避免ISP監測破解或者防止DNS的ssl污染。

D:\gost\gost.exe -L=socks5://:55555?dns=1.0.0.1/https -F=socks5://127.0.0.1:9090

**Comment by ginuerzh** [comment]
可以通过端口转发配合实现：
gost -L socks5://:55555?dns=127.0.0.1:1053/tcp -L=tcp://:1053/1.0.0.1:53 -F=socks5://127.0.0.1:9090

**Comment by ginuerzh** [comment]
2.10已经支持代理链
