### ISSUE TITLE
可否编译IOS版本

### ISSUE THREAD

**Issue by TheWanderingCoel** [ginuerzh/gost#387]
如题,个人想在ios中使用gost项目,不知可否实现。先谢谢各位大佬了

**Comment by xuiv** [comment]
换v2ray，速度更好，比gost穿透能力强一点。

**Comment by TheWanderingCoel** [comment]
> 换v2ray，速度更好，比gost穿透能力强一点。

是的,v2ray穿透强,但是不知道怎么编译成framework.Gost可以用``gomobile bind -target=ios``

**Comment by TheWanderingCoel** [comment]
> gomobile是什么？没用过ios，android上有v2rayNG和BifrostV，这俩都要手动设置参数，导入json文件不能正常工作，不知有没ios版。
> 你有没有申请过阿里云的免费vps啊，我需要一个备案服务号，我想用国内的CDN加速

Gomobile是go的移动端的编译工具,可以编译成framework供swift和objc使用。  
至于CDN，我一直用的Cloudflare,备案太麻烦了

**Comment by TheWanderingCoel** [comment]
> https://ssr.tools/295
> ios也是有v2ray客户端的，只是中国区被下架了。

嗯,这个知道,自己在尝试做一个ios的
