### ISSUE TITLE
转发代理认证访问http网站问题

### ISSUE THREAD

**Issue by juan8510** [ginuerzh/gost#388]
gost -L :8100   -F=http://user:name@fr251.nordvpn.com:80

https网站正常访问
访问 http://httpbin.org/ 会出现代理未验证
同个代理在谷歌浏览器代理插件里面使用完全没有问题
已近反复试验,确实是gost的问题
别的代理软件可以正常使用

**Comment by ginuerzh** [comment]
我用最新版测试过，没有遇到这个问题。
可否提供客户端和服务端的Log?

**Comment by juan8510** [comment]
gost搭建的验证代理使用正常.
使用Squid或是Polipo 的验证代理,用gost转发,浏览器chrome和IE都测试过,都会出问题.
第一个http请求正常,网页里面css文件的请求就会要密码了.
