### ISSUE TITLE
gost.exe打不开，运行闪退

### ISSUE THREAD

**Issue by caorizabiaozima** [ginuerzh/gost#39]
求助啊大神，系统是win10，双击gost.exe就发生闪退

**Comment by ginuerzh** [comment]
这是个命令行程序，双击执行无效，需要在终端命令行中执行

**Comment by caorizabiaozima** [comment]
能不能做一个视频演示一下，因为本人小白，命令行那里看不懂

**Comment by helloyan** [comment]
新建run.bat，与gost.exe同目录
填写以下内容 

`gost -L=:**localport** -F=socks+tls://remoteip:port
pause
`
