### ISSUE TITLE
通过 ssh 转发 -F=ssh 与 -F=forward+ssh 用法区别

### ISSUE THREAD

**Issue by m2acgi** [ginuerzh/gost#391]
能否解释下用法 `gost -L=tcp://127.0.0.1:1080/x.x.x.x:8080 -F=forward+ssh://username:password@vps:7123` 与 `gost -L=tcp://127.0.0.1:1080/x.x.x.x:8080 -F=ssh://username:password@vps:7123`  的区别？什么情况下用 `-F=ssh`, 什么情况下用 `-F=forward+ssh` ?

谢谢。

**Comment by f4nff** [comment]
ssh 支持udp转发,是在ssh标准的协议上的扩充
forward+ssh 是标准的ssh协议,不支持udp,
