### ISSUE TITLE
udp端口转发rdp协议报错

### ISSUE THREAD

**Issue by vjeson** [ginuerzh/gost#394]
最新代码，部署在centos7上面，开启tcp和udp转发，会报加密错误
测试命令
./gost -L=tcp://:16001/172.19.1.225:3389 -L=udp://:16001/172.19.1.225:3389

用mstsc连接 ip：16001 会报数据加密错误
如果只开启tcp不会报错

而且在windows下面同样的转发不报错

**Comment by vjeson** [comment]
补充一下，采用别的golang 写的udp转发则没有这个问题

**Comment by f4nff** [comment]
![image](https://user-images.githubusercontent.com/19538878/57789561-c57cb080-776b-11e9-9854-a633e0f0069e.png)
我测试了下,也是如此.

**Comment by f4nff** [comment]
`gost -L=tcp://:33/106.14.164.12:3389 -L=udp://:33/106.14.164.12:3389`

这样会出错

`gost -L=tcp://:33/106.14.164.127:3389 -L=udp://:33/106.14.164.127:3389 -F=mwss://baidu.com:443`

反而正常.

**Comment by vjeson** [comment]
> `gost -L=tcp://:33/106.14.164.12:3389 -L=udp://:33/106.14.164.12:3389`
> 
> 这样会出错
> 
> `gost -L=tcp://:33/106.14.164.127:3389 -L=udp://:33/106.14.164.127:3389 -F=mwss://baidu.com:443`
> 
> 反而正常.

这个区别在哪里？ 后面加了-F=mwss://baidu.com:443 啥意思

**Comment by f4nff** [comment]
这个是bug

**Comment by vjeson** [comment]
什么时候可以修复？https://github.com/docker/go-connections这里的udp转发没有这个问题

**Comment by vjeson** [comment]
这个问题能修复么？别的udp转发也可能有问题

**Comment by ginuerzh** [comment]
gost日志有报错吗，或者把，ttl调大一些试试：
-L=udp://:33/106.14.164.12:3389?ttl=300

**Comment by ginuerzh** [comment]
可以用v2.8.2试试。
