### ISSUE TITLE
2.7.2版本不能转发多地址

### ISSUE THREAD

**Issue by fyhong** [ginuerzh/gost#395]
用2.61运行以下命令正常
./gost -L tcp://:40104/24.6.173.182:8899,24.8.50.100:8899

用2.7.2运行会报错
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x8b7266]

goroutine 12 [running]:
github.com/ginuerzh/gost.(*failMarker).Clone(0x0, 0x0)
        /Users/zhengrui/src/code/gost/selector.go:214 +0x36
github.com/ginuerzh/gost.(*FailFilter).Filter(0xc00002ae70, 0xc000003b00, 0x2, 0x2, 0xc00002c920, 0xf, 0x0)
        /Users/zhengrui/src/code/gost/selector.go:177 +0xd5
github.com/ginuerzh/gost.(*defaultSelector).Select(0xee0700, 0xc000003b00, 0x2, 0x2, 0xc000051d70, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
        /Users/zhengrui/src/code/gost/selector.go:31 +0x145
github.com/ginuerzh/gost.(*NodeGroup).Next(0xc0000ec2a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/zhengrui/src/code/gost/node.go:244 +0x149
github.com/ginuerzh/gost.(*tcpDirectForwardHandler).Handle(0xc000170ec0, 0xac9220, 0xc000122018)
        /Users/zhengrui/src/code/gost/forward.go:97 +0x19f
created by github.com/ginuerzh/gost.(*Server).Serve
        /Users/zhengrui/src/code/gost/server.go:92 +0x2b4

**Comment by chenhw2** [comment]
same as https://github.com/ginuerzh/gost/issues/279#issuecomment-455974588
fixed at https://github.com/ginuerzh/gost/pull/350
