### ISSUE TITLE
udp转发代理是否可以不设置目的ip和端口，通过在udp报文头部加入目的ip和端口

### ISSUE THREAD

**Issue by HuismanKwl** [ginuerzh/gost#397]

**Comment by HuismanKwl** [comment]
因为代理udp报文的时候，要根据客户端实际发出的报文转发到特定的服务器，所以把要访问的ip和端口加载udp数据报文的头部，代理服务器处理的时候，根据头部解析出来的ip和端口发送数据

**Comment by ginuerzh** [comment]
端口转发不关心实际转发的数据是什么，你需要的是类似于SOCKS5的UDP relay功能。

**Comment by HuismanKwl** [comment]
我想要对接udpspeeder
