### ISSUE TITLE
二级代理xshell会掉线问题

### ISSUE THREAD

**Issue by juan8510** [ginuerzh/gost#399]
配置1
gost -L :8080?dns=8.8.8.8,1.1.1.1:53/tcp  -F=socks5://user:password@ip:1080
xshell使用socks5或http代理都会掉线

配置2
gost -L :8080?dns=8.8.8.8,1.1.1.1:53/tcp  -F=http://user:password@ip:8080
xshell正常使用,很稳定

同一个服务器,已经多次反复试验,都会掉线.

**Comment by ginuerzh** [comment]
有什么错误提醒或日志吗？

**Comment by juan8510** [comment]
2019/05/26 04:18:23 route.go:464: auto://:8100 on [::]:8100
2019/05/26 04:18:26 socks.go:835: [socks5] 127.0.0.1:10106 -> auto://:8100 -> 107.174.61.12:22
2019/05/26 04:18:26 socks.go:887: [route] 127.0.0.1:10106 -> auto://:8100 -> 1@socks5://us967.nordvpn.com:1080 -> 107.174.61.12:22
2019/05/26 04:18:27 socks.go:922: [socks5] 127.0.0.1:10106 <-> 107.174.61.12:22
2019/05/26 04:18:41 socks.go:924: [socks5] 127.0.0.1:10106 >-< 107.174.61.12:22

xshell 
Connection closing...Socket close.

**Comment by ginuerzh** [comment]
无法复现，请确保二级socks5代理没有问题。
