### ISSUE TITLE
Gost at present doesn't support IPv6 right?

### ISSUE THREAD

**Issue by ljm625** [ginuerzh/gost#4]
I've tested it with an ipv6 address and it replied that there is to many colons. I want to make sure that whether is gost not supporting ipv6 or my command or server has issues,thanks.

**Comment by ginuerzh** [comment]
For now, ipv6 has not been tested yet.

**Comment by sobasin** [comment]
Tried these today, all works for IPv6 websites. 
1. SwitchyOmega(no IPv6)--> gost(https; no IPv6)--> cow(no IPv6)--> ss(with IPv6)
2. ss(no IPv6)--> gost(ss; no IPv6)--> ss(with IPv6) 
So if you were meaning this, then IPv6 works.
