### ISSUE TITLE
支持 jumper 参数吗？

### ISSUE THREAD

**Issue by pinghe** [ginuerzh/gost#402]
客户端和转发服务器之间，要通过http/https/socks代理，应该如何配置？

**Comment by ginuerzh** [comment]
请参考 https://docs.ginuerzh.xyz/gost/

**Comment by pinghe** [comment]
看了，没搞懂。也就是两个gost之间需要通过一个第三方http代理（如squid）连接。

**Comment by tangkv** [comment]
> 看了，没搞懂。也就是两个gost之间需要通过一个第三方http代理（如squid）连接。

gost 支持这种中间含有 http 代理的方式，只要中间 http 代理不主动 block gost 的请求。

**Comment by pinghe** [comment]
没搞懂如何配置，能给个示例吗？

**Comment by ginuerzh** [comment]
gost -L=:8888 -F=http://squid-server:port -F=gost-server:port

**Comment by pinghe** [comment]
多谢
