### ISSUE TITLE
2.8版本的http2 h2c 协议的ping失效.

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#404]
```
gost -L=:1081 -F=http2://127.0.0.1:888?ping=10
gost -L=:1081 -F=h2c://127.0.0.1:888?ping=10
```

我记得之前版本是正常的,没有ping,如果这个连接死了,并且状态没有断开,
只能手动重启程序了.

**Comment by f4nff** [comment]
`gost -L=:1081 -F="h2c://www.qq.com:999"`

h2c模式下没有心跳,也没有连接超时的判断,

`github.com/codeskyblue/netcat`

使用netcat监听端口,模拟接收不回的情况.

**Comment by ginuerzh** [comment]
HTTP2没有支持ping
