### ISSUE TITLE
UserAgent 能否在运行时自定义？

### ISSUE THREAD

**Issue by tangkv** [ginuerzh/gost#406]
由于内网防火墙会鉴别客户端请求的 UserAgent 信息进而阻止其访问外网，所以希望 gost 可以在运行时用自定义 UserAgent 来绕过防火墙的这一检测。

引用代码 gost/gost.go
...
var (
	// DefaultTLSConfig is a default TLS config for internal use.
	DefaultTLSConfig *tls.Config

	// DefaultUserAgent is the default HTTP User-Agent header used by HTTP and websocket.
	_DefaultUserAgent = "Chrome/60.0.3112.90"_
)
...

**Comment by ginuerzh** [comment]
目前仅websocket协议可以通过`agent`参数自定义UserAgent:

```
gost -L :1080 -F ws://:8080?agent=Custom-Agent
```

**Comment by tangkv** [comment]
感谢解答！后续有计划让 http 协议也支持自定义 UserAgent 吗？内网通常是 http 代理居多啊。

**Comment by ginuerzh** [comment]
下个版本会支持

**Comment by ginuerzh** [comment]
2.8.1中已支持：
```
gost -L :1080 -F=http://:8080?agent=Custom-Agent
```

**Comment by tangkv** [comment]
收到，非常感谢！

**Comment by tangkv** [comment]
在内网环境用 2.8.1 测试 gost.exe -L=:8888 -F=http://xx.xx.xx.xx:443?agent="Note, Lotus Note, IBM Lotus Note" 确认有效，成功“骗”过内网的简单防火墙。
