### ISSUE TITLE
GOST讨论群和捐助计划。

### ISSUE THREAD

**Issue by XYDsoft** [ginuerzh/gost#407]
为了更好更便捷的获取用户建议和BUG反馈，请作者创建GOST讨论QQ群。
为了使gost获得长足发展，最好能做一个捐助二维码。
若作者怕因此踩到法律边缘，我可代为创建QQ群。
不知道如何联系作者，请作者留个能够联系到的邮箱。

**Comment by 2378** [comment]
what the heck ! this guy gave himself a thumbs up :astonished:

shame on you, bro~
