### ISSUE TITLE
[bug] ss2 AEAD无法从secrets.txt加载密码

### ISSUE THREAD

**Issue by hexian000** [ginuerzh/gost#408]
使用ss2 + AEAD_AES_256_GCM
通过命令行传入密码正常工作
使用secrets.txt，在首个连接请求时提示“cipher not supported”

**Comment by hexian000** [comment]
已确认ss/ss2的服务端存在此问题

**Comment by ginuerzh** [comment]
ss/ss2目前不支持secrets参数，下个版本会添加

**Comment by everyx** [comment]
> ss/ss2目前不支持secrets参数，下个版本会添加

你好，能告知一下实现思路吗，有方法能从客户端的请求数据中解析出客户端的用户名吗？

比较需要这个功能，想尝试一下看自己能不能实现一下。

**Comment by ginuerzh** [comment]
@everyx  对于ss/ss2没有用户名一说吧。
