### ISSUE TITLE
User-Agent string after ; is completely removed between peers

### ISSUE THREAD

**Issue by miaomi** [ginuerzh/gost#409]
2.8.1中已支持：
```
gost -L :1080 -F=http://:8080?agent=Custom-Agent
```

_Originally posted by @ginuerzh in https://github.com/ginuerzh/gost/issues/406#issuecomment-504443416_

Server: `gost -D -L=https://:8081`
Client: `gost -D -L=http://:8080 -F=https://:8081?agent="Custom;Agent"`

While requesting an https url:
`curl -x http://127.0.0.1:8080 https://example.com`

Server log:
> User-Agent: Custom

Client log:
> User-Agent: Custom

**Comment by ginuerzh** [comment]
https://github.com/golang/go/issues/22641
`;`不会被转义，可以使用`%3b`代替
