### ISSUE TITLE
服务器端多ip的时候能否加个参数，指定用绑定ip做出口IP来请求资源？

### ISSUE THREAD

**Issue by cod1ingcoding** [ginuerzh/gost#410]
比如服务器A有3.3.3.3 和 4.4.4.4两个ip，当服务器端如下设置的时候：
gost -L=socks5://4.4.4.4:1080
客户端B连接服务器A
gost -L=:8080 -F=socks5://4.4.4.4:1080
用8080端口代理访问互联网，其实服务器A使用的是3.3.3.3这个ip发起请求，在多ip代理服务器上非常不方便（因为其中的一些ip可能会被一些中间网络设备block掉）

我记得socket在请求互联网资源的时候，无论是listen动作，还是connect动作，都可以用bind方法来指定监听IP或者出口ip。

如果能加一个参数，当设置这个参数的时候， 就会在代理服务器请求资源的时候，先bind代理服务器设置的ip就更好了，就如上面的服务器A，如果加一个参数(比如b)
gost -L=socks5://4.4.4.4:1080?b=1
这样设置就能让服务器A在请求资源的时候，都会先bind 4.4.4.4 这个ip。

不知道这个feature能否添加进来？

**Comment by xylake** [comment]
强烈支持，如果绑定出口ip，就可以通过在路由器上设定路由规则，控制不同ip走不同路线

**Comment by PaulCnth** [comment]
强烈建议添加。指定出口IP功能较为实用。

`curl --interface x.x.x.x example.com `

类似这样的功能真好。

**Comment by pylist** [comment]
同问, 希望这个功能尽快支持

**Comment by GeekDuanLian** [comment]
有一个临时的解决方法，v2ray 是支持指定出口的，可以用 v2ray 开一个 socks5 并只监听 127.0.0.1
然后 gost 后面加一个参数 `-F=socks5://127.0.0.1:1080` 来转发流量到 v2ray 出口
v2ray 出口配置示例：`"outbounds": [{"sendThrough": "出口内网ip", "protocol": "freedom"}]`

同时还是希望作者能尽快更新支持

**Comment by cod1ingcoding** [comment]
@GeekDuanLian 
更简单的方法就是用iptables的owner模块

```
$ useradd gostuser
$ sudo -u gostuser  gost -L :8080 &
$ iptables -t nat -A POSTROUTING -m owner --uid-owner gostuser -j SNAT --to-source 4.4.4.4
```

**Comment by GeekDuanLian** [comment]
@cod1ingcoding 
非常感谢，很有帮助！

**Comment by foxconndmd** [comment]
支持此功能，通过指定出口ip的服务中转或iptables都需单独开进程，希望增加个参数指定出口IP，类似于v2的sendThrough。

**Comment by cod1ingcoding** [comment]
https://github.com/go-gost/gost
已经开始开发3.0版，这个特性应该会加到3.0版本。

**Comment by cod1ingcoding** [comment]
#639 
在v2版本里，如果不用iptables的方法，可以看看这个PR，简单测试了下是没有问题的，如果要长期用，可以多测试下。

**Comment by ginuerzh** [comment]
V3版本已经支持
https://latest.gost.run/tutorials/multi-homed/
