### ISSUE TITLE
xtaci的stream.go的Read函数不会出现粘包吗？

### ISSUE THREAD

**Issue by alex-jin** [ginuerzh/gost#429]
session.go收到包之后放到stream 的buffer里，如果stream还没read，下一个包再放到buffer里不就出现粘包了吗？

**Comment by ginuerzh** [comment]
Stream本身就是流式，不存在粘包一说

**Comment by alex-jin** [comment]
请问比如我的代理模型是“客户端(udp)->我的gost_1(kcp)->我的gost_2(udp) -> 目标服务器" ，这种情况下"我的gost_2“节点从Stream读出来的不就有可能是2个客户端发的udp包粘在一起的了吗？ 我要在"我的gost_2"加额外的逻辑去处理这种情况吗？ 谢谢～

**Comment by ginuerzh** [comment]
UDP在gost里面是通过扩展的SOCKS5协议来转发的，所以是由协议层来保证数据的一致性。

**Comment by alex-jin** [comment]
所以我上面说的代理链模型（第一跳和第二跳用kcp传输）就不适用UDP的代理了是吗？？要改gost代码？

**Comment by alex-jin** [comment]
我看你是通过设置包的头部的rsv字段来从流式Steam里面正好读出1个udp包的， 感谢回复
