### ISSUE TITLE
建议：直接作为本地DNS-proxy

### ISSUE THREAD

**Issue by Justsoos** [ginuerzh/gost#434]
还以为可以直接作本地DNS解析，直接运行：
```
gost -L=:8080?dns=8.8.8.8,1.1.1.1:53/tcp,1.1.1.1:853/tls,https://1.0.0.1/dns-query
```
尴尬了，看来是我理解错了。既然能作这个功能，何必不作本地DNS-proxy呢，很多情况下，无法使用无污染DNS的时候，一个命令就用gost解决了

而且出现个问题，直接在 zsh 下运行 `gost -L=:8080?dns=8.8.8.8`，会出现
`zsh: no matches found: -L=:8080?dns=8.8.8.8`
在 bash 下不会报错，ubuntu18.04测试

**Comment by wendellou** [comment]
https://docs.ginuerzh.xyz/gost/port-forwarding/

**Comment by Justsoos** [comment]
同学，你确定 forwarding 里有 DoH，DoT 这些已经内置于 gost 的 dns 协议解读能力？
为什么不简单的通过设置 wiki 介绍释放出来呢？
至少目前版本，测试了多个可能命令形式，都没看出来可用

**Comment by ginuerzh** [comment]
端口转发不行吗？

**Comment by Justsoos** [comment]
> 端口转发不行吗？

现代的 DoH，DoT需要客户端支持特别协议进行解析啊，并不是系统直接 53 UDP 明文直接端口转发的时代了。
你的 gost 既然已经支持（也许我弄错？）了这些协议，不如直接就作本地 proxy 。

**Comment by ginuerzh** [comment]
端口转发是L4的数据转发，不管是DoH还是DoT都是L4上的协议，对于端口转发来说没有区别。即使支持DNS协议，最终还是要转发到公共服务器上，除非需要对DNS请求和响应进行人为干涉，才需要解析协议。

DoT:
```
gost -L :8000?dns=127.0.0.1:1053/tls -L tcp://:1053/1.1.1.1:853 -F https://SERVER_IP:443
```
DoH由于需要对server name进行校验，目前要稍微麻烦，需要修改Host映射:
```
gost -L "http://:8000?dns=https://cloudflare-dns.com:1053/dns-query" -L tcp://:1053/1.0.0.1:443 -F https://SERVER_IP:443
```
要手动把cloudflare-dns.com映射到127.0.0.1上。

**Comment by Justsoos** [comment]
我又去测了一下，确认我没弄错。
用curl 的远程 socks5 解析命令来测：
`curl -4Iv --socks5-hostname 127.0.0.1:8880 http://google.com`
确定这个 8880 后面的 gost 代理是用 tls 来查询的。
其中日志之一：
`resolver.go:199: [resolver] google.com via 1.1.1.1:853/tls`
这说明，gost 作为 proxy server 端，已经内置了 tls 的 dns 查询客户端。

既然有这个客户端代码内置能力，却找不到 gost 如何将 tls dns 查询直接转发到本地53端口的命令行啊？呵呵，这不是浪费了吗？这个功能实际上就是 tls dns proxy 的功能
也就是 https://github.com/DNSCrypt/dnscrypt-proxy  在作的

另外发现个问题，目前依照 wiki 运行如下命令会缺少协议部分参数，目测的确是少了点啥？：
`gost -L=:8080?dns=https://1.0.0.1/dns-query`
出错：
`main.go:88: parse :8880?dns=https://1.0.0.1/dns-query: missing protocol scheme`

**Comment by ginuerzh** [comment]
下个版本会支持DNS代理服务做协议转换。
这种前面的scheme不能省了：
`gost -L=http://:8080?dns=https://1.0.0.1/dns-query`
