### ISSUE TITLE
关于自签名证书，加入命令行参数无效的问题

### ISSUE THREAD

**Issue by wendellou** [ginuerzh/gost#435]
版本
$ gost -V
gost 2.8.1 (go1.13 linux/mips)
命令：
$ gost -L=socks5+tls://:8080

因为是开发板，性能差，根据 https://docs.ginuerzh.xyz/gost/tls/ 上面的说明，直接在当前目录下放入证书，无需生成，秒开。当cd到别的目录，命令行后面加入正确的绝对路径的证书参数的时候，貌似没有读取参数定义的证书，需要生成，导致命令不能立即生效，需要等证书生成。

两种方式命令生效以后，都是能正确连接的，没有问题。

**Comment by ginuerzh** [comment]
默认的证书是全局的，作用于所有需要证书的地方，通过cert/key参数指定的证书是局部的，只作用于参数所在的服务。全局证书不受局部证书影响，始终会初始化。
