### ISSUE TITLE
路由控制ip匹配

### ISSUE THREAD

**Issue by zhylmzr** [ginuerzh/gost#437]
希望能够匹配域名解析后的ip
目前是仅在域名解析前匹配, 这样只有直接访问ip才会走路由控制
如果能够匹配解析后的ip可以直接把CN地址加入到黑名单

**Comment by mylukin** [comment]
我也想要

**Comment by zhylmzr** [comment]
@mylukin 我这边提交了一个更改, 让域名解析成IP再走路由控制

**Comment by mylukin** [comment]
有代码吗？我看看，先合并到自己的库编译一下

**Comment by zhylmzr** [comment]
@mylukin 这里 #442
