### ISSUE TITLE
请问-L支持哪些协议绑定在同一个端口？

### ISSUE THREAD

**Issue by RonaldinhoL** [ginuerzh/gost#438]
只有 gost -L :8080 这种方式支持 http+socks绑定在同一端口吗， 其他的是否支持呢？

**Comment by ginuerzh** [comment]
仅 `-L :8080`这种方式支持绑定多种协议，目前支持http, socks4, socks5。

**Comment by Herbert8** [comment]
@ginuerzh 请问怎样做到多个协议绑定到一个端口呢？这部分代码没太看懂，能帮忙指点下思路吗？
