### ISSUE TITLE
docker方式启动失败

### ISSUE THREAD

**Issue by useaname** [ginuerzh/gost#444]
环境 centos7:

命令如下:

DOMAIN="xxxx.xyz"
USER="user1"
PASS="031009"
PORT=443

BIND_IP=0.0.0.0
CERT_DIR=/etc/letsencrypt
CERT=${CERT_DIR}/live/${DOMAIN}/fullchain.pem
KEY=${CERT_DIR}/live/${DOMAIN}/privkey.pem

sudo docker run -d --name gost \
    -v ${CERT_DIR}:${CERT_DIR}:ro \
    --net=host ginuerzh/gost \
    -L "http2://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}&probe_resist=code:404"

执行docker start 后 不能启动

**Comment by ginuerzh** [comment]
有什么错误提示吗?

**Comment by useaname** [comment]
> 有什么错误提示吗?

没有，执行后就立刻exit了。

**Comment by geekeritcom** [comment]
可以`docker logs gost`看下，我的同样起不来是由于端口占用，但是就算启动成功也无法访问

**Comment by useaname** [comment]
> 可以`docker logs gost`看下，我的同样起不来是由于端口占用，但是就算启动成功也无法访问

目前已经放弃docker的方式，正常方式启动起来了。

**Comment by zkkandrew** [comment]
同样的问题。sudo docker logs gost 显示 2020/10/20 02:00:44 main.go:88: listen tcp 0.0.0.0:443: bind: address already in use 请问该怎么办？
