### ISSUE TITLE
gost 2.8 , broken pipe after running the next day

### ISSUE THREAD

**Issue by androllen** [ginuerzh/gost#446]
前一天 服务端操作:
- 配置服务 gost.service
- 配置文件 config.json
- 加入自启动
- /usr/local/gost_2.8/gost -C /usr/local/gost_2.8/config.json
- systemctl start gost.service
- active (running) 状态

前一天客户端操作:
- gost -L :1080 -F mwss://user:pswd@server ip:port 
- 可以Google

后一天直接操作:
- gost -L :1080 -F mwss://user:pswd@server ip:port 
- 发现broken pipe
- 503 Service Unavailable

**Comment by ginuerzh** [comment]
一直是503 Service Unavailable吗?

**Comment by pingod** [comment]
我的也是一直出现503错误，奇怪的是通过代理可以正常访问baidu.com，访问youtube就报503
2020/02/28 02:14:47 http.go:251: [route] 127.0.0.1:6296 -> auto://:8080 -> 1@https://43.245.198.193:9008 -> [::1]:50051
2020/02/28 02:14:48 http.go:161: [http] 127.0.0.1:6300 -> auto://:8080 -> [::1]:50052
2020/02/28 02:14:48 http.go:251: [route] 127.0.0.1:6300 -> auto://:8080 -> 1@https://43.245.198.193:9008 -> [::1]:50052
2020/02/28 02:14:48 http.go:272: [http] 127.0.0.1:6296 -> 127.0.0.1:8080 : 503 Service Unavailable
2020/02/28 02:14:48 http.go:272: [http] 127.0.0.1:6300 -> 127.0.0.1:8080 : 503 Service Unavailable
2020/02/28 02:14:52 http.go:161: [http] 127.0.0.1:6306 -> auto://:8080 -> [::1]:50051
2020/02/28 02:14:52 http.go:251: [route] 127.0.0.1:6306 -> auto://:8080 -> 1@https://43.245.198.193:9008 -> [::1]:50051
2020/02/28 02:14:52 http.go:161: [http] 127.0.0.1:6310 -> auto://:8080 -> [::1]:50052
2020/02/28 02:14:52 http.go:251: [route] 127.0.0.1:6310 -> auto://:8080 -> 1@https://43.245.198.193:9008 -> [::1]:50052
2020/02/28 02:14:52 http.go:272: [http] 127.0.0.1:6306 -> 127.0.0.1:8080 : 503 Service Unavailable
2020/02/28 02:14:52 http.go:272: [http] 127.0.0.1:6310 -> 127.0.0.1:8080 : 503 Service Unavailable

**Comment by pingod** [comment]
我把proxifier停掉，然后使用系统自带的代理，好像又没有报错了，暂时看起来好像是proxifier的问题
