### ISSUE TITLE
日志出现downgrade to HTTP/1.1是表示HTTPS没有成功开起吗

### ISSUE THREAD

**Issue by useaname** [ginuerzh/gost#447]
如题。

**Comment by ginuerzh** [comment]
downgrade指的是你用HTTP/1协议访问HTTP2服务器，为了兼容，HTTP2服务器也会处理这种请求，相当于是降级为HTTP1代理，与是不是使用了TLS无关。

**Comment by useaname** [comment]
> downgrade指的是你用HTTP/1协议访问HTTP2服务器，为了兼容，HTTP2服务器也会处理这种请求，相当于是降级为HTTP1代理，与是不是使用了TLS无关。

谢谢指教。
