### ISSUE TITLE
多个入口出口运行出错 bind: address already in use

### ISSUE THREAD

**Issue by foxconndmd** [ginuerzh/gost#449]
{
  "Debug": false,
  "Retries": 0,
  "ServeNodes": [
    "socks5://127.0.0.1:7000",
    "tcp://:5356/8.8.4.4:53"
  ],
  "ChainNodes": [
    "wss://us:pa@1.1.1.1:443"
  ],

  "Routes": [
    {
      "Retries": 0,
      "ServeNodes": [
        "socks5://127.0.0.1:7001"
      ],
      "ChainNodes": [
        "mwss://us:pa@1.1.1.1:443"
      ]
    }
  ]
}
gost 2.8.1启动出现以下错误，确定无gost进程在运行。
2019/12/01 10:00:47 main.go:79: listen tcp 127.0.0.1:7000: bind: address already in use
有时前台运行时按ctrl c 取消后进程依然在后台运行。

**Comment by ginuerzh** [comment]
7000端口被占用。

**Comment by foxconndmd** [comment]
谢谢，再次测试没问题了。
