### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by u0x01** [ginuerzh/gost#45]
服务器上跑了7个gost进程，其中一个进程运行了大约48小时，出现了拒绝服务的情况。
`root     12158     1  0 18:26 pts/1    00:00:00 gost -log_dir=/var/log/gost/ -v=4 -L=:8082 -F=tls://usr:pass@ip`
查看日志报：
too many open files
日志大约900M

`lsof | grep gost`
可以看到有很多sock和IPv4没有释放。

重启gost后即恢复正常，请问这是程序没有正确释放文件句柄吗？

我把文件打开数限制提高到了4096，再观察几天看一下。

**Comment by dapao9999** [comment]
我的也出现这种情况了，你的解决没？
`I0704` 02:52:01.009138   26262 conn.go:79] accept tcp [::]:25: accept4: too many open `files`

**Comment by ginuerzh** [comment]
目前发现是有连接未关闭的情况，会出现CLOSE_WAIT的状态，暂时可以通过调高ulimit来解决。

**Comment by ginuerzh** [comment]
2.1版本中对网络连接做了一些优化，目前测试状况较好，没有再发现有CLOSE_WAIT的状况。

**Comment by FlowerWrong** [comment]
似乎不少go网络程序会出现该问题。

**Comment by ginuerzh** [comment]
正常来说不应该出现这种情况，如果出现了，很有可能是程序本身的问题(连接没有正常关闭)。
也有可能是并发连接很多，而系统参数(ulimit)设置的过小引起的。
