### ISSUE TITLE
Windows客户端报错 first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by hyb0926** [ginuerzh/gost#452]
版本：gost_2.8.1_windows_amd64

Windows客户端启动
gost.exe -L ss://aes-128-ctr:password@:8388 -F 'https://username:password@domainname:443'
报错内容：
main.go:79: parse 'https://username:password@domainname:443': first path segment in URL cannot contain colon

用户名密码无特殊字符

**Comment by william-hyx** [comment]
正确的应该是gost.exe -L ss://aes-128-ctr:password@:8388 -F https://username:password@domainname:443

**Comment by hyb0926** [comment]
> 正确的应该是gost.exe -L ss://aes-128-ctr:password@:8388 -F https://username:password@domainname:443

谢谢
