### ISSUE TITLE
aws+gost+https+patotso lite搭建不能访问

### ISSUE THREAD

**Issue by dream0411** [ginuerzh/gost#453]
在aws ec2上的服务端，配置好了域名、证书、非443的4位端口，ios端用patotso lite配置了一个https的方式，显示连接成功，但浏览器里还是不能访问google/twitter；

启动是这种
sudo docker run -d --name gost \
    -v ${CERT_DIR}:${CERT_DIR}:ro \
    --net=host ginuerzh/gost \
    -L "http2://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}&probe_resist=code:404"

在服务端用这个证书和端口，开了个简单的python https目录服务器，浏览器里就能访问到内容；用户名和密码也确认没配置错；

试着用l2tp/IPSec，ios端能成功访问google等；

有人碰到过类似问题吗？是不是访问内容被墙了呢？

**Comment by geekeritcom** [comment]
用https我也出现这个错误，我是使用的默认端口，SS就可以，HTTPS无法访问

**Comment by voidiak** [comment]
无法访问+1

**Comment by jackysp** [comment]
是参考 https://haoel.github.io/#33-%E7%94%A8-gost-%E8%AE%BE%E7%BD%AE-https-%E6%9C%8D%E5%8A%A1 来配置的是吧？ @dream0411 
我简单 debug 了一下，大概是 auth 出的问题。去掉 `${USER}:${PASS}@` 以后就 ok 了。本地试了下，如果用 http 协议，设置 `${USER}:${PASS}@` 也可以使用。所以，可能是加密以后的认证信息处理有些问题？不过也可能是使用使用姿势问题。这块不是很懂。
如果是 gost 自己做客户端来连接 proxy，认证是没问题的。
