### ISSUE TITLE
微信PC 端代理

### ISSUE THREAD

**Issue by shanjava** [ginuerzh/gost#455]
您好 我是腾讯云的服务器    代理设置好后。用在微信开发者工具 上测试代理是可以的。 但是在微信Pc端测试就不行   一直不行，弹出连接失败，。
日志如下 ：

2019/12/13 17:56:31 handler.go:222: [auto] 39.155.157.125:17261 - 172.30.0.6:8999: read tcp 172.30.0.6:8999->39.155.157.125:17261: read: connection reset by peer
2019/12/13 17:56:47 http.go:151: [http] 39.155.157.125:46566 -> auto://:8999 -> servicewechat.com:443

**Comment by ginuerzh** [comment]
命令参数是什么？
