### ISSUE TITLE
Bad version

### ISSUE THREAD

**Issue by coofo** [ginuerzh/gost#457]
最近在尝试用Netch(tun模式) 和 v2rayNG(android APP)链接gost起的socks5代理
启动命令：gost.exe -L root:root@:31080
发现只要加了认证，就无法使用。
Netch(tun模式)连  gost会报 bad version
v2rayNG(android APP)连 gost会报 EOF

**Comment by ginuerzh** [comment]
加上-D参数，看看日志

**Comment by coofo** [comment]
Netch：
2019/12/18 21:21:02 handler.go:222: [auto] 192.168.2.56:7643 - 192.168.115.100:31080: EOF
2019/12/18 21:21:07 socks.go:115: [socks5] 5 1 [0]
2019/12/18 21:21:07 socks.go:140: [socks5] 5 2
2019/12/18 21:21:07 socks.go:153: [socks5] 192.168.2.56:7713 - 192.168.115.100:31080: Bad version
2019/12/18 21:21:07 socks.go:801: [socks5] 192.168.2.56:7713 -> 192.168.115.100:31080 : Bad version
2019/12/18 21:21:07 socks.go:115: [socks5] 5 1 [0]
2019/12/18 21:21:07 socks.go:140: [socks5] 5 2
2019/12/18 21:21:07 socks.go:153: [socks5] 192.168.2.56:7717 - 192.168.115.100:31080: Bad version
2019/12/18 21:21:07 socks.go:801: [socks5] 192.168.2.56:7717 -> 192.168.115.100:31080 : Bad version
2019/12/18 21:21:08 socks.go:115: [socks5] 5 1 [0]
2019/12/18 21:21:08 socks.go:140: [socks5] 5 2
2019/12/18 21:21:08 socks.go:153: [socks5] 192.168.2.56:7719 - 192.168.115.100:31080: Bad version
2019/12/18 21:21:08 socks.go:801: [socks5] 192.168.2.56:7719 -> 192.168.115.100:31080 : Bad version


v2rayNG:
2019/12/18 21:22:21 socks.go:115: [socks5] 5 1 [2]
2019/12/18 21:22:21 socks.go:140: [socks5] 5 2
2019/12/18 21:22:21 socks.go:115: [socks5] 5 1 [2]
2019/12/18 21:22:21 socks.go:115: [socks5] 5 1 [2]
2019/12/18 21:22:21 socks.go:140: [socks5] 5 2
2019/12/18 21:22:21 socks.go:140: [socks5] 5 2
2019/12/18 21:22:21 socks.go:115: [socks5] 5 1 [2]
2019/12/18 21:22:21 socks.go:140: [socks5] 5 2
2019/12/18 21:22:21 socks.go:115: [socks5] 5 1 [2]
2019/12/18 21:22:21 socks.go:140: [socks5] 5 2
2019/12/18 21:22:21 socks.go:115: [socks5] 5 1 [2]
2019/12/18 21:22:21 socks.go:140: [socks5] 5 2
2019/12/18 21:22:21 socks.go:115: [socks5] 5 1 [2]
2019/12/18 21:22:21 socks.go:140: [socks5] 5 2
2019/12/18 21:22:25 socks.go:153: [socks5] 192.168.2.54:33006 - 192.168.115.100:31080: EOF
2019/12/18 21:22:25 socks.go:801: [socks5] 192.168.2.54:33006 -> 192.168.115.100:31080 : EOF
2019/12/18 21:22:25 socks.go:153: [socks5] 192.168.2.54:33012 - 192.168.115.100:31080: EOF
2019/12/18 21:22:25 socks.go:801: [socks5] 192.168.2.54:33012 -> 192.168.115.100:31080 : EOF
2019/12/18 21:22:25 socks.go:153: [socks5] 192.168.2.54:33014 - 192.168.115.100:31080: EOF
2019/12/18 21:22:25 socks.go:801: [socks5] 192.168.2.54:33014 -> 192.168.115.100:31080 : EOF
2019/12/18 21:22:25 socks.go:153: [socks5] 192.168.2.54:33016 - 192.168.115.100:31080: EOF
2019/12/18 21:22:25 socks.go:801: [socks5] 192.168.2.54:33016 -> 192.168.115.100:31080 : EOF
2019/12/18 21:22:25 socks.go:153: [socks5] 192.168.2.54:33018 - 192.168.115.100:31080: EOF
2019/12/18 21:22:25 socks.go:801: [socks5] 192.168.2.54:33018 -> 192.168.115.100:31080 : EOF
2019/12/18 21:22:25 socks.go:153: [socks5] 192.168.2.54:33020 - 192.168.115.100:31080: EOF
2019/12/18 21:22:25 socks.go:801: [socks5] 192.168.2.54:33020 -> 192.168.115.100:31080 : EOF
2019/12/18 21:22:25 socks.go:153: [socks5] 192.168.2.54:33022 - 192.168.115.100:31080: EOF
2019/12/18 21:22:25 socks.go:801: [socks5] 192.168.2.54:33022 -> 192.168.115.100:31080 : EOF

**Comment by ginuerzh** [comment]
从log上看，Netch应该是不支持用户认证。
v2rayNG支持认证，但在服务端读取接收认证信息时，客户端直接关闭连接了。
具体问题要看下客户端信息或抓包分析了。

**Comment by coofo** [comment]
好的，谢谢，我找客户端那里看看。
