### ISSUE TITLE
v2.8.2 gost-windows-386.exe “不是有效的 win32 应用程序”

### ISSUE THREAD

**Issue by jfc8000** [ginuerzh/gost#460]
如题 2.8.2 gost-windows-386.exe 不能运行

**Comment by ginuerzh** [comment]
release中的吗？测试没有问题。

**Comment by jfc8000** [comment]
是的
在server2003 32位版 运行 提示 gost.exe 有效，但不适用于此计算机类型。

**Comment by jfc8000** [comment]
上面错了 
server2003 提示 “不是有效的 win32 应用程序”

**Comment by ginuerzh** [comment]
Server 2003已经不再支持
https://github.com/golang/go/wiki/Windows
