### ISSUE TITLE
ftp端口转发不成功

### ISSUE THREAD

**Issue by xieyy09** [ginuerzh/gost#464]
192.168.1.19不能上外网且不能暴露端口: 
`
gost -L=rtcp://127.0.0.1:10896/192.168.1.112:21 -F socks5+tls://192.168.35.12:11033?mbind=true
`

192.168.35.12 可以通外网且不能暴露端口到外网:
`
./gost -L socks5+tls://:11033?whitelist=rtcp:127.0.0.1:10896 &
 ./gost -L=rtcp://127.0.0.1:10899/127.0.0.1:10896 -F socks5+tls://106.51.227.27:11021?mbind=true
`

106.51.227.27 云端(暴露端口)：
`
./gost  -L socks5+tls://:11021?whitelist=rtcp:127.0.0.1:10899
`
在浏览器直接访问 ftp://106.51.227.27:11021,一直再加载 后台没有任何日志

我使用的有什么问题吗？

**Comment by ginuerzh** [comment]
192.168.1.112:21最终转发到的是106.51.227.27上的127.0.0.1:10899。

没必要转发两次这么麻烦，
106.51.227.27上：`gost -L socks5+tls://:11021`
192.168.35.12 上：`gost -L http://:11033`
192.168.1.19上：
`gost -L rtcp://:10896/192.168.1.112:21 -F http://192.168.35.12:11033 -F socks5+tls://106.51.227.27:11021?mbind=true`

再访问：ftp://106.51.227.27:10896 （10896端口要开放)

**Comment by xieyy09** [comment]
你的方式更简单，但是我收到了下面的日志：

`
socks.go:1087: [socks5-mbind] 192.168.35.12:44766 <- 106.51.227.27:10896 : ACCEPT peer 106.51.227.27:52752
`
页面不能打开，和握手有关？

**Comment by xieyy09** [comment]
内网区对外网信息比较敏感，可能还是要用我初始方式！

初始是我的错误，应该访问ftp://106.51.227.27:10899，而不是 ftp://106.51.227.27:11021

**Comment by xieyy09** [comment]
从日志上看，好像是没有回路。

服务端主动以20端口连接到客户端的N+1端口是不是有问题？

> jasonx@jasonx-OptiPlex-7050 ~ $ curl ftp://106.51.227.27:10896/test/ -u ftp:test123 -T test.xlsx
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (25) Failed FTP upload: 425
> jasonx@jasonx-OptiPlex-7050 ~ $

**Comment by ginuerzh** [comment]
FTP有两个连接，这种单端口转发不适用。

**Comment by xieyy09** [comment]
OK, 我搞了另外一种办法 可以正常工作。但是感觉风险比较大: 在内网区直接搞一个socks5服务，不过这样就可以通过互联区访问任意一个内网机器可以访问的服务。

![image](https://user-images.githubusercontent.com/21615006/72118104-15f3ee80-338b-11ea-97ed-bf1a7279e39b.png)

上图是我的测试方案，有两个问题请教下：

1. 在红色箭头上，我总是担心安全方面。我是forward的具体IP，我不太担心中间人攻击，数据也是加密的，还有别的隐患吗？或者还可以增加些安全措施?（用户名密码？）

2. 在红色的命令行上，两次forward socks5 好像不太稳定，一次成功 一次失败 挺有规律的，是我写法上有问题吗？

想到另外一个问题：

mbind如果设置了true，多路复用在有些情况下有问题，需要重启gost服务。例如： 

1. 连接是在gost客户端控制的，ftp服务确实会让jvm卡住
```
...
FTPClient ftp = new FTPClient();
Proxy proxy = new Proxy(java.net.Proxy.Type.SOCKS, new InetSocketAddress("hostname'",10896));
ftp.setProxy(proxy);
ftp.connect("127.0.0.1",21);
....
ftp.storeFile("/var/ftp/test/gitlab.rb_"+ TIME, fis); #卡住这里，实际文件已经上传完成,去掉mbind正常
```
2. 在有些防火墙下，防火墙把连接关闭了，gost不会感知到。

可不可以增加写自身情况的监测？ 或者复用的连接有个最大时间？ 这个问题是我的猜测想法
