### ISSUE TITLE
使用Gost作为HTTP2/TLS termination前端

### ISSUE THREAD

**Issue by rankjie** [ginuerzh/gost#470]
Hi，
目前我们内部有一个HTTP代理服务器，每位使用者都有各自的用户名+密码做认证
现在想要提高数据安全性，但是并不准备直接改造后端的HTTP代理程序去支持HTTPS
考虑采用Gost作为HTTP2/TLS前端，用户只需要把原来代理配置的HTTP类型切换到HTTPS即可

我测试了 `gost -L "http2://:4433?cert=server.cer&key=server.key" -F=http://local-http-server:1234`
然后在Chrome里使用HTTPS类型代理连接服务器4433端口，无法正常连接（期望Chrome会弹出代理认证窗口）
检查gost输出发现似乎是gost接收到后端传来的`407 Proxy Authentication Required`就直接返回错误了，并没有把这一返回值直接透明转发给client，同时client动态传入的认证信息也没有保留转发到后端

请问Gost是否考虑支持此类应用方式？即提供透明传输的HTTP2 forward模式，不进行额外的代理逻辑计算

**Comment by ginuerzh** [comment]
可以尝试一下转发隧道:
```
gost -L "tls://:4433/local-http-server:1234?cert=server.cer&key=server.key"
```
这样4433就是一个https代理，在4433处进行TLS termination，然后会把HTTP请求原封不动的转发给local-http-server:1234。

**Comment by rankjie** [comment]
感谢，tls 转发测试可用。

尝试替换 tls 为 h2 则不成功，浏览器中访问 [ip.sb](ip.sb) 测试，gost输出提示：

    server.go:616: http2: server: error reading preface from client xxxxxx:59714: bogus greeting "CONNECT ip.sb:443 HTTP/1"

**Comment by miniaoe** [comment]
> 可以尝试一下转发隧道:
> 
> ```
> gost -L "tls://:4433/local-http-server:1234?cert=server.cer&key=server.key"
> ```
> 
> 这样4433就是一个https代理，在4433处进行TLS termination，然后会把HTTP请求原封不动的转发给local-http-server:1234。

是否支持websockset隧道转发。
http代理服务器在香港，需要用户密码认真，想通过百度云加速的websocket进行加速，是否支持这样搞

**Comment by ginuerzh** [comment]
@miniaoe 可以，用法类似
@rankjie http2不适用于这个场景，前后端的协议不一致，需要做协议转换。
