### ISSUE TITLE
在openwrt上运行出现out of memory

### ISSUE THREAD

**Issue by wwbfred** [ginuerzh/gost#473]
环境: MT7621,128MB内存.
配置: 本地redirect, 转发ss+mws.
复现方式: 使用gost解析域名(tcp方式),访问dmm.co.jp视频时拖动进度条高概率出现崩溃.
怀疑问题: 访问时出现大量解析与访问请求,断开连接后可用内存不恢复,怀疑是内存泄漏.
问题日志:
/tmp/gost/gost -L redirect://:1081 -F ss+mws://method:password@*:80?path=/path
2020/01/21 09:39:19 main.go:82: load TLS certificate files OK
2020/01/21 09:39:19 route.go:554: redirect://:1081 on [::]:1081
2020/01/21 09:39:19 redirect.go:50: [red-tcp] 192.168.1.208:6596 -> 74.125.24.105:443
...
2020/01/21 09:35:42 redirect.go:64: [red-tcp] public_ip:51750 >-< 8.8.4.4:53
fatal error: runtime: out of memory
[runtime stack.txt](https://github.com/ginuerzh/gost/files/4090395/runtime.stack.txt)

**Comment by f4nff** [comment]
128MB内存也敢跑，起码需要1G ，或者2G内存，
