### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by chonghai** [ginuerzh/gost#476]
ubuntu 18.04
运行 sudo go get -u github.com/ginuerzh/gost/cmd/gost
出现以下错误：
---------------------------------
package git.torproject.org/pluggable-transports/obfs4.git/transports/base: code in directory /root/go/src/git.torproject.org/pluggable-transports/obfs4.git/transports/base expects import "gitlab.com/yawning/obfs4.git/transports/base"
package git.torproject.org/pluggable-transports/obfs4.git/transports/obfs4: code in directory /root/go/src/git.torproject.org/pluggable-transports/obfs4.git/transports/obfs4 expects import "gitlab.com/yawning/obfs4.git/transports/obfs4"
-----------------------------------
请教该如何解决？谢谢。

**Comment by ginuerzh** [comment]
可以使用下面方法：
```
$ git clone https://github.com/ginuerzh/gost.git
$ cd cmd/gost
$ GOPROXY=https://goproxy.io go build
```

**Comment by chonghai** [comment]
试了一下，还是不行。我还是直接下载编译好的吧。
谢谢！

**Comment by ginuerzh** [comment]
2.9以后去掉了vendor，只支持module。
