### ISSUE TITLE
Shadowsocks 作为传输类型

### ISSUE THREAD

**Issue by lizongzeshunshun** [ginuerzh/gost#477]
目前从文档看来，`shadowsocks` 只能作为**协议类型**。
是否可能 / 有计划将其增加为一种**传输类型**呢？

**Comment by ginuerzh** [comment]
shadowsocks是基于SOCKS5协议的一种代理协议，本身不具备作为通用传输层的条件。

**Comment by lizongzeshunshun** [comment]
谢谢您的指导。
