### ISSUE TITLE
希望增加功能 DNS over Proxy

### ISSUE THREAD

**Issue by GeekDuanLian** [ginuerzh/gost#478]
类似：`gost -L='dns://:53?dns=1.1.1.1:53/tcp' -F='socks5://127.0.0.1:1080'`
这样查询 DNS 的流量就会通过 socks5 代理去远端查询，而不是在本机直接查询

因为有些程序设置了 socks5 代理后，DNS 查询还是用本机的，得多单独代理一次 DNS

希望能够实现，谢谢

**Comment by GeekDuanLian** [comment]
目前可以同时运行这两条语句实现这个功能：
`gost -L=dns://:53?dns=127.0.0.1:5353/tcp`
`gost -L=tcp://:5353/1.1.1.1:53 -F=socks5://127.0.0.1:1080`

我也不知道是什么原理，反正最终确实是通过代理查询的

**Comment by ginuerzh** [comment]
DNS代理可以支持代理链，具体使用参考DNS解析的用法：https://docs.ginuerzh.xyz/gost/resolver/

**Comment by GeekDuanLian** [comment]
> DNS代理可以支持代理链，具体使用参考DNS解析的用法：https://docs.ginuerzh.xyz/gost/resolver/

抱歉 文档没看仔细

**Comment by lyyx5858** [comment]
> 目前可以同时运行这两条语句实现这个功能：
> `gost -L=dns://:53?dns=127.0.0.1:5353/tcp`
> `gost -L=tcp://:5353/1.1.1.1:53 -F=socks5://127.0.0.1:1080`
> 
> 我也不知道是什么原理，反正最终确实是通过代理查询的

不好意思，没看懂您的配置，我想将DNS查询放在远端去，如何实现？

**Comment by GeekDuanLian** [comment]
> > 目前可以同时运行这两条语句实现这个功能：
> > `gost -L=dns://:53?dns=127.0.0.1:5353/tcp`
> > `gost -L=tcp://:5353/1.1.1.1:53 -F=socks5://127.0.0.1:1080`
> > 我也不知道是什么原理，反正最终确实是通过代理查询的
> 
> 不好意思，没看懂您的配置，我想将DNS查询放在远端去，如何实现？

具体文档看这里 https://docs.ginuerzh.xyz/gost/resolver/
就是协议后面加 -chain 就行，比如
`gost -L dns://:53?dns=https-chain://1.1.1.1/dns-query -F=socks5://127.0.0.1:1080`

**Comment by lyyx5858** [comment]
> > > 目前可以同时运行这两条语句实现这个功能：
> > > `gost -L=dns://:53?dns=127.0.0.1:5353/tcp`
> > > `gost -L=tcp://:5353/1.1.1.1:53 -F=socks5://127.0.0.1:1080`
> > > 我也不知道是什么原理，反正最终确实是通过代理查询的
> > 
> > 
> > 不好意思，没看懂您的配置，我想将DNS查询放在远端去，如何实现？
> 
> 具体文档看这里 https://docs.ginuerzh.xyz/gost/resolver/
> 就是协议后面加 -chain 就行，比如
> `gost -L dns://:53?dns=https-chain://1.1.1.1/dns-query -F=socks5://127.0.0.1:1080`

非常感谢回答，只是按我的理解，-F=后面的地址应该是远端VPS的IP地址，但你的例子里是127.0.0.1，我有点不太理解，是我理解错了还是?

**Comment by GeekDuanLian** [comment]
> > > > 目前可以同时运行这两条语句实现这个功能：
> > > > `gost -L=dns://:53?dns=127.0.0.1:5353/tcp`
> > > > `gost -L=tcp://:5353/1.1.1.1:53 -F=socks5://127.0.0.1:1080`
> > > > 我也不知道是什么原理，反正最终确实是通过代理查询的
> > > 
> > > 
> > > 不好意思，没看懂您的配置，我想将DNS查询放在远端去，如何实现？
> > 
> > 
> > 具体文档看这里 https://docs.ginuerzh.xyz/gost/resolver/
> > 就是协议后面加 -chain 就行，比如
> > `gost -L dns://:53?dns=https-chain://1.1.1.1/dns-query -F=socks5://127.0.0.1:1080`
> 
> 非常感谢回答，只是按我的理解，-F=后面的地址应该是远端VPS的IP地址，但你的例子里是127.0.0.1，我有点不太理解，是我理解错了还是?

没错，我这只是举例，后面可以跟任何协议，比如
`gost -L=dns://:53?dns=https-chain://1.1.1.1/dns-query -F=ss://chacha20:password@1.2.3.4:1234`
都是可以的
只是如果你已经开了一个远端协议转本地协议的，比如
`gost -L=:1080 -F=ss://chacha20:password@1.2.3.4:1234`
然后直接让dns走这个本地1080可能会更优雅一点

**Comment by lyyx5858** [comment]
非常感谢，如同您举例：gost -L=dns://:53?dns=https-chain://1.1.1.1/dns-query -F=ss://chacha20:password@1.2.3.4:1234
我的理解是：在本地将所有53端口的DNS查询转发至1.2.3.4服务器，然后 由1.2.3.4服务 器查询 1.1.1.1, 然后有了结果后，1.2.3.4再将结果返回到本地，我这样理解，对吗？

**Comment by GeekDuanLian** [comment]
> 非常感谢，如同您举例：gost -L=dns://:53?dns=https-chain://1.1.1.1/dns-query -F=ss://chacha20:password@1.2.3.4:1234
> 我的理解是：在本地将所有53端口的DNS查询转发至1.2.3.4服务器，然后 由1.2.3.4服务 器查询 1.1.1.1, 然后有了结果后，1.2.3.4再将结果返回到本地，我这样理解，对吗？

y，你可以设置一个错误的远端服务器地址作为对比，就会发现查询不到结果了

**Comment by lyyx5858** [comment]
> > 非常感谢，如同您举例：gost -L=dns://:53?dns=https-chain://1.1.1.1/dns-query -F=ss://chacha20:password@1.2.3.4:1234
> > 我的理解是：在本地将所有53端口的DNS查询转发至1.2.3.4服务器，然后 由1.2.3.4服务 器查询 1.1.1.1, 然后有了结果后，1.2.3.4再将结果返回到本地，我这样理解，对吗？
> 
> y，你可以设置一个错误的远端服务器地址作为对比，就会发现查询不到结果了

嗯 ，我明白了，但只是在这句配置里：gost -L=dns://:53?dns=https-chain://1.1.1.1/dns-query，53端口设置后，不起作用，改成1053后，DNS代理起作用了，但是如何将127.0.0.53:53端口的需求转发至127.0.0.1:1053? 需要端口映射 还是需要 dnsmasq? 多谢 指教，我的os是ubuntu 18.04 TLS.

**Comment by GeekDuanLian** [comment]
> > > 非常感谢，如同您举例：gost -L=dns://:53?dns=https-chain://1.1.1.1/dns-query -F=ss://chacha20:password@1.2.3.4:1234
> > > 我的理解是：在本地将所有53端口的DNS查询转发至1.2.3.4服务器，然后 由1.2.3.4服务 器查询 1.1.1.1, 然后有了结果后，1.2.3.4再将结果返回到本地，我这样理解，对吗？
> > 
> > 
> > y，你可以设置一个错误的远端服务器地址作为对比，就会发现查询不到结果了
> 
> 嗯 ，我明白了，但只是在这句配置里：gost -L=dns://:53?dns=https-chain://1.1.1.1/dns-query，53端口设置后，不起作用，改成1053后，DNS代理起作用了，但是如何将127.0.0.53:53端口的需求转发至127.0.0.1:1053? 需要端口映射 还是需要 dnsmasq? 多谢 指教，我的os是ubuntu 18.04 TLS.

你应该需要 sudo，小于 1024 端口的 root 才能用

**Comment by lyyx5858** [comment]
> 你应该需要 sudo，小于 1024 端口的 root 才能用

太感谢了，你太厉害了！剩下就是将系统的DNS 从127.0.0.53改为127.0.0.1,就行了

**Comment by perk67h6ins** [comment]
@GeekDuanLian 
你的意思是要开两个 gost 才能实现吗？

> 只是如果你已经开了一个远端协议转本地协议的，
> 比如
> gost -L=:1080 -F=ss://chacha20:password@1.2.3.4:1234
> 然后直接让dns走这个本地1080可能会更优雅一点

在这个远转本的协议基础上，怎么增加 dns over proxy 呢？谢谢
