### ISSUE TITLE
希望 ss 的混淆 simple_obfs_tls 支持 AEAD 加密模式

### ISSUE THREAD

**Issue by GeekDuanLian** [ginuerzh/gost#479]
服务器地址：1.2.3.4
服务器端口：1234
加密方式：chacha20-ietf-poly1305
密码：password
混淆：simple_obfs_tls
混淆参数：www.example.com

`gost -L=:1080 -F='ss+otls://AEAD_CHACHA20_POLY1305:password@1.2.3.4:1234?host=www.example.com'`

**Comment by ginuerzh** [comment]
目前不支持tls混淆

**Comment by GeekDuanLian** [comment]
> 目前不支持tls混淆

希望考虑增加此功能，谢谢

**Comment by lxf1992521** [comment]
justmysocks 只支持 obfs=tls 模式，希望考虑增加此功能

**Comment by lxf1992521** [comment]
希望增加支持 HAED 加密的 obfs=tls 模式，

**Comment by ginuerzh** [comment]
@lxf1992521 目前受`shadowsocks/go-shadowsocks2`库的实现限制(具体是shadowsocks/go-shadowsocks2#125)，暂无法支持AEAD。

**Comment by k79e** [comment]
https://github.com/Yee2/shadowsocks-go
这有个新的 不知道是不是和那个一样
