### ISSUE TITLE
tun/tap模式下无法启用ssu作为转发

### ISSUE THREAD

**Issue by ricky1203** [ginuerzh/gost#480]
ss server: 1.2.3.4:8388

on server:  gost -L 'tun://:4321?net=192.168.10.1/24'
on client: gost -L 'tun://:0/server_ip:4321?net=192.168.10.2/24' -F ssu://method:password@1.2.3.4:8388
这种情况无法工作，但是如果在client端拆成两条指令
1. gost -L 'tun://:0/:1234?net=192.168.10.2/24' 
2. gost -L udp://:1234/server_ip:4321 -F ssu://method:password@1.2.3.4:8388
这个就可以工作
是否可以在客户端一条指令就可以完成连接？

**Comment by ginuerzh** [comment]
下个版本会支持
