### ISSUE TITLE
多个后端会导致udp吃鸡无法进入，

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#483]
测试平台：ios

游戏：pubg mobile

代理客户端：shadowrocket

前端协议：ss+ssu

执行命令如下：

`gost -L="ss://rc4-md5:123456@:2381" -L="ssu://rc4-md5:123456@:2381" -F="ws://www.google.com:80" -F="ssh://user:123456@127.0.0.1:1122?ping=30"`

测试可以正常进游戏。

配置文件
peer1.json

```
strategy        round

max_fails       1

fail_timeout   30s

# period for live reloading
reload          10s

# peers

peer	ws://www.google.com:80?ip=19.147.134.4
peer	ws://www.google.com:80?ip=19.147.114.4
```

配置文件
peer2.json

```
strategy        round

max_fails       1

fail_timeout   30s

# period for live reloading
reload          10s

# peers
peer	ssh://user:123456@127.0.0.1:1122?ping=30
peer	ssh://user:123456@127.0.0.1:1122?ping=30
peer	ssh://user:123456@127.0.0.1:1122?ping=30
peer	ssh://user:123456@127.0.0.1:1122?ping=30
peer	ssh://user:123456@127.0.0.1:1122?ping=30
peer	ssh://user:123456@127.0.0.1:1122?ping=30
peer	ssh://user:123456@127.0.0.1:1122?ping=30
```
情况2：
`gost -L="ss://rc4-md5:123456@:2381" -L="ssu://rc4-md5:123456@:2381" -F="?peer=peer1.json" -F="ssh://user:123456@127.0.0.1:1122?ping=30"`

可以正常进入游戏。

情况3：

`gost -L="ss://rc4-md5:123456@:2381" -L="ssu://rc4-md5:123456@:2381" -F="?peer=peer1.json" -F="?peer=peer2.json"`

无法进入游戏

tcp不存在这样的问题，
测试结果，应该是负载均衡导致末端跟最初的前端的udp端口没有绑定一个，导致数据接收不到，

**Comment by f4nff** [comment]
如果是udp的话，前端的端口应该绑定末端的其中一个，不能轮询末端，
udp无链接，tcp也就不存在这样的情况，
但是多个连接才能争取更多的带宽，更好的容错性

**Comment by ginuerzh** [comment]
udp有类似于连接的通道概念，每一个请求对应一条通道，只要客户端的请求地址不变，通道不会变。但每个通道有超时时间，超时后通道会关闭。

**Comment by f4nff** [comment]
默认超时60s，进入吃鸡游戏，也只是2-5s的时间，不存在超时一说，
应该是多个隧道导致的混乱，单个隧道就没问题，
大神可以测测，

**Comment by freereaper** [comment]
确实有这个问题

**Comment by freereaper** [comment]
负载均衡，导致udp无法连接， 感觉转发地址没和tcp一样绑定。
udp.go:116: [udp] 171.41.70.58:31616 -> [::]:11422

**Comment by ginuerzh** [comment]
2.10.1之前是有问题，2.10.1中已经修复。

**Comment by freereaper** [comment]
我就是用的2.10.1的版本，接收端的版本也要更新么？

**Comment by ginuerzh** [comment]
@freereaper 你的具体使用方式是什么，LOG有什么异常？

2.10.1之前是由于最后一个节点认证问题导致无法连通，2.10.1中已经修复。
不过目前版本中UDP的缓冲大小限制在8192字节，如果发送的数据超过此大小也会失败。

**Comment by f4nff** [comment]
测试了下，ok 了，
