### ISSUE TITLE
snap安装的gost无法启动服务

### ISSUE THREAD

**Issue by scarletsakuya** [ginuerzh/gost#484]
系统：Debian GNU/Linux 10 (buster)
安装：apt-get install snapd
snap install gost
启动：gost -L :8080
报错：2020/02/07 07:36:11 main.go:88: listen tcp :8080: listen: operation not permitted
新的一台VPS，该怎么解决呢？

**Comment by ginuerzh** [comment]
需要安装`core`
```
sudo snap install core
```

**Comment by scarletsakuya** [comment]
安装core后可以启动了，谢谢！
麻烦更新下readme吧
