### ISSUE TITLE
DNS代理服务的运行模式支持 DNS over HTTPS (DoH, RFC 8484) 吗？

### ISSUE THREAD

**Issue by aitsc** [ginuerzh/gost#489]
“mode=https” 是指 DoH 吗？

**Comment by lyyx5858** [comment]
同问，能否再详细解释一下，DNS代理链的使用场景，比如：

gost -L=http://:8080?dns=8.8.8.8/udp-chain  -F=socks://remote_server:1080

上述用法，正常吗？DNS的解析是在本地还是在远端服务器？远端服务器解析时用的DNSf地址及协议是？
