### ISSUE TITLE
TCP透明代理部分网站无法打开

### ISSUE THREAD

**Issue by VictorSu000** [ginuerzh/gost#491]
版本：gost-linux-amd64-2.10.1
系统：CentOS Linux release 7.7.1908

过程：
```bash
./gost-linux-amd64-2.10.1 -L="red://:8997" -F="http://user:pass@server_ip:server_port"
```

设置iptables：
```bash
sudo iptables -t nat -A OUTPUT -p tcp --match multiport ! --dports 22,8997,29979 -j DNAT --to-destination 127.0.0.1:8997
```

iptables如下：
```bash
sudo iptables -L -t nat
```

![image](https://user-images.githubusercontent.com/18596923/74590536-3e39d180-504a-11ea-96e8-23c64a63b15e.png)

访问google play：
```bash
curl https://play.google.com/store
```

能够正常访问，gost输出如下：

![image](https://user-images.githubusercontent.com/18596923/74590568-8822b780-504a-11ea-896c-ed55e5953ab6.png)

访问google：
```bash
curl https://www.google.com
```

重复试了四次curl访问google，第一次正常，第二次第三次第四次提示证书不匹配

![image](https://user-images.githubusercontent.com/18596923/74590622-03846900-504b-11ea-9d04-7b6b67c1427f.png)
![image](https://user-images.githubusercontent.com/18596923/74590632-139c4880-504b-11ea-8788-a8530d6594b0.png)

这是为了复现专门截的图，尝试过好几次（也在不同系统尝试过）。结果均为：少部分网站可以访问（比如谷歌play），大部分访问不了的网站还是不能访问，其中部分会提示证书错误（之前试过duckduckgo.com也是，在浏览器看发现得到的是facebook的证书）。然而，访问ifconfig.me能网站查看IP，会发现IP已经变成了代理服务器的IP。

问题排查：
直接使用export https_proxy= 和 export http_proxy= 的方式设置代理的话一切正常。gost不使用透明代理而是使用
```bash
./gost-linux-amd64-2.10.1 -L=":8997" -F="http://user:pass@server_ip:server_port"
```
然后 ```export http_proxy=127.0.0.1:8997``` 的话也正常。

请问可以帮忙看下什么问题吗？万分感谢～

**Comment by yitong-ovo** [comment]
看看是不是 DNS 污染的问题。(GFW 会把 Google 之类的访问污染到 facebook 的服务器上。)

VictorSu000 <notifications@github.com> 于2020年2月15日周六 下午11:40写道：

**Comment by VictorSu000** [comment]
我想过这个问题，也试过
```bash
./gost-linux-amd64-2.10.1 -L="red://:8997?dns=8.8.8.8,1.1.1.1:53/tcp" -F="http://user:pass@server_ip:server_port"
```
但是没有效果。

我突然想到，会不会这样处理其实有问题？透明代理背后是iptables的转发，会不会在转发之前，系统已经完成了DNS的解析？

**Comment by rampageX** [comment]
明显是 DNS 问题，在 iptables 转发前本地已经解析了，iptables 只会处理 ip 转发。用

`curl --socks-hostname 代理地址:端口 https://www.google.com`

远程解析域名肯定就没问题。

要么另建防污染的 DNS 服务器，要么 iptables 也透明处理 UDP 53 的请求到代理服务器。

**Comment by VictorSu000** [comment]
是的，的确是DNS的问题，自建无污染的DNS服务器就可以了。谢谢！
