### ISSUE TITLE
请问怎么限制指定客户端IP能使用代理，并且支持热更新

### ISSUE THREAD

**Issue by gxlonline** [ginuerzh/gost#512]
新手学习，看了文档，不是太懂。

1、whitelist 和 blacklist ，是用来校验目标主机的，不是客户端IP？
2、bypass，也不是。

想搭建一个代理服务器，并且具备白名单功能，只能指定客户端（验证客户端IP是否在白名单内）能使用。
请指点下，谢谢。

**Comment by nic8888dsf** [comment]
iptables就可以做这个啊

**Comment by gxlonline** [comment]
已使用iptables，谢谢
