### ISSUE TITLE
请问将IP替换为域名后是怎样处理的？延迟会大大增加

### ISSUE THREAD

**Issue by ghost** [ginuerzh/gost#513]

**Comment by 643822883** [comment]
![IN~DNO9@(6D%)P XAPD)%X7](https://user-images.githubusercontent.com/33469503/76525082-2b2dec00-64a6-11ea-9615-788a15197ccf.png)

**Comment by ginuerzh** [comment]
对于GOST来说仅仅是多了一次DNS解析。
