### ISSUE TITLE
请问怎么样才能在systemctl/nohup内传递“?"后面的规则

### ISSUE THREAD

**Issue by wnark** [ginuerzh/gost#515]
我直接使用：
`gost -L sni://:443?in=500k&out=500k?whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443`
它能正常的限速并且实现白名单模式。

但我创建systemctl脚本或者是执行：
`nohup gost -L gost -L sni://:443?in=500k&out=500k?whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443 > /dev/null 2>&1 &`
后，限速与白名单就失去作用了。sni代理还是正常的。

**Comment by rampageX** [comment]
systemctl 脚本没必要用 nohup 去启动 gost 啊，它有自己的 failsafe 机制，你不想输出 log 加一句：
`StandardOutput=null` 就行了

**Comment by rampageX** [comment]
systemctl 脚本没必要用 nohup 去启动 gost 啊，它有自己的 failsafe 机制，你不想输出 log 加一句：
`StandardOutput=null` 就行了

**Comment by wnark** [comment]
> systemctl 脚本没必要用 nohup 去启动 gost 啊，它有自己的 failsafe 机制，你不想输出 log 加一句：
> `StandardOutput=null` 就行了

emmm我的意思是

单独在ssh内执行

`gost -L sni://:443?in=500k&out=500k?whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443`

能实现sni反代，并且拥有白名单和限速

但当我为了在后台运行时，使用
systemctl

```
[Unit]
Description=GO Simple Tunnel
After=network.target

[Service]
Type=simple
User=root
ExecStart=/usr/bin/gost -L sni://:443?in=500k&out=500k?whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443

[Install]
WantedBy=multi-user.target
```

或者是

`nohup gost -L gost -L sni://:443?in=500k&out=500k?whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443 > /dev/null 2>&1 &`

两种方式时，限速与白名单都没生效。

我不是为了不想输出log而同时使用了systemctl,nohup。

而是想让gost在实现sniproxy的同时，还有白名单与限速的功能

手动执行可以，但在systemctl或者是nohup内执行却不行

**Comment by wnark** [comment]
docker run -d -p 443:443 --name gost ginuerzh/gost -L="sni://:443?in=500k&out=500k?whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443"

在DOCKER里运行，也是sni代理正常，白名单失效

**Comment by k79e** [comment]
你是不是写错了
第一个用问号 后面不是其余所有都用&么
gost -L sni://:443?in=500k&out=500k**&**whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443

**Comment by wnark** [comment]
> 你是不是写错了
> 第一个用问号 后面不是其余所有都用&么
> gost -L sni://:443?in=500k&out=500k**&**whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443

原来是我写错了呀。。。demo里没有多个参数连在一起的配置demo，所以我照猫画虎写错了。

**Comment by wnark** [comment]
> 你是不是写错了
> 第一个用问号 后面不是其余所有都用&么
> gost -L sni://:443?in=500k&out=500k**&**whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443

请问`**&**`是这样连接而不是您多打了※？

**Comment by wnark** [comment]
> 你是不是写错了
> 第一个用问号 后面不是其余所有都用&么
> gost -L sni://:443?in=500k&out=500k**&**whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443

gost -L sni://:443?in=500k&out=500k&whitelist=tcp:www.baidu.com:443+tcp:baidu.com:443
你好，我测试了一下，白名单无效，不能限制使用的域名

**Comment by wnark** [comment]
in=500k&out=500k
是issue内的朋友臆想的功能。。。无效 被坑了
