### ISSUE TITLE
在openwrt路由器上做透明代理还有什么更好的方式实现特殊域名dns解析ip

### ISSUE THREAD

**Issue by lfznnzq** [ginuerzh/gost#517]
用的是dnamasq+ipset+iptables模式。

防火墙脚本如下:
ipset -N gfwlist iphash
iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345

dnsmasq配置如下
server=/google.com/127.0.0.1#5353
ipset=/google.com/gfwlist
server=/youtube.com/127.0.0.1#5353
ipset=/youtube.com/gfwlist

gost服务端运行命令
gost -L=socks5+mwss://user:password@:443

gost客户端运行命令
gost -L=udp://:5353/8.8.8.8:53  -L=red://:12345 -F=socks5+mwss://user:password@server_ip:443

这样是正常使用的，特殊域名dns解析ip是距离服务器最近的IP，访问也很快。

但是考虑用socks5+mwss模式比较容易被gfw封锁服务器IP，想改用http+wss模式。

尝试如下
gost服务端运行命令
gost -L=http+wss://:443

gost客户端运行命令
gost -L=red://:12345 -L="dns://:5353?mode=udp&dns=8.8.8.8:53" -F=http+wss://server_ip:443

这时候，特殊域名dns解析ip是在美国，访问时的速度就比较慢了。

请教还有什么方式能更好的实现特殊域名dns解析ip

**Comment by wendellou** [comment]
gost相对来说对性能要求比较高，不建议在路由器上使用gost，加解密会耗费大量性能导致有效数据传输效率降低很多。

**Comment by lfznnzq** [comment]
> gost相对来说对性能要求比较高，不建议在路由器上使用gost，加解密会耗费大量性能导致有效数据传输效率降低很多。

路由器用的是四核八线程E3 CPU，加解密没任何压力。

**Comment by rampageX** [comment]
监听 tcp 然后用个 udp 转 tcp 的工具比如 dns2tcp (https://github.com/zfl9/dns2tcp)

```
#配合 dnsmasq 监听 udp 但是转发 tcp 给上游：
dns2tcp -L 127.0.0.1:5353 -R 127.0.0.1:5352 

#gost服务端运行命令
gost -L=http+wss://:443

#gost客户端运行命令
gost -L=red://:12345 -L=tcp://:5352/8.8.8.8:53 -F=http+wss://server_ip:443
```

**Comment by lfznnzq** [comment]
> 监听 tcp 然后用个 udp 转 tcp 的工具比如 dns2tcp (https://github.com/zfl9/dns2tcp)
> 
> ```
> #配合 dnsmasq 监听 udp 但是转发 tcp 给上游：
> dns2tcp -L 127.0.0.1:5353 -R 127.0.0.1:5352 
> 
> #gost服务端运行命令
> gost -L=http+wss://:443
> 
> #gost客户端运行命令
> gost -L=red://:12345 -L=tcp://:5352/8.8.8.8:53 -F=http+wss://server_ip:443
> ```

测试了一下，特殊域名还是解析出美国的IP

**Comment by rampageX** [comment]
那就只有多监听一个本地的 socks5 服务，然后用 dns2socks 来处理了，这个支持 ecs 所以应该没问题。
