### ISSUE TITLE
希望可以添加一个端口转发功能

### ISSUE THREAD

**Issue by smounives** [ginuerzh/gost#52]
希望可以添加一个端口转发功能，这样就能利用一些不支持tcp只支持http的云平台通过Websocket转发端口

**Comment by ginuerzh** [comment]
这个功能可以考虑后面加上。

**Comment by smounives** [comment]
多谢！

**Comment by ginuerzh** [comment]
2.1版本中已经添加了端口转发功能，欢迎测试！

**Comment by ssfdust** [comment]
中秋快乐，今天还是好好休息吧。

2016年9月15日 09:40，"ginuerzh" <notifications@github.com>写道：

**Comment by ginuerzh** [comment]
在家闲着没事哈，中秋快乐

**Comment by smounives** [comment]
多谢作者，中秋快乐！
