### ISSUE TITLE
希望添加无控制台输出模式

### ISSUE THREAD

**Issue by cxlxkin** [ginuerzh/gost#522]
希望添加无控制台输出模式，谢谢

**Comment by k79e** [comment]
win下面 2>nul即可

**Comment by cxlxkin** [comment]
> win下面 2>nul即可

https://support.microsoft.com/zh-cn/help/110930/redirecting-error-messages-from-command-prompt-stderr-stdout
找到了，原来win也有类似>/dev/null 2>&1
谢谢
