### ISSUE TITLE
Certificate pinning

### ISSUE THREAD

**Issue by ofer-dev** [ginuerzh/gost#523]
When using quic the client does not verify the specified CA.
Lets say we have server.crt signed by goodCA and we also have badCA, representing broken certificate chain.

server:
gost -L=quic://:some_port?cert=server.crt?key=server.key

The client connect using both goodCA and badCA

gost -L=some_protocol -F=quic;//server_ip:some_port?keepalive=true?ca=goodCA.crt

gost -L=some_protocol -F=quic;//server_ip:some_port?keepalive=true?ca=badCA.crt

also fails to verify when specifing secure=true

gost -L=some_protocol -F=quic;//server_ip:some_port?keepalive=true?ca=goodCA.crt?secure=true

gost -L=some_protocol -F=quic;//server_ip:some_port?keepalive=true?ca=badCA.crt?secure=true

Is there any way to force certificate verification?

thx

**Comment by ofer-dev** [comment]
bump

**Comment by k79e** [comment]
果真是那样 我随便用了个证书 结果发现还能连接上...

**Comment by ofer-dev** [comment]
You are correct, after using & everything works as intended.
Thanks for this great tool.
