### ISSUE TITLE
自定义ua好像有bug

### ISSUE THREAD

**Issue by k79e** [ginuerzh/gost#525]
我用了ua参数写了个跟浏览器一样的ua
然后分析流量发现他被截断了

...&agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
![image](https://user-images.githubusercontent.com/6483602/77246771-64641a00-6c65-11ea-9e3e-df3f5f5d3bb1.png)

**Comment by ginuerzh** [comment]
See #409

**Comment by k79e** [comment]
原来如此
