### ISSUE TITLE
不知道这种网络环境如何配置了，试了很多

### ISSUE THREAD

**Issue by angrycans** [ginuerzh/gost#529]
我在公司内网 有个一个代理 可以访问外网 但是外网的google 不能访问。
white.txt 是内网域名
gost -L=:8888 -F=http://192?bypass=white.txt -F=ss:// 这样可以使用
但是所有的外网请求都从ss走了，我希望仅仅只有google的请求从ss走，该如何配置了

**Comment by ginuerzh** [comment]
在第二个-F=ss://上增加bypass白名单。

**Comment by angrycans** [comment]
gost -L=:8888 -F=http://192?bypass=white.txt -F=ss://?bypass=white2.txt
white2.txt 里面是
*.google.com
*.gstatic.com
我试过这样配置 似乎不行 日志显示的是
auto://:8888 -> 1@http://192:8080 -> 1@ss://45:8099 -> www.bing.com:443 
从页面的速度上面来看也是有点慢

**Comment by ginuerzh** [comment]
bypass默认是黑名单，需要加选项`reverse true`转成白名单。

**Comment by angrycans** [comment]
可以了
