### ISSUE TITLE
http+kcp，抓到的包不是http协议，为啥呢？

### ISSUE THREAD

**Issue by PHCSJC** [ginuerzh/gost#530]
版本：gost 2.10.1
服务端：gost -L=http+kcp://admin:admin@:443?tcp=true
客户端：gost -L=redirect://:1090 -F=http+kcp://admin:admin@*******:443?tcp=true

抓到的包是TCP协议的，不应该是http协议吗？where is wrong?
![QQ截图20200325132558](https://user-images.githubusercontent.com/22064544/77504983-d1152980-6e9c-11ea-85a7-552dffc27810.png)

**Comment by ginuerzh** [comment]
HTTP之前是要先进行KCP握手，你可以强制解码为HTTP协议试试。

**Comment by PHCSJC** [comment]
@ginuerzh 不会啊，怎么强制解码为http呢？

**Comment by ginuerzh** [comment]
kcp默认是加密的。

**Comment by lyyx5858** [comment]
> kcp默认是加密的。

wireshark目前好象没有可用的KCP插件。
