### ISSUE TITLE
路由表添加错误，

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#531]
`https://docs.ginuerzh.xyz/gost/tuntap/`

服务端：
`gost -L="tun://:8421?net=192.168.123.1/24"`

客户端
`gost -L “tun://:8421/157.233.11.22:8421?net=192.168.123.2/24&route=route.txt"`

route.txt
```
# Destination   Gateway

157.255.0.0/16  192.168.123.1
```

测试连接成功，
```
C:\Users\qq>ping 192.168.123.1

正在 Ping 192.168.123.1 具有 32 字节的数据:
来自 192.168.123.1 的回复: 字节=32 时间=40ms TTL=64
来自 192.168.123.1 的回复: 字节=32 时间=40ms TTL=64
来自 192.168.123.1 的回复: 字节=32 时间=39ms TTL=64
来自 192.168.123.1 的回复: 字节=32 时间=40ms TTL=64
```

但是路由表添加不对

log：

`netsh interface ip add route prefix=157.255.0.0/16 interface=以太网 store=active`

```
C:\Windows\system32>route print
===========================================================================
接口列表
 12...00 0c 29 ee a5 a5 ......Intel(R) 82574L Gigabit Network Connection
  8...00 ff 7e 4a 6a c5 ......TAP-Windows Adapter V9
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.2.1    192.168.2.161     25
       10.138.0.0      255.255.0.0            在链路上     192.168.123.2    281
   10.138.255.255  255.255.255.255            在链路上     192.168.123.2    281
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
      157.255.0.0      255.255.0.0            在链路上     192.168.123.2    281
  157.255.255.255  255.255.255.255            在链路上     192.168.123.2    281
```

只能手动删除，
然后执行

`route -p add 157.255.0.0 mask 255.255.0.0 192.168.123.1`

根据配置里面，
我已经写了网关是 192.168.123.1
但是写入到路由表里面依然是 192.168.123.2

**Comment by f4nff** [comment]
![image](https://user-images.githubusercontent.com/19538878/77517017-548f4480-6eb6-11ea-97cf-75eb82729470.png)

**Comment by f4nff** [comment]
服务端：
`gost -L="tun://:8421?net=192.168.123.1/24"`

客户端
`gost -L “tun://:8421/157.233.11.22:8421?net=192.168.123.2/24&route=route.txt"`

实现了基本功能，但是通信协议是udp的

如果通信协议是 ws 就好了，比如mws那种，

比如 
服务端：
`gost -L="tunmws://:80?net=192.168.123.1/24"`

客户端：
`gost -L “tunmws://:8421/?peer=?peer.txt&net=192.168.123.2/24&route=route.txt"`

route.txt

```
# strategy for node selecting
strategy        round

max_fails       1

fail_timeout   30s

# period for live reloading
reload          10s

# peers

peer	tunmws://www.qq.com:80?ip=219.147.134.1:80&path=/index.html
peer	tunmws://www.qq.com:80?ip=147.52.224.160:80&path=/index.html
peer	tunmws://www.qq.com:80?ip=219.141.134.1:80&path=/index.html
peer	tunmws://www.qq.com:80?ip=247.52.224.160:80&path=/index.html
```

gostvpn 如果支持websocket 握手，支持代理链，支持多连接，牛屁了，
如果支持这样就好了，可以取代openvpn，直接丢路由器里面，然后改下路由表就好了，
ss丢路由器里面贼不好用，tcp udp重定向很难配置。

**Comment by ginuerzh** [comment]
tun/tap是支持代理链的，由于是UDP，协议层只能用ssu/socks5/relay。
```
gost -L "tun://:0/:8421?net=192.168.123.2/24" -F relay+wss://SERVER_IP:PORT
```
当然还是可以利用KCP/QUIC等传输层来继续使用UDP
```
gost -L "tun://:0/:8421?net=192.168.123.2/24" -F relay+kcp://SERVER_IP:PORT
```
目前使用代理链不支持负载均衡。

**Comment by f4nff** [comment]
了解，但是原始协议是udp，需要多次转发，效率低
而且udp协议被qos，基本没法用，
如果支持我说的那种负载均衡，
真的可以取代openvpn

**Comment by ginuerzh** [comment]
tun/tap所转发的数据特性与UDP协议非常类似(无连接，无握手，无确认)，因此使用UDP是最理想的选择。
即使使用代理链，转发是在本地本地进行的，损耗与网络本身的延迟相比几乎可以忽略。
代理链的负载均衡后面会支持。

**Comment by f4nff** [comment]
虽然如此，但是实际测试中udp很垃圾，
iperf3测试我这边才10Mbps，
但是tcp直接200Mbps

openvpn实际用途中，默认udp，但是基本没法用，都用tcp
防火墙为了限制反射udp攻击，对udp很不友好，有些地方甚至基本上废弃的，

**Comment by f4nff** [comment]
多连接，长连接，tcp，限制每个tcp连接的带宽，
就像vpngate协议那样就完美了，
vpngate还可以设置每个连接的时效，
因为在互联网的传输中，突发速度快，但是长连接等一会会越来越慢，
断开重播之后，速度立马就快了。


`长连接，tcp，限制每个tcp连接的带宽，可以设置每个连接的时效，超过时效之后重新发起连接。`


就无敌了。

**Comment by f4nff** [comment]
vpngate里面那种实现比较麻烦，是把每个数据包进行编号，然后负载均衡使用几个tcp隧道进行全双工传输，然后再跟根据数据包编号合并，

这样就实现了几个连接合并带宽，而且还使用短链接避开了长连接被Qos的情况。

现在所有的vpn协议，连接一会就慢了，就是这个原因。

**Comment by f4nff** [comment]
`gost -L="tun://:8421?net=192.168.123.1/24" -L="relay+wss://:1722" -L="relay+wss://:1723" -L="relay+wss://:1724"`

`gost -L "tun://:0/127.0.0.1:8421?net=192.168.123.2/24" -F "relay+wss://160.191.221.7:1722?ip=160.191.221.7:1723,160.191.221.7:1724"`

测了下，通过这种方式，确实可以在互联网传输过程中使用websocket头，
但是，只有一个tcp连接，

不支持多并发，不支持多并发，那么隧道带宽就被qos限制，不能多连接叠加带宽，

**Comment by f4nff** [comment]
如果原生支持websocket ，并且支持多并发就好了，就像

均布荷载多个 mws协议那样。
