### ISSUE TITLE
关于tun/tap模式的一些题外话

### ISSUE THREAD

**Issue by cod1ingcoding** [ginuerzh/gost#535]
1. tuntap模式是不是数据传输的时候，数据在用户态、内核态多拷贝了一次？
2. gost貌似对内存需求比较高，普通路由器貌似都吃不消。

**Comment by f4nff** [comment]
没有1G内存不要想跑golang程序，

**Comment by ginuerzh** [comment]
1. 是的
2. 内存需求与使用模式和使用量都有关系，一般来说UDP会比TCP的内存消耗要大。
