### ISSUE TITLE
Socks5 client over socks5

### ISSUE THREAD

**Issue by srianand726** [ginuerzh/gost#536]
Hi,
We have socks5 proxy server available ,we were looking for client socks tls1.3 support from gost. Does gost works in client mode given that it has to communicate with socks proxy that supports TLS?
we are looking at initial handshake messages and read/write into ssl sockets.

Thanks,
Anand.S

**Comment by rampageX** [comment]
https://docs.ginuerzh.xyz/gost/socks/

> SOCKS5 negotiated encryption
> GOST supports the no-auth (0x00) and user-pass (0x02) methods of the standard SOCKS5 protocol, and on this basis, two extensions: tls (0x80) and tls-auth (0x82) are used for data encryption.
> 
> Server
> gost -L = socks5: //: 1080
> Client
> gost -L =: 8080 -F = socks5: // server_ip: 1080? notls = true
> If both ends are GOST (as above), the data transmission will be encrypted (the tls or tls-auth method is used for negotiation), otherwise the standard SOCKS5 is used for communication (no-auth or user / pass method).
> 
> notls-(2.9.1+) This parameter can disable negotiation encryption. Default value: false.

DONT KNOW TLS1.3 SUPPORT OR NOT.

BTW: Only for socks5 over tls(1.3) , maybe you should try `stunnel` (https://www.stunnel.org/static/stunnel.html)

**Comment by ginuerzh** [comment]
@srianand726 the scheme `socks5+tls` may meet your needs.
