### ISSUE TITLE
文档中的透明代理无效

### ISSUE THREAD

**Issue by DDCHlsq** [ginuerzh/gost#551]
环境为树莓派4B Rapbian系统
执行
`gost -L red://:12345 -F ss://cypher:passwd@:ip:port`
`iptables -t nat -A OUTPUT -p tcp --match multiport ! --dports 12345,port -j DNAT --to-destination 127.0.0.1:12345`
再将树莓派地址设置为网关，结果完全无效，运行gost后没有出现任何debug信息，无法访问任何网站，而`arp -a`表示我的设备将树莓派设置为网关之后是成功连接的

**Comment by f4nff** [comment]
`nohup ./gost -L=red://:12345 -F="ssh://122.224.208.3:80?ping=30" &`
`iptables -t nat -A OUTPUT -p tcp --match multiport ! --dports 12345,80 -j DNAT --to-destination 127.0.0.1:12345`

测试成功，

但是80端口就没走透明代理，
如何设置ip:port 例外，而不是只靠端口识别呢？

**Comment by f4nff** [comment]
```
iptables -t nat -N TCPNAT
iptables -t nat -A TCPNAT -d 122.224.208.12 -j RETURN
iptables -t nat -A TCPNAT -p tcp -j RETURN -m mark --mark 0xff
iptables -t nat -A TCPNAT -p tcp -j REDIRECT --to-ports 12345
iptables -t nat -A PREROUTING -p tcp -j TCPNAT
iptables -t nat -A OUTPUT -p tcp -j TCPNAT
```

搞定

**Comment by f4nff** [comment]
```
nohup ./gost -L=red://:12345 -F="ssh://122.224.208.3:80?ping=30" &
iptables -t nat -A OUTPUT -p tcp --match multiport ! --dports 12345,80 -j DNAT --to-destination 127.0.0.1:12345
```

测试成功，
但是有一点不明白，为什么122.224.208.3（服务端）-->>--101.227.22.22:12345（本地） 创建了2000多个tcp连接？
