### ISSUE TITLE
隧道转发端口过多，服务连接数过多导致严重断流

### ISSUE THREAD

**Issue by leif-Zhang** [ginuerzh/gost#567]
确认服务器性能和网络没有问题。
在隧道转发的功能中，如果有30个转发端口处于运行状态，并且总服务器连接数达到1000，会导致严重断流，如: 打开网站需要刷新多次，进入到网站会出现无法完全加载内容的情况。
断流的时候，服务器报错日记中提示too many open files. 我已经把Limited数量之类的优化到很高了，但依然会出现这种问题。
请问有什么解决方法吗？

**Comment by leif-Zhang** [comment]
> 确认服务器性能和网络没有问题。
> 在隧道转发的功能中，如果有30个转发端口处于运行状态，并且总服务器连接数达到1000，会导致严重断流，如: 打开网站需要刷新多次，进入到网站会出现无法完全加载内容的情况。
> 断流的时候，服务器报错日记中提示too many open files. 我已经把Limited数量之类的优化到很高了，但依然会出现这种问题。
> 请问有什么解决方法吗？

**Comment by horsegitted** [comment]
遇到同样的问题，为啥直接close了呀，搞定了吗？@Assumption-leif

**Comment by ZMer2019** [comment]
如何解决的？
