### ISSUE TITLE
建议:建议添加日志直接到文件功能，而不是使用重定向(>)。

### ISSUE THREAD

**Issue by proxy666-dev** [ginuerzh/gost#575]
建议:建议添加日志直接到文件功能，而不是使用重定向(>)。简书例子:https://www.jianshu.com/p/51995fb2b42a

**Comment by proxy666-dev** [comment]
关联issues:https://github.com/ginuerzh/gost/issues/574

**Comment by proxy666-dev** [comment]
https://github.com/ginuerzh/gost/pull/600

**Comment by ginuerzh** [comment]
重定向有什么问题吗？

**Comment by proxy666-dev** [comment]
> 重定向有什么问题吗？

我仔细找了原因，重定向没有问题，有问题的是gost 的日志没有输出到标准输出，导致重定向没有日志内容。

**Comment by proxy666-dev** [comment]
> 重定向有什么问题吗？

相关issues:https://github.com/ginuerzh/gost/issues/574

**Comment by proxy666-dev** [comment]
> 重定向有什么问题吗？

我简单搞了PR:https://github.com/ginuerzh/gost/pull/600

**Comment by proxy666-dev** [comment]
> > 重定向有什么问题吗？
> 
> 我仔细找了原因，重定向没有问题，有问题的是gost 的日志没有输出到标准输出，导致重定向没有日志内容。

这问题很久就存在了。

**Comment by ginuerzh** [comment]
目前日志是写到标准错误流，不再考虑增加额外命令行参数。

**Comment by proxy666-dev** [comment]
> 目前日志是写到标准错误流，不再考虑增加额外命令行参数。

为啥不写到标准输出流？

**Comment by proxy666-dev** [comment]
> 目前日志是写到标准错误流，不再考虑增加额外命令行参数。

多一种选择，满足一些人。

**Comment by lovitus** [comment]
> > 目前日志是写到标准错误流，不再考虑增加额外命令行参数。
> 
> 为啥不写到标准输出流？

2>&1 把stderr转发到stdout就行

**Comment by proxy666-dev** [comment]
> > > 目前日志是写到标准错误流，不再考虑增加额外命令行参数。
> > 
> > 
> > 为啥不写到标准输出流？
> 
> 2>&1 把stderr转发到stdout就行

有效？

**Comment by xiaokaixuan** [comment]
@proxy666-dev 日志写入错误流本身是常规做法。你可以用 >file.log 2>&1 将错误流重定向到标准输出流。

**Comment by shynome** [comment]
日志分等级的, 错误日志才写入错误流, gost目前是把所有的日志都写入了错误流

**Comment by SeaHOH** [comment]
> > 目前日志是写到标准错误流，不再考虑增加额外命令行参数。
> 
> 为啥不写到标准输出流？

今天突然想明白了，因为标准输出流是用于输出结果的，而日志不属于结果。日志是有个错误等级，但这和标准错误流没有任何必然联系。
