### ISSUE TITLE
HTTP代理无法使用密码验证

### ISSUE THREAD

**Issue by DDCHlsq** [ginuerzh/gost#583]
使用 gost -L http://usr:pswd@:port
或 gost -L usr:pswd@:port
建立代理之后，再使用客户端连接（尝试过包括Nintendo Switch代理设置iOS端Potatso Lite）均无效，服务端报authentication required。

**Comment by pscj** [comment]
同问，有计划支持这个功能吗，也是switch想用

**Comment by tubitzee** [comment]
https 代理同样有这个问题。

**Comment by mixool** [comment]
运行方式`-L="http2://admin:passwd@:443?probe_resist=code:501&knock=www.bing.bing&cert=/etc/gost/gost.crt&key=/etc/gost/gost.key"`
同样有这个问题，随意填写账号密码都能使用这个代理，希望能解决

@ginuerzh
