### ISSUE TITLE
客户端无法直接连接HTPPS模式代理

### ISSUE THREAD

**Issue by wen11497110** [ginuerzh/gost#589]
服务端配置:
-L "http2://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}&probe_resist=code:404"
服务端日志
![image](https://user-images.githubusercontent.com/10792245/82466989-b0133280-9af3-11ea-80de-213e6bcaf7f4.png)
ps. 不知道有没有更详细点的日志选项
客户端使用SwitchyOmega的HTTPS代理模式
访问谷歌出现
![image](https://user-images.githubusercontent.com/10792245/82467187-f799be80-9af3-11ea-8e8e-117c068e15c7.png)

请问有大佬出现这种情况嘛

我在本地用gost再启一个ss服务转发到远程https代理服务端, 客户端连ss服务就是正常的, 不知道为什么直接用https模式代理不行

**Comment by tychusyuan** [comment]
需要你在本地再启动一个gost客户端，-F 配置到你的服务端

**Comment by wen11497110** [comment]
关闭探测防御的probe_resist=code:404参数后可以直接使用https的代理了

**Comment by haoel** [comment]
我在我的这份文档里说了，参看这个change：
https://github.com/haoel/haoel.github.io/commit/87b7991cf39fb399e67e6e62c4089dfea2abf716

**Comment by wen11497110** [comment]
感谢浩叔^_^
