### ISSUE TITLE
能否编译一个android命令行可执行程序

### ISSUE THREAD

**Issue by edveen** [ginuerzh/gost#59]
能否编译一个android命令行可执行程序，如果能编译一个apk就更好

**Comment by virteman** [comment]
交叉编译个arm 的就行.
`cd cmd/gost
OS=linux GOARCH=arm go build -o /tmp/gost
file /tmp/gost 
 `

**Comment by ginuerzh** [comment]
2.6版本中可以使用自定义证书文件来替代默认的随机证书，可以省去证书生成这一步。

**Comment by xausky** [comment]
做了一个Shadowsocks客户端上用Gost的插件，欢迎试用：https://github.com/xausky/ShadowsocksGostPlugin
