### ISSUE TITLE
请问relay 隧道功能怎么支持后端应用获取IP？

### ISSUE THREAD

**Issue by echoowall** [ginuerzh/gost#593]
搭建了relay隧道模式，后端应用获取到的IP就都是127.0.0.1了，有什么方法能让后端应用正常获取前端传过来的客户端流量的IP吗？

**Comment by ginuerzh** [comment]
这是上层应用协议考虑的问题，例如隧道两端通过HTTP请求头部信息来获取客户端IP。

**Comment by humorwang** [comment]
> 这是上层应用协议考虑的问题，例如隧道两端通过HTTP请求头部信息来获取客户端IP。

但现实情况是应用层双方有一方不受开发者控制，这就很难达成一致，比较好的做法是希望可以像nginx一样可以在配置中加入header供后端获取ip

**Comment by uuiazusaouiha** [comment]
> 这是上层应用协议考虑的问题，例如隧道两端通过HTTP请求头部信息来获取客户端IP。

希望gost能够集成这个功能，就像haproxy的Proxy protocol，后端应用就能直接获取客户端IP了
