### ISSUE TITLE
建议更新一下 Quic

### ISSUE THREAD

**Issue by soffchen** [ginuerzh/gost#594]
quic-go 已经落后上游有两年了 :)

**Comment by pynne** [comment]
是的，强烈更新。。。

**Comment by ginuerzh** [comment]
QUIC由于处于快速开发阶段，接口变动比较大，且不向后兼容，暂时不会跟进。

**Comment by crawt** [comment]
http3规范不是发了吗？可以直接走http3了

**Comment by cute** [comment]
quic-go 落后3年了，最新版本 v0.24.0。
gost 当前使用的是 2018 年的 0.10.0 版本。
