### ISSUE TITLE
关于负载均衡

### ISSUE THREAD

**Issue by ec000** [ginuerzh/gost#599]
round - 轮询，random - 随机, fifo - 自上而下
函数
func (s *FIFOStrategy) Apply(nodes []Node) Node
中，在选择node的时候，如果node队列不为空的时候，返回的是return nodes[0]，这个fifo方式的均衡负载是不是就没有意义了。
我现在想做的是，默认连接node队列中的第一个node（主node），如果达到max_fails的时候再切换，fail_timeout 之后再次尝试连接 主node
 有没有什么办法，或者代码实现的思路

**Comment by ginuerzh** [comment]
fifo就是主备模式。

**Comment by ec000** [comment]
> fifo就是主备模式。

我现在主服务器重传高，带宽高，备用节点重传低，带宽低，除了将max_fails设置较大值还有什么其他检测办法没，这个max_fails是否有个最大值
