### ISSUE TITLE
请问作为代理服务器时，支持用户密码认证麽？

### ISSUE THREAD

**Issue by jzp820927** [ginuerzh/gost#6]
请问，服务器端兼容标准的socks5协议, 可直接用作socks5代理, 并额外增加协商加密功能。在直接作为 socks5代理时，能支持用户密码认证吗？也就是说我在分享给朋友这个代理时，能否提供认证功能？
包括客户端，在作为代理提供时，是否也能提供认证功能，这样在分享时，能避免被滥用。

**Comment by ginuerzh** [comment]
目前不支持，后续会考虑添加

**Comment by ginuerzh** [comment]
1.7版已支持认证

**Comment by jzp820927** [comment]
非常感谢，我马上试试
