### ISSUE TITLE
Proposal of obfuscating extension 

### ISSUE THREAD

**Issue by madeye** [ginuerzh/gost#60]
First of all, thanks for this great tool!

I've a proposal about adding obfuscating tunnel, such as TCP tunnel with HTTP GET/POST, to cheat on QoS and DPI. In addition, with the flexibility to configure host/user-agent/SNI we may hide the real traffic in a more "normal" traffic even better.

**Comment by ginuerzh** [comment]
Any more docs about this technical detail?

**Comment by ginuerzh** [comment]
I found the repo `simple-obfs`, I think that's what you mentioned here.
I checked the code, it supports two obfs types: http(actually websocket) and tls, so what is the difference between the ws/tls obfs tunnel and TCP over ws/tls? I think there is no difference except some header fields.

**Comment by madeye** [comment]
Right. They are almost the same from data flow's point of view. The reason we have two variants here is that different ISP would have different QoS settings, so that users can try different header obfuscations as he like.

**Comment by madeye** [comment]
Thanks!

**Comment by jzp820927** [comment]
说到 TCP tunnel with HTTP GET/POST，我也有个建议，希望能实现，那就是集成 meek 技术。
文档：https://trac.torproject.org/projects/tor/wiki/doc/meek
源码：https://gitweb.torproject.org/pluggable-transports/meek.git
希望作者能考虑添加 meek，非常实用。

**Comment by ginuerzh** [comment]
这种方法，我之前也尝试过([https://github.com/ginuerzh/pht](https://github.com/ginuerzh/pht))，就是只利用HTTP的GET和POST来传输数据，但效果不理想，每一次的数据发送都要建立一个新的连接。

目前我在实现SNI的时候，顺便也加入了域名混淆，效果可能会好一点。

**Comment by jzp820927** [comment]
好吧，那等 sni 功能出来了，看看再说吧，谢谢回复。
