### ISSUE TITLE
如何提升wget下载速度？

### ISSUE THREAD

**Issue by PatHoo** [ginuerzh/gost#601]
我有一台美国的VPS，在这台主机上用wget下载美国站点的文件非常快，请问怎么让我本地的wget下载美国站点的文件也快起来呢？需要配置成哪个模式？
我是这么干的，VPS设置http2模式。本地设置代理：gost -L=socks://0.0.0.0:8888 -F=http2://VPS... ；安装proxychains转发到本地的8888端口。 
然后命令下载文件：proxychains wget XXX；这个下载速度只有几十KB，怎么才能提升速度呢？

**Comment by 2378** [comment]
只有推到防火墙才能解决，或者半夜3、4点起床，那时速度还可以

**Comment by banyet1** [comment]
通过HK中转到美国能有很大提升。

**Comment by zz5678** [comment]
两个方法，都可行：
1，用Email协议发到国内支持大附件邮箱，再下载
2，先下载到vps，再多线程下载挤压国际出口
还有用kcp等超量发包方法冲关，用 cloudflare 中转

另外，首先确定，你已经在海外 vps 上安装了BBR 等协议
