### ISSUE TITLE
多端口监听和转发问题

### ISSUE THREAD

**Issue by banyet1** [ginuerzh/gost#602]
gost -L=:IN1 -F=http2://server1:port -L=:IN2 -F=http2://server2:port 实际上和
gost -L=:IN1 -F=http2://server1:port -F=http2://server2:port 
作用一样，最后都是通过Server1-Server2转发流量。

建议第一种写法的作用是开多端口，每个端口转发链是独立的，这样的好处在于客户端可以只用一个gost进程就能分别连接多个不同Server。

**Comment by ginuerzh** [comment]
多端口独立转发请使用配置文件。

**Comment by ClericPy** [comment]
```json
{
    "Debug": false,
    "Retries": 0,
    "ServeNodes": [],
    "ChainNodes": [],
    "Routes": [
        {
            "Retries": 1,
            "ServeNodes": ["http://127.0.0.1:7777"],
            "ChainNodes": [
                "http://a:b@c:d"
            ]
        }
    ]
}

```

感谢二位, 以上配置 OK, 之前配 v2ray 各种连不上, 这边一次成功!

**Comment by hookover** [comment]
> Server1

有配置示例嘛
docker
