### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by banyet1** [ginuerzh/gost#604]
gost -L=ss://aes-256-cfb:pass@:port -F=http2://overseaserver:port

用SS做前端，打开Youtube, 4K 视频，不到一分钟就不再工作，除非重启gost.

Memory access violation? 

check plz.

**Comment by f4nff** [comment]
http2协议是多路复用协议，
http2协议没有心跳机制，
半路连接挂了，但是连接状态还在，
然后就一直卡着不动了，所以只能通过重启进程强制断开连接，
很早很早之前的问题了，

**Comment by f4nff** [comment]
https://github.com/golang/go/issues/31643

**Comment by banyet1** [comment]
Not this case

如果这样，就没有问题，所以我判断是ss做前端的问题。

gost -L=:8080 -F=http2://overseaserver:port

**Comment by f4nff** [comment]
```
gost -L=ss://aes-256-cfb:pass@:port -F=ssh://overseaserver:port?ping=10
gost -L=ss://aes-256-cfb:pass@:port -F=mwss://overseaserver:port
```

这样都没事，说了还不信，我可以100%复现，

**Comment by f4nff** [comment]
tcp在nat转发层会出现死链（内网尤其移动网概率最高），连接状态正常，tcp自身的keepalive也正常，但是这个连接数据就是不通，只能在应用层设置心跳机制，心跳超时，client强制主动断开，等下次请求的时候发起新的连接。

**Comment by banyet1** [comment]
http2 gost Crash，程序崩溃了，和协议本身无关。
回头我把日志贴出来。

**Comment by banyet1** [comment]
ss和http2短时间运行无问题，客户端redirect模式超不过5小时必然Crash, 有日志，回头我贴出来。
和http2协议无关。
