### ISSUE TITLE
请教组合传输层的问题

### ISSUE THREAD

**Issue by amu1680c** [ginuerzh/gost#606]
使用组合传输层时，比如ss+kcp时，如何设置kcp参数？貌似直接加？设置无效

**Comment by ginuerzh** [comment]
```
gost -L=kcp://:8388?c=/path/to/conf/file
```

**Comment by amu1680c** [comment]
我说的是这一条
Shadowsocks Over KCP
gost -L ss+kcp://chacha20:123456@:8338
如何添加kcp的参数，试过kcp.json和?mode=normal crypt=none均无法连接

**Comment by tournet** [comment]
关注一下
