### ISSUE TITLE
指定加密算法的TUN UDP隧道只通一个包，然后丢失连接

### ISSUE THREAD

**Issue by missyoyo** [ginuerzh/gost#607]
作者你好：
我这边有两台测试电脑
10.10.10.66
10.10.10.14
udp 隧道地址默认

192.168.123.1
192.168.123.2
使用普通的未加密UDP 隧道通信没有问题，使用加密协议AEAD_CHACHA20_POLY1305，ping只能通一个包，然后就不行了
Server 10.10.10.66
gost -L "tun://AEAD_CHACHA20_POLY1305:init1234@10.10.10.66:8421?net=192.168.123.1/24" -D
Client 10.10.10.14
gost -L "tun://AEAD_CHACHA20_POLY1305:init1234@:8421/10.10.10.66:8421?net=192.168.123.2/24"

ping测试：
dhb@ubuntu1401:~$ ping -I tun0 192.168.123.1
PING 192.168.123.1 (192.168.123.1) from 192.168.123.2 tun0: 56(84) bytes of data.
64 bytes from 192.168.123.1: icmp_seq=1 ttl=64 time=1.40 ms
然后就没有了，客户端口跟服务器都报告错误：
Server:
2020/06/15 23:06:38 tuntap.go:206: [tun] 192.168.123.1: listen udp 10.10.10.66:8421: bind: address already in use
Client:
2020/06/15 23:06:51 tuntap.go:206: [tun] 192.168.123.2: listen udp :8421: bind: address already in use
请问有办法修正吗？
另外请教一个问题如果使用TUN VPN模式，服务器跟客户端的流量可以支持TLS吗（tcp=true）？有劳解答，非常感谢。

**Comment by ginuerzh** [comment]
tun可以使用relay配合传输层协议进行中转：
```
gost -L "tun://:0/10.10.10.66:8421?net=192.168.123.2/24" -F relay+tls://IP:443
```
