### ISSUE TITLE
建议考虑增加透明代理

### ISSUE THREAD

**Issue by douglas-lee** [ginuerzh/gost#61]
建议考虑增加透明代理，这样就可以省去redsocks了，直接用gost建立一个透明代理给iptables用。

**Comment by linhua55** [comment]
望早日增加透明代理，透明代理利用了 iptables 的 connection tracking 功能来获得 原来的ip地址和端口。可参考
https://unix.stackexchange.com/questions/166692/how-does-a-transparent-socks-proxy-know-which-destination-ip-to-use
https://github.com/ryanchapman/go-any-proxy/blob/master/any_proxy.go#L463

**Comment by ginuerzh** [comment]
2.3-rc1中已经支持透明代理
