### ISSUE TITLE
开启多路复用后出现掉速断流问题

### ISSUE THREAD

**Issue by kzw200015** [ginuerzh/gost#613]
开启多路复用，多线程下载，一开始速度正常，几秒后就会掉速至几百k/s，甚至出现断流；关闭多路复用后一切正常
我看到一个issue中也有人反馈这个问题 https://github.com/ginuerzh/gost/issues/540
希望作者能解决一下，谢谢

**Comment by ginuerzh** [comment]
后面会优化
