### ISSUE TITLE
GOST安装后的默认SSL证书会直接暴露GOST特征

### ISSUE THREAD

**Issue by NyaRabbit** [ginuerzh/gost#615]
![-5c54cf6b70a8b9cb](https://user-images.githubusercontent.com/53127913/86513622-4e5a1e00-be3e-11ea-82f3-1d79d2dc9621.png)

如图，在一台新服务器上安装后，它默认的SSL直接写了GOST四个字母。

建议是随机生成SSL证书。

**Comment by shellus** [comment]
我觉得不用改，nginx安装后还默认有nginx的header呢
gost是一个网络工具，不是一个gfw工具，没必要故意隐藏特征

**Comment by NyaRabbit** [comment]
> 
> 
> 我觉得不用改，nginx安装后还默认有nginx的header呢
> gost是一个网络工具，不是一个gfw工具，没必要故意隐藏特征

这样的嘛？那好吧
