### ISSUE TITLE
 net/url: invalid userinfo

### ISSUE THREAD

**Issue by marklove5102** [ginuerzh/gost#622]
系统：arch
版本：gost-linux-amd64-2.11.1.gz
./gost-linux-amd64 -L=:8080 -F=ss://'RC4':'dongtaiwangcom 123abc'@'162.245.239.68':'34567'
                       不管是用‘或者“ 都 出错
密码不能带空格。
错误内容：
main.go:88: parse "ss://RC4:dongtaiwangcom 123abc@162.245.239.68:34567": net/url: invalid userinfo

**Comment by marklove5102** [comment]
main.go:88: parse "ss://RC4:dongtaiwangcom 123abc@162.245.239.68:34567": net/url: invalid userinfo

**Comment by ginuerzh** [comment]
试试`auth`参数(https://docs.ginuerzh.xyz/gost/configuration/#auth-292)

```
$ base64 -
RC4:dongtaiwangcom 123abc
UkM0OmRvbmd0YWl3YW5nY29tIDEyM2FiYw==
```
```
$ gost -L=:8080 -F=ss://162.245.239.68:34567?auth=UkM0OmRvbmd0YWl3YW5nY29tIDEyM2FiYw==
```

**Comment by marklove5102** [comment]
auth 测试
RC4 ss.go:605: [ss] cipher not supported  不能上网，目测没这算法了。 好像新的只有rc4-md5？ 蛋疼

aes-256-gcm 测试没问题 可以上网
