### ISSUE TITLE
请问透明代理到v2ray的socks5时gost命令该如何写？

### ISSUE THREAD

**Issue by t66y100** [ginuerzh/gost#626]
gost运行在192.168.1.1。
v2ray运行在192.168.1.2，inbounds为socks5，开启udp，端口1080。

现在需要iptables透明把192.168.1.1的gfwlist流量通过gost的12345转发到192.168.1.2的1080。

gost命令我照搬wiki：
gost -L red://:12345 -F 192.168.1.2:1080
gost -L redu://:12345?ttl=60s -F ssu://192.168.1.2:1080

但是不通。

之前用ipt2socks是通的，iptables规则应该没有问题。

请问是不是gost命令不对呢？该如何修改？

谢谢！

**Comment by t66y100** [comment]
搞明白了，192.168.1.2:1080要加socks5://

**Comment by kingwilliam** [comment]
https://docs.ginuerzh.xyz/gost/socks/

**Tunnel UDP over TCP
"如果要转发SOCKS5的BIND和UDP请求，代理链的末端(最后一个-F参数)必须是GOST SOCKS5类型代理。"**

估计是 gost proxy chain 由第一个 -F 之後已经是 "udp over tcp" 所以中间可经过N个 不同的tcp proxy都可以 但最後出口一定要是 GOST 才可分离udp.

我入墙流程  -(tcp/udp)-> tproxy -> v2 -(socks5 tcp/udp +ws)-> gost -(tls+ws)-> (GFW) -> haproxy -(ws)-> gost -(tcp/udp)->
所以如要用gost, gost要放最後


但是 gost -(socks5 tcp)-> v2 socks5 这可以
但是 gost -(socks5 udp)-> v2 socks5 是不行

如您一定要gost入v2, 可试试 gost(socks5 tcp/udp) -> v2 dokodemo.

可否详述您的流程 为何要gost socks5 -> v2?

**Comment by t66y100** [comment]
> https://docs.ginuerzh.xyz/gost/socks/
> 
> **Tunnel UDP over TCP "如果要转发SOCKS5的BIND和UDP请求，代理链的末端(最后一个-F参数)必须是GOST SOCKS5类型代理。"**
> 
> 估计是 gost proxy chain 由第一个 -F 之後已经是 "udp over tcp" 所以中间可经过N个 不同的tcp proxy都可以 但最後出口一定要是 GOST 才可分离udp.
> 
> 我入墙流程 -(tcp/udp)-> tproxy -> v2 -(socks5 tcp/udp +ws)-> gost -(tls+ws)-> (GFW) -> haproxy -(ws)-> gost -(tcp/udp)->
> 所以如要用gost, gost要放最後
> 
> 但是 gost -(socks5 tcp)-> v2 socks5 这可以
> 但是 gost -(socks5 udp)-> v2 socks5 是不行
> 
> 如您一定要gost入v2, 可试试 gost(socks5 tcp/udp) -> v2 dokodemo.
> 
> 可否详述您的流程 为何要gost socks5 -> v2?

感谢回答。
不行就不转发udp了，其实用不上，就是强迫症。

**Comment by t66y100** [comment]
> https://docs.ginuerzh.xyz/gost/socks/
> 
> **Tunnel UDP over TCP "如果要转发SOCKS5的BIND和UDP请求，代理链的末端(最后一个-F参数)必须是GOST SOCKS5类型代理。"**
> 
> 估计是 gost proxy chain 由第一个 -F 之後已经是 "udp over tcp" 所以中间可经过N个 不同的tcp proxy都可以 但最後出口一定要是 GOST 才可分离udp.
> 
> 我入墙流程 -(tcp/udp)-> tproxy -> v2 -(socks5 tcp/udp +ws)-> gost -(tls+ws)-> (GFW) -> haproxy -(ws)-> gost -(tcp/udp)->
> 所以如要用gost, gost要放最後
> 
> 但是 gost -(socks5 tcp)-> v2 socks5 这可以
> 但是 gost -(socks5 udp)-> v2 socks5 是不行
> 
> 如您一定要gost入v2, 可试试 gost(socks5 tcp/udp) -> v2 dokodemo.
> 
> 可否详述您的流程 为何要gost socks5 -> v2?
不过透明代理 gost -L red://:12345，这入口的12345应该不算是socks5吧？
