### ISSUE TITLE
gost kcp模式断流问题

### ISSUE THREAD

**Issue by PHCSJC** [ginuerzh/gost#627]
花了不少时间挨个版本测试的
v2.3-2.6.1版本的kcp均正常不断流。
v2.7.0-2.11.1版本全部断流。

测试方法是：ssh配置代理，连本地gost，本地gost连到国外的gost服务端，ssh连上国外的服务器后1-10分钟就断了。

本地配置：
{
    "key": "it's a secrect",
    "crypt": "aes",
    "mode": "fast2",
    "mtu" : 1200,
    "sndwnd": 1024,
    "rcvwnd": 2048,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 30,
    "scavengettl":3600,
    "snmplog": "",
    "snmpperiod": 60
}
本地启动命令：
gost -L=redirect://:1090 -F=kcp://******:*******@*****:4000?c=gost.conf

服务器端配置：
{
    "key": "it's a secrect",
    "crypt": "aes",
    "mode": "fast2",
    "mtu" : 1200,
    "sndwnd": 2048,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 30,
    "scavengettl":3600,
    "snmplog": "",
    "snmpperiod": 60
}
服务器端启动命令：
gost -L=kcp://******:*******@:4000?c=gost.conf

**Comment by PHCSJC** [comment]
又测试了下，客户端用2.6.1版本，服务端用2.11.1版本，不会断流。
二边都用2.11.1就会断流。

**Comment by ayucapal** [comment]
相同情况 1-10分钟就会断流10秒-1分钟不等, 然后恢复

**Comment by 110560** [comment]
我是这个断流....Frelay+mws
断流大概。30秒左右  然后又自己恢复了
请问大佬们什么版本稳定

**Comment by 110560** [comment]
> 相同情况 1-10分钟就会断流10秒-1分钟不等, 然后恢复

请问你用的什么协议和加密。

**Comment by lyyx5858** [comment]
UDP运营商限速，与软件无关。

**Comment by PHCSJC** [comment]
> UDP运营商限速，与软件无关。
你就瞎说吧你

**Comment by PHCSJC** [comment]
测试了最新的2.11.2，还是有断流问题
https://github.com/go-gost/gost/issues/16

**Comment by ginuerzh** [comment]
v2.6与v2.7版本kcp-go是一个大版本升级，目前不确定是否是kcp-go兼容性问题所致。

**Comment by PHCSJC** [comment]
期待大佬早日解决，我一会一直测试的

**Comment by ginuerzh** [comment]
我这边的测试下来，`keepalive`和`interval`两个参数会影响空闲连接。
`mode`如果不是`manual`，`interval`的值会被强制设置为固定值，`fast2`模式下为20。`keepalive`这时如果小于`interval`(例如10)则连接是稳定的，具体二者关系没有仔细去研究。

可以拿[xtaci/kcptun](https://github.com/xtaci/kcptun)做对比，gost中kcp实现基本与kcptun一样。

**Comment by PHCSJC** [comment]
试了最新的v3 beta2，relay+kcp模式，挂了10个小时的ssh（走代理）没有断，已经没有断流的问题了，非常感谢！
