### ISSUE TITLE
wss 协议的证书锁定无效

### ISSUE THREAD

**Issue by luyuhuang** [ginuerzh/gost#629]
版本: gost 2.11.1 (go1.14.2 linux/amd64)

重现步骤:

- 随意生成一个证书 `server.crt`
- 使用 `./gost -L 'wss://127.0.0.1:10040'` 在本地启动一个服务端
- 使用 `./gost -L 127.0.0.1:10030 -F 'wss://127.0.0.1:10040?ca=server.crt'` 启动客户端
- 设置浏览器 socks5 代理为 `127.0.0.1:10030` 这时是可以正常访问的. 

在服务端没有使用 `server.crt` 作为证书的情况下应该校验失败才对. 而如果将 wss 协议改成 https, 就能看到 `certificate signed by unknown authority` 的错误日志了.

**Comment by kingwilliam** [comment]
如理解有误请指正.

您提出有以下3点.
1. 随意生成一个证书 server.crt
2. 使用 ./gost -L 'wss://127.0.0.1:10040' 在本地启动一个服务端
3. 使用 ./gost -L 127.0.0.1:10030 -F 'wss://127.0.0.1:10040?ca=server.crt' 启动客户端

A1. server.crt视为server的电子证书, 但密匙?
A2. -L wss视为一个服务端 security websocket, 但没证书?
A3. -F wss.....?ca=server.crt 视为一个客户端, 但为何伺服器证书会放在客户端? 
A3.1 但又为何伺服器证书会放在ca?,
A3.2 因您上面3点也没有说您有 ca.crt, 那麽您的ca.crt?

您的问题是  “在服务端没有使用 server.crt 作为证书的情况下应该校验失败才对. 而如果将 wss 协议改成 https, 就能看到 certificate signed by unknown authority 的错误日志了”

我尝试题供一些例子,看看可否解答您的问题
1. 首先电子证书有证书时 server.crt, 同时也要有 server.key 密匙 (证书和密匙是一对的)
2. 有证书和密匙 当然也应该有 ca.crt (在您的例子是可以没ca密匙的)
3. 首先修改您的服务端
   ./gost -L 'wss://127.0.0.1:10040?cert=server.crt&key=server.key'
4. 再修改您的客户端
   ./gost -L 127.0.0.1:10030 -F 'wss://127.0.0.1:10040?ca=ca.crt'

不知能否解决您的问题?

**Comment by luyuhuang** [comment]
谢谢您的回复. 我的意思是这样的:

服务端使用 -L wss , 没有指定证书, 这时 gost 会使用内置的证书 (见 https://docs.ginuerzh.xyz/gost/tls/);

而客户端使用随意生成的证书 server.crt 作为 ca 证书, 并指定 `?ca=server.crt`;

然后客户端尝试与服务端建立 TLS 连接;

此时, 服务端使用的内置证书显然不是我们随意生成的 ca 证书 server.crt 所签名的. 客户端应该认为这个服务端是不被信任的, 我们应该能看到 `certificate signed by unknown authority` 这样的报错才对. 但事实是, 没有报错, 正常连接. 这应该是不对的.

而如果把 wss 改成 https, 执行同样的操作, 我们就能在客户端看到我们所期望的报错: `certificate signed by unknown authority`

**Comment by luyuhuang** [comment]
我在阅读源码时没有发现 wss 协议使用 `ca` 参数所指定的证书对服务端证书作校验的代码 (TLS 有, 但是 wss 协议使用的是 websocket 库, 与 TLS 不同). 于是我尝试对 `ws.go` 作了一些修改, 见 #630. 修改后的客户端执行上述操作, 就能看到期望的报错了.

**Comment by k79e** [comment]
好像是开启secure才会有效.

**Comment by luyuhuang** [comment]
> 你开secure试试

开了 secure 就是正常校验证书, 并不会使用 `ca` 参数指定的证书校验. 而且这样的话自签名的证书就没法用了.

**Comment by k79e** [comment]
正常的+ca 两个一起用就行了

**Comment by luyuhuang** [comment]
> 正常的+ca 两个一起用就行了

不行. 这样自签名的证书就用不了了.

**Comment by k79e** [comment]
可以 要有域名

**Comment by luyuhuang** [comment]
如果这样可以的话, 那你有没有试过这样:

- 服务器执行 `./gost -L 'wss://0.0.0.0:10040?cert=server.crt&key=server.key'` 启动服务端, 其中证书 `server.crt` 由 `ca.crt` 颁发, 且与服务器域名匹配;
- 客户端随意生成一个 `ca1.crt` 证书
- 客户端执行 `./gost -L 127.0.0.1:10030 -F 'wss://server.com:10040?ca=ca1.crt&secure=true'` 启动客户端, 假设 `server.com` 是服务器域名
- 客户端测试 `socks5://127.0.0.1:10030`

这种情况下, 客户端仅信任 `ca1.crt` 及其颁发的证书. 这个例子中的服务器应该是不被信任的. 如果这样能够正常运行的话, 说明证书锁定无效.

> 可以 要有域名

如果在开启 `secure` 的情况下, 只要自签名证书与域名匹配就有效的话, 是不安全的. 中间人只需随意签名一个域名与之匹配的证书就可以劫持你的 ssl 链接, 并且不被你察觉, 你的传输内容就会被破解.

**Comment by luyuhuang** [comment]
又看了一遍代码, 在有域名的情况下, 开启 `secure` 并指定 `ca=` 是有效的. 而且, 在使用自签名证书的情况下, 开启 `secure` 但不指定 `ca=` 会不被信任. 这些都没有问题, 上面我说的问题也都不存在.

现在唯一的问题就是不使用域名就无法安全地使用 wss. 因为在没有域名的情况下不能使用正式的证书, 也无法使用证书锁定. 我看到 `tls.go` 271 行的 `wrapTLSClient` 函数就是用来解决这个问题的, 它对证书进行手动校验. 这样对于 https 协议, 不使用域名, 不开启 `secure` 也能够证书锁定. 所以我想 wss 也做类似的事情, 这样不使用域名也能正常证书锁定, 应该要好一些.

**Comment by proxy666-dev** [comment]
> 又看了一遍代码, 在有域名的情况下, 开启 `secure` 并指定 `ca=` 是有效的. 而且, 在使用自签名证书的情况下, 开启 `secure` 但不指定 `ca=` 会不被信任. 这些都没有问题, 上面我说的问题也都不存在.
> 
> 现在唯一的问题就是不使用域名就无法安全地使用 wss. 因为在没有域名的情况下不能使用正式的证书, 也无法使用证书锁定. 我看到 `tls.go` 271 行的 `wrapTLSClient` 函数就是用来解决这个问题的, 它对证书进行手动校验. 这样对于 https 协议, 不使用域名, 不开启 `secure` 也能够证书锁定. 所以我想 wss 也做类似的事情, 这样不使用域名也能正常证书锁定, 应该要好一些.

你的意思是说，这个如标题所说的bug是不存在的？

**Comment by luyuhuang** [comment]
> 你的意思是说，这个如标题所说的bug是不存在的？(如果是的话，这就很尴尬了。)

严格地来说, 是的. 只能说之前我理解的不充分. 应该是在不使用域名的情况下, wss 协议无法使用证书锁定. 我列出的复现步骤也能说明这个问题; #630 也能解决这个问题, 不过这种做法可能不够好, 应该有更好的办法.

**Comment by proxy666-dev** [comment]
> > 你的意思是说，这个如标题所说的bug是不存在的？(如果是的话，这就很尴尬了。)
> 
> 严格地来说, 是的. 只能说之前我理解的不充分. 应该是在不使用域名的情况下, wss 协议无法使用证书锁定. 我列出的复现步骤也能说明这个问题; #630 也能解决这个问题, 不过这种做法可能不够好, 应该有更好的办法.

#630 不用了，用 #641 ？

**Comment by proxy666-dev** [comment]
> > > 你的意思是说，这个如标题所说的bug是不存在的？(如果是的话，这就很尴尬了。)
> > 
> > 
> > 严格地来说, 是的. 只能说之前我理解的不充分. 应该是在不使用域名的情况下, wss 协议无法使用证书锁定. 我列出的复现步骤也能说明这个问题; #630 也能解决这个问题, 不过这种做法可能不够好, 应该有更好的办法.
> 
> #630 不用了，用 #641 ？

@luyuhuang 等确定了我再合并到我的gost

**Comment by luyuhuang** [comment]
嗯, 还是要请作者大大看下

**Comment by proxy666-dev** [comment]
> 嗯, 还是要请作者大大看下

帮你@作者大大 @ginuerzh

**Comment by proxy666-dev** [comment]
@luyuhuang 生成了diff文件，在https://github.com/proxy6-dev/diff/tree/master/gost/2.11.1
