### ISSUE TITLE
TLS 证书路径问题

### ISSUE THREAD

**Issue by rampageX** [ginuerzh/gost#63]
目前（包括最新的）版本指定 TLS 证书路径无效，必须放在与 gost 执行文件同目录而且在 shell 下必须 cd 到 gost 所在目录执行才能找到自定义的 TLS 证书文件，否则一律报无法找到 cert.pem。

请作者看看是什么原因？

**Comment by ginuerzh** [comment]
你的使用命令是什么样子的?

**Comment by rampageX** [comment]
@ginuerzh 

`/usr/local/sbin/gost -L="http://tester:fuckugfw@:25" -L="http2://tester:fuckugfw@:143?cert=/usr/local/sbin/cert.pem&key=/usr/local/sbin/key.pem" -L="socks+tls://tester:fuckugfw@:587?cert=/usr/local/sbin/cert.pem&key=/usr/local/sbin/key.pem" -L="http+tls://tester:fuckugfw@:465?cert=/usr/local/sbin/cert.pem&key=/usr/local/sbin/key.pem"`

**Comment by rampageX** [comment]
bind 失败那行不用管，我没用 sudo 执行。

第一次执行是 ssh 进去的默认目录，提示：
    open cert.pem: no such file or directory
第二次，我 cd /usr/local/sbin 也就是 gost 的目录后再执行就没有这个提示了

```
tester@ubuntu:~$ /usr/local/sbin/gost -L="http://tester:fuckugfw@:25" -L="http2://tester:fuckugfw@:143?cert=/usr/local/sbin/cert.pem&key=/usr/local/sbin/key.pem" -L="socks+tls://tester:fuckugfw@:587?cert=/usr/local/sbin/cert.pem&key=/usr/local/sbin/key.pem" -L="http+tls://tester:fuckugfw@:465?cert=/usr/local/sbin/cert.pem&key=/usr/local/sbin/key.pem" -logtostderr -v 5
I1222 13:52:10.271060    5275 gost.go:115] open cert.pem: no such file or directory
F1222 13:52:10.273526    5275 main.go:70] listen tcp :25: bind: permission denied
tester@ubuntu:~$ cd /usr/local/sbin/
tester@ubuntu:/usr/local/sbin$ /usr/local/sbin/gost -L="http://tester:fuckugfw@:25" -L="http2://tester:fuckugfw@:143?cert=/usr/local/sbin/cert.pem&key=/usr/local/sbin/key.pem" -L="socks+tls://tester:fuckugfw@:587?cert=/usr/local/sbin/cert.pem&key=/usr/local/sbin/key.pem" -L="http+tls://tester:fuckugfw@:465?cert=/usr/local/sbin/cert.pem&key=/usr/local/sbin/key.pem" -logtostderr -v 5
F1222 13:52:30.242641    5284 main.go:70] listen tcp :465: bind: permission denied
tester@ubuntu:/usr/local/sbin$
```

**Comment by ginuerzh** [comment]
这个错误属于误报，目前处理方式是所有-L指定的服务都会去加载证书，不管有没有用到。
下一版本中会修正，不过不影响正常使用。

**Comment by rampageX** [comment]
明白，我去掉 25 那个监听，的确在任意地方运行都不会提示了，谢谢。
