### ISSUE TITLE
安卓系统客户端有什么软件支持吗？

### ISSUE THREAD

**Issue by omyhub** [ginuerzh/gost#634]
pc 端用gost 代理+转发模式，然后浏览器用switchyomega 实现科学上网
手机端有什么软件可以呢？gost貌似没看到andriod版

**Comment by PShawnKD35** [comment]
> pc 端用gost 代理+转发模式，然后浏览器用switchyomega 实现科学上网
> 手机端有什么软件可以呢？gost貌似没看到andriod版

用postern

**Comment by BlueSedDragon** [comment]
termux

**Comment by omyhub** [comment]
有没有小白教程，我启用了http2.0 的证书认证模式
