### ISSUE TITLE
查看后台进程可看到帐号和密码

### ISSUE THREAD

**Issue by super-vip** [ginuerzh/gost#642]
命令行启动时设置帐号和密码的情况下，在查看后台进程时，可看到明文帐号和密码，这或许是个安全隐患。
如何避免后台进程显示明文信息？
![image](https://user-images.githubusercontent.com/19517568/92415126-15199380-f18a-11ea-8fd0-21f47fcdc019.png)

**Comment by DDCHlsq** [comment]
如果这不是你要与他人共享机器，就不要跑gost。这并不是安全隐患。

**Comment by super-vip** [comment]
不管是否与他人共享机器，后台进程可看到相关密码都是不安全的。
我不赞同你这种“不是安全隐患”的说法。

**Comment by SeaHOH** [comment]
既然别人能访问操作你使用的机器，那么读取硬盘、内存简单得很，这算什么“安全隐患”？

**Comment by super-vip** [comment]
夏虫不足以语冰。

**Comment by ginuerzh** [comment]
如果觉得不安全，也可以使用secrets参数指定文件来设置密码。

**Comment by DDCHlsq** [comment]
> 夏虫不足以语冰。

别动不动就骂人。
他说的是有道理的，查看进程，包括作者回复说用secret文件，只要别人可以操作机器都可以被查看到的，否则看不到，安全程度其实一致。所以不明白为什么你说这个不安全。

**Comment by super-vip** [comment]
没骂人，仁者见智，智者见智，仅此而已，不用过度解读。
对于进程显示了明文密码可请那些所谓的绿盟之类的厂商扫描下，看算不算安全隐患？
另：作者的建议就是个可缓解安全风险的解决思路。这个我还是比较认可的。

**Comment by SeaHOH** [comment]
真别，我懂的可多了。
先读取 secrets 参数找到配置文件，再读取配置文件找到帐号和密码。
你再看看有什么不对的地方？

**Comment by super-vip** [comment]
无语，实在佩服你懂的真多，还在纠结这问题。
root帐户和普通帐户的权限控制懂不懂？
文件针对不同用户有没有读写执行等的权限控制？
你用不同的帐户去玩儿一下：例如查看进程，查看未授读权限的文件……
测试完了后再来告诉大伙，有什么结果。

**Comment by SeaHOH** [comment]
还权限，小学生知识都拿来显摆，你也就只配用什么绿盟了。
虚拟机、容器、沙盒，会用不？隔离一下不比你这安全。实在不会，单独搞个服务器，反正不浪费，用得着的地方多了去。
另外，劝你先安装个安全软件，带主动防御那种，对小白来说有用得很。

哦，你已进入我的黑名单，不用回复了。

**Comment by RocFang** [comment]
大家稍安勿躁...

**Comment by super-vip** [comment]
就一个进程显示密码的安全问题，你会无限放大到宇宙中去……
多丢几个名词就表示你全天下第一了？就你懂，别人什么都不会？悠着点，谦虚点，务实点是有好处的。别那么眼高手低。
什么场景用什么安全技术那是另一回事。如你所言，是不是还要上个导弹防御系统？
回到问题本身，只问一句：为什么进程要显示帐号和密码？

**Comment by NomadJohn** [comment]
![image](https://user-images.githubusercontent.com/30516060/92553388-5ba7e480-f295-11ea-942f-fdeac07b4519.png)

**Comment by SeaHOH** [comment]
呵呵，夏虫。

**Comment by proxy666-dev** [comment]
> 如果觉得不安全，也可以使用secrets参数指定文件来设置密码。

最近在搞什么？怎么不见得你更新？

**Comment by proxy666-dev** [comment]
> 命令行启动时设置帐号和密码的情况下，在查看后台进程时，可看到明文帐号和密码，这或许是个安全隐患。
> 如何避免后台进程显示明文信息？
> ![image](https://user-images.githubusercontent.com/19517568/92415126-15199380-f18a-11ea-8fd0-21f47fcdc019.png)

用配置文件即可（命令:gost -C 配置文件名.json）

**Comment by lovitus** [comment]
这个issue提出还是有意义的.
或许作者可以参考下 ,比如为socket和ssh这些加上**?secure=true, 或者加上全局参数**.
**凭据存在内存里**就行,命令行脱敏显示. 毕竟执行参数所有用户可见, 而内存不是所有人都能dump的.
当然作者如果不打算做这个,也是有自己的考虑,或者选择.

**Comment by lovitus** [comment]
我不认为, linux里普通用户们 能互相看对方程序的敏感凭据是一个正常的情况.
文件权限可以做到隔离.

作者和其它网友都有给出意见或者解决方法.
 而SeaHOH就是一个喷子了.

**Comment by SeaHOH** [comment]
真好笑，狗咬人我踹它两下怎么了？
