### ISSUE TITLE
无法只使用标准ssh server 完成转发.

### ISSUE THREAD

**Issue by lovitus** [ginuerzh/gost#643]
- 有一台机器, 8.8.8.8 用户名root 密码 rootpwd -

我无法将这台机器做为-F 进行流量转发
**实例1:**
`gost -L ltcp://:8080/:80 -F ssh://root:rootpwd@8.8.8.8:22 `  _#实际是无法实现转发. ssh连接不了._

**或者可以实现用密钥进行连接?**
`-F ssh://root@8.8.8.8:22?priv_key=/**/key`

希望作者可以考虑实现 无客户端,仅openssh-server环境下的类似ssh 端口代理的功能, 
ssh自带的,和autossh 在重连/功能/设计上, 都没有gost来的舒服.
**如果已经实现, 是我不会用,还望解答 (已经搜索和尝试一个月了)**

**Comment by ginuerzh** [comment]
[端口转发](https://docs.ginuerzh.xyz/gost/port-forwarding/)中有说明：
```
gost -L tcp://:8080/127.0.0.1:80 -F forward+ssh://root:rootpwd@8.8.8.8:22
```
2.11+可以使用key:
```
gost -L tcp://:8080/127.0.0.1:80 -F forward+ssh://root@8.8.8.8:22?ssh_key=/path/to/id_rsa
```

**Comment by lovitus** [comment]
> [端口转发](https://docs.ginuerzh.xyz/gost/port-forwarding/)中有说明：
> 
> ```
> gost -L tcp://:8080/127.0.0.1:80 -F forward+ssh://root:rootpwd@8.8.8.8:22
> ```
> 
> 2.11+可以使用key:
> 
> ```
> gost -L tcp://:8080/127.0.0.1:80 -F forward+ssh://root@8.8.8.8:22?ssh_key=/path/to/id_rsa
> ```
