### ISSUE TITLE
tun性能问题

### ISSUE THREAD

**Issue by lovitus** [ginuerzh/gost#647]
![image](https://user-images.githubusercontent.com/14361541/93708318-bbd93900-fb67-11ea-81ee-123ae463fc3b.png)
![image](https://user-images.githubusercontent.com/14361541/93708321-bf6cc000-fb67-11ea-8658-71390437f1d0.png)

图一为 使用**socks5**进行代理的速度,  观察三天内, socks5的速度,**一直是300Mbps+**
图二为 使用**tun**进行传输的速度, 观察三天内, tun传输(上传/下载) **一直是40Mbps**
都分别使用iperf /speedtest/以及其它工具进行测试过, 数据准确   
socks5  :  `gost -L socks5://:7890 -F ss://** -F socks5://**`
tun         : `gost -L tun://**      -F ss://** -F socks5://**`

**Comment by cod1ingcoding** [comment]
客服端和服务器
`-F socks5://**?notls=true`
速度就上去了，参看文档：https://docs.ginuerzh.xyz/gost/socks/
```
如果两端都是GOST(如上)则**数据传输会被加密**(协商使用tls或tls-auth方法)，否则使用标准SOCKS5进行通讯(no-auth或user/pass方法)。
notls - (2.9.1+) 通过此参数可以禁用协商加密，默认值：false。
```
我自己测试是50M带宽，速度基本能达到满负荷，你也可以自己测试下。

**Comment by cod1ingcoding** [comment]
借这个issue说下问题，c/s都是gost

三种方案：
1. `-L socks5://:1080?notls=false`
2. `-L socks5://:1080?notls=true`
3. `-L socks5+tls://:1080?notls=true`

**内网**吞吐量测试结果：方案2 ≈ 方案3 ≫方案1。

按照文档
`https://docs.ginuerzh.xyz/gost/socks/`说的：

> GOST支持标准SOCKS5协议的no-auth(0x00)和user-pass(0x02)方法，并在此基础上扩展了两个：tls(0x80)和tls-auth(0x82)，用于数据加密

这个协议扩展是不是有性能问题？
