### ISSUE TITLE
ssh+forward 的密码无法使用@字符

### ISSUE THREAD

**Issue by lovitus** [ginuerzh/gost#648]
**当有@字符做为ssh的密码时, 无法进行连接**, 项目上的服务器有大量的特殊字符, 无法简单使用gost进行代理
加' 或者" 或者\转义也没用. 
可以考虑对特殊字符的处理么, 这样就不需要使用其它工具,或者交换密钥了.简化使用

**Comment by hyq5436** [comment]
可用将密码url encode一下
