### ISSUE TITLE
ss协议不支持rc4和xchacha20-ietf-poly1305

### ISSUE THREAD

**Issue by yzqiang666** [ginuerzh/gost#662]
ss协议不支持rc4和xchacha20-ietf-poly1305，能否加入这些未支持的协议？

**Comment by yzqiang666** [comment]
ss.go:605: [ss] cipher not supported

**Comment by 2378** [comment]
这问题是 https://github.com/shadowsocks/shadowsocks-go 决定的
ss-go兼容性是有些问题
