### ISSUE TITLE
带RPC的web端口，转发后工作不正常

### ISSUE THREAD

**Issue by badgv** [ginuerzh/gost#665]
服务端使用   gost -L ws://:8080
客户端使用  gost -L rtcp://:8888/127.0.0.1:8888 -F ws://xxx.com:8080
将服务端的8888端口转发至本地8888端口，8888端口是个WEB服务器端口，带/RPC服务，工作不正常

**Comment by c1ayy** [comment]
rpc有很多种实现，具体是什么rpc协议？

**Comment by badgv** [comment]
> rpc有很多种实现，具体是什么rpc协议？

具体是什么RPC协议不太懂，是BT软件rtorrent的RPC服务，但是它的RPC监听端口是被nginx反代的，上面描述的8888端口是nginx的WEB监听，nginx的配置如下：
location /RPC2 {
        	include scgi_params;
	        scgi_pass 127.0.0.1:5000;
                scgi_param SCRIPT_NAME /RPC2;
}
5000是BT软件rtorrent的RPC监听端口
