### ISSUE TITLE
自编译2.3-rc2，报错。

### ISSUE THREAD

**Issue by jlzsss** [ginuerzh/gost#67]
报错信息如下：
..\..\conn.go:152: undefined: shadowsocks.DialWithRawAddrConn
godep: exit status 2
请社长看看，是否是我编译的不对。

**Comment by ginuerzh** [comment]
go的版本是多少？请使用1.6及以上版本，由于使用了go的vendor特性，直接clone下来，进入cmd/gost目录执行go build就可以了，不需要再额外下载依赖库

**Comment by jlzsss** [comment]
搞定了，谢谢社长。

**Comment by supppig** [comment]
遇到同样问题，请问是如何解决的？ @jlzsss

**Comment by jlzsss** [comment]
go get 只下载gost主分支，虽然go get 还要下载其他依赖包，CTRL+C终止就是了。然后进入cmd/gost目录执行go build就可以了。
