### ISSUE TITLE
关于反向socks5代理功能疑问

### ISSUE THREAD

**Issue by k-vulner** [ginuerzh/gost#673]
您好，有幸接触到您编写的工具。目前有一个场景：
vps[1.1.1.1]---[防火墙]---[内网主机A 2.2.2.1]---[多级内网]
主机A可以访问VPS，但VPS无法访问到内网主机A。希望可以通过vps开启的socks5来达到访问内网主机A所在内网的目的。之后再进行多级内网代理。
尝试了在vps上运行：
gost -L ssh://admin:123456@:2222
在A上运行：
gost -L=socks5://:8888 -L rtcp://0.0.0.0:8888/localhost:8888 -F ssh://admin:123456@110.110.110.110:2222?ping=60
来将A上的socks5:8888代理出去，但是失败。
请问您能帮助下我么？谢谢。

**Comment by kingwilliam** [comment]
会否 [frp](https://github.com/fatedier/frp) 更合适?

**Comment by k-vulner** [comment]
> [frp](https://github.com/fatedier/frp) 会否更合适?
感谢回复！ew，frp，nps确实可以，就是想收集收集相关工具进行一个比较。
frp的话不知道我做的对不对：首先是需要配置ini文件，其次是分为server端和client端，在内网中间的机子上需要同时开启frps和frpc，如果之后继续深入内网的话还需要构建一条新的端口转发的链路，感觉比较麻烦，不知道是不是我不会用的原因。我比较喜欢的是Termite这种设计，只需要不断后续机子反连即可，可惜不是很稳定。
作者这个工具很强大，我觉得应该是有这个功能的，但是不太会用。

**Comment by ginuerzh** [comment]
可以这样做：
vps:
```
gost -L forward+ssh://admin:123456@:2222
```

本地:
```
gost -L=socks5://:8888
```
```
gost  -L rtcp://0.0.0.0:8888/localhost:8888 -F forward+ssh://admin:123456@110.110.110.110:2222?ping=60
```

**Comment by k-vulner** [comment]
感谢作者，确实可以。准备再试一试多级代理。
