### ISSUE TITLE
请问这个能用在SSH上么？

### ISSUE THREAD

**Issue by manandgod** [ginuerzh/gost#68]
试着连了一下，没成功。

**Comment by ginuerzh** [comment]
请问你想怎么个用法？

**Comment by manandgod** [comment]
就是把SSH节点当一般代理使用

**Comment by ginuerzh** [comment]
首先你的SSH要运行为代理隧道模式，让其成为一个标准的代理节点，然后就可以通过它去进行转发了。

**Comment by manandgod** [comment]
额，我明白了，要先运行SSH通道，然后再转发，我以为可以像SS一样可以登录直接用呢

不过可以作到直接支持SSH么？就像SS一样直接使用，就不用麻烦开两个软件了

**Comment by ginuerzh** [comment]
为什么要通过SSH转发呢? gost本身就可以创建多种类型的隧道。

**Comment by manandgod** [comment]
有时手上正好有SSH，不利用觉得浪费了。
