### ISSUE TITLE
建议增加透传ip

### ISSUE THREAD

**Issue by ixmu** [ginuerzh/gost#686]
建议gost做转发的时候可以透传IP，这样可以方便源获取用户ip

**Comment by humorwang** [comment]
臣附议

**Comment by lovitus** [comment]
这样有一个问题: 然后服务端就绕过了代理链, 直接将返回报文发给了客户端. 而且客户端一般都是内网IP, 路由不可达.

**Comment by humorwang** [comment]
> 这样有一个问题: 然后服务端就绕过了代理链, 直接将返回报文发给了客户端. 而且客户端一般都是内网IP, 路由不可达.

底层的TCP/IP 网络这方面我不太懂，但有没有可能像nginx一样设置一个参数供后端取值？客户端首先连的是gost那只有gost知道客户端的真实ip，如果依赖上层应用客户端和服务端判断，客户端很容易伪造这个信息。

**Comment by lovitus** [comment]
> > 这样有一个问题: 然后服务端就绕过了代理链, 直接将返回报文发给了客户端. 而且客户端一般都是内网IP, 路由不可达.
> 
> 底层的TCP/IP 网络这方面我不太懂，但有没有可能像nginx一样设置一个参数供后端取值？客户端首先连的是gost那只有gost知道客户端的真实ip，如果依赖上层应用客户端和服务端判断，客户端很容易伪造这个信息。

nginx传客户端的ip给服务实例的时候不是修改源ip, 而是加了http的header.

**Comment by humorwang** [comment]
> > > 这样有一个问题: 然后服务端就绕过了代理链, 直接将返回报文发给了客户端. 而且客户端一般都是内网IP, 路由不可达.
> > 
> > 
> > 底层的TCP/IP 网络这方面我不太懂，但有没有可能像nginx一样设置一个参数供后端取值？客户端首先连的是gost那只有gost知道客户端的真实ip，如果依赖上层应用客户端和服务端判断，客户端很容易伪造这个信息。
> 
> nginx传客户端的ip给服务实例的时候不是修改源ip, 而是加了http的header.

对，我的意思也是增加一个参数供后端取值，而不是交给客户端去设置这个参数。客户端比较容易伪造。

**Comment by humorwang** [comment]
> > > 这样有一个问题: 然后服务端就绕过了代理链, 直接将返回报文发给了客户端. 而且客户端一般都是内网IP, 路由不可达.
> > 
> > 
> > 底层的TCP/IP 网络这方面我不太懂，但有没有可能像nginx一样设置一个参数供后端取值？客户端首先连的是gost那只有gost知道客户端的真实ip，如果依赖上层应用客户端和服务端判断，客户端很容易伪造这个信息。
> 
> nginx传客户端的ip给服务实例的时候不是修改源ip, 而是加了http的header.

对，我的意思也是增加一个参数供后端取值，而不是交给客户端去设置这个参数。客户端比较容易伪造。

**Comment by ginuerzh** [comment]
正常情况下是获取不到的，需要额外协议的支持例如proxy_protocol
