### ISSUE TITLE
如何以最省流量的方式建立加密隧道

### ISSUE THREAD

**Issue by ouxmm** [ginuerzh/gost#691]
如题：本身没有翻墙需求，只希望在两台服务器之间建立加密隧道以避免业务流量以明文的方式传输被窃听
尝试使用wss建立隧道，原始流量和加密后传输的流量比大概是一比二一比三，流量翻了好几倍
请教下，应该以什么协议或传输类型建立加密隧道最省流量？

**Comment by ginuerzh** [comment]
试试多路复用，relay+h2, relay+mtls等
