### ISSUE TITLE
UDP over TCP单向发送

### ISSUE THREAD

**Issue by satifanie** [ginuerzh/gost#70]
不知道能否配合实现发送UDP的时候  over tcp ，但是回程的时候
使用原有的 UDP返回数据?就是将KCP 发送的包 用TCP封装发送送到
服务器，但是使用原有协议进行返程。
我尝试使用Iptable 解决，但是到了服务器端，转发到目标UDP端口的时候，
sourceip 和 port 已经变了。有什么方案可以讨论？

**Comment by ginuerzh** [comment]
这种方式需要自定义协议来实现
