### ISSUE TITLE
使用转发时服务器端不读取系统hosts吗？

### ISSUE THREAD

**Issue by wpzzz** [ginuerzh/gost#701]
测试好像是不读取的，  使用?hosts=指定hosts文件，也没有效果

**Comment by JamesYuan** [comment]
我也刚测试了下，应该是不支持的。不过修改relay.go中的

		cc, err = h.options.Chain.DialContext(ctx,
			network, raddr,
			RetryChainOption(h.options.Retries),
			TimeoutChainOption(h.options.Timeout),
			HostsChainOption(h.options.Hosts),
			ResolverChainOption(h.options.Resolver),
		)

应该就可以。不知道是不是可以提个PR。
