### ISSUE TITLE
第一次使用gost，希望能当http通道用，但是connection refused

### ISSUE THREAD

**Issue by bcjin1991** [ginuerzh/gost#704]
希望能用gost实现http通道功能，安装好gost后，输入指令：./gost -L=6061 -F=127.0.0.1:6062。即希望6061端口监听，然后传递到本机6062端口，再去访问网页。

同时，在开启另一终端，输入curl www.baidu.com -x 127.0.0.1:6061
gost服务器提示：
[root@ip-172-31-52-154 gost]# ./gost -L=:6061 -F=127.0.0.1:6062
2021/03/23 15:38:55 route.go:677: auto://:6061 on [::]:6061
2021/03/23 15:39:00 http.go:161: [http] 127.0.0.1:40772 -> auto://:6061 -> www.baidu.com:80
2021/03/23 15:39:00 http.go:251: [route] 127.0.0.1:40772 -> auto://:6061 -> 1@auto://127.0.0.1:6062 -> www.baidu.com:80
2021/03/23 15:39:00 http.go:272: [http] 127.0.0.1:40772 -> 127.0.0.1:6061 : dial tcp 127.0.0.1:6062: connect: connection refused
请问这是怎么回事，是gost不支持connect连接吗？

**Comment by guqing637** [comment]
@bcjin1991 你用错了吧？

**Comment by bcjin1991** [comment]
> @bcjin1991 你用错了吧？
你好，感谢你的回复，方便细说一下我是哪里用错了吗？我的应用场景是前方客户端会传递connect指令，然后我希望能搭建一个proxy，后方是proxy2，然后通过proxy去连接Internet。

**Comment by bcjin1991** [comment]
> @bcjin1991 你用错了吧？

你好，感谢你的回复，方便细说一下我是哪里用错了吗？我的应用场景是前方客户端会传递connect指令，然后我希望能搭建一个proxy，后方是proxy2，然后通过proxy去连接Internet。

**Comment by bcjin1991** [comment]
> @bcjin1991 你用错了吧？

你好，感谢你的回复，方便细说一下我是哪里用错了吗？我的应用场景是前方客户端会传递connect指令，然后我希望能搭建一个proxy（称为proxy1），后方是proxy2，即用户通过proxy1，然后proxy2去访问具体网站

**Comment by sumerzhang** [comment]
你的6062没有开代理，当然connection refused

./gost -L=:6062

./gost -L=:6061 -F=127.0.0.1:6062

-F是转发的意思，要你的6062有端口监听

**Comment by bcjin1991** [comment]
> 你的6062没有开代理，当然connection refused
> 
> ./gost -L=:6062
> 
> ./gost -L=:6061 -F=127.0.0.1:6062
> 
> -F是转发的意思，要你的6062有端口监听

确实是这样，对的，我没有监听6062端口，我刚刚按照你说的试了一下确实成功了。谢谢大佬。
