### ISSUE TITLE
使用自定义证书发生错误

### ISSUE THREAD

**Issue by LSSCP** [ginuerzh/gost#707]
如果使用默认证书没问题.

启动命令如下:

服务端:
gost -L relay+tls://:22222?cert=/home/user/certificates/\_.exp.com.crt&key=/home/user/certificates/\_.exp.com.key/127.0.0.1:7777

客户端:
gost-L udp://:33333 -L tcp://:33333 -F relay+tls://mtk.exp.com:22222

### 1. 是不是因为自定义证书的路径里“/”太多,导致服务端那个/127.0.0.1:7777转发失败?
当使用自定义证书后,会有下面提示:
relay.go:187: [relay] x.x.x.x:40652 -> x.x.x.x:22222 : bad request, target addr is needed.

### 2. 是不是服务端要使用mtk.exp.com的证书,而不能用*.exp.com的证书?
还有一个问题是客户端使用子域名连接(mtk.exp.com),服务端用的是wildcard证书.
这时候客户端加上secure=true,会提示证书不符合:
x509: certificate is not valid for any names, but wanted to match mtk.exp.com

**Comment by guqing637** [comment]
@LSSCP 你用法都用错了。

**Comment by LSSCP** [comment]
好吧,先不折腾了.
