### ISSUE TITLE
可以支持正向代理用法吗？

### ISSUE THREAD

**Issue by QLeelulu** [ginuerzh/gost#709]
serverA(192.168.1.10):  gost  -L http://:80

clientB: 直接把域名解析到 192.168.1.10，类似 curl以下命令：`curl -v -H "Host: www.baidu.com" http://192.168.1.10`

目前测试看来应该是不行的。

**Comment by guqing637** [comment]
@QLeelulu 你这是反向代理了，gost目前是不支持的。
