### ISSUE TITLE
win64 v2.3 RC2的UDP不能接收了

### ISSUE THREAD

**Issue by edveen** [ginuerzh/gost#71]
网络流：客服端（win64）-->HTTP代理-->服务端（linux64）
服务端启动命令：nohup ./gost -L=socks://:1080 > /dev/null 2>&1 &
客户端启动命令：gost.exe -logtostderr -L=:1080 -F=http://172.10.10.254:80 -F=socks://123.12
5.112.100:1080 -v=5

服务端采用的gost_2.3-rc2_linux_amd64版本，
客户端用gost_2.3-**rc1**_windows_amd64是可以正常接收UDP数据的，
客户端用gost_2.3-**rc2**_windows_amd64不能传输接收UDP数据了。

**Comment by ginuerzh** [comment]
SOCKS5的UDP吗?

**Comment by edveen** [comment]
是的，SOCKS5的UDP。今天本来打算升rc2，发现不行，服务端升级到rc2了，客户端继续用rc1

**Comment by edveen** [comment]
另外，ss协议为什么不支持UDP

**Comment by ginuerzh** [comment]
ss是基于shadowsocks-go，这个库目前还不支持UDP
