### ISSUE TITLE
求自动切换策略

### ISSUE THREAD

**Issue by wpzzz** [ginuerzh/gost#710]
一个快的服务器 但不稳定，和几个慢的服务器，希望日常连接快服务器，如果挂掉了自动去连接慢服务器。
目前自带的负载均衡似乎无法实现这个功能

**Comment by yitong-ovo** [comment]
试试 Haproxy 的负载均衡和故障转移，具体可以参考:

- https://gist.github.com/SilverBut/32be4a41cbdc50dd3a02627738b2b9cb
- https://blog.sbw.so/u/haproxy-shadowsocks-load-balance-useibility.html
- https://github.com/sbwtw/haproxy-shadowsocks-checker

如果要 UDP 支持的话，也可以试试 Nginx: https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/

**Comment by ginuerzh** [comment]
主备模式？fifo应该满足条件。

**Comment by depfish** [comment]
> 主备模式？fifo应该满足条件。

但是fifo流量始终会被打到第一个服务器上面，累的累死 闲的闲死。参考下haproxy的配置

```
frontend hkaz_in
bind 0.0.0.0:50025
default_backend hkaz

backend hkaz
server server1 hkaz1.xxxx.xyz:33659  check resolvers mydns resolve-prefer ipv4
server server2 hkaz2.xxxx.fun:33659  check resolvers mydns resolve-prefer ipv4
server server3 hkcm.xxxx.fun:33659 maxconn 250 check resolvers mydns resolve-prefer ipv4 backup
```
server1 和 server2是同时工作的，当且仅当 server1 和server2同时挂了，流量才会打到 server3上面去。

**Comment by rampageX** [comment]
[glider](https://github.com/nadoo/glider) with priority
