### ISSUE TITLE
Support for TLS 1.3

### ISSUE THREAD

**Issue by fortuna** [ginuerzh/gost#72]
Does Gost support TLS 1.3?
There seems to be an implementation of the protocol here: https://github.com/bifurcation/mint

**Comment by ginuerzh** [comment]
The `bifurcation/mint` is a standalone and very experimental library, and I think TLS 1.3 can be integrated with the `crypto/tls` seamlessly, so we can use it unconsciously.

**Comment by jzp820927** [comment]
https://github.com/cloudflare/tls-tris/
看看这个能不能用于支持 1.3 ？

**Comment by ginuerzh** [comment]
这个库直接取代了标准库，可以直接用其提供的的方法重新编译即可，不用修改源码，但是它使用的是修改过的go编译器。

**Comment by jzp820927** [comment]
好吧，谢谢提醒，空了我用这个编译试试看。

**Comment by ginuerzh** [comment]
#151
