### ISSUE TITLE
如何以守护进程的方式运行？

### ISSUE THREAD

**Issue by CCint3** [ginuerzh/gost#722]
一般的软件都有-D参数让程序以守护模式运行，-o参数来输出日志到指定的文件中去。

希望能加入这一功能。

**Comment by RocFang** [comment]
传统的服务器多会用daemon方式运行，但现在新的服务器很多都不加这个了，尤其是在容器越来越流行的情况下。
个人觉得这个功能不用加，自己用 nohup 等方式跑更直接。

**Comment by RocFang** [comment]
传统的服务器多会用daemon方式运行，但现在新的服务器很多都不加这个了，尤其是在容器越来越流行的情况下。
个人觉得这个功能不用加，自己用 nohup 等方式跑更直接。

**Comment by David-yanp** [comment]
输出日志这个有利用统一收集和审计
