### ISSUE TITLE
尝试把 gost 放在 k8s 或 k3s 中

### ISSUE THREAD

**Issue by gongzili456** [ginuerzh/gost#728]
一直使用 gost 直接暴露 443 端口，但是这样一来就无法部署其他程序了，比较浪费。
目前想是将 gost 放在 k3s 集群内部。
但发现 gost 是使用 HTTP Method CONNECT 来实现的连接，而 ingress 还不支持该方法，所以无法使用。

请问，还有其他方式能实现我的想法吗？

**Comment by ginuerzh** [comment]
如果想用ingress目前只能使用ws再在本地加一层中转

**Comment by gongzili456** [comment]
是这样的结构吗？
![image](https://user-images.githubusercontent.com/6082335/124212231-31276080-db21-11eb-9259-1f97a046518e.png)

**Comment by ginuerzh** [comment]
https://gost.run/blog/2022/deploy/
可以尝试一下以上部署方式。

**Comment by xzycn** [comment]
这种应用用支持4层转发的LB就行了。例如Traefik、Nginx等都可以。

**Comment by kk17** [comment]
HTTP2代理可以关闭TLS吗？我用Traefik处理TLS。

**Comment by xzycn** [comment]
@kk17 https://gost.run/tutorials/http-tunnel/#http2_1
h2c应该是你需要的。

**Comment by gongzili456** [comment]
> https://gost.run/blog/2022/deploy/ 可以尝试一下以上部署方式。

@ginuerzh 请问 Server 上用 websocket 方式部署了代理，在 clash 中的配置如何写呢？
