### ISSUE TITLE
gost 什么时候能够更新出vmess协议

### ISSUE THREAD

**Issue by qqqqqqrrrrhh123a** [ginuerzh/gost#730]
gost 什么时候能够更新出vmess协议，本人非常看好这个开源项目，建议开发者更新vmess协议，缺少资金可以众酬，我愿意出1000元人民币加快vmess协议的更新速度，希望的不缺钱但缺时间的程序员也可以出资激励开发者

**Comment by vaakian** [comment]
你可能需要 🚀[glider](https://github.com/nadoo/glider)

**Comment by qqqqqqrrrrhh123a** [comment]
> 
> 
> 你可能需要 🚀[glider](https://github.com/nadoo/glider)

两个我都有用，今天测试反向代理内网穿透时发现glider不支持，gost支持，glider还很占内存多开几个就死机了。gost貌似没有

**Comment by qqqqqqrrrrhh123a** [comment]
> 
> 
> 你可能需要 🚀[glider](https://github.com/nadoo/glider)

https://github.com/nadoo/glider/issues/270 帮我看看这个问题

**Comment by nswjming** [comment]
> > 你可能需要 🚀[glider](https://github.com/nadoo/glider)
> 
> 两个我都有用，今天测试反向代理内网穿透时发现glider不支持，gost支持，glider还很占内存多开几个就死机了。gost貌似没有

你好，能向你请教下gost内网穿透应该怎么配置吗？
我有两台内网的机器10.80.0.122 和192.168.217.128
有一台在外网的中继服务器10.80.5.244，请问怎么配置这三台机器能让两台内网机器通信？
