### ISSUE TITLE
([client]gost-[ss]proxy1-[socks5]proxy2-[ssr]proxy3-internet)的多级转发问题

### ISSUE THREAD

**Issue by qqqqqqrrrrhh123a** [ginuerzh/gost#734]
在这样一条代理链中：
([client]gost-[ss]proxy1-[socks5]proxy2-[ssr]proxy3-internet)
数字是否在 [client]gost 被加密过三次，分别是ss,socks5,ssr加密，然后每经过一层proxy被解密一次，只有在[ssr]proxy3-internet抓包得到原数据，而在[client]gost-[ss]proxy1抓包只能得到加密了三次的数据，在[ss]proxy1-[socks5]proxy2得到加密了两次的数据？我这样理解是否有错误？

**Comment by ginuerzh** [comment]
是的
