### ISSUE TITLE
远程端口转发到内网端口，也就是反向代理隧道，隧道的协议是否支持ss,ssr,ws,socks5,ssh？

### ISSUE THREAD

**Issue by qqqqqqrrrrhh123a** [ginuerzh/gost#736]
远程端口转发到内网端口，也就是反向代理隧道，隧道的协议是否支持ss,ssr,ws,socks5,ssh？文档中使用的是socks5，搜索到的issues使用的是ssh，但其他协议可行吗？

**Comment by ginuerzh** [comment]
远程端口转发要用到socks5的BIND方法，或ssh的端口转发功能，所以只能是这两种协议
