### ISSUE TITLE
请问gost做代理转发时是否支持协议转换？比如tcp报文转udp,或者tcp转quic？

### ISSUE THREAD

**Issue by nswjming** [ginuerzh/gost#749]
文档里使用socks5协议时，有讲到udp-over-tcp的转发方式，请问这个方式是否是在tcp报文上再加一层udp头然后到客户端再拆解udp报文头还原数据？

**Comment by fannwong001** [comment]
同问，感觉文档方面说的不清楚

**Comment by ginuerzh** [comment]
> 文档里使用socks5协议时，有讲到udp-over-tcp的转发方式，请问这个方式是否是在tcp报文上再加一层udp头然后到客户端再拆解udp报文头还原数据？

TCP和UDP只是数据传输方式上有差别，UDP单个报文是不可分割的最小单元，因此无法直接通过TCP方式流式传输，必须包一层告诉对端数据长度。所以你的理解是对的。
