### ISSUE TITLE
是否可以加入 dns over https 支持

### ISSUE THREAD

**Issue by wxyzh** [ginuerzh/gost#75]
如题，参考[dns.google.com ](dns.google.com)

**Comment by ginuerzh** [comment]
你是指DNS查询服务的数据通过HTTPS转发吗?

**Comment by FlowerWrong** [comment]
他说的应该是这个[dns-over-https](https://developers.google.com/speed/public-dns/docs/dns-over-https)

`curl 'https://dns.google.com/resolve?name=www.google.com'`

**Comment by ginuerzh** [comment]
这个是Google提供的API，可以直接使用，没有必要再去自己实现。

**Comment by wxyzh** [comment]
确实是这个，我是想，是否可以监听53，然后直接把dns请求转发出去

**Comment by ginuerzh** [comment]
可以利用UDP端口转发，不过不支持UDP over HTTPS，但可以利用其他方式，例如:

UDP over TLS: `gost -L udp://:53/8.8.8.8:53 -F http2://SERVER_IP:443`
UDP over HTTP2: `gost -L udp://:53/8.8.8.8:53 -F socks+tls://SERVER_IP:443`
UDP over ws(s): `gost -L udp://:53/8.8.8.8:53 -F socks+wss://SERVER_IP:443`
甚至UDP over KCP: `gost -L udp://:53/8.8.8.8:53 -F socks+kcp://SERVER_IP:8388`

这样访问本地的53端口就相当于直接访问8.8.8.8:53

**Comment by wxyzh** [comment]
@ginuerzh 这个我明白
我主要是想用 google 的dns-over-https的edns 功能，有个edns-subnet的参数，可以解析到cdn的ip地址

**Comment by ginuerzh** [comment]
这个属于特殊使用方式，不在考虑范围内
