### ISSUE TITLE
gost直接转发socks5后显示的是中转机的IP

### ISSUE THREAD

**Issue by bak003** [ginuerzh/gost#757]
gost -L socks5://:1234/1.1.1.1:1234

1.1.1.1 为落地机的IP，实际使用时显示的是中转IP。使用tcp协议直接转发则能显示落地IP。版本为v2.11.1

**Comment by soffchen** [comment]
socks5 有这样的写法？

gost -L :1234 -F socks5://1.1.1.1:1234

**Comment by bak003** [comment]
> 

这样并不通

**Comment by bak003** [comment]
> socks5 有这样的写法？
> 
> gost -L :1234 -F socks5://1.1.1.1:1234

这样并不通
