### ISSUE TITLE
http2，只有首次连接才是Tlsv1.3，如果同一个程序断开重连，会跌落到Tls 1.2

### ISSUE THREAD

**Issue by Error996** [ginuerzh/gost#758]
如题，证书为acme申请的证书
server：gost -L="http2://:443?cert=/root/cert.crt&key=/root/key.key"
client:    gost -L=:8080 -F=http2://mydomain.com:443

![image](https://user-images.githubusercontent.com/12880110/142192804-c1eeb1f6-a922-4576-a05a-d1ff25b260fa.png)
![image](https://user-images.githubusercontent.com/12880110/142192848-f1808c03-1435-4389-823c-338af5759cf6.png)

**Comment by Error996** [comment]
图中ip为临时测试ip

**Comment by ginuerzh** [comment]
#794 
可能是这个原因。
