### ISSUE TITLE
Forwarding socks5 is failed, when char # appears in password/username

### ISSUE THREAD

**Issue by chirok11** [ginuerzh/gost#768]
Problem: **parse error**

`./gost-darwin-amd64 -L="socks5://:1080" -F="socks5://newgcp0512:Gv\$s5XnEJ#B3@11.1.1.1:5555"
2021/12/10 17:32:50 main.go:88: parse "socks5://newgcp0512:Gv$s5XnEJ": invalid port ":Gv$s5XnEJ" after host`

**Comment by ginuerzh** [comment]
Try `auth` or `secrets` parameter. 
Please refer to https://v2.gost.run/en/configuration/#auth-parameter-292
