### ISSUE TITLE
帮忙看一下，这是bug，还是我配置方法不正确（配置信息详见正文）？

### ISSUE THREAD

**Issue by aa51513** [ginuerzh/gost#776]
【服务端配置】
{
    "Debug": true,
    "Retries": 0,
    "ServeNodes": [
        "relay+kcp://:443",
        "dns://:53?mode=udp&dns=8.8.8.8:53/udp,[2001:4860:4860::8888]:53/udp"
    ]
}
--------
【客户端配置】
{
    "Debug": true,
    "Retries": 0,
    "ServeNodes": [
        "udp://:53/:53",
        "tcp://:443/:443"
    ],
    "ChainNodes": [
        "relay+kcp://服务器IP:443"
    ]
}
------
【客户端操作】
dig @127.0.0.1 www.google.com
------
【服务端日志】
2021/12/28 03:10:21 route.go:650: dns://:53 on :53
2021/12/28 03:10:21 route.go:650: relay+kcp://:443 on [::]:443
2021/12/28 03:10:28 kcp.go:338: [kcp] [2409:8a28:441d:8b90:6cee:1b17:efb7:c03f]:45259 - [::]:443
2021/12/28 03:10:28 kcp.go:351: [kcp] [2409:8a28:441d:8b90:6cee:1b17:efb7:c03f]:45259 <-> [::]:443
2021/12/28 03:10:28 relay.go:223: [relay] [2409:8a28:441d:8b90:6cee:1b17:efb7:c03f]:45259 -> [::]:443 -> 0.0.0.0:53
2021/12/28 03:10:28 relay.go:253: [relay] [2409:8a28:441d:8b90:6cee:1b17:efb7:c03f]:45259 <-> 0.0.0.0:53
2021/12/28 03:10:28 dns.go:75: [dns] 127.0.0.1:38967 -> :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
2021/12/28 03:10:28 dns.go:77: [dns] 127.0.0.1:38967 >>> :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;www.google.com.        IN       A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
; COOKIE: 42f2acdf9c1136e8
2021/12/28 03:10:28 resolver.go:405: [dns] exchange message 39967 via [2001:4860:4860::8888]:53/udp: ;www.google.com.   IN       A
2021/12/28 03:10:28 resolver.go:646: [resolver] cache store www.google.com.IN.A
2021/12/28 03:10:28 dns.go:99: [dns] 127.0.0.1:38967 <- :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1 [12.415149ms]
2021/12/28 03:10:28 dns.go:102: [dns] 127.0.0.1:38967 <<< :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;www.google.com.        IN       A

;; ANSWER SECTION:
www.google.com. 75      IN      A       172.217.171.196

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 512
2021/12/28 03:10:33 dns.go:75: [dns] 127.0.0.1:38967 -> :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
2021/12/28 03:10:33 dns.go:77: [dns] 127.0.0.1:38967 >>> :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;www.google.com.        IN       A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
; COOKIE: 42f2acdf9c1136e8
2021/12/28 03:10:33 resolver.go:629: [resolver] cache hit www.google.com.IN.A
2021/12/28 03:10:33 resolver.go:390: [dns] exchange message 39967 (cached): ;www.google.com.    IN       A
2021/12/28 03:10:33 dns.go:99: [dns] 127.0.0.1:38967 <- :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1 [48.48µs]
2021/12/28 03:10:33 dns.go:102: [dns] 127.0.0.1:38967 <<< :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;www.google.com.        IN       A

;; ANSWER SECTION:
www.google.com. 75      IN      A       172.217.171.196

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 512
2021/12/28 03:10:38 dns.go:75: [dns] 127.0.0.1:38967 -> :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
2021/12/28 03:10:38 dns.go:77: [dns] 127.0.0.1:38967 >>> :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;www.google.com.        IN       A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
; COOKIE: 42f2acdf9c1136e8
2021/12/28 03:10:38 resolver.go:629: [resolver] cache hit www.google.com.IN.A
2021/12/28 03:10:38 resolver.go:390: [dns] exchange message 39967 (cached): ;www.google.com.    IN       A
2021/12/28 03:10:38 dns.go:99: [dns] 127.0.0.1:38967 <- :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1 [24.827µs]
2021/12/28 03:10:38 dns.go:102: [dns] 127.0.0.1:38967 <<< :53: ;; opcode: QUERY, status: NOERROR, id: 39967
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;www.google.com.        IN       A

;; ANSWER SECTION:
www.google.com. 75      IN      A       172.217.171.196

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 512
2021/12/28 03:11:28 kcp.go:357: [kcp] accept stream: broken pipe
2021/12/28 03:11:28 kcp.go:358: [kcp] [2409:8a28:441d:8b90:6cee:1b17:efb7:c03f]:45259 >-< [::]:443
2021/12/28 03:11:28 relay.go:255: [relay] [2409:8a28:441d:8b90:6cee:1b17:efb7:c03f]:45259 >-< 0.0.0.0:53
------
【客户端日志】
2021/12/28 10:10:20 route.go:650: tcp://:443 on [::]:443
2021/12/28 10:10:20 route.go:650: udp://:53 on [::]:53
2021/12/28 10:10:28 udp.go:118: [udp] 127.0.0.1:58956 -> [::]:53 (1)
2021/12/28 10:10:28 udp.go:128: [udp] 127.0.0.1:58956 >>> [::]:53 : length 55
2021/12/28 10:10:28 forward.go:188: [udp] 127.0.0.1:58956 - [::]:53
2021/12/28 10:10:28 forward.go:213: [udp] 127.0.0.1:58956 <-> :53
2021/12/28 10:10:28 udp.go:128: [udp] 127.0.0.1:58956 >>> [::]:53 : length 55
2021/12/28 10:10:28 udp.go:128: [udp] 127.0.0.1:58956 >>> [::]:53 : length 55
2021/12/28 10:10:33 relay.go:287: [relay] [::]:47490 <- %!s(<nil>): broken pipe
2021/12/28 10:10:33 forward.go:215: [udp] 127.0.0.1:58956 >-< :53
2021/12/28 10:10:33 udp.go:111: [udp] 127.0.0.1:58956 closed (0)

**Comment by f4nff** [comment]
【服务端配置】
```
{
"Debug": true,
"Retries": 0,
"ServeNodes": [
"relay+kcp://:443"
]
}
```


【客户端配置】
```
{
"Debug": true,
"Retries": 0,
"ServeNodes": [
"udp://:53/8.8.8.8:53"
],
"ChainNodes": [
"relay+kcp://服务器IP:443"
]
}
```

**Comment by aa51513** [comment]
自身网络问题

**Comment by aa51513** [comment]
自身网络问题
