### ISSUE TITLE
请问 DNS 代理模式是否可以插入自己的解析规则？

### ISSUE THREAD

**Issue by Herbert8** [ginuerzh/gost#778]
请问在 DNS 转发模式下，gost -L dns:// 的模式可以转发已有的代理服务，请问是否可以同时插入自己的一些解析规则？如果可以的话可以作为自建的 DNS 服务使用，比较方便，所以问下是否可以实现这样的功能。

**Comment by aa51513** [comment]
可以自建dn服务器，我现在就是这么用着，当然如果开发大佬们能支持你所说的功能，那是再好不过了

**Comment by ginuerzh** [comment]
具体是什么样的解析规则？

**Comment by ginuerzh** [comment]
3.0中会支持
