### ISSUE TITLE
UDP NAT traversal problem

### ISSUE THREAD

**Issue by lars18th** [ginuerzh/gost#78]
Hi,

I'm testing the last version 2.3. My objective is use only the udp transport (with KCP). So, I have a problem with NAT traversal.

Here my config:

- Server: gost -L=kcp://aes:123456@:8888 -logtostderr -v=3
- Client: gost -L=:1084 -F=kcp://aes:123456@192.168.168.2:8888 -logtostderr -v=5

The server is running in a machine with the IP 192.168.168.2, listening in the port 8888.
The client  is in another network with the "local" IP 192.168.2.4.
The client is behing a NAT router (router "public" IP 192.168.1.1; "local" network is 192.168.2.0).

The problem is related to the **send** udp port used. It seems to be random and different in each running.

When I try to use the tunnel I see these messages in the server:

```
I0203 09:49:10.181627    9773 kcp.go:172] [kcp] 192.168.1.1:46673 >-< :8888
I0203 09:49:11.532673    9773 kcp.go:152] [kcp] 192.168.1.1:46673 - :8888
I0203 09:49:11.532747    9773 kcp.go:165] [kcp] 192.168.1.1:46673 <-> :8888
I0203 09:49:11.580898    9773 kcp.go:171] [kcp] broken pipe
I0203 09:49:11.580953    9773 kcp.go:172] [kcp] 192.168.1.1:46673 >-< :8888
I0203 09:49:13.981966    9773 kcp.go:152] [kcp] 192.168.1.1:46673 - :8888
I0203 09:49:13.982048    9773 kcp.go:165] [kcp] 192.168.1.1:46673 <-> :8888
I0203 09:49:13.982245    9773 kcp.go:171] [kcp] broken pipe
I0203 09:49:13.982263    9773 kcp.go:172] [kcp] 192.168.1.1:46673 >-< :8888
I0203 09:49:16.489494    9773 kcp.go:152] [kcp] 192.168.1.1:46673 - :8888
I0203 09:49:16.489589    9773 kcp.go:165] [kcp] 192.168.1.1:46673 <-> :8888
I0203 09:49:16.489738    9773 kcp.go:171] [kcp] broken pipe
I0203 09:49:16.489851    9773 kcp.go:172] [kcp] 192.168.1.1:46673 >-< :8888
I0203 09:49:19.090382    9773 kcp.go:152] [kcp] 192.168.1.1:46673 - :8888
I0203 09:49:19.090519    9773 kcp.go:165] [kcp] 192.168.1.1:46673 <-> :8888
I0203 09:49:19.090606    9773 kcp.go:171] [kcp] broken pipe
I0203 09:49:19.090620    9773 kcp.go:172] [kcp] 192.168.1.1:46673 >-< :8888
```

As you see the server is sending back udp packets to the "source" address: 192.168.1.1. This corresponds to the "public" IP of the NAT router. However, the "target" port, is a radom value. Then, the problem is how to map this port to the local client.

I suggest to include one option to specify the "source" udp port, or force to use the same destination port for the source port. This simplifies the use of the udp protocol traversing NAT routers.

You agree?

**Comment by ginuerzh** [comment]
In KCP each session corresponds to a fixed port, the port will be saved to the end of the session. Under normal circumstances, a session will be always alive, so your problem may not be caused by NAT router.

**Comment by lars18th** [comment]
Hi,

Sorry! It seems is my fault! I close this issue.
Thank you!
