### ISSUE TITLE
请问可以增加一个CPU架构是 s390x 的版本吗？

### ISSUE THREAD

**Issue by fscarmen** [ginuerzh/gost#789]
用于 IBM Linux1 的，希望能在下个版本增加支持。

**Comment by zjl88858** [comment]
git clone https://github.com/ginuerzh/gost.git
cd gost/cmd/gost
export GOOS=linux
export GOARCH=s390x
go build

善用golang的特性

**Comment by fscarmen** [comment]
嗯，这个会的。我想法是作者加到release里，我脚本判断好 amd64 ,arm64, s390x 之后，官方release里取更好：）

**Comment by ginuerzh** [comment]
最新一版中已经添加。

**Comment by fscarmen** [comment]
> 最新一版中已经添加。

谢谢老大。已增加到我项目去，测试OK。
该项目判断CPU架构并在官方项目下载相应的最新版本，故希望s390x的支持。
