### ISSUE TITLE
套域名后服务器连接失败

### ISSUE THREAD

**Issue by DNLINYJ** [ginuerzh/gost#792]
服务器命令：./gost-linux-amd64-2.11.1 -L=relay+tls://:2181
客户端命令（连接失败）：.\gost-windows-amd64.exe -L=tcp://:16666/:16666 -F=relay+tls://proxycn1.xxxx.xxx:2181
客户端命令（连接成功）：.\gost-windows-amd64.exe -L=tcp://:16666/:16666 -F=relay+tls://139.xxx.xxx.xxx:2181
![image](https://user-images.githubusercontent.com/82745795/155849736-3bde8043-7be8-48e2-b72f-025af039e218.png)

**Comment by ginuerzh** [comment]
域名解析出的IP和你一开始的IP是一样的吗

**Comment by DNLINYJ** [comment]
是一样的

**Comment by la0wei** [comment]
@ginuerzh 借楼问套域名的问题。
服务端：/gost -L mwss://username:password@aaa.com:443
客户端： gost.exe -L=127.0.0.1:1988 -F=mwss://username:password@aaa.com:443
此种情况下可以访问。
此时在cloudflare打开代理，也可以访问。
但服务端重启，在执行相同命令时，解析到的IP时cloudflare的，无法绑定。
gost 是先解析域名再绑定吗？类似caddy申请证书需要验证
