### ISSUE TITLE
为什么我中转的时候都是TLS1.2

### ISSUE THREAD

**Issue by cute-pidan** [ginuerzh/gost#794]
用的腾讯云服务器
服务器端
./gost -L=relay+tls://:18888
客户端 
gost-windows-amd64.exe -L=tcp://:12345/域名:443 -F=relay+tls://服务端IP:18888

能成功中转，但是wireshark里看到基本都是TCP和TLS1.2，要怎么升到TLS1.3啊？

**Comment by ginuerzh** [comment]
Wireshark对于TLS协议，只有从TLS握手开始才能识别真正的TLS版本，如果是从中间抓的就会识别为TLS1.2。

**Comment by ginuerzh** [comment]
TCP是TCP传输层的ACK确认数据包，758中可能使用了过滤。

**Comment by cute-pidan** [comment]
> TCP是TCP传输层的ACK确认数据包，758中可能使用了过滤。

非常感谢您的耐心解答
