### ISSUE TITLE
希望增加RISC-V架构的支持

### ISSUE THREAD

**Issue by emmomme** [ginuerzh/gost#797]
随着RISC-V服务器,VPS 和终端的增多,希望gost增加对RISC-V架构的支持,谢谢.

**Comment by zjl88858** [comment]
git clone https://github.com/ginuerzh/gost.git
cd gost/cmd/gost
export GOOS=linux
export GOARCH=riscv64
go build

善用golang的特性

**Comment by ginuerzh** [comment]
V2.11.3中已添加
