### ISSUE TITLE
Using tun device and wss

### ISSUE THREAD

**Issue by shmul** [ginuerzh/gost#800]
Hi,

Is it possible to use gost with a setup where the client sends TCP packets to a tun device and these are sent over a wss tunnel to a server which then routes the received packets based on their packet destination address?

Cheers,
Shmul

**Comment by ginuerzh** [comment]
TUN is based on UDP, a chain can be used to forward UDP datagram.

server:
```
gost -L tun://:8421?net=192.168.123.1/24 -L relay+wss://:8443
```
client:
```
gost -L tun://:0/:8421?net=192.168.123.2/24 -F relay+wss://SERVER_IP:8443
```
