### ISSUE TITLE
gost客户端使用SS走KCP通道的正确姿势?

### ISSUE THREAD

**Issue by CuminLo** [ginuerzh/gost#81]
服务器上分别单独了安装了SS和KCP并启动(未使用gost)

在客户端我现在的做法是单独安装一个KCP客户端链接到服务器KCP并监听1090
然后使用 gost -L=:8888 -F=ss://rc4-md5:xxoo@127.0.0.1:1090 -v=5 -logtostderr
最后使用127.0.0.1:8888来HTTP代理

现在需求就是怎么实现不需要单独安装KCP客户端,直接用gost来一套搞定(只是客户端)
尝试了几组参数没搞定,而且指定kcp的参数搞不懂

请求大神给予解答,感谢!

**Comment by FlowerWrong** [comment]
目前不支持

**Comment by ginuerzh** [comment]
你是想让SS走KCP通道吗，为什么不直接使用KCP呢。

这个也是可以做到的：
gost -L :8888 -F kcp://server_ip:kcp_port -F ss://server_ip:ss_port

**Comment by CuminLo** [comment]
@ginuerzh 我这样尝试过,但是没成功. 我再研究一下

**Comment by CuminLo** [comment]
@ginuerzh 你好
```
gost -L :8889 -F kcp://aes-128:xxoo@server_ip:80 -F ss://rc4-md5:xxoo@server_id:443 -v=5 -logtostderr
```
失败了.

客户端 gost log
```
I0209 15:21:26.115590   29772 http.go:32] [http] CONNECT 127.0.0.1:58890 - www.google.com:443 HTTP/1.1
I0209 15:21:26.115818   29772 http.go:36] CONNECT www.google.com:443 HTTP/1.1
Host: www.google.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36


I0209 15:21:26.115844   29772 http.go:49]
I0209 15:21:26.115861   29772 chain.go:304] [kcp] new kcp session
I0209 15:21:26.126889   29772 http.go:81] [http] 127.0.0.1:58890 -> www.google.com:443 : max receive buffer must be positive
I0209 15:21:26.126925   29772 http.go:85] [http] 127.0.0.1:58890 <- www.google.com:443
HTTP/1.1 503 Service unavailable
Proxy-Agent: gost/2.3
```

服务器端 kcp log
```
2017/02/09 07:22:56 main.go:355: remote address: 119.129.227.171:21120
2017/02/09 07:22:56 main.go:91: stream opened
2017/02/09 07:22:56 main.go:108: stream closed
2017/02/09 07:22:56 main.go:91: stream opened
2017/02/09 07:22:56 main.go:108: stream closed
2017/02/09 07:22:56 main.go:91: stream opened
2017/02/09 07:22:56 main.go:108: stream closed
2017/02/09 07:22:56 main.go:91: stream opened
2017/02/09 07:22:56 main.go:108: stream closed
2017/02/09 07:22:56 main.go:91: stream opened
```

服务端 SS log
```
没见到有日志
```

是什么问题呢?

**Comment by ginuerzh** [comment]
我用gost(v2.3)作为KCP服务端是可以的，其他的KCP应用(如kcptun)由于在不停的更新，可能与gost的KCP不兼容。

**Comment by drinkmystery** [comment]
@CuminLo 这个问题完全是kcp的配置错误引起的
你使用的kcp.json是kcptun的配置,可以省略一些参数
gost用的是kcp-go,代码实现里 如果使用了自定义kcp配置 就没有单独的默认值 所以不能省略
完整的参数在代码里如下
type KCPConfig struct {
Key string `json:"key"`
Crypt string `json:"crypt"`
Mode string `json:"mode"`
MTU int `json:"mtu"`
SndWnd int `json:"sndwnd"`
RcvWnd int `json:"rcvwnd"`
DataShard int `json:"datashard"`
ParityShard int `json:"parityshard"`
DSCP int `json:"dscp"`
NoComp bool `json:"nocomp"`
AckNodelay bool `json:"acknodelay"`
NoDelay int `json:"nodelay"`
Interval int `json:"interval"`
Resend int `json:"resend"`
NoCongestion int `json:"nc"`
SockBuf int `json:"sockbuf"`
KeepAlive int `json:"keepalive"`
}
你出这个错误就是少了sockbuf

这个issue可以关闭了
