### ISSUE TITLE
建议SS支持AEAD算法

### ISSUE THREAD

**Issue by wxyzh** [ginuerzh/gost#82]
目前[shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.0.0) 已经增加了AEAD算法。
新增了 ```AES-128-GCM,AES-192-GCM,AES-256-GCM,ChaCha20-IETF-Poly1305```算法
参考 [SIP004](https://github.com/shadowsocks/shadowsocks-org/issues/30)

有一个新的Golang版本 [go-shadowsocks2](https://github.com/shadowsocks/go-shadowsocks2)

**Comment by ginuerzh** [comment]
先观望，再考虑要不要更换ss库

**Comment by wxyzh** [comment]
等等吧，go-shadowsocks2 结构还没弄好，而且不支持老的算法

**Comment by ccaapton** [comment]
直接使用go-shadowsocks2已经能连AEAD服务器了，现在可以重新考虑这个问题了吗？

**Comment by everyx** [comment]
新库不支持旧的加密方式也是一个问题，而且貌似以后也不打算支持 https://github.com/shadowsocks/go-shadowsocks2/pull/69

**Comment by ginuerzh** [comment]
可以把go-shadowsocks2当作一种新的协议(ss2://)，这样二者就可以并存了。

**Comment by ginuerzh** [comment]
Done!
