### ISSUE TITLE
请问 ginuerzh/gost 支持调用外部配置文件吗？

### ISSUE THREAD

**Issue by aglent** [ginuerzh/gost#823]
比如下面的docker，好像外部配置文件没生效。
docker run -d \
     --network host \
     --name gost \
     --restart=always \
     -v /etc/gost/config.json:/etc/gost/config.json \
     ginuerzh/gost

**Comment by aglent** [comment]
现在明白了 是少加了一句话

docker run -d \
     --network host \
     --name gost \
     --restart=always \
     -v /etc/gost/config.json:/etc/gost/config.json \
     ginuerzh/gost -C /etc/gost/config.json

**Comment by alexallen1** [comment]
非常感谢思路，很好使
docker run --restart=always --name gost -d -v /home/www/docker/gost/config.json:/etc/gost/config.json --network=host ginuerzh/gost -C /etc/gost/config.json
