### ISSUE TITLE
socks5手机代理出现EOF

### ISSUE THREAD

**Issue by botao1995** [ginuerzh/gost#824]
![image](https://user-images.githubusercontent.com/47848566/166206463-0a5462db-dc96-4176-9476-847eb8c0f515.png)

**Comment by cdswyda** [comment]
请问是否有解决，相同的代码换了个服务器，出现了这个问题？

**Comment by cdswyda** [comment]
发现问题了，是客户端对auth的支持存在问题，换客户端或不加auth即可。

**Comment by imldy** [comment]
客户端内核v2ray-core(v5.1.0)/Xray-core(v1.4.5-sn-4)，服务端为gost(2.11.4)，加密码会提示如上；
服务端更换为sing-box(1.0.7.18162df)正常。
