### ISSUE TITLE
非配置直接参数方式启动，参数失效问题

### ISSUE THREAD

**Issue by wertaaaaex** [ginuerzh/gost#829]
我使用以下命令启动一个绑定指定出口IP和支持UDP的socks5，但是实践发现，interface放前面则udp不生效，udp放前面则interface不生效，我改成使用配置文件 gost.json 启动后发现均支持，请问是我下面启动命令格式错误还是其他原因导致？谢谢

./gost -L socks5://12345:12345@:10010?interface=目标出口IP&udp=true

**Comment by ginuerzh** [comment]
Linux下使用&连接多个参数选项时需要用引号：
```
./gost -L "socks5://12345:12345@:10010?interface=目标出口IP&udp=true"
```

**Comment by wertaaaaex** [comment]
> 

谢谢
