### ISSUE TITLE
With KCP transport: Disabling congestion control the traffic is limited!

### ISSUE THREAD

**Issue by lars18th** [ginuerzh/gost#83]
Hi,

I'm using GOST configured with NO_DELAY and without CONGESTION_CONTROL with this config (also without RESEND):

```
{
        "nodelay": 1,
        "nc": 1,
        "resend": 0
}
```

However, I see with this config that the **input stream** (sending one unlimited udp traffic ) is limited when the bandwith is fully used.

One example: imagine one udp traffic with a bandwith of 10-15mbps. Your total bandwith is 20mbps. Then when you send another stream with 10mbps outside of the gost stream, when the bandwith reach more than 20mbps several packets are discarded. This is OK! However, in this case the GOST **input stream** starts to read slowly. I check this with " -logtostderr -v=4". When the bandwith is exhausted the GOST sender only reads some input packets, and not all packets!

I feel the expected behaviour is continue reading at full speed, and send all packets. I'm wrong?

**Comment by ginuerzh** [comment]
Can you use the [KCPTUN](https://github.com/xtaci/kcptun) to test and compare with gost?

**Comment by lars18th** [comment]
> Can you use the KCPTUN to test and compare with gost?

Hi, 
The problem is that KCPTUN only forwards TCP streams, not UDP !
This is one of the reasons to check GOST instead of KCPTUN.
