### ISSUE TITLE
能否实现起点多重加密

### ISSUE THREAD

**Issue by Steve-L-Ban** [ginuerzh/gost#830]
之前在论坛上看到讨论Tor和gost多重加密的类比：
如果使用多台机器，每台机器上都安装gost，搭建一个gost转发链
能否在起点多重加密，然后在gost转发链中一次次解密，直至明文
如果可以的话，起点和中转的gost应该怎么配置呢？

**Comment by Steve-L-Ban** [comment]
非常感谢作者，然后刚刚又调研了下这个链式和桥式，那请问桥式是不是就实现了在起点多重加密

**Comment by Steve-L-Ban** [comment]
非常感谢作者的回复，我预期使用gost实现Tor的层层加密，现在看来这个功能已经能复现了。

**Comment by ZhuangJiayu** [comment]
这个想法很好，我在尝试在多层加密中混入ssr混淆，绕过mitm
