### ISSUE TITLE
握手协议实现的优化建议

### ISSUE THREAD

**Issue by wen-long** [ginuerzh/gost#833]
建议参考 CPU 分支预测的思路，收发握手包时，预判成功，提前发送后续信息

比如 socks5 客户端，不要等待服务器握手信息，而是一股脑发过去，后续的数据慢慢解析，如果解析出服务器错误，断开连接罢了

再比如多层转发代理，一层一层握手白白浪费时间，客户端可以预判所有的握手都成功，在首个包就一股脑发送全部握手信息和负载(若有)。

可以节约很多时间

**Comment by f4nff** [comment]
来来来，你来，还预判……这概念真牛逼，你懂不懂tcp？

**Comment by wen-long** [comment]
@[f4nff](https://github.com/f4nff) 你好棒啊，给你一朵小红花🌹

**Comment by f4nff** [comment]
越是啥也不懂，越是想当然……

**Comment by wen-long** [comment]
这个关了吧，我看 relay 协议已经是跟 ss 一样没有握手开销了，用 relay 就好

**Comment by wen-long** [comment]
@[f4nff](https://github.com/f4nff) 你说的对极了，🌹
