### ISSUE TITLE
Windows怎么设置后台运行？

### ISSUE THREAD

**Issue by Hhhhelix** [ginuerzh/gost#838]

**Comment by fredwangsap** [comment]
用 clash for windows， 可以配置一下
直接在默认配置中，只加入下面的内容就可以了。

proxies:
- name: "gost"  
  type: http
  server: your domain
  port: your port
  username: xxx
  password: xxx
  tls: true

**Comment by egg1234** [comment]
如果你接受clash for windows这种方式的话，那么也可以试试下面go语言开发的supervisord项目，
https://github.com/ochinchina/supervisord
只需要下载https://github.com/ochinchina/supervisord/releases 里面的windows版本，然后写一个supervisord的启动bat批文件，编辑好supervisor.conf初始配置文件，在windows里面指派这个启动bat文件开机启动（windows指派启动文件方法网上很多教程），之后就可以像linux的supervisor一样去操作这个gost的启停及修改配置文件并重新热加载，
另外提醒一下，由于当前这个版本的supervisord有一个windows里面独有的issues，所以千万不要直接用supervisord的web管理界面去停止进程，因为这样停止的进程不能在web界面再启动，最好的方法是修改supervisor.conf配置文件，然后用web界面的reload命令
