### ISSUE TITLE
Add support for KCP connection statistics collector

### ISSUE THREAD

**Issue by lars18th** [ginuerzh/gost#84]
Hi,

The KCPTUN tool has support for printing the data from the connection statistics collector included in the KCP protocol. This is a function incorporated internally inside the kcp.go implementation.

I suggest to replicate this for logging the status of the KCP connection.
I see that only minimal changes are required:

- Add the function "snmpLogger": http://github.com/xtaci/kcptun/blob/master/server/main.go#L376
- And the "signal.go" interface: http://github.com/xtaci/kcptun/blob/master/server/signal.go

You agree?

**Comment by ginuerzh** [comment]
The `xtaci/kcp-go` library has changed a lot since I used it, so the better choice is to merge the latest commits.

**Comment by lars18th** [comment]
Hi @ginuerzh ,

Can you, please, release a version 2.4rc1 with last commits?
I see the branch 2.4 in development with the updated vendor "kcp-go.v2" and I like to test it.
Another question: This 2.4 branch has the statistics of the KCP connection?

Thank you!

**Comment by ginuerzh** [comment]
No, I just updated the dependent libraries, some new features have not yet been merged.

**Comment by lars18th** [comment]
Hi @ginuerzh ,

> No, I just updated the dependent libraries, some new features have not yet been merged.

But the updated library improves the KCP connection? In this case, I like to test it. ;)

**Comment by ginuerzh** [comment]
I will merge the features this weekend, and a dev version will be released.

**Comment by lars18th** [comment]
> I will merge the features this weekend, and a dev version will be released.

Great! Thank you!

**Comment by ginuerzh** [comment]
The latest dev version has been released, you can test the kcp now.
