### ISSUE TITLE
我觉得让gost支持vmess和trojan比开发v3版本重要一点

### ISSUE THREAD

**Issue by passerbyo** [ginuerzh/gost#848]

**Comment by ginuerzh** [comment]
暂不考虑支持。
vmess是专有协议，并不通用。
trojan本质上就是基于tls或wss传输的协议。

**Comment by L-codes** [comment]
@ginuerzh 既然 trojan本质上就是基于tls或wss传输的协议的，又因为 gost 支持 tls/wss 协议，请问 gost  -F 怎么利用其 tls 或 wss 连接 trojan协议呢？

**Comment by ginuerzh** [comment]
trojan类似于relay+tls的组合，tls之上是自定义协议。

**Comment by L-codes** [comment]
我想用`gost -F`连接 trojan 在本地开一个 socks5，学习了 gost 的文档，没有找到连接的方法，正如你说的 trojan 实际上是在 tls 里自定义协议了，那不是无法使用 gost 实现？

**Comment by L-codes** [comment]
@ginuerzh gost的设计我感觉挺好的，正向代理要是能带上 trojan ss 等支持就很棒，有时候代理的协议不是自己选择的就是不喜欢 trojan的设计，所以才需要 gost 转换代理协议
