### ISSUE TITLE
Microsoft Defender Antivirus

### ISSUE THREAD

**Issue by morying** [ginuerzh/gost#851]
[由 Microsoft Defender Antivirus 检测到](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=VirTool%3aWin32%2fGolly.B&threatid=2147818060) VirTool:Win32/Golly.B
大家是否有碰到此问题，大佬有什么办法解决么？

**Comment by JackZxj** [comment]
@morying 可以试试v3版本，我也报毒，换v3目前没有问题
https://github.com/go-gost/gost
