### ISSUE TITLE
用docker安装的gost为什么提示not found？

### ISSUE THREAD

**Issue by chandler0714** [ginuerzh/gost#854]
使用的是搬瓦工的centos7系统
ssh到服务器然后使用docker安装了gost
参考：https://github.com/haoel/haoel.github.io/issues/73
按照这个教程在配置，但是到了gost -L的时候就提示-bash: gost: command not found
之后去安装了go，但是还是同样提示。。。
求助应该怎么解呀？

**Comment by chandler0714** [comment]
在线等

**Comment by ginuerzh** [comment]
具体命令？

**Comment by ginuerzh** [comment]
```
docker run --rm ginuerzh/gost -V
```
