### ISSUE TITLE
Connection issues for remote port forwarding

### ISSUE THREAD

**Issue by sheerun** [ginuerzh/gost#86]
Hey,

I use remote port forwarding with tls and auth. It seems that not all connections are successful if hitting port repedately. Here's how to reproduce:

server (with cert.pem and key.pem)
```
./gost -logtostderr -v=5 -L=socks://admin:password@0.0.0.0:8080
```

client
```
python -m SimpleHTTPServer 8000
./gost -logtostderr -v=5 -L=rtcp://:2222/0.0.0.0:8000 -F=socks://admin:password@51.15.46.248:8080
```

then:

```
while ~; do curl $SERVER_IP:2222; done
```

here's the output:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html>
<title>Directory listing for /</title>
<body>
<h2>Directory listing for /</h2>
<hr>
<ul>
<li><a href="ca-key.pem">ca-key.pem</a>
<li><a href="ca.csr">ca.csr</a>
<li><a href="ca.pem">ca.pem</a>
<li><a href="csr.json">csr.json</a>
<li><a href="gost">gost</a>
</ul>
<hr>
</body>
</html>
curl: (7) Failed to connect to 51.15.46.248 port 2222: Connection refused
curl: (7) Failed to connect to 51.15.46.248 port 2222: Connection refused
curl: (7) Failed to connect to 51.15.46.248 port 2222: Connection refused
curl: (7) Failed to connect to 51.15.46.248 port 2222: Connection refused
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html>
<title>Directory listing for /</title>
<body>
<h2>Directory listing for /</h2>
<hr>
<ul>
<li><a href="ca-key.pem">ca-key.pem</a>
<li><a href="ca.csr">ca.csr</a>
<li><a href="ca.pem">ca.pem</a>
<li><a href="csr.json">csr.json</a>
<li><a href="gost">gost</a>
</ul>
<hr>
</body>
</html>
curl: (7) Failed to connect to 51.15.46.248 port 2222: Connection refused
curl: (7) Failed to connect to 51.15.46.248 port 2222: Connection refused
curl: (7) Failed to connect to 51.15.46.248 port 2222: Connection refused
curl: (7) Failed to connect to 51.15.46.248 port 2222: Connection refused
```

Here are server logs: http://pastebin.com/ecVBtJ7n
Here are client logs: http://pastebin.com/E56gr9FH

Any idea what is wrong? Why is socks5 connection closing and opening? Why gost doesn't keep the connection alive?

**Comment by sheerun** [comment]
Actually the same happens when not using tls or auth

**Comment by sheerun** [comment]
It might be, that some latency between client and server is required or reproducing this bug.

**Comment by sheerun** [comment]
I've managed to fix it by proxying socks5 connection through socks5 connection...

server
```
./gost -logtostderr -v 5 -L=socks://0.0.0.0:8080
./gost -logtostderr -v 5 -L=tcp://:2222/localhost:8000 -F=socks://localhost:5000
```

client
```
python -m SimpleHTTPServer 8000
./gost -logtostderr -v=5 -L=socks://:5000
./gost -logtostderr -v=5 -L=rtcp://:5000/0.0.0.0:5000 -F=socks://51.15.46.248:8080
while ~; do curl 51.15.46.248:2222; done
```

But this seems like a hacky approach and the latency is terrible... Could you please try to fix this bug, so I can prevent such hacks? Thank you!

**Comment by ginuerzh** [comment]
There needs some tricks: https://groups.google.com/d/msg/go-gost/ouzBXF0Fqk8/c0Wn9_ykCgAJ

**Comment by sheerun** [comment]
Thanks for the response! That's actually the same solution I've came up with in the comment above (with the difference I forward tcp connection instead of http connection), but it still seems hacky :(

Couldn't gost automatically setup persistent connection? I'd imagine that running following:

```
gost -L rtcp://:1443/localhost:8080?persistent=true -F socks://1.2.3.4:1080
```

would actually automatically do behind the scenes the equivalent of following on client side:

```
gost -L socks://localhost:RANDOM1
gost -L rtcp://localhost:RANDOM2/localhost:RANDOM1 -F socks://1.2.3.4:1080
```

and following on server side:

```
gost -L tcp://:1443/localhost:8080 -F socks://localhost:RANDOM2
```

where `RANDOM1` and `RANDOM2` are temporary random port allocated by gost (ideally it could be implemented in-memory without allocating these two extra ports). Please notice the `persistent=true` parameter for rtcp connection.

Is it reasonable?

**Comment by ginuerzh** [comment]
There is a difference between the trick you provided and mine. You expose a SOCKS5 proxy, but it still need to re-bind when a connection is established, in fact it's the same as the original method.

HTTP2 supports multiplexing several streams over a single connection, so when forwarding through HTTP2 proxy, only one connection holds, this is analogous to the `persistent` param in your proposal.

I admit the better option is to implement persistent connection directly, but it may need to make significant changes to the socks5 protocol, or change to other protocol that supports multiplexing.

**Comment by sheerun** [comment]
It's not entirely the same, as the second socks server on server side:

```
gost -L tcp://:1443/localhost:8080 -F socks://localhost:RANDOM2
```

doesn't do reverse port forwarding, but rather forward port forwarding.

It seems that forward port forwarding with socks has no issues with short-lived sessions, as I experience issues only for short-living **reverse** port forwarding. I hope you get what I mean :)

**Comment by ginuerzh** [comment]
Yes, I understand what you said. A single persistent connection for reverse port forwarding needs the connection support **multiplexing** (such as HTTP2), but SOCKS does not have this feature, so the short-lived sessions (HTTP) does not work, you will get many connection refused errors when there are multiple concurrent HTTP requests.

**Comment by sheerun** [comment]
Okay then, I'll leave it up to you what to do with this issue. Feel free to close it.

**Comment by sheerun** [comment]
btw. I was under impression that forward tcp forwarding requires SOCKS5 proxy, but it seems it's only the case for UDP forwarding. Maybe you could consider following alternate version:

---

Running following:

```
gost -L rtcp://:1443/localhost:8080?persistent=true -F socks://1.2.3.4:1080
```

would automatically do behind the scenes the equivalent of following on client side:

```
gost -L http2://localhost:RANDOM1
gost -L rtcp://localhost:RANDOM2/localhost:RANDOM1 -F socks://1.2.3.4:1080
```

and following on server side:

```
gost -L tcp://:1443/localhost:8080 -F http2://localhost:RANDOM2
```

where `RANDOM1` and `RANDOM2` are temporary random port allocated by gost (ideally it could be implemented in-memory without allocating these two extra ports).

**Comment by ginuerzh** [comment]
Maybe the SSH protocol can be used to achieve this goal, I will check it later.

**Comment by ginuerzh** [comment]
The latest version (v2.4-dev) has support the ssh tunnel for tcp port forwarding, it works well for short-live connections.

server:
gost -L ssh://:2222

client:
gost -L rtcp://0.0.0.0:8080/127.0.0.1:80 -F ssh://server:2222

**Comment by sheerun** [comment]
I get following issue then trying to `go get` gost from 2.4 branch ;/

# github.com/lucas-clemente/quic-go/h2quic
../../lucas-clemente/quic-go/h2quic/request_writer.go:64: undefined: httplex.PunycodeHostPort

**Comment by ginuerzh** [comment]
All third-party dependent libraries are in the `cmd/gost/vendor` directory, you just need to clone the repo:
```bash
$ git clone https://github.com/ginuerzh/gost.git
$ cd cmd/gost
$ go build
```

I also released the binary files of dev version: https://github.com/ginuerzh/gost/releases/tag/v2.4-dev

**Comment by sheerun** [comment]
@ginuerzh I'm testing your implementation :) So far one bug:

```
./gost -L rtcp://:8001/127.0.0.1:8000 -F ssh://admin:password@localhost:2222
```

```
I0309 15:51:12.750002   96798 ssh.go:146] [ssh-rtcp] listening tcp <nil>:8001
I0309 15:51:12.790475   96798 ssh.go:149] [ssh-rtcp] listen tcp: lookup <nil>: no such host
```

but following is ok:

```
./gost -L rtcp://127.0.0.1:8001/127.0.0.1:8000 -F ssh://admin:password@localhost:2222
```

**Comment by sheerun** [comment]
Also, performing the trick we used for socks5 connections seems to be beneficial for ssh reverse tunnel as well, as without it ssh seems to allocate new port upon each connection, like so:

```
I0309 15:22:34.629725   37230 ssh.go:203] [ssh-rtcp] 78.10.86.9:64148 <-> 10.0.1.4:8001
I0309 15:22:34.670108   37230 ssh.go:205] [ssh-rtcp] 78.10.86.9:64148 >-< 10.0.1.4:8001
I0309 15:22:34.792436   37230 ssh.go:203] [ssh-rtcp] 78.10.86.9:64150 <-> 10.0.1.4:8001
I0309 15:22:34.830017   37230 ssh.go:205] [ssh-rtcp] 78.10.86.9:64150 >-< 10.0.1.4:8001
I0309 15:22:34.949684   37230 ssh.go:203] [ssh-rtcp] 78.10.86.9:64152 <-> 10.0.1.4:8001
I0309 15:22:34.985315   37230 ssh.go:205] [ssh-rtcp] 78.10.86.9:64152 >-< 10.0.1.4:8001
I0309 15:22:35.105746   37230 ssh.go:203] [ssh-rtcp] 78.10.86.9:64154 <-> 10.0.1.4:8001
I0309 15:22:35.142539   37230 ssh.go:205] [ssh-rtcp] 78.10.86.9:64154 >-< 10.0.1.4:8001
I0309 15:22:35.267390   37230 ssh.go:203] [ssh-rtcp] 78.10.86.9:64156 <-> 10.0.1.4:8001
I0309 15:22:35.303185   37230 ssh.go:205] [ssh-rtcp] 78.10.86.9:64156 >-< 10.0.1.4:8001
I0309 15:22:35.425128   37230 ssh.go:203] [ssh-rtcp] 78.10.86.9:64158 <-> 10.0.1.4:8001
I0309 15:22:35.425279   37230 ssh.go:205] [ssh-rtcp] 78.10.86.9:64158 >-< 10.0.1.4:8001
```
