### ISSUE TITLE
请教下，v2.11.3 版本发生了什么改变？ virustotal 病毒扫描数量相比上个版本增加了一倍多

### ISSUE THREAD

**Issue by m2acgi** [ginuerzh/gost#862]
不是不信任 gost, 单纯从技术上请教下，相比上个版本有什么具体的异同。

![2022-08-22_09-59-14_chrome](https://user-images.githubusercontent.com/34497122/185824253-0ef17eb5-aba2-4346-9df5-5c8034cc1dcb.png)

![2022-08-22_09-58-19_chrome](https://user-images.githubusercontent.com/34497122/185824259-7b53a216-1653-4bb6-b359-32764cd1cdcb.png)

**Comment by ylot0** [comment]
我也觉得奇怪，这个版本按说很稳定不会再动了的，但这段时间使用netstat -antp多了CLOSE_WAIT，导致资源占尽，服务器当机。

**Comment by ginuerzh** [comment]
2.11.4已经修复
