### ISSUE TITLE
用户名和 密码中有特殊字符，怎么输入？

### ISSUE THREAD

**Issue by lzuxz** [ginuerzh/gost#863]
大家好，我在使用中碰到一个问题，因为自己使用的ss密码有特殊字符比如‘.}’这一类的，输入密码的时候总出问题，请问有没有解决的办法，比如加""或者加''?

**Comment by chkai81** [comment]
可以通过auth参数使用base64值，这里有说：https://latest.gost.run/concepts/auth/

**Comment by lzuxz** [comment]
即使这样输入了，还是会有
ss.go:605: [ss] cipher not supported
这样的输出，不知道是ss的问题还是gost的问题，特殊字符在密码中不能用
