### ISSUE TITLE
【求助】带有SNI的SOCKS5 Over TLS在客户端转SOCKS5不成功

### ISSUE THREAD

**Issue by Hokia** [ginuerzh/gost#868]
服务端如下运行：
gost -L=socks+tls://user:passwd@:8091?cert=/path/cert.pem&key=/path/key.pem

客户端官网没有现成的举例我拼接尝试如下：
gost -L=:8090 -F=socks5+tls://domain.com:8091?host=domain.com
gost -L=:8090 -F=tls://domain.com:8091?host=domain.com

目的是在客户端实现8090端口socks5直接连接但没有成功，提示“ connection reset by peer”，服务端有domain.com白名单。

在写此贴时做了如下尝试就成功了，说明socks+tls包括用户名密码要一起解除，使用本地8090端口则没有用户名密码。
gost -L=:8090 -F=socks5+tls://user:passwd@domain.com:8091?host=domain.com

**Comment by zhenjie1022** [comment]
gost -L=:8090 -F=forward+tls://domain.com:8091?host=domain.com
客户端这样写才对，文档里是有的
