### ISSUE TITLE
Support ip/port whitelist for SOCKS bind and SSH forward tunnel

### ISSUE THREAD

**Issue by ginuerzh** [ginuerzh/gost#87]
This is a proposal from https://github.com/ginuerzh/gosocks5/issues/1

**Comment by lars18th** [comment]
Hi,

I agree! This is a must have to limiting the UDP forward to only whitelisted ips/ports. Using this is possible to use it in a public IP address. Great!

I like to see soon this implement. ;)
Thank you!
