### ISSUE TITLE
udp 不通

### ISSUE THREAD

**Issue by f4nff** [ginuerzh/gost#871]
```
gost -L=relay+wss://:8811
gost -L=:1080 -F=relay+wss://127.0.0.1:8811
```

通过socks5连接1080 ，
udp测试不通。

**Comment by ginuerzh** [comment]
v2版本中的relay只能用在端口转发中，v3版本支持socks5 UDP。

**Comment by f4nff** [comment]
得空可以修复下，
v2用习惯了，
v3完全不会用，
v2的用户群是v3的好几倍吧，
relay握手比socks5快。
