### ISSUE TITLE
在v2.11.3版本及以后，同样的配置会报错resolver: domain  does not exists

### ISSUE THREAD

**Issue by jxjeff** [ginuerzh/gost#883]
如图，貌似没有找到原因
![photo_2022-09-27_09-54-30](https://user-images.githubusercontent.com/28191881/192413315-679c417a-dd69-497d-80f4-3764caf8801b.jpg)
![photo_2022-09-27_09-55-03](https://user-images.githubusercontent.com/28191881/192413321-f8334354-6405-4009-9849-fd2ced8f560c.jpg)

**Comment by aglent** [comment]
我也遇到了 2.11.3和2.11.4 就会报错，只能退回到2.11.2。

**Comment by haoasdasdf** [comment]
昨天刚想发issue，我也是遇到了同样问题没有解决。

**Comment by tonyshaoxu** [comment]
+1

**Comment by shiftu** [comment]
+1

**Comment by abcskjowjeoj** [comment]
+1
