### ISSUE TITLE
faketls

### ISSUE THREAD

**Issue by hiddify-com** [ginuerzh/gost#884]
Current TLS proxy  is awesome, however it would be great if we can have faketls.

For instance, we setup our proxy with sni of google.com and a user and password
if the user and password is not passed we just forward the proxy to https://google.com

It is the suggestion to improve gost to be undetectable.
[Telegram MTProxy](https://github.com/alexbers/mtprotoproxy) has provided similar approach

**Comment by ginuerzh** [comment]
Maybe probing resistance is what you need.
https://v2.gost.run/en/probe_resist/

**Comment by hiddify** [comment]
No it is not the same
in tls probe_resist, it will check tls and then it will check the authentication. So we can not use for example google.com probe_resist without certificate error.

**Comment by r3a1d3a1** [comment]
[Shadow-tls](https://github.com/ihciah/shadow-tls/blob/master/docs/protocol-en.md) may be what you're looking for.
