### ISSUE TITLE
Support preserving original source IP with UDP tunnel

### ISSUE THREAD

**Issue by SonOfBytes** [ginuerzh/gost#89]
We are forwarding UDP agents to a server that needs to know the the originating source IP so it can distinguish the records between originating servers.

Is there an option to preserve the original IP with UDP tunnel once it is sent from the last gost agent to the destination server:port?

**Comment by ginuerzh** [comment]
It a one-to-one relationship mapping from the original source IP/port to the gost endpoint.
For the destination server, there is no way to know the original source IP/port.
The only thing you can do is to control the timeout of this relationship, the `ttl` parameter.

**Comment by SonOfBytes** [comment]
Ok thank you for clarifying!
