### ISSUE TITLE
HTTP3支持计划？

### ISSUE THREAD

**Issue by meiyingqishi** [ginuerzh/gost#890]
请问有HTTP3支持计划吗？

**Comment by ginuerzh** [comment]
请使用v3版本：https://gost.run/tutorials/protocols/http3/

**Comment by hktalent** [comment]
@ginuerzh 
抱歉，我在代码中没有看见HTTP3相关呢？
是我错过什么了吗？

另外能加上
mDNS（Multicast DNS，组播域名）
吗？
当私有网络中
A 节点无法上互联网，但是他和 B节点的key（id）是一样的，也就是身份鉴别是“自己人”
那么 A 可以通过 mDNS 发现更多节点，并通过他们 连接到互联网

很想一起共享，可惜golang功力有限
非常感谢

**Comment by ginuerzh** [comment]
HTTP/3目前仅为初步支持，后续会增加对WebTransport的支持，相关代码在V3版本中：https://github.com/go-gost/x/tree/master/listener/http3

mDNS用于服务发现是不错的选择，但GOST会尽量减少对外部服务的直接依赖以降低复杂度。节点的选择也可以通过Hop插件来实现：https://gost.run/concepts/hop/#_9

**Comment by hktalent** [comment]
@ginuerzh 

抱歉，我一直尝试想通过WebRTC实现中间服务器交换节点信息，然后实现节点的发现，并通过其他节点建立socks5
但是golang基础不好，没有成功，如果您将来实现就好了

为什么要基于WebRTC发现其他节点呢？因为不想用自己的服务器做server。避免被GFW，而其他webrtc server是动态的ip，甚至可能是私有网络，但是可以访问google等这些受限网络
