### ISSUE TITLE
gost socks5 黑白名单

### ISSUE THREAD

**Issue by halee1123** [ginuerzh/gost#892]
socks5 代理 如果无验证,如何添加黑白名单.测了很多方法都不行,怎么让某一个ip地址可以连接代理呢？

**Comment by FlashIvano** [comment]
我也碰到同样的问题。socks5 标准代理下，配置分流器无效，且所有请求都会失败。

**Comment by ginuerzh** [comment]
黑白名单是v3版本的功能：https://gost.run/concepts/admission/
