### ISSUE TITLE
希望日志功能可以增强

### ISSUE THREAD

**Issue by FlashIvano** [ginuerzh/gost#894]
现在连时间都无法记录........

**Comment by helloworldyuhaiyang** [comment]
`
{"caller":"http/handler.go:75","duration":5064657729,"handler":"http","kind":"handler","level":"info","listener":"tcp","local":"10.100.195.188:8080","msg":"10.100.80.0:10851 >< 10.100.195.188:8080","remote":"10.100.80.0:10851","service":"service-0","time":"2022-10-08T06:01:03.130Z"}
`

你的日志难道不是这样的吗
