### ISSUE TITLE
Add HTTP header

### ISSUE THREAD

**Issue by KiarashS** [ginuerzh/gost#90]
Dear,

How we can add HTTP headers to requests, `Like HTTP cookie header`?

Thanks

**Comment by ginuerzh** [comment]
No, the HTTP proxy (protocol layer) does not support setting headers, except for basic authentication.

**Comment by KiarashS** [comment]
We need a proxy for load a remote web site with modify request headers and show the response to user, What is the best open source tool/library for this purpose?

**Comment by ginuerzh** [comment]
May be the [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) can help you.
