### ISSUE TITLE
https代理认证问题

### ISSUE THREAD

**Issue by ykelvis** [ginuerzh/gost#91]
gost -v=4 -logtostderr -L=http://127.0.0.1:8119 -F=http+tls://user:pass@server:port

当使用需认证的https代理时，访问http页面依旧会提示输入用户名密码。

访问https页面不会提示，如果-L是socks5也不会提示。

![screen shot 2017-02-19 at 7 04 29 pm](https://cloud.githubusercontent.com/assets/2928657/23101773/892887b6-f6d6-11e6-8f23-7adc2bdccf2b.jpg)

```
$ gost -V
gost 2.3 (go1.7.4)
```

**Comment by ginuerzh** [comment]
我这边无法复现，只有在客户端的认证信息与服务器设置的不一致时才会弹出认证窗口。
你的服务器端运行命令是什么？

**Comment by ykelvis** [comment]
这个不知道，买的服务不是自己搭的

**Comment by ginuerzh** [comment]
这需要知道服务器端的代理配置方式才能进行分析。

**Comment by ginuerzh** [comment]
你可以尝试用chrome+switchyomega直接使用这个https代理看看有没有问题。

**Comment by ykelvis** [comment]
试了下，直接chrome+swithyomega设置用没问题

**Comment by ginuerzh** [comment]
OK，我已经复现了这个问题，当服务器是HTTP2代理类型，客户端用常规HTTPS代理类型去连接时非CONNECT请求会报407错误，你用HTTP2去连接应该就可以了：
gost -v=4 -logtostderr -L=http://127.0.0.1:8119 -F=**http2**://user:pass@server:port

**Comment by ykelvis** [comment]
感觉不是一个问题..我这服务器用了-F=http2什么都打不开了

**Comment by ginuerzh** [comment]
最新版已经修正了一个类似的bug，不一定解决了你的问题，不过你也可以试用一下看看可不可以。

**Comment by ykelvis** [comment]
用了一天，的确没再遇到那个问题了，谢谢。
