### ISSUE TITLE
socks5: BIND is disabled

### ISSUE THREAD

**Issue by woqutech-qdecoder** [ginuerzh/gost#916]
按照这个文档里面跑rtcp远程端口映射的时候https://groups.google.com/g/go-gost/c/_-akAbTe3ho
proxy_host会报错`{"cmd":"mbind","dst":":5788/tcp","handler":"socks","kind":"handler","level":"error","listener":"tcp","local":"10.10.30.5:1080","msg":"socks5: BIND is disabled","remote":"10.10.30.127:46498","service":"service-0","time":"2022-12-26T22:18:59.614+08:00"}`

**Comment by woqutech-qdecoder** [comment]
确认过了，v3跑会有这个问题，v2跑没问题

**Comment by victoryhb** [comment]
遇到同样问题，v3的文档和功能还远不及v2完善

**Comment by ginuerzh** [comment]
BIND功能在v3中默认为禁用状态，参考https://gost.run/tutorials/port-forwarding/#_4 中的限制部分说明。
