### ISSUE TITLE
ICMP是怎么执行的？抓包看是tcp啊？

### ISSUE THREAD

**Issue by ghost** [ginuerzh/gost#927]
网站https://latest.gost.run/en/tutorials/icmp/上面说的是错的，它上面说：
server : gost -L icmp://:0
client : gost -L :8080 -F "relay+icmp://server_ip:12345?keepAlive=true&ttl=10s"
实际这样执行会报错。

把client改成icmp或者server改成relay+icmp后可以通，但是抓包看都是tcp啊。

**Comment by fannwong001** [comment]
哦哦，那命令执行是不是应该提示失败呢。

**Comment by ginuerzh** [comment]
目前如果使用未识别的传输类型会fallback到TCP模式。
