### ISSUE TITLE
公司代理服务器是NTLM验证

### ISSUE THREAD

**Issue by 5high** [ginuerzh/gost#93]
软件可以直接通过验证吗，还是需要填写域登录信息？

**Comment by ginuerzh** [comment]
目前的认证方式只支持用户名/密码认证

**Comment by 5high** [comment]
今后是否可以考虑增加NTLM认证

**Comment by 5high** [comment]
I0301 09:34:45.340880   35604 conn.go:217] HTTP/1.1 407 Proxy Authentication Required
Content-Length: 3332
Content-Type: text/html
Date: Wed, 01 Mar 2017 01:34:59 GMT
Proxy-Authenticate: NTLM
Proxy-Connection: close

**Comment by ginuerzh** [comment]
这属于较特殊的认证方式，目前暂不支持。
