### ISSUE TITLE
gost -L=rtcp://:1234/1.1.1.1:80 重定向后，返回的地址里丢失端口。

### ISSUE THREAD

**Issue by wgf4242** [ginuerzh/gost#938]
首先80端口已经被别的占用的。当前ip是 2.2.2.2

gost -L=rtcp://:1234/1.1.1.1:80

访问 2.2.2.2:1234 后返回 1.1.1.1:80 的结果。然后重定向到 /test. 这时地址变成 2.2.2.2/test 。 丢失了端口，返回不了页面了。

正确的地址应该为 2.2.2.2:1234/test

怎么解决？

**Comment by ginuerzh** [comment]
这是重定向的问题，端口转发本身解决不了，除非使用80端口。
