### ISSUE TITLE
How use Cloudflare CDN on the Gost ?

### ISSUE THREAD

**Issue by esmaeilch81** [ginuerzh/gost#944]
Hello friends, I use Ghost to tunnel between two internal and external servers, and it works well, but after a few days, the IP of the server outside of Iran is filtered.
These are the codes that I use for the Iranian server

gost -L tcp://:443/127.0.0.1:443 -F relay wss://Server_out_domain.com:8443

And the codes that I put out on the server side are this

gost -L relay wss://:8443

When I turn on cloudflare's cdn for a foreign domain, the connection is disconnected.
Can anyone guide?

**Comment by esmaeilch81** [comment]
> Beside that it's ridiculous to use github issues for question and answer help; it's not "Ghost"! When you learn to read and write proper name; then you will get one step closer to read the available tutorials.

I suggest that when you don't know the answer to a question, please shut up and let others answer.
The solution is to use mwss ghost and https ports

**Comment by Generator20** [comment]
@esmaeilch81, From which datacenter did you get your IR server ?
It doesn't work for me! [Fucking Hostiran] :-(
