### ISSUE TITLE
Windows 10/ 11 会自动删除 gost

### ISSUE THREAD

**Issue by DamianSheldon** [ginuerzh/gost#947]
最近在 Windows 上使用 gost, 发现 Windows 会自动把 zip 包和可执行文件都删除掉，Mac 上用 BootCamp 安装的 Windows 10， 新买的联想小新 Pro 16 带的是 Windows 11。 Windows 10/ 11 都出现了这种情况。不知道有没有其他人遇到过，又或者有什么解决办法。

**Comment by cwt8805** [comment]
遇到同样的问题，Windows defender会报毒删除

**Comment by cwt8805** [comment]
自己编译的也被删掉了，希望解决一下这个问题

**Comment by DamianSheldon** [comment]
暂时通过[将排除项添加到 Windows 安全中心](https://support.microsoft.com/zh-cn/windows/%E5%B0%86%E6%8E%92%E9%99%A4%E9%A1%B9%E6%B7%BB%E5%8A%A0%E5%88%B0-windows-%E5%AE%89%E5%85%A8%E4%B8%AD%E5%BF%83-811816c0-4dfd-af4a-47e4-c301afe13b26) 绕过了。
