### ISSUE TITLE
阿里云服务器socks转发udp出现问题

### ISSUE THREAD

**Issue by supppig** [ginuerzh/gost#95]
服务端配置：IP：114.215.140.*   gost启动参数： -L=socks://supppig:password@:6699  -v=5

客户端：
gost参数：-L=socks://127.0.0.1:1251 -F=socks://127.0.0.1:1252 -F=socks://supppig:password@114.215.140.*:6699
注：127.0.0.1:1252是SSR客户端，114.215.140.*是服务器IP
redsocks2绑定前段端口1250，后端端口1251
通过iptables的TPROXY转发UDP数据包到redsocks2端口，仅转发UDP数据。

客户端运行虎牙视频APP（这个APP用UDP连接视频）
出现的问题是：
如果SSR服务器和gost服务器是同一个服务器，就会出现bug（见log）。表现为虎牙视频无法播放视频。
而如果换一个SSR服务器（log中SSR的IP是59.111.101.*，gost服务器还是114.215.140.* 且配置不变），该bug不会出现。虎牙视频正常播放。

目前该bug仅发现出现在阿里云服务器（测试时是centos7，防火墙已关闭。换成Ubuntu同样存在该问题）上，如果是网易的服务器或者其他服务器，没出现这个bug。

[本地连接gost不正常.txt](https://github.com/ginuerzh/gost/files/811051/gost.txt)
[外网连接gost正常.txt](https://github.com/ginuerzh/gost/files/811050/gost.txt)

**Comment by ginuerzh** [comment]
从log上看是有udp数据交互的，说明udp通道已经建立成功了。
我也在阿里云上测试过，udp数据交互是正常的。
如果是在同一台服务器上，你可以再尝试一下：
gost -L=socks://127.0.0.1:1251 -F=socks://127.0.0.1:1252 -F=socks://supppig:password@**:6699**
这样udp会绑定在本地回路(127.0.0.1)上。

如果能提供客户端的日志，可能更有助于分析问题。
