### ISSUE TITLE
服务端 ss之后 还能定向到socks5吗

### ISSUE THREAD

**Issue by jnxyatmjx** [ginuerzh/gost#950]
比如配置如下
服务端 -L wss://xx:yy@:443/:8080 -L ss://none:@:8080
这个ss之后还能把流量定位到socks5服务吗？

**Comment by jnxyatmjx** [comment]
本地 shadowsocks客户端 通过wss方式  链接远端到远端shadowsocks
比如如下配置
svr  -L wss://12:dd@:8443/:8080 -L ss://none:@:8080
cli   -L tcp://172.30.1.2:17569 -L udp://172.30.1.2:17569  -F forward+wss://12:dd@ip:8443

现在 如果想在远端shadowsocks后面 再指向socks5服务可行吗？比如
svr  -L wss://12:dd@:8443/:8080 -L ss://none:@:8080 -F socks5:127.0.0.1:40000
目前看是不行的。

**Comment by yourNameIsGood** [comment]
port  40000   想必也是 cf 的 warp client 吧？ 
我觉得没问题  你跑起来试试就知道了

**Comment by jnxyatmjx** [comment]
> port 40000 想必也是 cf 的 warp client 吧？ 我觉得没问题 你跑起来试试就知道了
对的，不过我这边一直不成功。有报错

**Comment by jnxyatmjx** [comment]
> port 40000 想必也是 cf 的 warp client 吧？ 我觉得没问题 你跑起来试试就知道了



> port 40000 想必也是 cf 的 warp client 吧？ 我觉得没问题 你跑起来试试就知道了

服务端--》./gost-2.11.5 -L wss://hh:23@:8443/:8080 -L ss://none:@:8080 -F socks5://127.0.0.1:40000
客户端--》-L tcp://192.168.199.184:17569 -L udp://192.168.199.184:17569  -F forward+wss://hh:23@hkk.amabc.xyz:8443

会有类似这个错误
2023/04/01 19:36:33 ws.go:413: [ws] 140.206.194.4:44106 -> [::]:8443
2023/04/01 19:36:33 forward.go:109: [tcp] ip:44106 - ip1:8443
2023/04/01 19:36:33 ws.go:413: [ws] ip:44104 -> [::]:8443
2023/04/01 19:36:33 forward.go:109: [tcp] ip:44104 - ip1:8443
2023/04/01 19:36:33 forward.go:137: [tcp] ip:44104 -> ip1:8443 : unexpected EOF

**Comment by jnxyatmjx** [comment]
address this problem by fix unexpected EOF bug

**Comment by leyafo** [comment]
> > port 40000 想必也是 cf 的 warp client 吧？ 我觉得没问题 你跑起来试试就知道了
> 
> > port 40000 想必也是 cf 的 warp client 吧？ 我觉得没问题 你跑起来试试就知道了
> 
> 服务端--》./gost-2.11.5 -L wss://hh:23@:8443/:8080 -L ss://none:@:8080 -F socks5://127.0.0.1:40000 客户端--》-L tcp://192.168.199.184:17569 -L udp://192.168.199.184:17569 -F forward+wss://hh:[23@h.123.xyz](mailto:23@h.123.xyz):8443
> 
> 会有类似这个错误 2023/04/01 19:36:33 ws.go:413: [ws] 140.206.194.4:44106 -> [::]:8443 2023/04/01 19:36:33 forward.go:109: [tcp] ip:44106 - ip1:8443 2023/04/01 19:36:33 ws.go:413: [ws] ip:44104 -> [::]:8443 2023/04/01 19:36:33 forward.go:109: [tcp] ip:44104 - ip1:8443 2023/04/01 19:36:33 forward.go:137: [tcp] ip:44104 -> ip1:8443 : unexpected EOF

Thank you, It works.
