### ISSUE TITLE
Wrong use of the DST.ADDR and DST.PORT in UDP ASSOCIATE request???

### ISSUE THREAD

**Issue by drinkmystery** [ginuerzh/gost#96]
According to the rfc1928:
https://github.com/ginuerzh/gosocks5/blob/master/rfc1928.txt#L348-L355
<pre>
The DST.ADDR and DST.PORT fields contain the address and port
that the client expects to use to send UDP datagrams <b>!on!</b> for the association.
The server <b>MAY</b> use this information to limit access to the association. 

It's <b>on</b>. It's not <b>to</b>.
</pre>

https://github.com/ginuerzh/gosocks5/blob/master/rfc1928.txt#L424-L428
<pre>
The UDP relay server MUST acquire from the SOCKS server
<b>the expected IP address of the client</b>
that will send datagrams
to the BND.PORT given in the reply to UDP ASSOCIATE. 
It MUST drop any datagrams
arriving from any source IP address other than
<b>the one recorded for the particular association</b>.

I think this IP is the IP which client used to establish tcp connection to the SOCKS5 server or
the DST.ADDR in UDP ASSOCIATE request.

</pre>

So I think the DST.PORT in UDP ASSOCIATE request is the **source port**
which client will use for sending UDP packet to the UDP relay server.
**Its not a hint for the SOCKS5 server to choose UDP relay port.**

This project use the DST.PORT as UDP relay port.
In socks.go:
https://github.com/ginuerzh/gost/blob/master/socks.go#L255-L257
```
bindAddr, _ := net.ResolveUDPAddr("udp", req.Addr.String())
relay, err := net.ListenUDP("udp", bindAddr)
```

If a client want to use port XXX as the source port to send UDP packet through the gost,
it will send this port XXX as the DST.PORT to the gost. 
Then it will send from this port to the udp relay port.
However the gost reply says the udp relay port (BND.PORT) is the same port XXX.
So the client will send packet from port XXX to port XXX.

When the client and the gost SOCKS5 server is running on same host.
The client will send packet to itself.

This Example code(gost listen on 8080):
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#UDP client with SOCKS5 proxy
import socket, sys
import socks
SOCKS5_PROXY_IP = "127.0.0.1"
SOCKS5_PROXY_PORT = 8080
TARGET_IP = "127.0.0.1"
TARGET_PORT = 9999
s = socks.socksocket(socket.AF_INET, socket.SOCK_DGRAM)
s.set_proxy(socks.SOCKS5, SOCKS5_PROXY_IP, SOCKS5_PROXY_PORT)
s.sendto('This is client message', (TARGET_IP, TARGET_PORT))
data, address = s.recvfrom(1024)
print 'The server', address, 'says', repr(data)
```
Just run this client and gost(no need udp server).
A real client output:
The server ('127.0.0.1', 9999) says 'This is client message'

I use the PySocks library as SOCKS5 proxy client library.
And I have read its source code.
The PySocks library will use a random port as the source port to send UDP packet.
It uses this random port as DST.PORT in UDP ASSOCIATE request.
I think PySocks is ok. It reach the specifications of the rfc1928.
So this project gost maybe is using DST.ADDR and DST.PORT in UDP ASSOCIATE request
the wrong way?

**Comment by ginuerzh** [comment]
Yeah, you are right, I misunderstood the spec, and I also found some unusual behavior when the client and server are on same host before, now I know the reason, Thanks!
