### ISSUE TITLE
&probe_resist 503

### ISSUE THREAD

**Issue by systemctls** [ginuerzh/gost#963]
-L "http2://:443?secrets=${Secrets}&cert=${CERT}&key=${KEY}&&probe_resist=file:/root/gost/index.html&knock=www.google.com"

访问的域名得到的结果是 503，没有展示这个index.html

**Comment by nobodyintheworld** [comment]
我遇到一样的问题，你解决了吗？

**Comment by systemctls** [comment]
> 我遇到一样的问题，你解决了吗？

没有解决，

**Comment by nobodyintheworld** [comment]
我解决了。。。我刚看了下go代码，应该不是bug，而是docker的时候没有带上-v，，，带上就解决了。。。希望对你哟用

**Comment by systemctls** [comment]
> 我解决了。。。我刚看了下go代码，应该不是bug，而是docker的时候没有带上-v，，，带上就解决了。。。希望对你哟用

哈哈哈，确实，要-v映射进来。感谢感谢

?secrets=${Secrets}&cert=${CERT}&key=${KEY}&probe_resist=file:${Files}&knock=www.google.com"
