### ISSUE TITLE
使用特定类型的 cdn

### ISSUE THREAD

**Issue by HEISEN3ERG** [ginuerzh/gost#965]
亲爱的朋友们，来自伊朗的问候，我正在尝试实现从 GFW 内的 vps A 到 GFW 外的 vps B 的隧道，因为 cloudflare IP 有严格的带宽限制，并且不使用 cdn 会导致 vps B IP 在使用 200-300 GB 的数据后被检测到并受到限制。
所以我设法扫描了范围广泛的 cloudflare cdn IP，并发现了一些白名单 IP，这些 IP 在我的 vps A 中完全不受限制，我如何使用我发现的特定白名单 cloudflare IP 建立隧道到我的 vps B？ 我已将它们放在一个域名下，并在 cloudflare 仪表板下关闭了代理状态，因此如果它们稍后进入黑名单，我可以轻松更改它们。

**Comment by la0wei** [comment]
@HEISEN3ERG If you know how to create a tunnel, let's say you already have  one like A<=====websocket==>B

maybe you can set hosts to specific ip on vps A
