### ISSUE TITLE
关于 代理协议类型 的一个想法。

### ISSUE THREAD

**Issue by jzp820927** [ginuerzh/gost#98]
只是提一个关于 代理协议类型 的一个想法，不知道合不合理。。。
看到目前 gost 支持的 代理模式 已经非常丰富了，基本上主流的（比如：ss，kcp 等），标准的（比如：http，socks）都支持了。但是我感觉还有一种代理模式也很实用，不知道 ginuerzh 大，是否考虑开发支持？就是 sniproxy 模式。

比如服务端通过 sni://:443 开启 sni 透明传输 https 流量模式。
客户端可以直接配置 hosts 使用，
或者配置 gost -L :443 -F sni://server_ip:443，做中转？
或者配置前置 socks 代理转发  gost -L :443 -F socks://:1080 -F sni://server_ip:443

**Comment by jlzsss** [comment]
gost 支持 sniproxy 需要在hosts里配置

**Comment by jzp820927** [comment]
@jlzsss 好吧，可能我表达的不是太清楚，我知道 gost 支持 sni 中转，我的意思是希望 gost 能支持搭建 sni 服务器端。

**Comment by wangyi2005** [comment]
此方法可能有问题：
1、http流量无法加密。
2、connect google.com 之类的在TLS握手阶段估计就被reset了。

**Comment by jzp820927** [comment]
我知道 http 过不了 sni，sni 也不能处理所有流量。只是作为 gost 众多代理协议中的一种，对于有这种需求的时候，可以作为一种选择而已。而且我顶楼也说了，只是用来处理 https 流量。

**Comment by ljm000** [comment]
http过不了sni的原因是内容并未加密。之前试过用kcptun加密并将sni的80和443端口转发到路由，可以实现sni 80不被reset。

**Comment by jzp820927** [comment]
通过多种协议组合肯定是可以处理 http 的

**Comment by ginuerzh** [comment]
2.5版本中将增加对SNI proxy的支持 #140

**Comment by jzp820927** [comment]
@ginuerzh 感谢 G 大，终于等到你的回复了，半年的等待没有白费啊，那就静候佳音了。
